import { NextResponse } from "next/server";
import { z } from "zod";
import { apiError } from "@/lib/api";
import { requireUser } from "@/lib/supabase/server";
const tables={topics:"research_topics",sources:"knowledge_sources",findings:"research_findings",questions:"research_questions",collections:"knowledge_collections",briefs:"research_briefs",watches:"watch_entities",evidence:"finding_evidence",relations:"knowledge_relations",links:"knowledge_entity_links",collection_items:"collection_items"} as const;
const resource=z.enum(Object.keys(tables) as [keyof typeof tables,...(keyof typeof tables)[]]);
const safeUrl=z.string().url().refine(value=>/^https?:\/\//i.test(value),"Use an http or https URL.");
const changes:Record<keyof typeof tables,z.ZodType>={topics:z.object({title:z.string().trim().min(1).max(240).optional(),description:z.string().max(10000).nullable().optional(),status:z.enum(["active","monitoring","paused","complete","archived"]).optional(),domain:z.enum(["work","business","founder","life","strategy","personal","other"]).optional(),priority:z.enum(["low","medium","high"]).optional(),next_review_at:z.string().date().nullable().optional(),last_reviewed_at:z.string().datetime().optional()}),sources:z.object({title:z.string().trim().min(1).max(400).optional(),source_type:z.string().min(1).optional(),url:safeUrl.nullable().optional(),author:z.string().max(240).nullable().optional(),publisher:z.string().max(240).nullable().optional(),published_at:z.string().date().nullable().optional(),accessed_at:z.string().datetime().nullable().optional(),notes:z.string().max(20000).nullable().optional(),reliability:z.enum(["primary","strong","useful","unverified","weak"]).nullable().optional(),freshness_expires_at:z.string().date().nullable().optional(),archived_at:z.string().datetime().nullable().optional()}),findings:z.object({title:z.string().trim().min(1).max(400).optional(),summary:z.string().max(20000).optional(),status:z.enum(["draft","supported","mixed","contradicted","superseded"]).optional(),confidence_label:z.enum(["low","medium","high"]).nullable().optional(),reviewed_at:z.string().datetime().optional()}),questions:z.object({question:z.string().trim().min(1).max(1000).optional(),status:z.enum(["open","researching","answered","deferred","dropped"]).optional(),answer_summary:z.string().max(10000).nullable().optional(),priority:z.enum(["low","medium","high"]).optional()}),collections:z.object({title:z.string().trim().min(1).max(240).optional(),description:z.string().max(10000).nullable().optional()}),briefs:z.object({title:z.string().trim().min(1).max(240).optional(),summary:z.string().max(20000).optional(),implications:z.string().max(10000).nullable().optional(),next_research:z.string().max(10000).nullable().optional(),status:z.enum(["draft","current","outdated","archived"]).optional()}),watches:z.object({status:z.enum(["active","paused","archived"]).optional(),last_checked_at:z.string().datetime().optional(),next_check_at:z.string().date().nullable().optional()}),evidence:z.object({relation_type:z.enum(["supports","contradicts","context","weak_support"]),excerpt:z.string().max(2000).nullable().optional()}),relations:z.object({relation_type:z.enum(["related","supports","contradicts","derived_from","supersedes","depends_on","impacts","about"])}),links:z.object({}),collection_items:z.object({})};
export async function PATCH(request:Request,{params}:{params:Promise<{resource:string;id:string}>}){try{const{resource:raw,id}=await params;const key=resource.parse(raw);const values=changes[key].parse(await request.json()) as Record<string,unknown>;const{supabase,userId}=await requireUser();if(key==="questions"&&values.status==="answered")Object.assign(values,{answered_at:new Date().toISOString()});if(key==="topics"&&values.status==="archived")Object.assign(values,{archived_at:new Date().toISOString()});const{data,error}=await supabase.from(tables[key]).update(values as never).eq("id",id).eq("user_id",userId).select("*").maybeSingle();if(error)throw error;if(!data)return NextResponse.json({error:"Knowledge record is unavailable."},{status:404});return NextResponse.json({item:data})}catch(error){return apiError(error,"Knowledge record could not be updated.")}}
export async function DELETE(_:Request,{params}:{params:Promise<{resource:string;id:string}>}){try{const{resource:raw,id}=await params;const key=resource.parse(raw);const{supabase,userId}=await requireUser();const{error}=await supabase.from(tables[key]).delete().eq("id",id).eq("user_id",userId);if(error)throw error;return NextResponse.json({ok:true})}catch(error){return apiError(error,"Knowledge record could not be removed.")}}
