"use client";
import { StyledSelect } from "@/components/ui/styled-select";
import Link from "next/link";
import { useMemo, useState } from "react";
import { Icons } from "@/components/icons";
import type { DomainRecord } from "@/lib/domains";
import "./client-dashboard.css";

type Props={rows:DomainRecord[];onEdit:(record:DomainRecord)=>void;onCreate:()=>void};
const str=(value:unknown)=>String(value??"");
const initials=(name:string)=>name.trim().split(/\s+/).map(word=>word[0]).slice(0,2).join("").toUpperCase();
const contactDate=(value:unknown)=>value?new Date(str(value)).toLocaleDateString([], {month:"short",day:"numeric",year:"numeric"}):"—";
const dueIn=(value:unknown,now:number)=>{if(!value)return "Not scheduled";const days=Math.ceil((new Date(str(value)).getTime()-now)/86400000);return days<0?`${Math.abs(days)}d overdue`:days===0?"Today":`In ${days} days`};
export function ClientDashboard({rows,onEdit,onCreate}:Props){
 const [selected,setSelected]=useState<string|null>(null);
 const [query,setQuery]=useState("");
 const [filter,setFilter]=useState<"all"|"active"|"followup"|"risk"|"archived">("all");
 const [sort,setSort]=useState("updated");
 const [layout,setLayout]=useState<"list"|"grid">("list");
 const [tab,setTab]=useState<"overview"|"tasks"|"activity"|"files">("overview");
 const [checked,setChecked]=useState<string[]>([]);
 const [now]=useState(()=>Date.now());
 const active=rows.filter(row=>str(row.status)!=="archived");
 const due=useMemo(()=>rows.filter(row=>row.next_follow_up_at&&new Date(str(row.next_follow_up_at)).getTime()<now&&str(row.status)!=="archived"),[rows,now]);
 const counts={all:rows.length,active:active.length,followup:due.length,risk:due.length,archived:rows.length-active.length};
 const visible=useMemo(()=>rows.filter(row=>str(row.name).toLowerCase().includes(query.toLowerCase())&&(filter==="all"||filter==="active"&&str(row.status)!=="archived"||filter==="archived"&&str(row.status)==="archived"||(filter==="followup"||filter==="risk")&&due.some(item=>item.id===row.id))).sort((a,b)=>sort==="name"?str(a.name).localeCompare(str(b.name)):sort==="contact"?str(a.next_follow_up_at||"9999").localeCompare(str(b.next_follow_up_at||"9999")):str(b.updated_at).localeCompare(str(a.updated_at))),[rows,query,filter,sort,due]);
 const client=rows.find(row=>row.id===selected)??null;
 return <div className="clients-ui"><div className="clients-ui__stats" aria-label="Client summary filters"><button type="button" className={filter==="all"?"is-selected":""} aria-pressed={filter==="all"} onClick={()=>setFilter("all")}><span><Icons.Users size={23}/></span><div><small>Total clients</small><strong>{rows.length}</strong><small>Across your workspace</small></div><i/><i/><i/><i/></button><button type="button" className={filter==="active"?"is-selected":""} aria-pressed={filter==="active"} onClick={()=>setFilter("active")}><span><Icons.HeartHandshake size={23}/></span><div><small>Active relationships</small><strong>{active.length}</strong><small>{rows.length?Math.round(active.length/rows.length*100):0}% of total</small></div><i/><i/><i/><i/></button><button type="button" className={filter==="followup"?"is-selected":""} aria-pressed={filter==="followup"} onClick={()=>setFilter("followup")}><span><Icons.Clock3 size={23}/></span><div><small>Follow-ups due</small><strong>{due.length}</strong><small>{due.length?"Needs a response":"No follow-ups pending"}</small></div><i/><i/><i/><i/></button><button type="button" className={filter==="risk"?"is-selected":""} aria-pressed={filter==="risk"} onClick={()=>setFilter("risk")}><span><Icons.AlertTriangle size={23}/></span><div><small>At risk</small><strong>{due.length}</strong><small>{due.length?"Review overdue contacts":"Healthy relationships"}</small></div><i/><i/><i/><i/></button></div>
 <div className="clients-ui__toolbar"><label className="clients-ui__search"><Icons.Search size={18}/><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Search clients..." aria-label="Search clients"/></label><div className="clients-ui__tabs">{(["all","active","followup","archived"] as const).map(item=><button key={item} className={filter===item?"active":""} onClick={()=>setFilter(item)}>{item==="followup"?"Follow-up":item[0].toUpperCase()+item.slice(1)} <b>{counts[item]}</b></button>)}</div><div className="clients-ui__tools"><button onClick={()=>setFilter(filter==="followup"?"all":"followup")}><Icons.Filter size={16}/> Filter <Icons.ChevronDown size={13}/></button><div><Icons.ListTodo size={16}/><StyledSelect label="Sort clients" value={sort} onChange={setSort} options={[{value:"updated",label:"Sort: Recently updated"},{value:"name",label:"Sort: Name"},{value:"contact",label:"Sort: Next contact"}]}/></div><div><button className={layout==="list"?"active":""} onClick={()=>setLayout("list")} aria-label="List view"><Icons.Menu size={19}/></button><button className={layout==="grid"?"active":""} onClick={()=>setLayout("grid")} aria-label="Grid view"><Icons.Package size={18}/></button></div></div></div>
 <div className={`clients-ui__body ${client?"has-detail":""}`}><section className="clients-ui__table" aria-label="Clients"><div className="clients-ui__thead"><input type="checkbox" aria-label="Select all visible clients" checked={visible.length>0&&visible.every(row=>checked.includes(row.id))} onChange={event=>setChecked(event.target.checked?visible.map(row=>row.id):[])}/><span>Client</span><span>Status</span><span>Last interaction</span><span>Next contact</span><span>Owner</span><span>Health</span></div>{visible.map(row=>{const overdue=due.some(item=>item.id===row.id);return <div className={`clients-ui__row ${selected===row.id?"selected":""}`} key={row.id}><input type="checkbox" aria-label={`Select ${str(row.name)}`} checked={checked.includes(row.id)} onChange={event=>setChecked(current=>event.target.checked?[...current,row.id]:current.filter(id=>id!==row.id))}/><button className="clients-ui__name" onClick={()=>{setSelected(row.id);setTab("overview")}}><span className="clients-ui__initials">{initials(str(row.name))}</span><span><strong>{str(row.name)}</strong><small>{str(row.company)||"No company specified"}</small></span></button><span className={`clients-ui__pill ${str(row.status)==="archived"?"muted":""}`}><i/>{str(row.status)==="archived"?"Archived":"Active"}</span><span className="clients-ui__meta"><Icons.MessageSquareText size={16}/><span>—<small>No activity recorded</small></span></span><span className="clients-ui__meta"><Icons.CalendarDays size={16}/><span>{contactDate(row.next_follow_up_at)}<small className={overdue?"overdue":""}>{dueIn(row.next_follow_up_at,now)}</small></span></span><span className="clients-ui__owner"><i>Y</i>You</span><span className={`clients-ui__pill ${overdue?"risk":""}`}><i/>{overdue?"Follow-up due":"Healthy"}</span><button className="clients-ui__row-more" onClick={()=>onEdit(row)} aria-label={`Edit ${str(row.name)}`}><Icons.MoreHorizontal size={17}/></button></div>})}{!visible.length&&<div className="clients-ui__empty"><p>{rows.length?"No clients match these filters.":"No clients yet."}</p><button onClick={rows.length?()=>{setQuery("");setFilter("all")}:onCreate}>{rows.length?"Clear filters":"New client"}</button></div>}</section>
 {client&&<aside className="clients-ui__detail"><div className="clients-ui__detail-head"><span className="clients-ui__detail-avatar">{initials(str(client.name))}</span><div><h2>{str(client.name)}</h2><p>{str(client.company)||"No company specified"}</p><span className="clients-ui__pill"><i/>Active</span></div><button onClick={()=>onEdit(client)} aria-label="Edit client"><Icons.MoreHorizontal size={18}/></button><button onClick={()=>setSelected(null)} aria-label="Close client details"><Icons.X size={18}/></button></div><div className="clients-ui__detail-actions"><Link href={`/clients/${client.id}`}><Icons.ExternalLink size={16}/> Open profile</Link><button onClick={()=>onEdit(client)}><Icons.FileText size={16}/> Add note</button><button onClick={()=>onEdit(client)}><Icons.CalendarDays size={16}/> Schedule follow-up</button></div><div className="clients-ui__detail-tabs">{(["overview","tasks","activity","files"] as const).map(item=><button key={item} className={tab===item?"active":""} onClick={()=>setTab(item)}>{item[0].toUpperCase()+item.slice(1)}</button>)}</div>{tab==="overview"?<><div className="clients-ui__detail-facts"><div><Icons.CalendarDays size={18}/><span>Next contact<strong>{contactDate(client.next_follow_up_at)}</strong><small>{dueIn(client.next_follow_up_at,now)}</small></span></div><div><Icons.Users size={18}/><span>Owner<strong>You</strong></span></div><div><Icons.Activity size={18}/><span>Relationship health<strong>{due.some(row=>row.id===client.id)?"Follow-up due":"Healthy"}</strong><small>{due.some(row=>row.id===client.id)?"Contact is overdue":"No issues"}</small></span></div><div><Icons.BriefcaseBusiness size={18}/><span>Company<strong>{str(client.company)||"—"}</strong></span></div></div><button className="clients-ui__notes" onClick={()=>onEdit(client)}><Icons.FileText size={17}/><span><strong>Notes</strong><small>{str(client.notes)||"Add notes about this client..."}</small></span><Icons.Pencil size={15}/></button><div className="clients-ui__activity"><strong>Contact</strong><p>{str(client.email)||"No email"}</p><p>{str(client.phone)||"No phone"}</p></div></>:<div className="clients-ui__tab-empty"><p>{tab==="activity"?"No activity recorded yet.":tab==="tasks"?"Open the client profile to see linked tasks.":"Open the client profile to see files."}</p><Link href={`/clients/${client.id}`}>Open profile <Icons.ArrowRight size={14}/></Link></div>}</aside>}</div></div>;
}
