'use client';

import Link from 'next/link';
import {useEffect,useMemo,useRef,useState,useSyncExternalStore,type ReactNode} from 'react';
import {PieChart,Pie,Cell,ResponsiveContainer,Tooltip} from 'recharts';
import {Users,HeartHandshake,TriangleAlert,CircleAlert,CalendarDays,Clock3,FileText,ChartNoAxesColumnIncreasing,Search,ChevronRight,X,ShieldCheck,LayoutGrid,Activity,User,Mail,CheckCircle2,ArrowUpDown,RefreshCw,MessageSquareText,ArrowRight,type LucideIcon} from 'lucide-react';
import {Modal} from '@/components/ui/modal';
import {StyledSelect} from '@/components/ui/styled-select';
import {filterSuccessAccounts,healthStates,healthColors,successLabel,nextRenewal,nextCheckIn,latestSignal,type SuccessAccount,type SuccessPortfolio} from '@/lib/success-dashboard';
import './success-home.css';

const date=(value?:string|null)=>value?new Date(value).toLocaleDateString('en',{month:'short',day:'numeric',year:'numeric'}):'Not scheduled';
const initial=(name:string)=>name.trim().split(/\s+/).slice(0,2).map(part=>part[0]).join('').toUpperCase();
const subscribeMobile=(listener:()=>void)=>{const media=window.matchMedia('(max-width: 900px)');media.addEventListener('change',listener);return()=>media.removeEventListener('change',listener);};
const profile=(id:string)=>`/success/clients/${id}`;
function Avatar({name,large=false}:{name:string;large?:boolean}){return <span className={`cs-avatar ${large?'is-large':''}`} aria-hidden="true">{initial(name)}</span>;}
function Badge({state}:{state:string}){return <span className={`cs-badge state-${state}`}><span/>{successLabel(state)}</span>;}
function Panel({title,icon:Icon,children,href,onView,className=''}:{title:string;icon:LucideIcon;children:ReactNode;href?:string;onView?:()=>void;className?:string}){return <section className={`cs-panel ${className}`}><header><span className="cs-icon"><Icon size={19}/></span><h2>{title}</h2>{onView?<button className="cs-view" onClick={onView}>View all</button>:href&&<Link className="cs-view" href={href}>View all</Link>}</header>{children}</section>;}
function Empty({children}:{children:ReactNode}){return <p className="cs-empty">{children}</p>;}

export function SuccessHome(){
 const mobile=useSyncExternalStore(subscribeMobile,()=>window.matchMedia('(max-width: 900px)').matches,()=>false);
 const [data,setData]=useState<SuccessPortfolio|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(true),[retry,setRetry]=useState(0),[unavailable,setUnavailable]=useState(false);
 const [showIssues,setShowIssues]=useState(false);
 const [query,setQuery]=useState(''),[health,setHealth]=useState('all'),[owner,setOwner]=useState('all'),[sort,setSort]=useState('name'),[selected,setSelected]=useState<string|null>(null),[tab,setTab]=useState('overview');
 const panel=useRef<HTMLElement>(null),trigger=useRef<HTMLElement|null>(null);
 useEffect(()=>{const controller=new AbortController();fetch('/api/success/portfolio',{signal:controller.signal}).then(async response=>{if(!response.ok)throw new Error('Unable to load customer success.');return response.json();}).then(json=>{setUnavailable(json.schemaStatus==='unavailable');setData(json.data);setLoading(false);}).catch(e=>{if(e.name!=='AbortError'){setError('Customer Success could not be loaded. Please try again.');setLoading(false);}});return()=>controller.abort();},[retry]);
 const accounts=useMemo(()=>data?.portfolioAccounts??[],[data]);
 const current=accounts.find(a=>a.client.id===selected);
 const owners=useMemo(()=>Array.from(new Map(accounts.flatMap(a=>a.owners).map(o=>[o.id,o])).values()),[accounts]);
 const rows=useMemo(()=>filterSuccessAccounts(accounts,query,health,owner).sort((a,b)=>sort==='health'?['critical','at_risk','needs_attention','healthy','insufficient_data'].indexOf(a.health.state)-['critical','at_risk','needs_attention','healthy','insufficient_data'].indexOf(b.health.state)||a.client.name.localeCompare(b.client.name):a.client.name.localeCompare(b.client.name)),[accounts,query,health,owner,sort]);
 const select=(account:SuccessAccount)=>{trigger.current=document.activeElement as HTMLElement;setSelected(account.client.id);setTab('overview');};
 const close=()=>setSelected(null);
 useEffect(()=>{if(!selected)return;panel.current?.querySelector<HTMLButtonElement>('[aria-label="Close client overview"]')?.focus({preventScroll:true});const onKey=(e:KeyboardEvent)=>{if(e.key==='Escape'){setSelected(null);}if(e.key==='Tab'&&window.matchMedia('(max-width: 900px)').matches){const items=[...panel.current?.querySelectorAll<HTMLElement>('button,a[href],input,textarea,select')??[]].filter(el=>!el.hasAttribute('disabled'));if(e.shiftKey&&document.activeElement===items[0]){e.preventDefault();items.at(-1)?.focus();}else if(!e.shiftKey&&document.activeElement===items.at(-1)){e.preventDefault();items[0]?.focus();}}};document.addEventListener('keydown',onKey);return()=>{document.removeEventListener('keydown',onKey);trigger.current?.focus({preventScroll:true});};},[selected]);
 const renewal=current?nextRenewal(current):null,checkIn=current?nextCheckIn(current):null;
 const renewals=accounts.flatMap(a=>a.renewals.filter(r=>!['renewed','not_renewing','cancelled'].includes(r.status)).map(r=>({...r,account:a}))).sort((a,b)=>a.renewal_date.localeCompare(b.renewal_date));
 const risks=accounts.filter(a=>['at_risk','critical','needs_attention'].includes(a.health.state));
 const issues=accounts.flatMap(a=>a.issues.filter(i=>!['resolved','closed'].includes(i.status)).map(i=>({...i,account:a})));
 const signals=accounts.flatMap(a=>a.signals.map(s=>({...s,account:a}))).sort((a,b)=>b.recorded_at.localeCompare(a.recorded_at));
 const breakdown=healthStates.map(state=>({state,name:successLabel(state),value:data?.summary.healthBreakdown[state]??0}));
 const metrics=[{label:'Total Clients',value:accounts.length,icon:Users,state:'all'},{label:'Healthy',value:breakdown[0].value,icon:HeartHandshake,state:'healthy'},{label:'Needs Attention',value:breakdown[1].value,icon:TriangleAlert,state:'needs_attention'},{label:'At Risk',value:breakdown[2].value,icon:CircleAlert,state:'at_risk'},{label:'Critical',value:breakdown[3].value,icon:TriangleAlert,state:'critical'},{label:'Upcoming Renewals',value:data?.summary.upcomingRenewalsCount??0,icon:CalendarDays,href:'/success/renewals'},{label:'Waiting On Us',value:data?.waitingOnUs.length??0,icon:Clock3,href:'/success/journey'},{label:'Open Issues',value:issues.length,icon:FileText}];
 const metricContents=(m:typeof metrics[number])=><><span className={`cs-icon tone-${m.state??'blue'}`}><m.icon size={23}/></span><span><small>{m.label}</small><strong>{m.value}</strong><em>{m.label==='Upcoming Renewals'?'Next 60 days':'Current portfolio'}</em></span></>;
 return <div className="cs-dashboard"><header className="cs-heading"><div><nav aria-label="Breadcrumb"><Link href="/business">Business</Link><ChevronRight size={13}/><span>Customer Success</span></nav><h1>Customer Success</h1><p>Client health, retention risks, renewal pipeline, and check-in momentum.</p></div><div className="cs-heading-actions"><Link href="/success/portfolio">Portfolio</Link><Link href="/success/renewals">Renewals</Link><Link href="/success/risks">Risks</Link><Link href="/success/review" className="cs-primary">Retention review</Link></div></header>
 {loading?<div className="cs-loading" role="status">Loading your client portfolio…</div>:error?<div className="cs-loading" role="alert"><CircleAlert/><p>{error}</p><button onClick={()=>{setError('');setLoading(true);setRetry(n=>n+1);}}>Try again</button></div>:unavailable?<div className="cs-loading"><HeartHandshake/><h2>Customer Success is not configured yet</h2><p>The Customer Success data tables need to be configured before health assessments are available.</p><Link href="/clients">Open client directory<ArrowRight size={15}/></Link></div>:<>
 <section className="cs-metrics" aria-label="Portfolio summary">{metrics.map(m=>m.href?<Link key={m.label} href={m.href} className="cs-metric">{metricContents(m)}</Link>:<button key={m.label} className={`cs-metric ${health===m.state?'is-filtered':''}`} aria-pressed={health===m.state} onClick={()=>{if(m.label==='Open Issues'){setShowIssues(true);return;}setHealth(m.state??'all');setSelected(null);}}>{metricContents(m)}</button>)}</section>
 <div className={`cs-main ${current?'has-selection':''}`}><div className="cs-left" inert={mobile&&Boolean(current)}><section className="cs-panel cs-portfolio"><header><span className="cs-icon"><ChartNoAxesColumnIncreasing size={22}/></span><div><h2>Portfolio Health</h2><p>A view of your clients, their health status, and upcoming milestones.</p></div><div className="cs-filters"><label className="cs-search"><Search size={16}/><input aria-label="Search clients" placeholder="Search clients…" value={query} onChange={e=>setQuery(e.target.value)}/></label><StyledSelect label="Filter by health" value={health} onChange={setHealth} options={[{value:'all',label:'All health'},...healthStates.map(value=>({value,label:successLabel(value)}))]}/><StyledSelect label="Filter by owner" value={owner} onChange={setOwner} options={[{value:'all',label:'All owners'},{value:'unassigned',label:'Unassigned'},...owners.map(o=>({value:o.id,label:o.name}))]}/><button className="cs-sort" aria-label={sort==='name'?'Sort by health':'Sort by client name'} title={sort==='name'?'Sort by health':'Sort by client name'} onClick={()=>setSort(sort==='name'?'health':'name')}><ArrowUpDown size={16}/></button></div></header>
 <div className="cs-table-wrap"><table><thead><tr><th>Client</th><th>Owner</th><th>Health</th><th>Next check-in</th><th>Renewal date</th><th>Satisfaction</th><th>Last interaction</th></tr></thead><tbody>{rows.map(a=><tr key={a.client.id} className={selected===a.client.id?'is-selected':''} onClick={()=>select(a)}><td><button className="cs-client" onClick={e=>{e.stopPropagation();select(a);}} aria-label={`View ${a.client.name} overview`} aria-expanded={selected===a.client.id}><Avatar name={a.client.name}/><strong>{a.client.name}</strong></button></td><td>{a.owners.map(o=>o.name).join(', ')||'Unassigned'}</td><td><Badge state={a.health.state}/></td><td>{date(nextCheckIn(a)?.scheduled_at??a.client.next_follow_up_at)}</td><td>{date(nextRenewal(a)?.renewal_date)}</td><td>{latestSignal(a)?<span className="cs-signal-label">{successLabel(latestSignal(a)!.signal_type)}</span>:<span className="cs-muted">No signal</span>}</td><td>{a.engagement.daysSince==null?'Not recorded':a.engagement.daysSince===0?'Today':`${a.engagement.daysSince} days ago`}</td></tr>)}</tbody></table></div>
 {!rows.length&&<div className="cs-portfolio-empty"><Users size={29}/><h3>{accounts.length?'No clients match your filters':'Your client portfolio starts here'}</h3><p>{accounts.length?'Try another name, owner, or health status.':'Add a client to start tracking relationships, check-ins, and renewal health.'}</p>{accounts.length?<button onClick={()=>{setQuery('');setOwner('all');setHealth('all');}}>Clear filters</button>:<Link href="/clients">Open client directory<ArrowRight size={14}/></Link>}</div>}<footer className="cs-table-footer">{rows.length} of {accounts.length} clients <span>Select a client to explore their overview</span></footer></section>
 <div className="cs-support-grid"><Panel title="Client health distribution" icon={HeartHandshake}><div className="cs-distribution"><div className="cs-donut" role="img" aria-label={breakdown.map(b=>`${b.name}: ${b.value}`).join(', ')}><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={accounts.length?breakdown:[{name:'No clients',value:1,state:'insufficient_data'}]} dataKey="value" innerRadius="67%" outerRadius="95%" stroke="none" isAnimationActive={false}>{(accounts.length?breakdown:[{state:'insufficient_data'}]).map(b=><Cell key={b.state} fill={healthColors[b.state]}/>)}</Pie>{accounts.length>0&&<Tooltip/>}</PieChart></ResponsiveContainer><div><strong>{accounts.length}</strong><span>Clients</span></div></div><div className="cs-distribution-legend">{breakdown.filter(b=>b.value||b.state!=='insufficient_data').map(b=><button key={b.state} onClick={()=>setHealth(b.state)}><i style={{background:healthColors[b.state]}}/>{b.name}<strong>{b.value}</strong><span>{accounts.length?Math.round(b.value/accounts.length*100):0}%</span></button>)}</div></div></Panel>
 <Panel title="At-Risk Clients" icon={ShieldCheck} href="/success/risks">{risks.length?risks.slice(0,4).map(a=><button className="cs-mini-row" key={a.client.id} onClick={()=>select(a)}><Avatar name={a.client.name}/><span>{a.client.name}</span><Badge state={a.health.state}/></button>):<Empty>No client risks recorded.</Empty>}</Panel>
 <Panel title="Upcoming Renewals" icon={CalendarDays} href="/success/renewals">{renewals.length?renewals.slice(0,4).map(r=><button className="cs-mini-row" key={r.id} onClick={()=>select(r.account)}><Avatar name={r.account.client.name}/><span>{r.account.client.name}</span><small>{date(r.renewal_date)}</small></button>):<Empty>No renewals scheduled yet.</Empty>}</Panel></div></div>
 {current&&<><button className="cs-backdrop" aria-label="Close client details" onClick={close}/><aside ref={panel} className="cs-panel cs-client-panel" role={mobile?'dialog':'region'} aria-modal={mobile?true:undefined} aria-label={`${current.client.name} client overview`}><header><span className="cs-icon"><LayoutGrid size={20}/></span><h2>Client overview</h2><Link href={profile(current.client.id)} className="cs-view">View full profile</Link><button className="cs-close" aria-label="Close client overview" onClick={close}><X size={17}/></button></header><div className="cs-client-identity"><Avatar large name={current.client.name}/><div><h2>{current.client.name}</h2><p>{current.client.company||successLabel(current.client.tier??'standard')}{current.client.created_at?` · Client since ${new Date(current.client.created_at).toLocaleDateString('en',{month:'short',year:'numeric'})}`:''}</p></div><Badge state={current.health.state}/></div><div className="cs-client-stats"><div><CalendarDays/><span>Renewal date<strong>{date(renewal?.renewal_date)}</strong></span></div><div><RefreshCw/><span>Renewal stage<strong>{renewal?successLabel(renewal.status):'Not tracked'}</strong></span></div><div><HeartHandshake/><span>Health assessment<strong>{successLabel(current.health.state)}</strong></span></div></div><div className="cs-panel-tabs" role="tablist" aria-label="Client details">{['overview','activity','notes','actions'].map(t=><button key={t} role="tab" aria-selected={tab===t} aria-controls="cs-client-tab-content" id={`cs-tab-${t}`} onClick={()=>setTab(t)}>{({overview:'Overview',activity:'Recent activity',notes:'Notes',actions:'Upcoming actions'})[t]}</button>)}</div><div id="cs-client-tab-content" role="tabpanel" aria-labelledby={`cs-tab-${tab}`}>
 {tab==='overview'?<><div className="cs-details-columns"><section><h3>Key details</h3><dl>{[{icon:User,label:'Owner',value:current.owners.map(o=>o.name).join(', ')||'Unassigned'},{icon:Activity,label:'Last interaction',value:current.engagement.daysSince==null?'Not recorded':`${current.engagement.daysSince} days ago`},{icon:CalendarDays,label:'Next check-in',value:date(checkIn?.scheduled_at??current.client.next_follow_up_at)},{icon:FileText,label:'Client tier',value:successLabel(current.client.tier??'standard')},{icon:Mail,label:'Contact',value:current.client.email||'Not recorded'}].map(({icon:Icon,label,value})=><div key={label}><dt><Icon size={14}/>{label}</dt><dd>{value}</dd></div>)}</dl></section><section><h3>Recent notes<button onClick={()=>setTab('notes')}>View all</button></h3>{current.client.notes?<p className="cs-note-preview">{current.client.notes}</p>:<Empty>No client notes yet.</Empty>}<h3>Upcoming actions<button onClick={()=>setTab('actions')}>View all</button></h3><Actions account={current} limit={3}/></section></div><div className="cs-health-summary"><HeartHandshake size={18}/><div><strong>Health context</strong><p>{current.health.summary}</p></div></div></>:tab==='activity'?<div className="cs-activity">{current.signals.length?[...current.signals].sort((a,b)=>b.recorded_at.localeCompare(a.recorded_at)).map(s=><article key={s.id}><Activity size={17}/><div><strong>{successLabel(s.signal_type)}</strong><p>{s.summary}</p><small>{date(s.recorded_at)}</small></div></article>):<Empty>No satisfaction signals recorded yet.</Empty>}</div>:tab==='notes'?<div className="cs-notes"><MessageSquareText size={25}/><h3>Client notes</h3><p>{current.client.notes||'No notes have been recorded for this client.'}</p><Link href={profile(current.client.id)}>Open full client profile<ArrowRight size={14}/></Link></div>:<Actions account={current}/>}
 </div></aside></>}
 </div><div className="cs-bottom-grid"><Panel title="Waiting On Us" icon={Clock3} href="/success/journey">{data?.waitingOnUs.length?data.waitingOnUs.slice(0,3).map(w=><Link className="cs-mini-row" href={w.route} key={w.id}><Avatar name={w.client_name}/><span>{w.client_name}</span><small>{w.what}</small><Badge state={w.is_overdue?'at_risk':'needs_attention'}/></Link>):<Empty>No outstanding commitments owed to clients.</Empty>}</Panel><Panel title="Open Issues" icon={FileText} onView={()=>setShowIssues(true)}>{issues.length?issues.slice(0,3).map(i=><button className="cs-mini-row" key={i.id} onClick={()=>select(i.account)}><Avatar name={i.account.client.name}/><span>{i.account.client.name}</span><small>{i.title}</small><span className={`cs-severity severity-${i.severity}`}>{successLabel(i.severity)}</span></button>):<Empty>No open client issues.</Empty>}</Panel><Panel title="Recent Signals" icon={Activity} href="/success/portfolio">{signals.length?signals.slice(0,3).map(s=><button className="cs-mini-row" key={s.id} onClick={()=>{select(s.account);setTab('activity');}}><Avatar name={s.account.client.name}/><span>{s.account.client.name}</span><small>{s.summary}</small></button>):<Empty>Client feedback and signals will appear here.</Empty>}</Panel></div>
 <footer className="cs-views"><span className="cs-icon"><LayoutGrid size={23}/></span><div><strong>Views</strong><small>Switch between different perspectives</small></div>{[{label:'Portfolio Health',href:'/success/portfolio',icon:ChartNoAxesColumnIncreasing},{label:'Renewals',href:'/success/renewals',icon:CalendarDays},{label:'Risks',href:'/success/risks',icon:ShieldCheck},{label:'Check-ins',href:'/success/check-ins',icon:Users},{label:'Client Journey',href:'/success/journey',icon:HeartHandshake},{label:'Retention Review',href:'/success/review',icon:Activity}].map(({label,href,icon:Icon})=><Link key={label} href={href}><Icon size={17}/>{label}</Link>)}</footer>
 </>}
 <Modal open={showIssues} onClose={()=>setShowIssues(false)} title="Open client issues">{issues.length?issues.map(i=><Link className="cs-mini-row" key={i.id} href={profile(i.account.client.id)}><span>{i.account.client.name} · {i.title}</span><Badge state={i.severity}/><ChevronRight size={15}/></Link>):<Empty>No open client issues recorded.</Empty>}</Modal>
 </div>;
}
function Actions({account,limit=20}:{account:SuccessAccount;limit?:number}){const commitments=account.commitments.filter(c=>c.status==='open');const checks=account.checkIns.filter(c=>c.status==='scheduled');const items=[...commitments.map(c=>({id:c.id,title:c.statement,date:c.due_at})),...checks.map(c=>({id:c.id,title:c.purpose,date:c.scheduled_at}))].sort((a,b)=>String(a.date??'9999').localeCompare(String(b.date??'9999'))).slice(0,limit);return items.length?<div className="cs-actions-list">{items.map(i=><Link href={profile(account.client.id)} key={i.id}><CheckCircle2 size={16}/><span>{i.title}</span><small>{date(i.date)}</small></Link>)}</div>:<Empty>No upcoming actions recorded.</Empty>;}
