import { z } from "zod";
import { createRecord,updateRecord } from "@/lib/repository";
import { pushGoogleEvent } from "@/lib/integrations/google-calendar";
import type { SupabaseClient } from "@supabase/supabase-js";
import { getAnalyticsSummary,getContentSummary,getFinanceSummary,getFitnessWeek,getTodayInsights } from "@/lib/intelligence";
import { renderPrompt } from "@/lib/v2";

const query=z.object({query:z.string().max(240).default("")}).strict();const id=z.object({id:z.uuid()}).strict();const tool=(name:string,description:string,properties:Record<string,unknown>,required:string[]=[])=>({type:"function",name,description,parameters:{type:"object",properties,required,additionalProperties:false}});
const string={type:"string"};const nullableString={type:["string","null"]};
export const assistantTools=[
 tool("search_tasks","Search the authenticated user's tasks.",{query:string},["query"]),tool("create_task","Create a task after explicit user confirmation.",{title:string,due_date:nullableString,project_id:nullableString,confirmed:{type:"boolean"}},["title","due_date","project_id","confirmed"]),tool("update_task","Update a task after explicit user confirmation.",{id:string,title:nullableString,status:nullableString,due_date:nullableString,confirmed:{type:"boolean"}},["id","title","status","due_date","confirmed"]),tool("complete_task","Complete a task after explicit user confirmation.",{id:string,confirmed:{type:"boolean"}},["id","confirmed"]),
 tool("search_projects","Search projects.",{query:string},["query"]),tool("get_project","Get one project and linked work.",{id:string},["id"]),tool("search_notes","Search notes.",{query:string},["query"]),tool("create_note","Create a note after explicit user confirmation.",{title:string,content:string,project_id:nullableString,confirmed:{type:"boolean"}},["title","content","project_id","confirmed"]),tool("search_clients","Search clients.",{query:string},["query"]),tool("create_followup","Create a follow-up after explicit user confirmation.",{title:string,client_id:nullableString,due_at:nullableString,confirmed:{type:"boolean"}},["title","client_id","due_at","confirmed"]),
 tool("get_calendar","Get calendar events in an ISO date range.",{start:string,end:string},["start","end"]),tool("create_calendar_event","Create and sync a calendar event after explicit user confirmation.",{title:string,starts_at:string,ends_at:string,timezone:string,confirmed:{type:"boolean"}},["title","starts_at","ends_at","timezone","confirmed"]),tool("get_waiting_items","Get open waiting items.",{}),tool("search_decisions","Search decisions.",{query:string},["query"]),tool("get_goals","Get active goals.",{}),
 tool("get_finance_summary","Get current finance totals and overdue invoices.",{}),tool("search_invoices","Search invoices by title or number.",{query:string},["query"]),tool("create_invoice","Create an invoice after explicit confirmation.",{title:string,client_id:nullableString,project_id:nullableString,subtotal:{type:"number"},tax_amount:{type:"number"},discount_amount:{type:"number"},currency:string,due_date:nullableString,confirmed:{type:"boolean"}},["title","client_id","project_id","subtotal","tax_amount","discount_amount","currency","due_date","confirmed"]),tool("record_payment","Record an invoice payment after explicit confirmation.",{invoice_id:string,amount:{type:"number"},payment_date:string,confirmed:{type:"boolean"}},["invoice_id","amount","payment_date","confirmed"]),tool("search_expenses","Search expenses.",{query:string},["query"]),
 tool("search_content","Search content items.",{query:string},["query"]),tool("create_content_item","Create content after explicit confirmation.",{title:string,status:string,client_id:nullableString,project_id:nullableString,due_date:nullableString,confirmed:{type:"boolean"}},["title","status","client_id","project_id","due_date","confirmed"]),tool("update_content_status","Change content workflow status after explicit confirmation.",{id:string,status:string,confirmed:{type:"boolean"}},["id","status","confirmed"]),tool("get_content_pipeline","Get the current content workflow.",{}),
 tool("search_prompts","Search prompts.",{query:string},["query"]),tool("get_prompt","Get a prompt and its template.",{id:string},["id"]),tool("render_prompt_with_variables","Render a prompt with variable values and track usage.",{id:string,variables:{type:"object",additionalProperties:{type:"string"}}},["id","variables"]),tool("create_decision","Create a decision after explicit confirmation.",{title:string,decision:string,project_id:nullableString,impact:string,confidence:string,review_date:nullableString,confirmed:{type:"boolean"}},["title","decision","project_id","impact","confidence","review_date","confirmed"]),tool("get_decisions_due_for_review","Get decisions due for review.",{}),
 tool("get_fitness_week","Get this week's activities and target progress.",{}),tool("log_fitness_activity","Log an activity after explicit confirmation.",{activity_type:string,date:string,duration_minutes:{type:["number","null"]},distance_km:{type:["number","null"]},confirmed:{type:"boolean"}},["activity_type","date","duration_minutes","distance_km","confirmed"]),tool("get_fitness_targets","Get active fitness targets.",{}),tool("get_productivity_summary","Get productivity analytics.",{}),tool("get_business_summary","Get business analytics.",{}),tool("get_project_summary","Get project analytics.",{}),tool("get_content_summary","Get content analytics.",{}),tool("get_fitness_summary","Get fitness analytics.",{}),tool("get_today_insights","Get ranked cross-domain Today insights.",{})
];
type Ctx={client:SupabaseClient;userId:string};
const searchSchema=query;const writeGuard=(confirmed:boolean)=>confirmed?null:{confirmation_required:true,message:"Ask the user to confirm this change before executing it."};
async function search(ctx:Ctx,table:string,column:string,value:string,extra="*"){let request=ctx.client.from(table).select(extra).eq("user_id",ctx.userId).is("deleted_at",null);if(value)request=request.ilike(column,`%${value.replaceAll("%","\\%")}%`);const{data,error}=await request.limit(25);if(error)throw error;return data??[]}
export async function executeAssistantTool(ctx:Ctx,name:string,raw:unknown){
 if(name==="search_tasks"){const input=searchSchema.parse(raw);return search(ctx,"tasks","title",input.query)}if(name==="search_projects"){const input=searchSchema.parse(raw);return search(ctx,"projects","name",input.query)}if(name==="search_notes"){const input=searchSchema.parse(raw);return search(ctx,"notes","title",input.query)}if(name==="search_clients"){const input=searchSchema.parse(raw);return search(ctx,"clients","name",input.query)}if(name==="search_decisions"){const input=searchSchema.parse(raw);return search(ctx,"decisions","title",input.query)}
 if(name==="get_waiting_items")return search(ctx,"waiting_items","title","");if(name==="get_goals")return search(ctx,"goals","title","");
 if(name==="get_project"){const input=id.parse(raw);const project=await ctx.client.from("projects").select("*,clients(name),goals(title)").eq("id",input.id).eq("user_id",ctx.userId).maybeSingle();if(project.error)throw project.error;if(!project.data)return null;const[tasks,notes,decisions,waiting]=await Promise.all(["tasks","notes","decisions","waiting_items"].map((table)=>ctx.client.from(table).select("*").eq("user_id",ctx.userId).eq("project_id",input.id).limit(50)));return{project:project.data,tasks:tasks.data??[],notes:notes.data??[],decisions:decisions.data??[],waiting:waiting.data??[]}}
 if(name==="get_calendar"){const input=z.object({start:z.iso.datetime({offset:true}),end:z.iso.datetime({offset:true})}).strict().parse(raw);const{data,error}=await ctx.client.from("calendar_events").select("*").eq("user_id",ctx.userId).gte("starts_at",input.start).lte("starts_at",input.end).is("deleted_at",null).order("starts_at");if(error)throw error;return data??[]}
 if(name==="create_task"){const input=z.object({title:z.string().min(1).max(240),due_date:z.iso.date().nullable(),project_id:z.uuid().nullable(),confirmed:z.boolean()}).strict().parse(raw);const blocked=writeGuard(input.confirmed);if(blocked)return blocked;return createRecord(ctx.client,ctx.userId,"tasks",{title:input.title,due_date:input.due_date,project_id:input.project_id,status:"inbox",priority:"none",created_by:"ai"})}
 if(name==="create_note"){const input=z.object({title:z.string().min(1).max(240),content:z.string().max(20000),project_id:z.uuid().nullable(),confirmed:z.boolean()}).strict().parse(raw);const blocked=writeGuard(input.confirmed);if(blocked)return blocked;return createRecord(ctx.client,ctx.userId,"notes",{title:input.title,content:input.content,project_id:input.project_id,category:"note",created_by:"ai"})}
 if(name==="create_followup"){const input=z.object({title:z.string().min(1).max(240),client_id:z.uuid().nullable(),due_at:z.iso.datetime({offset:true}).nullable(),confirmed:z.boolean()}).strict().parse(raw);const blocked=writeGuard(input.confirmed);if(blocked)return blocked;return createRecord(ctx.client,ctx.userId,"followups",{title:input.title,client_id:input.client_id,due_at:input.due_at,status:"open"})}
 if(name==="update_task"){const input=z.object({id:z.uuid(),title:z.string().min(1).max(240).nullable(),status:z.enum(["inbox","planned","in_progress","waiting","blocked","completed","cancelled"]).nullable(),due_date:z.iso.date().nullable(),confirmed:z.boolean()}).strict().parse(raw);const blocked=writeGuard(input.confirmed);if(blocked)return blocked;const changes=Object.fromEntries(Object.entries(input).filter(([key,value])=>key!=="id"&&key!=="confirmed"&&value!==null));return updateRecord(ctx.client,ctx.userId,"tasks",input.id,changes)}
 if(name==="complete_task"){const input=z.object({id:z.uuid(),confirmed:z.boolean()}).strict().parse(raw);const blocked=writeGuard(input.confirmed);if(blocked)return blocked;return updateRecord(ctx.client,ctx.userId,"tasks",input.id,{status:"completed",completed_at:new Date().toISOString()})}
 if(name==="create_calendar_event"){const input=z.object({title:z.string().min(1).max(240),starts_at:z.iso.datetime({offset:true}),ends_at:z.iso.datetime({offset:true}),timezone:z.string().min(1).max(120),confirmed:z.boolean()}).strict().parse(raw);const blocked=writeGuard(input.confirmed);if(blocked)return blocked;let event=await createRecord(ctx.client,ctx.userId,"calendar",{title:input.title,starts_at:input.starts_at,ends_at:input.ends_at,timezone:input.timezone,all_day:false,status:"confirmed"});event=await pushGoogleEvent(ctx.client,ctx.userId,event);return event}
 if(name==="get_finance_summary")return getFinanceSummary(ctx.client,ctx.userId);if(name==="search_invoices"){const input=query.parse(raw);return search(ctx,"invoices","title",input.query)}if(name==="search_expenses"){const input=query.parse(raw);return search(ctx,"expenses","description",input.query)}
 if(name==="create_invoice"){const input=z.object({title:z.string().min(1).max(240),client_id:z.uuid().nullable(),project_id:z.uuid().nullable(),subtotal:z.number().nonnegative(),tax_amount:z.number().nonnegative(),discount_amount:z.number().nonnegative(),currency:z.string().length(3),due_date:z.iso.date().nullable(),confirmed:z.boolean()}).strict().parse(raw);const blocked=writeGuard(input.confirmed);if(blocked)return blocked;const{confirmed,...values}=input;void confirmed;return createRecord(ctx.client,ctx.userId,"invoices",{...values,status:"draft",issue_date:new Date().toISOString().slice(0,10)})}
 if(name==="record_payment"){const input=z.object({invoice_id:z.uuid(),amount:z.number().positive(),payment_date:z.iso.date(),confirmed:z.boolean()}).strict().parse(raw);const blocked=writeGuard(input.confirmed);if(blocked)return blocked;const{data,error}=await ctx.client.rpc("record_invoice_payment",{payment_invoice_id:input.invoice_id,payment_amount:input.amount,payment_date_value:input.payment_date});if(error)throw error;return data}
 if(name==="search_content"){const input=query.parse(raw);return search(ctx,"content_items","title",input.query)}if(name==="get_content_pipeline")return getContentSummary(ctx.client,ctx.userId);
 if(name==="create_content_item"){const input=z.object({title:z.string().min(1).max(240),status:z.enum(["idea","brief","copy","designing","review","approved","scheduled","published","archived"]),client_id:z.uuid().nullable(),project_id:z.uuid().nullable(),due_date:z.iso.date().nullable(),confirmed:z.boolean()}).strict().parse(raw);const blocked=writeGuard(input.confirmed);if(blocked)return blocked;const{confirmed,...values}=input;void confirmed;return createRecord(ctx.client,ctx.userId,"content",values)}
 if(name==="update_content_status"){const input=z.object({id:z.uuid(),status:z.enum(["idea","brief","copy","designing","review","approved","scheduled","published","archived"]),confirmed:z.boolean()}).strict().parse(raw);const blocked=writeGuard(input.confirmed);if(blocked)return blocked;return updateRecord(ctx.client,ctx.userId,"content",input.id,{status:input.status,published_at:input.status==="published"?new Date().toISOString():undefined})}
 if(name==="search_prompts"){const input=query.parse(raw);return search(ctx,"prompts","title",input.query)}if(name==="get_prompt"){const input=id.parse(raw);const{data,error}=await ctx.client.from("prompts").select("*").eq("id",input.id).eq("user_id",ctx.userId).is("deleted_at",null).maybeSingle();if(error)throw error;return data}if(name==="render_prompt_with_variables"){const input=z.object({id:z.uuid(),variables:z.record(z.string(),z.string())}).strict().parse(raw);const{data,error}=await ctx.client.from("prompts").select("prompt_text,prompt,usage_count").eq("id",input.id).eq("user_id",ctx.userId).is("deleted_at",null).maybeSingle();if(error)throw error;if(!data)return null;const rendered=renderPrompt(String(data.prompt_text??data.prompt),input.variables);if(rendered.missing.length)return{error:"Missing variables",missing:rendered.missing};await ctx.client.from("prompts").update({usage_count:Number(data.usage_count??0)+1,last_used_at:new Date().toISOString()}).eq("id",input.id).eq("user_id",ctx.userId);return rendered}
 if(name==="create_decision"){const input=z.object({title:z.string().min(1).max(240),decision:z.string().min(1).max(10000),project_id:z.uuid().nullable(),impact:z.enum(["low","medium","high","critical"]),confidence:z.enum(["low","medium","high"]),review_date:z.iso.date().nullable(),confirmed:z.boolean()}).strict().parse(raw);const blocked=writeGuard(input.confirmed);if(blocked)return blocked;const{confirmed,...values}=input;void confirmed;return createRecord(ctx.client,ctx.userId,"decisions",{...values,status:"active",decision_date:new Date().toISOString().slice(0,10)})}if(name==="get_decisions_due_for_review"){const end=new Date(Date.now()+7*86400000).toISOString().slice(0,10);const{data,error}=await ctx.client.from("decisions").select("*").eq("user_id",ctx.userId).is("deleted_at",null).in("status",["active","review_due"]).lte("review_date",end);if(error)throw error;return data??[]}
 if(name==="get_fitness_week")return getFitnessWeek(ctx.client,ctx.userId);if(name==="get_fitness_targets")return search(ctx,"fitness_targets","activity_type","");if(name==="log_fitness_activity"){const input=z.object({activity_type:z.enum(["Running","Gym","Walking","Swimming","Hiking","Cycling","Other"]),date:z.iso.date(),duration_minutes:z.number().int().positive().nullable(),distance_km:z.number().nonnegative().nullable(),confirmed:z.boolean()}).strict().parse(raw);const blocked=writeGuard(input.confirmed);if(blocked)return blocked;const{confirmed,...values}=input;void confirmed;return createRecord(ctx.client,ctx.userId,"fitness",{...values,source:"ai"})}
 if(["get_productivity_summary","get_business_summary","get_project_summary","get_content_summary","get_fitness_summary"].includes(name)){const summary=await getAnalyticsSummary(ctx.client,ctx.userId);return name==="get_productivity_summary"?summary.productivity:name==="get_business_summary"?summary.business:name==="get_project_summary"?summary.projects:name==="get_content_summary"?summary.content:summary.fitness}if(name==="get_today_insights")return getTodayInsights(ctx.client,ctx.userId);
 throw new Error("Unknown assistant tool.");
}
