import {addFinancialDays,calculateBudgetVariance,evaluateInvestmentAffordability,buildCashflowForecast,rankNextFinancialMove,type FinancialData,type ForecastEntry,type FinancialRisk} from './financial-control';
export function expandedFinancialConditions(data:FinancialData,opening:Record<string,number|null>,entries:ForecastEntry[],base:FinancialRisk[],today:string){
 const risks=[...base];
 const add=(key:string,title:string,evidence:string,currency:string,route:string,amount:number|null,score=75)=>risks.push({key:'financial:'+key,title,evidence,currency,route,amount,score,severity:score>=90?'critical':'important',date:null,action:'Review financial record'});
 for(const settings of data.settings??[]){const c=String(settings.currency),buffer=settings.buffer_amount!=null?Number(settings.buffer_amount):settings.buffer_months!=null&&settings.baseline_monthly_cost!=null?Number(settings.buffer_months)*Number(settings.baseline_monthly_cost):null;if(buffer===null)continue;
  if(opening[c]!=null&&opening[c]!<buffer)add('current-buffer:'+c,'Recorded cash below buffer','Manual recorded cash is below the configured reserve.',c,'/financial-control/accounts',buffer-opening[c]!,95);
  for(const i of data.investments??[]){if(i.currency!==c||['spent','cancelled'].includes(String(i.status)))continue;const forecast=buildCashflowForecast(opening,entries.filter(e=>!(e.sourceType==='investment'&&e.sourceId===i.id)),today).find(f=>f.currency===c);if(evaluateInvestmentAffordability(Number(i.amount),opening[c]??null,forecast?.lowest??null,buffer)==='Would breach buffer')add('investment:'+i.id,'Investment needs funding review',String(i.title)+' would breach the configured cash buffer.',c,'/financial-control/investments',Number(i.amount),85);}
 }
 for(const b of data.budgets??[]){if(b.status!=='active'||String(b.period_start)>today||String(b.period_end)<today)continue;const variance=calculateBudgetVariance(b,data.expenses??[],data.obligations??[]);if(variance.budget<=0)continue;if(variance.remaining<=variance.budget*.1)add('budget:'+b.id,variance.remaining<0?'Budget exceeded':'Budget nearly allocated',String(b.name)+': recorded expenses and commitments use at least 90% of the budget.',String(b.currency),'/financial-control/budgets',Math.max(0,-variance.remaining),variance.remaining<0?85:75);}
 for(const s of data.subscriptions??[]){if(s.status!=='active'||!s.next_billing_date||String(s.next_billing_date)<today||String(s.next_billing_date)>addFinancialDays(today,7))continue;const review=(data.subscription_reviews??[]).find(r=>r.subscription_id===s.id);if(review?.status==='review'||review?.status==='cancel_candidate')add('subscription:'+s.id,'Review subscription before renewal',String(s.name)+' renews '+s.next_billing_date+'. Usage was explicitly flagged for review.',String(s.currency),'/financial-control/subscriptions',Number(s.amount));}
 return rankNextFinancialMove(risks,risks.length);
}
