import { z } from 'zod';
export const financialViews=['accounts','cashflow','inflows','outflows','receivables','collections','promises','obligations','expenses','subscriptions','budgets','runway','working-capital','profitability','concentration','scenarios','investments','allocation','risks','calendar','goals','links','settings','review/monthly','review/quarterly'] as const;
const money=z.number().finite().min(0).max(999999999999).refine(v=>Math.abs(v*100-Math.round(v*100))<0.0001,'Use at most two decimal places.');
const code=z.string().regex(/^[A-Z]{3}$/,'Use a three-letter currency code.');
const title=z.string().trim().min(1).max(240);
const date=z.string().date();
const optionalId=z.uuid().nullable().optional();
const notes=z.string().max(10000).nullable().optional();
export const financialTables={accounts:'financial_cash_accounts',snapshots:'financial_cash_snapshots',obligations:'financial_obligations',budgets:'financial_budgets',budget_lines:'financial_budget_lines',scenarios:'financial_scenarios',investments:'financial_investments',promises:'financial_payment_promises',settings:'financial_settings',subscription_reviews:'financial_subscription_reviews',links:'financial_context_links'} as const;
export type FinancialResource=keyof typeof financialTables;
export const financialSchemas={
 accounts:z.object({name:title,type:z.enum(['bank','cash','processor','wallet','other']),currency:code,status:z.enum(['active','inactive','archived']).default('active'),notes}).strict(),
 snapshots:z.object({cash_account_id:z.uuid(),currency:code,balance:z.number().finite().min(-999999999999).max(999999999999),as_of:z.string().datetime(),source:z.enum(['manual','import']).default('manual'),notes,request_id:z.uuid()}).strict(),
 obligations:z.object({title,amount:money.positive(),currency:code,due_at:date,status:z.enum(['planned','committed','due','paid','deferred','cancelled']).default('planned'),criticality:z.enum(['optional','standard','critical']).default('standard'),category:title,can_delay:z.boolean().default(false),paid_at:date.nullable().optional(),expense_id:optionalId,source_type:z.string().nullable().optional(),source_id:optionalId,owner_person_id:optionalId,notes}).strict(),
 budgets:z.object({name:title,period_start:date,period_end:date,currency:code,amount:money,scope_type:z.string().default('custom'),scope_id:optionalId,category:z.string().nullable().optional(),status:z.enum(['draft','active','closed','archived']).default('draft'),owner_person_id:optionalId,notes}).strict(),
 budget_lines:z.object({budget_id:z.uuid(),category:title,amount:money}).strict(),
 scenarios:z.object({title,type:z.enum(['base','best','stress','custom']).default('custom'),currency:code,collection_delay_days:z.number().int().min(0).max(365).default(0),inflow_change_percent:z.number().min(-100).max(500).default(0),outflow_change_percent:z.number().min(-100).max(500).default(0),monthly_cost:money.default(0),setup_cost:money.default(0),starts_at:date.nullable().optional(),include_pipeline:z.boolean().default(false),status:z.enum(['active','archived']).default('active'),notes}).strict(),
 investments:z.object({title,amount:money.positive(),currency:code,target_date:date.nullable().optional(),priority:z.enum(['low','medium','high','critical']).default('medium'),status:z.enum(['idea','considering','approved','scheduled','spent','cancelled']).default('idea'),commitment_id:optionalId,expense_id:optionalId,notes}).strict(),
 promises:z.object({invoice_id:z.uuid(),amount:money.positive(),currency:code,promised_date:date,status:z.enum(['open','met','missed','cancelled']).default('open'),notes}).strict(),
 settings:z.object({currency:code,buffer_amount:money.nullable().optional(),buffer_months:z.number().min(0).max(120).nullable().optional(),baseline_monthly_cost:money.nullable().optional(),cash_history_complete_from:date.nullable().optional(),concentration_threshold:z.number().min(.01).max(1).default(.5),stale_days:z.number().int().min(1).max(90).default(7),notes}).strict(),
 subscription_reviews:z.object({subscription_id:z.uuid(),status:z.enum(['keep','review','cancel_candidate','unknown']).default('unknown'),reviewed_at:date.nullable().optional(),criticality:z.enum(['optional','standard','critical']).default('standard'),owner_person_id:optionalId,notes}).strict(),
 links:z.object({origin_type:z.enum(['account','budget','obligation','scenario','investment']),origin_id:z.uuid(),target_type:z.string().min(1),target_id:z.uuid()}).strict(),
};
export function validateFinancialRecord(resource:FinancialResource,input:unknown) {
 const value=financialSchemas[resource].parse(input) as Record<string,unknown>;
 if(resource==='budgets'&&String(value.period_end)<String(value.period_start))throw new Error('Budget end must be on or after its start.');
 if(resource==='snapshots'&&Date.parse(String(value.as_of))>Date.now())throw new Error('Balance date cannot be in the future.');
 if(resource==='obligations'&&value.status==='paid'&&!value.paid_at)throw new Error('Record the actual paid date.');
 if(resource==='obligations'&&Boolean(value.source_type)!==Boolean(value.source_id))throw new Error('Select both source type and source record.');
 if(resource==='scenarios'&&(Number(value.monthly_cost)>0||Number(value.setup_cost)>0)&&!value.starts_at)throw new Error('Choose the hypothetical cost start date.');
 return value;
}
export const financialTargets:Record<string,{table:string;label:string;route:string}>={
 account:{table:'financial_cash_accounts',label:'name',route:'/financial-control/accounts'},budget:{table:'financial_budgets',label:'name',route:'/financial-control/budgets'},obligation:{table:'financial_obligations',label:'title',route:'/financial-control/obligations'},scenario:{table:'financial_scenarios',label:'title',route:'/financial-control/scenarios'},investment:{table:'financial_investments',label:'title',route:'/financial-control/investments'},
 invoice:{table:'invoices',label:'title',route:'/finance/invoices'},payment:{table:'payments',label:'reference',route:'/finance/invoices'},expense:{table:'expenses',label:'description',route:'/finance/expenses'},subscription:{table:'subscriptions',label:'name',route:'/finance/subscriptions'},client:{table:'clients',label:'name',route:'/clients'},project:{table:'projects',label:'name',route:'/projects'},opportunity:{table:'opportunities',label:'title',route:'/pipeline'},supplier:{table:'supplier_records',label:'name',route:'/founder'},supplier_order:{table:'supplier_orders',label:'reference',route:'/founder/supplier-orders'},product:{table:'product_catalog_refs',label:'name',route:'/founder/products'},campaign:{table:'campaigns',label:'name',route:'/campaigns'},goal:{table:'goals',label:'title',route:'/goals'},commitment:{table:'strategic_commitments',label:'title',route:'/control-tower'},milestone:{table:'strategic_milestones',label:'title',route:'/control-tower'},period:{table:'planning_periods',label:'title',route:'/control-tower'},gate:{table:'decision_gates',label:'title',route:'/control-tower'},person:{table:'team_people',label:'name',route:'/team/people'},process:{table:'process_templates',label:'name',route:'/operations/processes'},decision:{table:'decisions',label:'title',route:'/decisions'},topic:{table:'research_topics',label:'title',route:'/knowledge'},finding:{table:'research_findings',label:'title',route:'/knowledge'},source:{table:'knowledge_sources',label:'title',route:'/knowledge'},brief:{table:'research_briefs',label:'title',route:'/knowledge/briefs'},company:{table:'companies',label:'name',route:'/founder'},roadmap:{table:'product_roadmap_items',label:'title',route:'/founder'},
};
