export type FitnessActivity={id:string;activity_type:string;date:string;duration_minutes?:number|null;distance_km?:number|null;calories?:number|null;effort?:string|null;notes?:string|null;source?:string;metadata?:{steps?:number;total_volume_kg?:number}};
export type FitnessTarget={id:string;activity_type:string;target_type:string;target_value:number;period:string;active:boolean};
export function dayShift(day:string,offset:number){const d=new Date(`${day}T12:00:00Z`);d.setUTCDate(d.getUTCDate()+offset);return d.toISOString().slice(0,10)}
export function weekStart(day:string,start=1){const d=new Date(`${day}T12:00:00Z`);return dayShift(day,-((d.getUTCDay()-start+7)%7))}
export function periodActivities(rows:FitnessActivity[],start:string,days=7){const end=dayShift(start,days-1);return rows.filter(r=>r.date>=start&&r.date<=end)}
export function activityValue(row:FitnessActivity,measure:string){return measure==="steps"?Number(row.metadata?.steps??0):measure==="volume"?Number(row.metadata?.total_volume_kg??0):Number(row[measure as keyof FitnessActivity]??0)||0}
export function fitnessTotals(rows:FitnessActivity[]){return {sessions:rows.filter(r=>!['pacer','myfitnesspal'].includes(r.source??'')).length,distance:rows.reduce((s,r)=>s+activityValue(r,'distance_km'),0),duration:rows.reduce((s,r)=>s+activityValue(r,'duration_minutes'),0),steps:rows.reduce((s,r)=>s+activityValue(r,'steps'),0),volume:rows.reduce((s,r)=>s+activityValue(r,'volume'),0),calories:rows.filter(r=>r.source!=="myfitnesspal").reduce((s,r)=>s+activityValue(r,'calories'),0)}}
export function targetActual(target:FitnessTarget,rows:FitnessActivity[]){const matching=rows.filter(r=>target.activity_type==='Steps'?r.source==='pacer':target.activity_type==='Nutrition'?r.source==='myfitnesspal':r.activity_type===target.activity_type);return target.target_type==='sessions'?matching.length:target.target_type==='days'?new Set(matching.map(r=>r.date)).size:matching.reduce((s,r)=>s+activityValue(r,target.target_type),0)}
export function dayStreak(rows:FitnessActivity[],today:string){const days=new Set(rows.map(r=>r.date));let count=0;let cursor=days.has(today)?today:dayShift(today,-1);while(days.has(cursor)){count++;cursor=dayShift(cursor,-1)}return count}
export function fitnessPreview(today:string){const start=weekStart(today);const activities:FitnessActivity[]=[];for(let week=0;week<3;week++){const base=dayShift(start,-week*7);[0,2,4].forEach((day,i)=>activities.push({id:`run-${week}-${day}`,activity_type:'Running',date:dayShift(base,day),duration_minutes:32+i*5,distance_km:3.1+i*.7,calories:240+i*65,effort:i===2?'hard':'moderate',source:'strava',notes:['Morning easy run','Park intervals','Evening run'][i]}));[1,3].forEach((day,i)=>activities.push({id:`gym-${week}-${day}`,activity_type:'Gym',date:dayShift(base,day),duration_minutes:48+i*7,calories:310+i*40,source:'hevy',effort:'moderate',notes:i?'Leg day':'Upper body strength',metadata:{total_volume_kg:2450+i*1470}}));for(let day=0;day<7;day++){activities.push({id:`steps-${week}-${day}`,activity_type:'Walking',date:dayShift(base,day),source:'pacer',metadata:{steps:[5100,6200,4500,7100,5200,5800,4600][day]}});if(day!==5)activities.push({id:`nutrition-${week}-${day}`,activity_type:'Other',date:dayShift(base,day),source:'myfitnesspal',calories:2100+day*40,notes:'Balanced meals · nutrition logged'})}}for(const row of activities){if(row.date>=start)continue;const factor=row.date>=dayShift(start,-7)?.82:.67;if(row.duration_minutes)row.duration_minutes=Math.round(row.duration_minutes*factor);if(row.distance_km)row.distance_km=Number((row.distance_km*factor).toFixed(1));if(row.calories&&row.source!=='myfitnesspal')row.calories=Math.round(row.calories*factor);if(row.metadata?.steps)row.metadata.steps=Math.round(row.metadata.steps*factor);if(row.metadata?.total_volume_kg)row.metadata.total_volume_kg=Math.round(row.metadata.total_volume_kg*factor);}return {activities,targets:[{id:'target-run',activity_type:'Running',target_type:'sessions',target_value:5,period:'week',active:true},{id:'target-gym',activity_type:'Gym',target_type:'sessions',target_value:3,period:'week',active:true},{id:'target-steps',activity_type:'Steps',target_type:'steps',target_value:50000,period:'week',active:true},{id:'target-nutrition',activity_type:'Nutrition',target_type:'days',target_value:7,period:'week',active:true}] as FitnessTarget[]}}

/** Stable dashboard categories; missing goals are display-only, never saved records. */
export function weeklyFitnessCards(targets:FitnessTarget[]){
 return ([['Running','sessions'],['Gym','sessions'],['Steps','steps'],['Nutrition','days']] as const).map(([kind,measure])=>{
  const saved=targets.find(target=>target.active&&target.activity_type===kind&&target.period==='week')??targets.find(target=>target.active&&target.activity_type===kind);
  return {hasTarget:!!saved,target:saved??{id:`summary-${kind}`,activity_type:kind,target_type:measure,target_value:0,period:'week',active:false}};
 });
}

/** Calendar day in the browser timezone, including around local midnight. */
export function fitnessLocalDay(now=new Date()){return `${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,"0")}-${String(now.getDate()).padStart(2,"0")}`}
