import type { SupabaseClient } from "@supabase/supabase-js";
import { daysBetween,effectiveInvoiceStatus,rankInsights,targetProgress,type Insight } from "@/lib/v2";

type Client=SupabaseClient<Record<string,unknown>>;
type Row=Record<string,unknown>&{id:string};
type InvoiceRow=Row&{status:string;due_date?:string|null;amount_remaining?:number|null;effective_status:string};
type FitnessTargetRow=Row&{activity_type:string;target_type:string;target_value:number;progress:{actual:number;target:number;remaining:number;complete:boolean}};
const isoDay=(date:Date)=>date.toISOString().slice(0,10);
const money=(value:number,currency="MAD")=>new Intl.NumberFormat("en",{style:"currency",currency,maximumFractionDigits:0}).format(value);
function assertResults(results:{error:unknown}[]){const failed=results.find((result)=>result.error);if(failed?.error)throw failed.error}

export async function getFinanceSummary(client:Client,userId:string,now=new Date()){
  const today=isoDay(now);const monthStart=`${today.slice(0,7)}-01`;const monthEnd=new Date(Date.UTC(now.getUTCFullYear(),now.getUTCMonth()+1,0)).toISOString().slice(0,10);
  const [invoiceResult,paymentResult,expenseResult,subscriptionResult]=await Promise.all([
    client.from("invoices").select("*,clients(id,name),projects(id,name)").eq("user_id",userId).is("deleted_at",null).order("due_date"),
    client.from("payments").select("*,clients(id,name),projects(id,name),invoices(id,invoice_number,title)").eq("user_id",userId).is("deleted_at",null).gte("payment_date",monthStart).lte("payment_date",monthEnd).order("payment_date",{ascending:false}),
    client.from("expenses").select("*,clients(id,name),projects(id,name)").eq("user_id",userId).is("deleted_at",null).gte("expense_date",monthStart).lte("expense_date",monthEnd).order("expense_date",{ascending:false}),
    client.from("subscriptions").select("*,projects(id,name)").eq("user_id",userId).eq("status","active").is("deleted_at",null).order("next_billing_date")
  ]);assertResults([invoiceResult,paymentResult,expenseResult,subscriptionResult]);
  const invoices=((invoiceResult.data??[]) as unknown as (Row&{status:string;due_date?:string|null;amount_remaining?:number|null})[]).map((invoice)=>({...invoice,effective_status:effectiveInvoiceStatus(invoice,today)})) as InvoiceRow[];const payments=(paymentResult.data??[]) as unknown as Row[];const expenses=(expenseResult.data??[]) as unknown as Row[];const subscriptions=(subscriptionResult.data??[]) as unknown as Row[];
  const overdue=invoices.filter((item)=>item.effective_status==="overdue");const currencies=new Set(["MAD",...invoices.map((item)=>String(item.currency??"MAD")),...payments.map((item)=>String(item.currency??"MAD")),...expenses.map((item)=>String(item.currency??"MAD"))]);const metricsFor=(currency:string)=>{const currencyInvoices=invoices.filter((item)=>String(item.currency??"MAD")===currency);const received=payments.filter((item)=>String(item.currency??"MAD")===currency).reduce((sum,item)=>sum+Number(item.amount??0),0);const expenseTotal=expenses.filter((item)=>String(item.currency??"MAD")===currency).reduce((sum,item)=>sum+Number(item.amount??0),0);return{expected:currencyInvoices.filter((item)=>String(item.due_date??"").startsWith(today.slice(0,7))&&!['paid','cancelled'].includes(String(item.effective_status))).reduce((sum,item)=>sum+Number(item.amount_remaining??0),0),received,outstanding:currencyInvoices.filter((item)=>!['paid','cancelled'].includes(String(item.effective_status))).reduce((sum,item)=>sum+Number(item.amount_remaining??0),0),overdue:currencyInvoices.filter((item)=>item.effective_status==="overdue").reduce((sum,item)=>sum+Number(item.amount_remaining??0),0),expenses:expenseTotal,net:received-expenseTotal}};const metricsByCurrency=Object.fromEntries([...currencies].map((currency)=>[currency,metricsFor(currency)]));
  return{currency:"MAD",period:{start:monthStart,end:monthEnd},metrics:metricsByCurrency.MAD,metricsByCurrency,invoices,payments,expenses,subscriptions,overdue};
}

export async function getContentSummary(client:Client,userId:string,now=new Date()){
  const today=isoDay(now);const soon=isoDay(new Date(now.getTime()+7*86400000));const [items,campaigns]=await Promise.all([
    client.from("content_items").select("*,clients(id,name),projects(id,name),campaigns(id,name)").eq("user_id",userId).is("deleted_at",null).neq("status","archived").order("due_date"),
    client.from("campaigns").select("*,clients(id,name),projects(id,name)").eq("user_id",userId).is("deleted_at",null).order("end_date")
  ]);assertResults([items,campaigns]);const rows=(items.data??[]) as Row[];
  return{items:rows,campaigns:(campaigns.data??[]) as Row[],dueSoon:rows.filter((item)=>item.due_date&&String(item.due_date)>=today&&String(item.due_date)<=soon&&!['published','archived'].includes(String(item.status))),awaitingApproval:rows.filter((item)=>item.approval_status==="pending"||item.status==="review"),scheduled:rows.filter((item)=>item.status==="scheduled"),recentlyPublished:rows.filter((item)=>item.status==="published").slice(-8)};
}

export async function getFitnessWeek(client:Client,userId:string,now=new Date()){
  const profile=await client.from("profiles").select("week_starts_on").eq("id",userId).maybeSingle();if(profile.error)throw profile.error;const profileRow=profile.data as unknown as {week_starts_on?:number}|null;const day=now.getUTCDay();const start=new Date(now);start.setUTCDate(start.getUTCDate()-((day-Number(profileRow?.week_starts_on??1)+7)%7));const end=new Date(start);end.setUTCDate(end.getUTCDate()+6);
  const [activities,targets]=await Promise.all([client.from("fitness_activities").select("*").eq("user_id",userId).is("deleted_at",null).gte("date",isoDay(start)).lte("date",isoDay(end)).order("date",{ascending:false}),client.from("fitness_targets").select("*").eq("user_id",userId).eq("active",true).is("deleted_at",null)]);assertResults([activities,targets]);const rows=(activities.data??[]) as unknown as Row[];const targetRows=(targets.data??[]) as unknown as (Row&{activity_type:string;target_type:string;target_value:number})[];const targetsWithProgress=targetRows.map((target)=>({...target,progress:targetProgress(target,rows)})) as FitnessTargetRow[];return{period:{start:isoDay(start),end:isoDay(end)},activities:rows,targets:targetsWithProgress,totals:{sessions:rows.length,distance_km:rows.reduce((sum,item)=>sum+Number(item.distance_km??0),0),duration_minutes:rows.reduce((sum,item)=>sum+Number(item.duration_minutes??0),0)}};
}

export async function getAnalyticsSummary(client:Client,userId:string,now=new Date()){
  const today=isoDay(now);const from=isoDay(new Date(now.getTime()-28*86400000));
  const [tasks,projects,focus,waiting,milestones,finance,content,fitness]=await Promise.all([
    client.from("tasks").select("id,status,project_id,completed_at,created_at,due_date,estimated_minutes,actual_minutes").eq("user_id",userId).is("deleted_at",null).or(`created_at.gte.${from}T00:00:00Z,completed_at.gte.${from}T00:00:00Z`),
    client.from("projects").select("id,name,status,progress,target_date,created_at").eq("user_id",userId).is("deleted_at",null),
    client.from("focus_sessions").select("project_id,task_id,duration_seconds,started_at").eq("user_id",userId).gte("started_at",`${from}T00:00:00Z`),
    client.from("waiting_items").select("id,project_id,status,requested_at,created_at").eq("user_id",userId).is("deleted_at",null),
    client.from("milestones").select("id,project_id,status,progress,target_date").eq("user_id",userId),
    getFinanceSummary(client,userId,now),getContentSummary(client,userId,now),getFitnessWeek(client,userId,now)
  ]);
  assertResults([tasks,projects,focus,waiting,milestones]);
  const taskRows=(tasks.data??[]) as unknown as Row[];const projectRows=(projects.data??[]) as unknown as Row[];const focusRows=(focus.data??[]) as unknown as Row[];const waitingRows=(waiting.data??[]) as unknown as Row[];const milestoneRows=(milestones.data??[]) as unknown as Row[];
  const completed=taskRows.filter((item)=>item.status==="completed"&&String(item.completed_at??"")>=`${from}T00:00:00Z`);const overdue=taskRows.filter((item)=>item.due_date&&String(item.due_date)<today&&!['completed','cancelled'].includes(String(item.status)));const focusSeconds=focusRows.reduce((sum,item)=>sum+Number(item.duration_seconds??0),0);
  const countBy=(rows:Row[],key:string,label:((row:Row)=>string)=(row)=>String(row[key]??"Unassigned"))=>Object.fromEntries([...rows.reduce((map,row)=>{const value=label(row);map.set(value,(map.get(value)??0)+1);return map},new Map<string,number>())].sort((a,b)=>b[1]-a[1]));
  const projectNames=new Map(projectRows.map((project)=>[project.id,String(project.name)]));const tasksByProject=countBy(taskRows,"project_id",(row)=>projectNames.get(String(row.project_id))??"Unassigned");const focusByProject=Object.fromEntries([...focusRows.reduce((map,row)=>{const name=projectNames.get(String(row.project_id))??"Unassigned";map.set(name,(map.get(name)??0)+Number(row.duration_seconds??0)/3600);return map},new Map<string,number>())].sort((a,b)=>b[1]-a[1]));
  const openWaiting=waitingRows.filter((item)=>item.status==="waiting");const averageWaitingDays=openWaiting.length?openWaiting.reduce((sum,item)=>sum+Math.max(0,(now.getTime()-new Date(String(item.requested_at??item.created_at)).getTime())/86400000),0)/openWaiting.length:0;
  const paidInvoices=finance.invoices.filter((invoice)=>invoice.paid_at&&invoice.due_date);const averagePaymentDelay=paidInvoices.length?paidInvoices.reduce((sum,invoice)=>sum+Math.max(0,daysBetween(String(invoice.due_date),String(invoice.paid_at).slice(0,10))),0)/paidInvoices.length:0;const revenueBy=(key:"clients"|"projects")=>Object.fromEntries([...finance.payments.reduce((map,payment)=>{const relation=payment[key] as {name?:string}|null;const name=relation?.name??"Unassigned";const currency=String(payment.currency??"MAD");const mapKey=`${name} (${currency})`;map.set(mapKey,(map.get(mapKey)??0)+Number(payment.amount??0));return map},new Map<string,number>())].sort((a,b)=>b[1]-a[1]));
  const createdThisMonth=content.items.filter((item)=>String(item.created_at??"").startsWith(today.slice(0,7))).length;const publishedThisMonth=content.items.filter((item)=>String(item.published_at??item.publish_date??"").startsWith(today.slice(0,7))).length;const approved=content.items.filter((item)=>item.approved_at&&item.created_at);const averageApprovalHours=approved.length?approved.reduce((sum,item)=>sum+(new Date(String(item.approved_at)).getTime()-new Date(String(item.created_at)).getTime())/3600000,0)/approved.length:null;
  const activityDays=new Set(fitness.activities.map((activity)=>String(activity.date))).size;const targetsMet=fitness.targets.filter((target)=>target.progress.complete).length;
  return{
    productivity:{completed:completed.length,total:taskRows.length,completion_rate:taskRows.length?completed.length/taskRows.length:0,overdue_rate:taskRows.length?overdue.length/taskRows.length:0,focus_hours:focusSeconds/3600,estimate_delta_minutes:completed.reduce((sum,item)=>sum+Number(item.actual_minutes??0)-Number(item.estimated_minutes??0),0),tasks_by_project:tasksByProject,focus_by_project:focusByProject,average_waiting_days:averageWaitingDays},
    projects:{active:projectRows.filter((item)=>item.status==="active").length,items:projectRows,focus:focusRows,milestones:{total:milestoneRows.length,completed:milestoneRows.filter((item)=>item.status==="completed"||Number(item.progress)>=100).length},blocked_tasks:taskRows.filter((item)=>item.status==="blocked").length},
    business:{...finance,revenueByClient:revenueBy("clients"),revenueByProject:revenueBy("projects"),averagePaymentDelay},
    content:{...content,metrics:{createdThisMonth,publishedThisMonth,averageApprovalHours,byPlatform:countBy(content.items,"platform"),byClient:countBy(content.items,"client_id",(row)=>String((row.clients as {name?:string}|null)?.name??"Unassigned"))}},
    fitness:{...fitness,analytics:{activeDays:activityDays,targetAdherence:fitness.targets.length?targetsMet/fitness.targets.length:0,activityMix:countBy(fitness.activities,"activity_type")}}
  };
}

export async function getTodayInsights(client:Client,userId:string,now=new Date()){
  const today=isoDay(now);const soon=isoDay(new Date(now.getTime()+7*86400000));const historyStart=isoDay(new Date(now.getTime()-120*86400000));const [finance,content,fitness,decisions,waiting,blocked,preferences,expenseHistory]=await Promise.all([getFinanceSummary(client,userId,now),getContentSummary(client,userId,now),getFitnessWeek(client,userId,now),client.from("decisions").select("*").eq("user_id",userId).is("deleted_at",null).in("status",["active","review_due"]).lte("review_date",soon),client.from("waiting_items").select("*").eq("user_id",userId).eq("status","waiting").is("deleted_at",null),client.from("tasks").select("*,projects(id,name,priority)").eq("user_id",userId).eq("status","blocked").is("deleted_at",null),client.from("notification_preferences").select("category,enabled,minimum_severity").eq("user_id",userId),client.from("expenses").select("category,amount,expense_date,currency").eq("user_id",userId).is("deleted_at",null).gte("expense_date",historyStart)]);assertResults([decisions,waiting,blocked,preferences,expenseHistory]);const generated=now.toISOString();const insights:Insight[]=[];
  for(const invoice of finance.overdue){const amount=Number(invoice.amount_remaining??0);if(amount<500)continue;const clientName=String((invoice.clients as {name?:string}|null)?.name??invoice.title??invoice.invoice_number??"An invoice");const days=Math.max(1,daysBetween(String(invoice.due_date),today));insights.push({id:`invoice-${invoice.id}`,type:"invoice_overdue",priority:90+Math.min(9,Math.floor(amount/5000)),severity:days>=14?"critical":"high",title:`${money(amount,String(invoice.currency??"MAD"))} overdue`,message:`${clientName} is ${days} day${days===1?"":"s"} overdue.`,entity_type:"invoice",entity_id:invoice.id,action_label:"Review invoice",action_route:`/finance/invoices?invoice=${invoice.id}`,expires_at:null,generated_at:generated})}
  for(const invoice of finance.invoices){if(["paid","cancelled","overdue"].includes(invoice.effective_status)||!invoice.due_date)continue;const days=daysBetween(today,String(invoice.due_date));if(days<0||days>3)continue;const amount=Number(invoice.amount_remaining??0);insights.push({id:`invoice-due-${invoice.id}`,type:"invoice_due",priority:days===0?82:68,severity:days===0?"high":"medium",title:`${money(amount,String(invoice.currency??"MAD"))} due ${days===0?"today":days===1?"tomorrow":`in ${days} days`}`,message:String(invoice.title??invoice.invoice_number??"Invoice payment is approaching."),entity_type:"invoice",entity_id:invoice.id,action_label:"Review invoice",action_route:`/finance/invoices?invoice=${invoice.id}`,expires_at:`${invoice.due_date}T23:59:59Z`,generated_at:generated})}
  for(const subscription of finance.subscriptions){if(!subscription.next_billing_date)continue;const days=daysBetween(today,String(subscription.next_billing_date));if(days<0||days>7)continue;insights.push({id:`subscription-${subscription.id}`,type:"subscription_renewal",priority:days<=1?64:48,severity:days<=1?"medium":"low",title:`${String(subscription.name)} renews ${days===0?"today":days===1?"tomorrow":`in ${days} days`}`,message:`${money(Number(subscription.amount??0),String(subscription.currency??"MAD"))} ${String(subscription.billing_cycle??"subscription")}.`,entity_type:"subscription",entity_id:subscription.id,action_label:"Review subscription",action_route:"/finance/subscriptions",expires_at:`${subscription.next_billing_date}T23:59:59Z`,generated_at:generated})}
  const friday=new Date(now);friday.setUTCDate(friday.getUTCDate()+((5-friday.getUTCDay()+7)%7));const fridayDay=isoDay(friday);const fridayTotals=new Map<string,number>();for(const invoice of finance.invoices){if(!invoice.due_date||String(invoice.due_date)<today||String(invoice.due_date)>fridayDay||['paid','cancelled','overdue'].includes(invoice.effective_status))continue;const currency=String(invoice.currency??"MAD");fridayTotals.set(currency,(fridayTotals.get(currency)??0)+Number(invoice.amount_remaining??0))}for(const[currency,expectedByFriday]of fridayTotals){if(expectedByFriday<1000)continue;insights.push({id:`finance-friday-${currency}-${fridayDay}`,type:"invoice_expected",priority:66,severity:"medium",title:`${money(expectedByFriday,currency)} expected by Friday`,message:"Open invoices with due dates in the current workweek.",entity_type:"invoice",entity_id:`${currency}-${fridayDay}`,action_label:"Review receivables",action_route:"/finance/invoices",expires_at:`${fridayDay}T23:59:59Z`,generated_at:generated})}
  const history=(expenseHistory.data??[]) as unknown as {category:string;amount:number;expense_date:string;currency:string}[];const currentMonth=today.slice(0,7);const totals=new Map<string,Map<string,number>>();for(const expense of history){const month=expense.expense_date.slice(0,7);const key=`${expense.category}\u0000${expense.currency??"MAD"}`;const months=totals.get(key)??new Map<string,number>();months.set(month,(months.get(month)??0)+Number(expense.amount));totals.set(key,months)}for(const [key,months] of totals){const[category,currency]=key.split("\u0000");const current=months.get(currentMonth)??0;const previous=[...months.entries()].filter(([month])=>month!==currentMonth).map(([,amount])=>amount);if(previous.length<2)continue;const average=previous.reduce((sum,amount)=>sum+amount,0)/previous.length;if(current>=Math.max(500,average*1.5))insights.push({id:`expense-${category}-${currency}-${currentMonth}`,type:"expense_above_normal",priority:62,severity:"medium",title:`${category} spending is above normal`,message:`${money(current,currency)} this month versus ${money(average,currency)} in prior active months.`,entity_type:"expense",entity_id:`${category}-${currency}`,action_label:"Review expenses",action_route:"/finance/expenses",expires_at:`${new Date(Date.UTC(now.getUTCFullYear(),now.getUTCMonth()+1,0)).toISOString().slice(0,10)}T23:59:59Z`,generated_at:generated})}
  for(const item of content.dueSoon){const days=daysBetween(today,String(item.due_date));if(days>2)continue;insights.push({id:`content-${item.id}`,type:"content_deadline",priority:days<=0?88:76,severity:days<=0?"high":"medium",title:String(item.title),message:`Due ${days<=0?"today":days===1?"tomorrow":`in ${days} days`} and still in ${String(item.status)}.`,entity_type:"content",entity_id:item.id,action_label:"Open content",action_route:`/content/${item.id}`,expires_at:`${item.due_date}T23:59:59Z`,generated_at:generated})}
  if(content.awaitingApproval.length>=2)insights.push({id:"content-approvals",type:"content_approval",priority:70,severity:"medium",title:"Client approval is waiting",message:`${content.awaitingApproval.length} content items need approval.`,entity_type:"content",entity_id:"pipeline",action_label:"Review pipeline",action_route:"/content?view=kanban",expires_at:null,generated_at:generated});
  for(const campaign of content.campaigns){if(!campaign.end_date||!['planning','active'].includes(String(campaign.status)))continue;const days=daysBetween(today,String(campaign.end_date));if(days<0||days>2)continue;const unfinished=content.items.filter((item)=>item.campaign_id===campaign.id&&!['published','archived'].includes(String(item.status)));if(unfinished.length<2)continue;insights.push({id:`campaign-${campaign.id}`,type:"content_campaign_deadline",priority:80,severity:"high",title:String(campaign.name),message:`${unfinished.length} unfinished pieces with ${days===0?"less than one day":`${days} day${days===1?"":"s"}`} remaining.`,entity_type:"campaign",entity_id:campaign.id,action_label:"Open campaign",action_route:"/campaigns",expires_at:`${campaign.end_date}T23:59:59Z`,generated_at:generated})}
  const decisionRows=(decisions.data??[]) as unknown as Row[];for(const decision of decisionRows){const days=daysBetween(today,String(decision.review_date));if(days>7)continue;insights.push({id:`decision-${decision.id}`,type:"decision_review",priority:String(decision.impact)==="critical"?86:String(decision.impact)==="high"?74:58,severity:String(decision.impact)==="critical"?"high":"medium",title:String(decision.title),message:`A ${String(decision.impact)}-impact decision is due for review ${days<=0?"now":`in ${days} days`}.`,entity_type:"decision",entity_id:decision.id,action_label:"Review decision",action_route:`/decisions/${decision.id}`,expires_at:decision.review_date?`${decision.review_date}T23:59:59Z`:null,generated_at:generated})}
  const lowConfidence=decisionRows.filter((decision)=>decision.confidence==="low");if(lowConfidence.length>=2)insights.push({id:"decisions-low-confidence",type:"decision_confidence",priority:54,severity:"medium",title:"Active decisions need confidence",message:`${lowConfidence.length} decisions approaching review were recorded with low confidence.`,entity_type:"decision",entity_id:"low-confidence",action_label:"Review decisions",action_route:"/decisions",expires_at:null,generated_at:generated});
  for(const item of (waiting.data??[]) as unknown as Row[]){const age=Math.max(0,Math.floor((now.getTime()-new Date(String(item.requested_at??item.created_at)).getTime())/86400000));if(age<3)continue;insights.push({id:`waiting-${item.id}`,type:"waiting_stale",priority:55+Math.min(age,10),severity:age>=10?"high":"medium",title:String(item.title),message:`Waiting for ${age} days${item.contact?` · ${String(item.contact)}`:""}.`,entity_type:"waiting",entity_id:item.id,action_label:"Review open loop",action_route:`/waiting/${item.id}`,expires_at:null,generated_at:generated})}
  for(const task of (blocked.data??[]) as unknown as Row[]){const project=task.projects as {name?:string;priority?:string}|null;insights.push({id:`blocked-${task.id}`,type:"project_blocked",priority:project?.priority==="urgent"?87:72,severity:project?.priority==="urgent"?"high":"medium",title:String(task.title),message:`${project?.name??"A project"} is blocked by this task.`,entity_type:"task",entity_id:task.id,action_label:"Open task",action_route:`/tasks/${task.id}`,expires_at:null,generated_at:generated})}
  const nearWeekEnd=now.getUTCDay()>=4;for(const target of fitness.targets){const progress=target.progress as {remaining:number;complete:boolean};if(!nearWeekEnd||progress.complete)continue;insights.push({id:`fitness-${target.id}`,type:"fitness_target",priority:35,severity:"low",title:`${String(target.activity_type)} target`,message:`${progress.remaining} ${target.target_type==="sessions"?progress.remaining===1?"session":"sessions":String(target.target_type).replace("_"," ")} left this week.`,entity_type:"fitness_target",entity_id:target.id,action_label:"Open fitness",action_route:"/fitness",expires_at:`${fitness.period.end}T23:59:59Z`,generated_at:generated})}
  const preferenceRows=(preferences.data??[]) as unknown as {category:string;enabled:boolean;minimum_severity:string}[];const levels={low:1,medium:2,high:3,critical:4};const categoryFor=(type:string)=>type.startsWith("invoice")||type.startsWith("subscription")?"finance":type.startsWith("content")?"content":type.startsWith("decision")?"decisions":type.startsWith("fitness")?"fitness":type.startsWith("waiting")?"waiting":"projects";const allowed=insights.filter((insight)=>{const preference=preferenceRows.find((item)=>item.category===categoryFor(insight.type));return !preference||preference.enabled&&levels[insight.severity]>=levels[preference.minimum_severity as keyof typeof levels]});return rankInsights(allowed,now).slice(0,5);
}
