import type { SupabaseClient } from "@supabase/supabase-js";
import { notifyOnce, resolveNotifications } from "@/lib/v4-notifications";
export async function emitWorkspaceNotifications(client:SupabaseClient,userId:string){const today=new Date().toISOString().slice(0,10);const soon=new Date(Date.now()+35*60_000).toISOString();const week=new Date(Date.now()+7*86400_000).toISOString().slice(0,10);const [tasks,events,threads,followups,invoices,subs,content,decisions,fitness,integrations,automations,conflicts]=await Promise.all([client.from("tasks").select("id,title,due_date,priority").eq("user_id",userId).is("deleted_at",null).in("status",["inbox","planned","in_progress"]).lte("due_date",week),client.from("calendar_events").select("id,title,starts_at").eq("user_id",userId).is("deleted_at",null).gte("starts_at",new Date().toISOString()).lte("starts_at",soon),client.from("email_threads").select("id,subject,reply_state,metadata").eq("user_id",userId).eq("reply_state","awaiting_user_reply"),client.from("followups").select("id,title,due_at").eq("user_id",userId).eq("status","open").lte("due_at",soon),client.from("invoices").select("id,invoice_number,due_date").eq("user_id",userId).is("deleted_at",null).in("status",["sent","partial"]).lt("due_date",today),client.from("subscriptions").select("id,name,next_billing_date").eq("user_id",userId).is("deleted_at",null).eq("status","active").lte("next_billing_date",week),client.from("content_items").select("id,title,due_date,approval_status").eq("user_id",userId).is("deleted_at",null).lte("due_date",week),client.from("decisions").select("id,title,review_date").eq("user_id",userId).is("deleted_at",null).in("status",["active","review_due"]).lte("review_date",today),client.from("fitness_targets").select("id,activity_type,target_value,period").eq("user_id",userId).eq("active",true).eq("period","week"),client.from("integrations").select("id,provider,status,last_error").eq("user_id",userId).in("status",["expired","error"]),client.from("automations").select("id,name,last_status").eq("user_id",userId).eq("last_status","error"),client.from("calendar_event_sync_state").select("calendar_event_id,conflict_type").eq("user_id",userId).not("conflict_type","is",null)]);const failed=[tasks,events,threads,followups,invoices,subs,content,decisions,fitness,integrations,automations,conflicts].find(x=>x.error);if(failed?.error)throw failed.error;
for(const task of tasks.data??[]){const overdue=task.due_date&&task.due_date<today;if(overdue&&["high","urgent"].includes(String(task.priority)))await notifyOnce(client,userId,{type:"tasks",title:"High-priority task overdue",body:String(task.title),entityType:"task",entityId:String(task.id),severity:"important",dedupeKey:`task:overdue:${task.id}`});else if(task.due_date===today)await notifyOnce(client,userId,{type:"tasks",title:"Task deadline today",body:String(task.title),entityType:"task",entityId:String(task.id),severity:"attention",dedupeKey:`task:today:${task.id}`})}
for(const event of events.data??[])await notifyOnce(client,userId,{type:"calendar",title:"Meeting starts soon",body:`${event.title} starts within 35 minutes.`,entityType:"calendar_event",entityId:String(event.id),severity:"important",dedupeKey:`meeting:${event.id}:${event.starts_at}`});
for(const thread of threads.data??[]){const metadata=thread.metadata as Record<string,unknown>|null;if(!metadata?.handled_at)await notifyOnce(client,userId,{type:"clients",title:"Client reply needs attention",body:String(thread.subject),entityType:"client",severity:"important",dedupeKey:`reply:${thread.id}:${metadata?.latest_message_id??"latest"}`})}
for(const followup of followups.data??[])await notifyOnce(client,userId,{type:"clients",title:"Follow-up due",body:String(followup.title),entityType:"followup",entityId:String(followup.id),severity:"important",dedupeKey:`followup:${followup.id}:${followup.due_at}`});
for(const invoice of invoices.data??[])await notifyOnce(client,userId,{type:"finance",title:"Invoice overdue",body:`${invoice.invoice_number??"Invoice"} is overdue.`,entityType:"invoice",entityId:String(invoice.id),severity:"important",dedupeKey:`invoice:overdue:${invoice.id}`});for(const sub of subs.data??[])await notifyOnce(client,userId,{type:"finance",title:"Subscription renewal soon",body:String(sub.name),entityType:"subscription",entityId:String(sub.id),severity:"attention",dedupeKey:`subscription:${sub.id}:${sub.next_billing_date}`});
for(const item of content.data??[]){if(item.approval_status==="pending"&&item.due_date&&item.due_date<today)await notifyOnce(client,userId,{type:"content",title:"Content approval overdue",body:String(item.title),entityType:"content",entityId:String(item.id),severity:"important",dedupeKey:`content:approval:${item.id}`});else if(item.due_date===today)await notifyOnce(client,userId,{type:"content",title:"Content deadline today",body:String(item.title),entityType:"content",entityId:String(item.id),severity:"attention",dedupeKey:`content:deadline:${item.id}:${item.due_date}`})}for(const decision of decisions.data??[])await notifyOnce(client,userId,{type:"decisions",title:"Decision review due",body:String(decision.title),entityType:"decision",entityId:String(decision.id),severity:"attention",dedupeKey:`decision:${decision.id}:${decision.review_date}`});for(const target of fitness.data??[])await notifyOnce(client,userId,{type:"fitness",title:"Weekly fitness target needs attention",body:String(target.activity_type),severity:"attention",dedupeKey:`fitness:${target.id}:${today.slice(0,7)}`});for(const item of integrations.data??[])await notifyOnce(client,userId,{type:"integrations",title:"Reconnect required",body:`${item.provider} needs attention.`,entityType:"integration",entityId:String(item.id),severity:"important",dedupeKey:`integration:${item.id}:${item.status}`});for(const item of automations.data??[])await notifyOnce(client,userId,{type:"automations",title:"Automation failed",body:String(item.name),entityType:"automation",entityId:String(item.id),severity:"important",dedupeKey:`automation:${item.id}:${item.last_status}`});for(const conflict of conflicts.data??[])await notifyOnce(client,userId,{type:"calendar",title:"Calendar conflict needs review",body:"A Calendar event changed and needs your decision.",entityType:"calendar_event",entityId:String(conflict.calendar_event_id),severity:"important",dedupeKey:`calendar-conflict:${conflict.calendar_event_id}:${conflict.conflict_type}`});await emitFounderOperationalHooks(client,userId,today);
}

export async function emitFounderOperationalHooks(client: SupabaseClient, userId: string, today = new Date().toISOString().slice(0, 10)) {
  const company = await client.from("companies").select("id").eq("user_id", userId).eq("active", true).maybeSingle();
  if (company.error) throw company.error;
  if (!company.data) return;
  const companyId = company.data.id;
  const [products, inventory, deployments, incidents, supplierOrders, currentOrders, previousOrders] = await Promise.all([
    client.from("product_catalog_refs").select("id,name").eq("user_id", userId).eq("company_id", companyId).eq("active", true),
    client.from("inventory_snapshots").select("id,product_id,available_stock,reorder_level,captured_at").eq("user_id", userId).eq("company_id", companyId).order("captured_at", { ascending: false }).limit(500),
    client.from("deployment_records").select("id,status,environment,completed_at,external_id").eq("user_id", userId).eq("company_id", companyId).eq("environment", "production").order("completed_at", { ascending: false }).limit(30),
    client.from("incidents").select("id,title,severity,status,updated_at").eq("user_id", userId).eq("company_id", companyId).in("severity", ["major", "critical"]).neq("status", "resolved"),
    client.from("supplier_orders").select("id,reference,status,expected_at,updated_at").eq("user_id", userId).eq("company_id", companyId).in("status", ["ordered", "partially_received"]).lt("expected_at", today),
    client.from("commerce_orders").select("id,status").eq("user_id", userId).eq("company_id", companyId).gte("created_at", new Date(Date.now() - 7 * 86_400_000).toISOString()),
    client.from("commerce_orders").select("id,status").eq("user_id", userId).eq("company_id", companyId).gte("created_at", new Date(Date.now() - 14 * 86_400_000).toISOString()).lt("created_at", new Date(Date.now() - 7 * 86_400_000).toISOString()),
  ]);
  const failed = [products, inventory, deployments, incidents, supplierOrders, currentOrders, previousOrders].find((result) => result.error);
  if (failed?.error) throw failed.error;
  const latest = new Map<string, { id: string; available_stock: number | string | null; reorder_level: number | string | null; captured_at: string }>();
  for (const row of inventory.data ?? []) if (!latest.has(row.product_id)) latest.set(row.product_id, row);
  const productsById = new Map((products.data ?? []).map((product) => [product.id, product]));
  const lowProductIds = new Set<string>();
  for (const [productId, snapshot] of latest) {
    if (snapshot.available_stock == null || snapshot.reorder_level == null || Number(snapshot.available_stock) > Number(snapshot.reorder_level)) continue;
    const key = `founder:low-stock:${productId}:${snapshot.id}`; lowProductIds.add(productId);
    await notifyOnce(client, userId, { type: "automations", title: "Low stock needs attention", body: `${productsById.get(productId)?.name ?? "Product"} is at or below its reorder level.`, entityType: "product", entityId: productId, severity: "important", dedupeKey: key, cooldownHours: 168 });
  }
  for (const productId of productsById.keys()) if (!lowProductIds.has(productId)) await resolveNotifications(client, userId, `founder:low-stock:${productId}:`);
  const failedDeploymentIds = new Set<string>();
  for (const deployment of deployments.data ?? []) {
    if (deployment.status !== "failed") continue;
    failedDeploymentIds.add(deployment.id);
    await notifyOnce(client, userId, { type: "automations", title: "Production deployment failed", body: "A production deployment needs founder review.", entityType: "deployment", entityId: deployment.id, severity: "critical", dedupeKey: `founder:deployment:${deployment.id}:${deployment.external_id ?? deployment.status}`, cooldownHours: 168 });
  }
  for (const deployment of deployments.data ?? []) if (!failedDeploymentIds.has(deployment.id)) await resolveNotifications(client, userId, `founder:deployment:${deployment.id}:`);
  for (const incident of incidents.data ?? []) await notifyOnce(client, userId, { type: "automations", title: `${incident.severity === "critical" ? "Critical" : "Major"} incident is active`, body: incident.title, entityType: "incident", entityId: incident.id, severity: incident.severity === "critical" ? "critical" : "important", dedupeKey: `founder:incident:${incident.id}:${incident.updated_at}`, cooldownHours: 24 });
  for (const order of supplierOrders.data ?? []) await notifyOnce(client, userId, { type: "automations", title: "Supplier delivery overdue", body: order.reference ?? "A supplier order is past its expected date.", entityType: "supplier_order", entityId: order.id, severity: "important", dedupeKey: `founder:supplier-overdue:${order.id}:${order.expected_at}`, cooldownHours: 72 });
  const cancellationRate = (orders: Array<{ status: string }>) => orders.length ? orders.filter((order) => order.status === "canceled").length / orders.length : 0;
  const current = currentOrders.data ?? []; const previous = previousOrders.data ?? [];
  if (current.length >= 10 && cancellationRate(current) >= 0.25 && cancellationRate(current) >= cancellationRate(previous) + 0.15) await notifyOnce(client, userId, { type: "automations", title: "Commerce cancellation rate changed", body: "Recent confirmed commerce data shows a meaningful cancellation increase.", severity: "important", dedupeKey: `founder:commerce-anomaly:${today}`, cooldownHours: 168 });
}
