export type PromptRecord={id:string;title:string;description?:string|null;prompt_text?:string|null;prompt?:string|null;category:string;favorite?:boolean;usage_count?:number;rating?:number|null;last_used_at?:string|null;created_at:string;updated_at:string};
export const promptCategories=["Coding","Marketing","Design","Image Generation","Business","Research","Writing","Other"];
export function filterPrompts(records:PromptRecord[],query:string,category:string,favorite:string,sort:string){const needle=query.trim().toLocaleLowerCase();return records.filter(row=>(!needle||`${row.title} ${row.description??""} ${row.prompt_text??row.prompt??""}`.toLocaleLowerCase().includes(needle))&&(category==="all"||row.category===category)&&(favorite!=="favorites"||row.favorite)).sort((a,b)=>sort==="name"?a.title.localeCompare(b.title):sort==="uses"?Number(b.usage_count??0)-Number(a.usage_count??0):Date.parse(b.updated_at)-Date.parse(a.updated_at));}
export const previewPrompts:PromptRecord[]=[
 ["SEO Blog Writer","Writing","Write a high-ranking, SEO-optimized blog post on any topic with a clear structure, engaging tone, and meta details.",142,"You are an expert SEO content writer. Write a comprehensive blog post about {topic} for {target_audience}.\n\nRequirements:\n- SEO-optimized with keyword: {keyword}\n- Compelling title and meta description\n- Clear headings (H2, H3)\n- End with this call to action: {cta}"],
 ["Client Follow-up Email","Business","Generate a professional follow-up email after a client meeting.",87,"Write a warm, professional follow-up email to {client} about {topic}. Include the next step: {next_step}."],
 ["Product Page Copy","Marketing","Create compelling product page copy with benefits and a clear call to action.",64,"Write product page copy for {product}. Highlight {benefits} for {audience}."],
 ["Radiology Ad Caption","Marketing","Short, engaging captions for radiology services.",52,"Write three concise captions about {service} for {audience}."],
 ["Meeting Summary Formatter","Other","Turn meeting notes into clear action items and decisions.",38,"Summarize these meeting notes: {notes}. Include decisions and action items."],
 ["Outreach Sequence","Business","Create a multi-step cold outreach sequence for a new prospect.",91,"Create an outreach sequence for {client} introducing {service}."],
].map(([title,category,description,usage_count,prompt_text],index)=>({id:`preview-${index}`,title:String(title),category:String(category),description:String(description),usage_count:Number(usage_count),prompt_text:String(prompt_text),favorite:index===0,created_at:"2026-09-01T12:00:00Z",updated_at:`2026-09-${27-index}T12:00:00Z`}));
