import { capacityState, horizonFor, type StrategicItem } from "@/lib/strategy";

export type PortfolioItem = StrategicItem & { domain: "work" | "business" | "founder" | "life"; health: "on_track" | "needs_attention" | "at_risk" | "blocked"; nextMilestone?: string | null; value?: number | null; route: string };
export type GoalHealth = { id: string; title: string; progress: number; health: "on_track" | "needs_attention" | "at_risk" | "stalled"; reason: string; hasAction: boolean; nextMilestone?: string | null };
export type StrategicRisk = { id: string; title: string; evidence: string; impact: string; action: string; route: string; priority: number };
const daysBetween = (start: string, end: string) => Math.floor((Date.parse(`${end}T00:00:00Z`) - Date.parse(`${start}T00:00:00Z`)) / 86400000);
export function portfolioHealth(input: { blocked?: boolean; status?: string; deadline?: string | null; today: string }) { if (input.blocked) return "blocked" as const; if (input.status === "at_risk") return "at_risk" as const; if (input.deadline && input.deadline < input.today) return "at_risk" as const; if (input.deadline && daysBetween(input.today, input.deadline) <= 14) return "needs_attention" as const; return "on_track" as const; }
const portfolioScore = (item: PortfolioItem, today: string) => ({ blocked: 100, at_risk: 80, needs_attention: 45, on_track: 0 }[item.health] + (item.priority ?? 0) * 6 + Math.min(30, (item.value ?? 0) / 1000) + (item.targetDate ? Math.max(0, 30 - daysBetween(today, item.targetDate)) : 0));
export const rankPortfolio = (items: PortfolioItem[], today: string) => [...items].sort((a, b) => portfolioScore(b, today) - portfolioScore(a, today));
export function goalHealth(input: { id: string; title: string; progress: number; targetDate?: string | null; commitments: number; milestones: number; recentActivity: boolean }, today: string): GoalHealth { const hasAction = input.commitments > 0 || input.milestones > 0; if (!hasAction) return { ...input, health: "stalled", reason: "No active commitment or next action.", hasAction }; if (input.targetDate && input.targetDate < today && input.progress < 100) return { ...input, health: "at_risk", reason: "Target date passed before the goal was complete.", hasAction }; if (!input.recentActivity) return { ...input, health: "needs_attention", reason: "No recent linked planning activity.", hasAction }; return { ...input, health: "on_track", reason: "Active strategic work is linked to this goal.", hasAction }; }
export function strategicRisks(input: { portfolio: PortfolioItem[]; goals: GoalHealth[]; capacity: { state: string; reason: string } }) { const risks: StrategicRisk[] = [...input.portfolio.filter((item) => item.health !== "on_track").map((item) => ({ id: `portfolio:${item.id}`, title: item.health === "blocked" ? `${item.title} is blocked` : `${item.title} needs attention`, evidence: item.blocked ? "An unresolved dependency is recorded." : item.targetDate ? `Deadline ${item.targetDate} requires review.` : "Current planning state needs review.", impact: "This affects a strategic portfolio item.", action: "Review item", route: item.route, priority: item.health === "blocked" ? 95 : 75 })), ...input.goals.filter((goal) => goal.health === "stalled" || goal.health === "at_risk").map((goal) => ({ id: `goal:${goal.id}`, title: `${goal.title} has no active strategic path`, evidence: goal.reason, impact: "Goal progress may drift without a commitment or milestone.", action: "Open goals", route: "/goals", priority: 70 })), ...(input.capacity.state === "overcommitted" ? [{ id: "capacity", title: "Strategic capacity is overcommitted", evidence: input.capacity.reason, impact: "Commitments may miss their target dates.", action: "Review weekly plan", route: "/plan/week", priority: 85 }] : [])]; return risks.sort((a, b) => b.priority - a.priority).slice(0, 5); }
export const tradeoffPreview = (input: { commitments: number; deadlines: number; meetingHours: number; availableHours: number; adding?: number }) => ({ current: capacityState(input), next: capacityState({ ...input, commitments: input.commitments + (input.adding ?? 1) }), suggestReview: capacityState({ ...input, commitments: input.commitments + (input.adding ?? 1) }).state === "overcommitted" });
export function horizon<T extends { targetDate?: string | null }>(items: T[], today: string) { return { 30: items.filter((item) => horizonFor(item.targetDate, today) === 30), 60: items.filter((item) => horizonFor(item.targetDate, today) === 60), 90: items.filter((item) => horizonFor(item.targetDate, today) === 90) }; }
export type DecisionGateSignal = { id: string; title: string; dueDate?: string | null; commitmentPriority?: number | null; blockedCount: number; status?: string | null };
export const decisionGateScore = (gate: DecisionGateSignal, today: string) => { const days = gate.dueDate ? daysBetween(today, gate.dueDate) : 91; return (days < 0 ? 90 : Math.max(0, 35 - days)) + gate.blockedCount * 20 + (gate.commitmentPriority ?? 0) * 7; };
export const rankDecisionGates = (gates: DecisionGateSignal[], today: string) => [...gates].filter((gate) => gate.status !== "resolved" && gate.status !== "canceled").sort((a, b) => decisionGateScore(b, today) - decisionGateScore(a, today));
export type SlippageSignal = { id: string; title: string; evidence: string; impact: string; action: string; priority: number };
export function slippageSignals(input: { commitments: Array<{ id: string; title: string; status?: string | null; targetDate?: string | null }>; milestones: Array<{ id: string; title: string; status?: string | null }>; gates: DecisionGateSignal[]; goals: GoalHealth[] }, today: string) { const signals: SlippageSignal[] = []; for (const item of input.commitments) if (item.status === "at_risk" && item.targetDate && item.targetDate < today) signals.push({ id: `commitment:${item.id}`, title: `${item.title} is slipping`, evidence: "It remains at risk after its target date.", impact: "A committed outcome may move forward.", action: "Review commitment", priority: 85 }); for (const item of input.milestones) if (item.status === "missed") signals.push({ id: `milestone:${item.id}`, title: `${item.title} was missed`, evidence: "The milestone is recorded as missed.", impact: "Related strategic work needs a new decision.", action: "Review milestone", priority: 80 }); for (const goal of input.goals) if (goal.health === "stalled" && goal.nextMilestone == null) signals.push({ id: `goal:${goal.id}`, title: `${goal.title} has remained stalled`, evidence: "No active commitment or next action is linked.", impact: "Goal progress may not move.", action: "Add a commitment", priority: 75 }); for (const gate of rankDecisionGates(input.gates, today)) if (gate.dueDate && gate.dueDate < today && gate.blockedCount > 0) signals.push({ id: `gate:${gate.id}`, title: `${gate.title} is overdue`, evidence: `It blocks ${gate.blockedCount} strategic item${gate.blockedCount === 1 ? "" : "s"}.`, impact: "Blocked work cannot progress.", action: "Resolve decision", priority: 95 }); return signals.sort((a, b) => b.priority - a.priority).slice(0, 5); }
