export type InvoiceNumbers={subtotal:number;taxAmount:number;discountAmount:number;amountPaid:number};
export function invoiceTotals(input:InvoiceNumbers){const total=roundMoney(input.subtotal+input.taxAmount-input.discountAmount);if(total<0)throw new Error("Discount cannot exceed subtotal and tax.");if(input.amountPaid<0||input.amountPaid>total)throw new Error("Amount paid must be between zero and the invoice total.");return{total,remaining:roundMoney(total-input.amountPaid),status:input.amountPaid===0?"sent":input.amountPaid===total?"paid":"partial" as const}}
export function effectiveInvoiceStatus(invoice:{status:string;due_date?:string|null;amount_remaining?:number|null},today:string){if(invoice.status==="paid"||invoice.status==="cancelled")return invoice.status;return invoice.due_date&&invoice.due_date<today&&Number(invoice.amount_remaining??0)>0?"overdue":invoice.status}
export function renderPrompt(template:string,values:Record<string,string>){const missing=new Set<string>();const text=template.replace(/\{([a-z][a-z0-9_]*)\}/g,(_,name:string)=>{const value=values[name]?.trim();if(!value){missing.add(name);return `{${name}}`}return value});return{text,missing:[...missing]}}
export function promptVariables(template:string){return[...new Set([...template.matchAll(/\{([a-z][a-z0-9_]*)\}/g)].map((match)=>match[1]))]}
export function weekBounds(now:Date,weekStartsOn=1){const date=new Date(Date.UTC(now.getUTCFullYear(),now.getUTCMonth(),now.getUTCDate()));const delta=(date.getUTCDay()-weekStartsOn+7)%7;const start=new Date(date);start.setUTCDate(start.getUTCDate()-delta);const end=new Date(start);end.setUTCDate(end.getUTCDate()+6);return{start:start.toISOString().slice(0,10),end:end.toISOString().slice(0,10)}}
export function targetProgress(target:{activity_type:string;target_type:string;target_value:number},activities:Record<string,unknown>[]){const matching=activities.filter((item)=>item.activity_type===target.activity_type);const actual=target.target_type==="sessions"?matching.length:matching.reduce((sum,item)=>sum+Number(item[target.target_type]??0),0);return{actual:roundMoney(actual),target:Number(target.target_value),remaining:roundMoney(Math.max(Number(target.target_value)-actual,0)),complete:actual>=Number(target.target_value)}}

export type Insight={id:string;type:string;priority:number;severity:"low"|"medium"|"high"|"critical";title:string;message:string;entity_type:string;entity_id:string;action_label:string;action_route:string;expires_at:string|null;generated_at:string};
export function rankInsights(insights:Insight[],now=new Date()){const severity={critical:4,high:3,medium:2,low:1};const seen=new Set<string>();return insights.filter((item)=>!item.expires_at||new Date(item.expires_at)>=now).sort((a,b)=>b.priority-a.priority||severity[b.severity]-severity[a.severity]).filter((item)=>{const key=`${item.type}:${item.entity_type}:${item.entity_id}`;if(seen.has(key))return false;seen.add(key);return true})}
export function daysBetween(from:string,to:string){return Math.floor((new Date(`${to}T12:00:00Z`).getTime()-new Date(`${from}T12:00:00Z`).getTime())/86400000)}
export function decisionReviewState(reviewDate:string|null|undefined,today:string,windowDays=7){if(!reviewDate)return"none" as const;const days=daysBetween(today,reviewDate);return days<0?"overdue" as const:days<=windowDays?"due_soon" as const:"later" as const}
function roundMoney(value:number){return Math.round((value+Number.EPSILON)*100)/100}
