export type ReplyState = "awaiting_user_reply" | "waiting_for_other" | "no_action_detected" | "unknown";
export function inferReplyState(messages: Array<{ fromUser: boolean; meaningful?: boolean }>): ReplyState { const latest = [...messages].reverse().find((message) => message.meaningful !== false); return !latest ? "unknown" : latest.fromUser ? "waiting_for_other" : "awaiting_user_reply"; }
export function stravaActivityType(value: string) { return ({ Run: "Running", Walk: "Walking", Swim: "Swimming", Ride: "Cycling", Hike: "Hiking" } as Record<string, string>)[value] ?? "Other"; }
export const safeAutomationTypes = ["morning_brief", "evening_review", "weekly_review", "overdue_invoice_alert", "client_followup_reminder", "calendar_sync", "strava_sync", "github_sync", "subscription_warning", "content_approval_reminder", "weekly_planning_reminder", "monthly_planning_reminder", "quarterly_planning_reminder", "milestone_risk_check", "blocked_commitment_check"] as const;
export function actionNeedsApproval(action: string) { return ["send_email", "create_multiple_meeting_actions", "record_payment", "reschedule_calendar_event", "create_automation", "disable_automation"].includes(action); }
export type CalendarConflict={firstId:string;secondId:string;kind:"overlap"|"concurrent_change"};
export function detectCalendarConflicts(events:Array<{id:string;starts_at:string;ends_at:string;provider?:string;external_updated_at?:string|null;updated_at?:string|null;sync_hash?:string|null}>){const conflicts:CalendarConflict[]=[];for(let i=0;i<events.length;i++)for(let j=i+1;j<events.length;j++){const a=events[i],b=events[j];if(new Date(a.starts_at)<new Date(b.ends_at)&&new Date(b.starts_at)<new Date(a.ends_at))conflicts.push({firstId:a.id,secondId:b.id,kind:"overlap"})}return conflicts}
export function normalizeEmail(value:string){const match=value.match(/<([^>]+)>/)?.[1]??value;const address=match.trim().replace(/^['"]|['"]$/g,"").toLowerCase();return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(address)?address:null}
export function normalizeParticipants(values:string[]){return [...new Set(values.map(normalizeEmail).filter((value):value is string=>Boolean(value)))].sort()}
export function inferConservativeReplyState(input:{latestFrom?:string;userAddresses:string[];participants:string[];automated?:boolean;ambiguous?:boolean}){if(input.automated)return"no_action_detected";const latest=normalizeEmail(input.latestFrom??"");const users=new Set(normalizeParticipants(input.userAddresses));if(input.ambiguous||!latest||users.size!==1||input.participants.length>8)return"unknown";return users.has(latest)?"waiting_for_other":"awaiting_user_reply"}
export function shouldReactivateHandled(input:{handledMessageId?:string|null;latestMessageId?:string|null;latestFrom?:string;userAddresses:string[];automated?:boolean}){if(!input.handledMessageId||!input.latestMessageId||input.handledMessageId===input.latestMessageId||input.automated)return false;return inferConservativeReplyState({latestFrom:input.latestFrom,userAddresses:input.userAddresses,participants:[]})==="awaiting_user_reply"}
export type CalendarSnapshot={title:string;description:string;start:string;end:string;all_day:boolean;timezone:string;recurrence:string|null;recurring_event_id:string|null;original_start_time:string|null};
export function canonicalizeCalendarEvent(event:Record<string,unknown>):CalendarSnapshot{const allDay=Boolean(event.all_day??event.allDay);const date=(value:unknown)=>String(value??"").slice(0,10);const instant=(value:unknown)=>new Date(String(value??"")).toISOString();return{title:String(event.title??event.summary??"").trim(),description:String(event.description??"").trim(),start:allDay?date(event.starts_at??event.start):instant(event.starts_at??event.start),end:allDay?date(event.ends_at??event.end):instant(event.ends_at??event.end),all_day:allDay,timezone:String(event.timezone??"UTC"),recurrence:event.recurrence_rule??event.recurrence?String(event.recurrence_rule??event.recurrence):null,recurring_event_id:event.recurring_event_id?String(event.recurring_event_id):null,original_start_time:event.original_start_time?String(event.original_start_time):null}}
const snapshotFields:(keyof CalendarSnapshot)[]=["title","description","start","end","all_day","timezone","recurrence","recurring_event_id","original_start_time"];
export function compareCalendarSnapshots(base:CalendarSnapshot,local:CalendarSnapshot,remote:CalendarSnapshot){const changed=(value:CalendarSnapshot)=>snapshotFields.filter(field=>value[field]!==base[field]);const localFields=changed(local),remoteFields=changed(remote);const sameResult=snapshotFields.every(field=>local[field]===remote[field]);return{localChanged:localFields.length>0,remoteChanged:remoteFields.length>0,sameResult,conflict:localFields.length>0&&remoteFields.length>0&&!sameResult,changedFieldsLocal:localFields,changedFieldsRemote:remoteFields,conflictingFields:snapshotFields.filter(field=>local[field]!==remote[field]&&(local[field]!==base[field]||remote[field]!==base[field]))}}
export function calendarSyncDecision(base:CalendarSnapshot,local:CalendarSnapshot,remote:CalendarSnapshot){const comparison=compareCalendarSnapshots(base,local,remote);return{...comparison,action:comparison.conflict?"conflict":!comparison.localChanged&&!comparison.remoteChanged?"noop":comparison.localChanged&&!comparison.remoteChanged?"push_local":!comparison.localChanged&&comparison.remoteChanged?"apply_remote":"advance_identical"} as const}
