import { z } from "zod";
export const plannedExerciseSchema = z.object({ exerciseId:z.string().min(1).max(80), name:z.string().trim().min(1).max(240), sets:z.number().int().min(1).max(20), reps:z.number().int().min(1).max(500), weightKg:z.number().min(0).max(1500), restSeconds:z.number().int().min(0).max(900) });
export const routineSchema = z.object({ id:z.uuid(), name:z.string().trim().min(1).max(120), notes:z.string().trim().max(2000).default(""), exercises:z.array(plannedExerciseSchema).min(1).max(30), version:z.number().int().min(0).default(0), archived:z.boolean().default(false) });
export const loggedSetSchema = z.object({ reps:z.number().int().min(0).max(500), weightKg:z.number().min(0).max(1500), completed:z.boolean() }).refine(set=>!set.completed||set.reps>0,{message:"A completed set needs at least one rep."});
export const loggedExerciseSchema = z.object({ exerciseId:z.string().min(1).max(80), name:z.string().trim().min(1).max(240), restSeconds:z.number().int().min(0).max(900), sets:z.array(loggedSetSchema).min(1).max(20) });
export const sessionSchema = z.object({id:z.uuid(), routineId:z.uuid().nullable(), name:z.string().trim().min(1).max(120), startedAt:z.iso.datetime({offset:true}), notes:z.string().trim().max(2000).default(""), exercises:z.array(loggedExerciseSchema).min(1).max(30), version:z.number().int().min(0).default(0), status:z.enum(["in_progress","completed","discarded"]).default("in_progress")}).refine(session=>session.status!=="completed"||session.exercises.some(exercise=>exercise.sets.some(set=>set.completed)),{message:"Complete at least one set before finishing the workout."});
export type PlannedExercise=z.infer<typeof plannedExerciseSchema>;
export type LoggedExercise=z.infer<typeof loggedExerciseSchema>;
export type Routine={id:string;name:string;notes:string;exercises:PlannedExercise[];version:number;archived:boolean;updated_at:string};
export type Workout={id:string;routine_id:string|null;name:string;notes:string;exercises:LoggedExercise[];version:number;status:"in_progress"|"completed"|"discarded";started_at:string;completed_at:string|null;activity_id:string|null};
export function workoutTotals(exercises:LoggedExercise[]){return exercises.reduce((total,exercise)=>{for(const set of exercise.sets)if(set.completed){total.sets++;total.reps+=set.reps;total.volumeKg+=set.reps*set.weightKg;}return total;},{sets:0,reps:0,volumeKg:0});}
export function routineToWorkout(exercises:PlannedExercise[]):LoggedExercise[]{return exercises.map(exercise=>({exerciseId:exercise.exerciseId,name:exercise.name,restSeconds:exercise.restSeconds,sets:Array.from({length:exercise.sets},()=>({reps:exercise.reps,weightKg:exercise.weightKg,completed:false}))}));}
export function restRemaining(deadline:number|null,now=Date.now()){return deadline===null?0:Math.max(0,Math.ceil((deadline-now)/1000));}
