import { NextResponse } from "next/server";
import { z } from "zod";
import { apiError } from "@/lib/api";
import { safeAutomationTypes } from "@/lib/v4";
import { requireUser } from "@/lib/supabase/server";
const schema=z.object({type:z.enum(safeAutomationTypes),name:z.string().trim().min(1).max(120),enabled:z.boolean().default(true),schedule_or_condition:z.record(z.string(),z.unknown()).default({})});
const names:Record<string,string>={morning_brief:"Morning brief",evening_review:"Evening review reminder",weekly_review:"Weekly review",overdue_invoice_alert:"Overdue invoice alert",client_followup_reminder:"Client follow-up reminder",calendar_sync:"Calendar sync",strava_sync:"Strava sync",github_sync:"GitHub sync",subscription_renewal_warning:"Subscription renewal warning",content_approval_reminder:"Content approval reminder",weekly_planning_reminder:"Weekly planning reminder",monthly_planning_reminder:"Monthly planning reminder",quarterly_planning_reminder:"Quarterly planning reminder",milestone_risk_check:"Milestone risk check",blocked_commitment_check:"Blocked commitment check",daily_sales_attention:"Daily sales attention",weekly_growth_review:"Weekly growth review",proposal_followup_review:"Proposal follow-up review",lead_reactivation_review:"Lead reactivation review",client_expansion_review:"Client expansion review",pipeline_hygiene:"Pipeline hygiene review",experiment_review:"Sales experiment review"};
export async function GET(){try{const{supabase,userId}=await requireUser();let existing=await supabase.from("automations").select("*").eq("user_id",userId).order("updated_at",{ascending:false});if(existing.error)throw existing.error;const present=new Set((existing.data??[]).map(item=>String(item.type)));const missing=safeAutomationTypes.filter(type=>!present.has(type));if(missing.length){const seed=missing.map(type=>({user_id:userId,type,name:names[type]??type.replaceAll("_"," "),enabled:false,schedule_or_condition:{},configuration:{},last_status:"idle"}));const seeded=await supabase.from("automations").insert(seed as never).select("*");if(seeded.error)throw seeded.error;existing={data:[...(existing.data??[]),...(seeded.data??[])],error:null} as typeof existing}const connections=await supabase.from("integrations").select("provider,status,provider_email,last_synced_at").eq("user_id",userId).in("provider",["google","strava","github"]);if(connections.error)throw connections.error;const providerFor:Record<string,string>={calendar_sync:"google",strava_sync:"strava",github_sync:"github"};const items=(existing.data??[]).map(item=>{const provider=providerFor[String(item.type)];const connection=provider?(connections.data??[]).find(row=>row.provider===provider):null;return{...item,provider_connection:connection??null}});return NextResponse.json({items})}catch(error){return apiError(error,"Automations could not be loaded.")}}
export async function POST(request:Request){try{const input=schema.parse(await request.json());const{supabase,userId}=await requireUser();const{data,error}=await supabase.from("automations").upsert({...input,user_id:userId,last_status:"idle"},{onConflict:"user_id,type"}).select("*").single();if(error)throw error;await supabase.from("action_audit_log").insert({user_id:userId,actor:"user",action_type:"automation_configured",entity_type:"automation",entity_id:data.id,summary:data.name});return NextResponse.json({item:data},{status:201})}catch(error){return apiError(error,"Automation could not be saved.")}}
export async function PATCH(request:Request){try{const input=z.object({id:z.uuid(),enabled:z.boolean().optional(),schedule_or_condition:z.record(z.string(),z.unknown()).optional(),configuration:z.record(z.string(),z.unknown()).optional()}).parse(await request.json());const{supabase,userId}=await requireUser();const{data,error}=await supabase.from("automations").update({...input,id:undefined} as never).eq("id",input.id).eq("user_id",userId).select("*").maybeSingle();if(error)throw error;if(!data)return NextResponse.json({error:"Automation is unavailable."},{status:404});await supabase.from("action_audit_log").insert({user_id:userId,actor:"user",action_type:input.enabled===undefined?"automation_configuration_changed":input.enabled?"automation_enabled":"automation_disabled",entity_type:"automation",entity_id:data.id,summary:data.name});return NextResponse.json({item:data})}catch(error){return apiError(error,"Automation could not be updated.")}}
