import { NextResponse } from "next/server";
import { z } from "zod";
import { apiError, isMissingOptionalSchema } from "@/lib/api";
import { capacityState } from "@/lib/strategy";
import { requireUser } from "@/lib/supabase/server";

const typeSchema=z.enum(["month","quarter"]);
const selection=z.object({periodId:z.uuid(),commitmentIds:z.array(z.uuid()).max(10)}).strict();
export async function GET(request:Request){try{const type=typeSchema.parse(new URL(request.url).searchParams.get("type"));const{supabase,userId}=await requireUser();const today=new Date().toISOString().slice(0,10);const horizon=type==="month"?30:90;const end=new Date(Date.now()+horizon*86400000).toISOString().slice(0,10);const[periods,commitments,milestones,gates,events,goals]=await Promise.all([supabase.from("planning_periods").select("*").eq("user_id",userId).eq("type",type).neq("status","archived").order("starts_at",{ascending:false}).limit(12),supabase.from("strategic_commitments").select("*").eq("user_id",userId).not("status","in","(completed,dropped)").order("target_date").limit(30),supabase.from("strategic_milestones").select("*").eq("user_id",userId).not("status","in","(reached,canceled)").gte("milestone_date",today).lte("milestone_date",end).order("milestone_date").limit(20),supabase.from("decision_gates").select("*").eq("user_id",userId).eq("status","open").lte("due_date",end).order("due_date").limit(20),supabase.from("calendar_events").select("id,title,starts_at,ends_at").eq("user_id",userId).gte("starts_at",`${today}T00:00:00Z`).lt("starts_at",new Date(Date.now()+horizon*86400000).toISOString()).is("deleted_at",null).limit(40),supabase.from("goals").select("id,title,progress,target_date").eq("user_id",userId).eq("status","active").is("deleted_at",null).limit(20)]);const failed=[periods,commitments,milestones,gates,events,goals].find(result=>result.error);if(failed?.error)throw failed.error;const meetingHours=(events.data??[]).reduce((total,row)=>total+(Date.parse(row.ends_at)-Date.parse(row.starts_at))/3600000,0);return NextResponse.json({type,periods:periods.data??[],commitments:commitments.data??[],milestones:milestones.data??[],gates:gates.data??[],events:events.data??[],goals:goals.data??[],capacity:capacityState({commitments:(commitments.data??[]).length,deadlines:(commitments.data??[]).filter(row=>row.target_date&&row.target_date<=end).length,meetingHours,availableHours:type==="month"?80:240})},{headers:{"Cache-Control":"private, no-store"}})}catch(error){if(isMissingOptionalSchema(error))return NextResponse.json({periods:[],commitments:[],milestones:[],gates:[],events:[],goals:[],capacity:{state:"unknown",reason:"Planning capacity is unavailable."},schemaStatus:"unavailable",schemaDependency:"V8 strategic planning schema"},{headers:{"Cache-Control":"private, no-store"}});return apiError(error,"Planning inputs could not be loaded.")}}
export async function POST(request:Request){try{const values=selection.parse(await request.json());const type=typeSchema.parse(new URL(request.url).searchParams.get("type"));const{supabase,userId}=await requireUser();const period=await supabase.from("planning_periods").select("id,type").eq("id",values.periodId).eq("user_id",userId).maybeSingle();if(period.error)throw period.error;if(!period.data||period.data.type!==type)return NextResponse.json({error:"Choose one of your own matching planning periods."},{status:404});const owned=await supabase.from("strategic_commitments").select("id").eq("user_id",userId).in("id",values.commitmentIds);if(owned.error)throw owned.error;if((owned.data??[]).length!==values.commitmentIds.length)return NextResponse.json({error:"Choose commitments from your own workspace."},{status:422});const activate=await supabase.from("planning_periods").update({status:"active"} as never).eq("id",values.periodId).eq("user_id",userId);if(activate.error)throw activate.error;if(values.commitmentIds.length){const assign=await supabase.from("strategic_commitments").update({planning_period_id:values.periodId,status:"committed"} as never).eq("user_id",userId).in("id",values.commitmentIds);if(assign.error)throw assign.error}return NextResponse.json({confirmed:true,selected:values.commitmentIds.length})}catch(error){return apiError(error,"Planning period could not be confirmed.")}}
