import { NextResponse } from "next/server";
import { z } from "zod";
import { apiError } from "@/lib/api";
import { requireUser } from "@/lib/supabase/server";
const tables = { topics: "research_topics", sources: "knowledge_sources", findings: "research_findings", questions: "research_questions", collections: "knowledge_collections", briefs: "research_briefs", watches: "watch_entities", evidence: "finding_evidence", relations: "knowledge_relations", links: "knowledge_entity_links", collection_items: "collection_items", watch_updates: "watch_updates" } as const;
const resource = z.enum(Object.keys(tables) as [keyof typeof tables, ...(keyof typeof tables)[]]);
const safeUrl = z.string().url().refine((value) => /^https?:\/\//i.test(value), "Use an http or https URL.");
const schemas: Record<keyof typeof tables, z.ZodType> = {
  topics: z.object({ title:z.string().trim().min(1).max(240),description:z.string().max(10000).nullable().optional(),status:z.enum(["active","monitoring","paused","complete","archived"]).default("active"),domain:z.enum(["work","business","founder","life","strategy","personal","other"]).default("other"),priority:z.enum(["low","medium","high"]).default("medium"),next_review_at:z.string().date().nullable().optional() }),
  sources: z.object({ title:z.string().trim().min(1).max(400),source_type:z.string().min(1),url:safeUrl.nullable().optional(),author:z.string().max(240).nullable().optional(),publisher:z.string().max(240).nullable().optional(),published_at:z.string().date().nullable().optional(),notes:z.string().max(20000).nullable().optional(),reliability:z.enum(["primary","strong","useful","unverified","weak"]).nullable().optional(),freshness_expires_at:z.string().date().nullable().optional(),attachment_id:z.uuid().nullable().optional() }),
  findings: z.object({ topic_id:z.uuid(),title:z.string().trim().min(1).max(400),summary:z.string().max(20000).default(""),status:z.enum(["draft","supported","mixed","contradicted","superseded"]).default("draft"),confidence_label:z.enum(["low","medium","high"]).nullable().optional() }),
  questions: z.object({ topic_id:z.uuid(),question:z.string().trim().min(1).max(1000),status:z.enum(["open","researching","answered","deferred","dropped"]).default("open"),priority:z.enum(["low","medium","high"]).default("medium"),answer_summary:z.string().max(10000).nullable().optional() }),
  collections: z.object({ title:z.string().trim().min(1).max(240),description:z.string().max(10000).nullable().optional() }), briefs: z.object({ topic_id:z.uuid().nullable().optional(),title:z.string().trim().min(1).max(240),summary:z.string().max(20000).default(""),implications:z.string().max(10000).nullable().optional(),next_research:z.string().max(10000).nullable().optional(),status:z.enum(["draft","current","outdated","archived"]).default("draft") }), watches:z.object({ topic_id:z.uuid().nullable().optional(),name:z.string().trim().min(1).max(240),watch_type:z.string().min(1).max(80),status:z.enum(["active","paused","archived"]).default("active"),next_check_at:z.string().date().nullable().optional(),notes:z.string().max(10000).nullable().optional() }),
  evidence:z.object({ finding_id:z.uuid(),source_id:z.uuid(),relation_type:z.enum(["supports","contradicts","context","weak_support"]),excerpt:z.string().max(2000).nullable().optional() }), relations:z.object({ from_type:z.string().min(1),from_id:z.uuid(),to_type:z.string().min(1),to_id:z.uuid(),relation_type:z.enum(["related","supports","contradicts","derived_from","supersedes","depends_on","impacts","about"]) }), links:z.object({ knowledge_type:z.enum(["topic","source","finding","question","brief","collection"]),knowledge_id:z.uuid(),entity_type:z.string().min(1),entity_id:z.uuid() }), collection_items:z.object({ collection_id:z.uuid(),item_type:z.string().min(1),item_id:z.uuid() }), watch_updates:z.object({ watch_id:z.uuid(),update_type:z.string().min(1).max(80).default("observation"),summary:z.string().trim().min(1).max(4000) }) };
export async function GET(_:Request,{params}:{params:Promise<{resource:string}>}){try{const key=resource.parse((await params).resource);const{supabase,userId}=await requireUser();const{data,error}=await supabase.from(tables[key]).select("*").eq("user_id",userId).order("created_at",{ascending:false}).limit(100);if(error)throw error;return NextResponse.json({items:data??[]})}catch(error){return apiError(error,"Knowledge records could not be loaded.")}}
async function owned(supabase:Awaited<ReturnType<typeof requireUser>>["supabase"],userId:string,table:string,id:unknown){if(typeof id!=="string")return;const{data,error}=await supabase.from(table).select("id").eq("id",id).eq("user_id",userId).maybeSingle();if(error)throw error;if(!data)throw new Error("Choose a record from your own workspace.")}
const knowledgeTables:Record<string,string>={topic:"research_topics",source:"knowledge_sources",finding:"research_findings",question:"research_questions",brief:"research_briefs",collection:"knowledge_collections"};
const entityTables:Record<string,string>={project:"projects",client:"clients",lead:"leads",opportunity:"opportunities",proposal:"proposals",campaign:"campaigns",content:"content_items",goal:"goals",decision:"decisions",roadmap:"product_roadmap_items",product:"product_catalog_refs",supplier:"supplier_records",trip:"trips",commitment:"strategic_commitments",milestone:"strategic_milestones",note:"notes",file:"attachments"};
async function ownedType(supabase:Awaited<ReturnType<typeof requireUser>>["supabase"],userId:string,type:unknown,id:unknown,map:Record<string,string>){if(typeof type!=="string"||!map[type])throw new Error("Choose a supported record type.");await owned(supabase,userId,map[type],id)}
export async function POST(request:Request,{params}:{params:Promise<{resource:string}>}){try{const key=resource.parse((await params).resource);const input=schemas[key].parse(await request.json()) as Record<string,unknown>;const{supabase,userId}=await requireUser();if(["findings","questions","watches"].includes(key))await owned(supabase,userId,"research_topics",input.topic_id);if(key==="evidence"){await owned(supabase,userId,"research_findings",input.finding_id);await owned(supabase,userId,"knowledge_sources",input.source_id)}if(key==="watch_updates")await owned(supabase,userId,"watch_entities",input.watch_id);if(key==="collection_items"){await owned(supabase,userId,"knowledge_collections",input.collection_id);await ownedType(supabase,userId,input.item_type,input.item_id,{...knowledgeTables,...entityTables})}if(key==="relations"){await ownedType(supabase,userId,input.from_type,input.from_id,knowledgeTables);await ownedType(supabase,userId,input.to_type,input.to_id,{...knowledgeTables,decision:"decisions"})}if(key==="links"){await ownedType(supabase,userId,input.knowledge_type,input.knowledge_id,knowledgeTables);await ownedType(supabase,userId,input.entity_type,input.entity_id,entityTables)}if(key==="sources"&&input.attachment_id)await owned(supabase,userId,"attachments",input.attachment_id);const{data,error}=await supabase.from(tables[key]).insert({...input,user_id:userId} as never).select("*").single();if(error)throw error;return NextResponse.json({item:data},{status:201})}catch(error){return apiError(error,"Knowledge record could not be saved.")}}
