import { NextResponse } from "next/server";
import { z } from "zod";
import { apiError, isMissingOptionalSchema } from "@/lib/api";
import { requireUser } from "@/lib/supabase/server";

const blank = (value: unknown) => typeof value === "string" && !value.trim() ? null : value;
const nullableText = (max = 5000) => z.preprocess(blank, z.string().trim().max(max).nullable().optional());
const nullableUuid = z.preprocess(blank, z.uuid().nullable().optional());
const nullableDate = z.preprocess(blank, z.iso.date().nullable().optional());
const nullableDateTime = z.preprocess(blank, z.iso.datetime({ offset: true }).nullable().optional());
const currency = z.string().trim().length(3).transform((value) => value.toUpperCase()).default("MAD");

const resources = {
  trips: { table: "trips", order: "start_date", schema: z.object({ title: z.string().trim().min(1).max(240), destination_country: nullableText(120), destination_city: nullableText(120), start_date: nullableDate, end_date: nullableDate, purpose: nullableText(240), status: z.enum(["idea","planning","booked","in_progress","completed","canceled"]).default("idea"), budget: z.preprocess(blank, z.coerce.number().nonnegative().nullable().optional()), currency, notes: nullableText(10000) }) },
  segments: { table: "trip_segments", order: "starts_at", schema: z.object({ trip_id: z.uuid(), calendar_event_id: nullableUuid, title: z.string().trim().min(1).max(240), type: z.enum(["flight","train","bus","hotel","activity","meeting","transfer","other"]).default("other"), location: nullableText(240), starts_at: nullableDateTime, ends_at: nullableDateTime, notes: nullableText(5000) }) },
  reservations: { table: "travel_reservations", order: "departure_at", schema: z.object({ trip_id: z.uuid(), segment_id: nullableUuid, type: z.enum(["flight","hotel","riad","apartment","activity","car_rental","restaurant","other"]), provider: nullableText(240), name: z.string().trim().min(1).max(240), location: nullableText(240), confirmation_reference: nullableText(240), status: z.enum(["booked","scheduled","delayed","canceled","completed"]).default("booked"), payment_status: z.enum(["paid","partially_paid","pay_at_property","not_paid"]).nullable().optional(), amount: z.preprocess(blank, z.coerce.number().nonnegative().nullable().optional()), currency, check_in: nullableDateTime, check_out: nullableDateTime, airline: nullableText(240), flight_number: nullableText(80), departure_airport: nullableText(80), arrival_airport: nullableText(80), departure_at: nullableDateTime, arrival_at: nullableDateTime, terminal: nullableText(80), gate: nullableText(80), checked_baggage: nullableText(240), cabin_baggage: nullableText(240), notes: nullableText(5000) }) },
  documents: { table: "personal_documents", order: "expires_at", schema: z.object({ type: z.enum(["passport","national_id","residence_permit","travel_insurance","vaccination_certificate","driving_permit","insurance","bank_document","vehicle_document","membership","certificate","contract","other"]), label: z.string().trim().min(1).max(240), country: nullableText(120), issued_at: nullableDate, expires_at: nullableDate, notes: nullableText(5000) }) },
  "trip-document-links": { table: "trip_document_links", order: "created_at", schema: z.object({ trip_id: z.uuid(), document_id: z.uuid(), required: z.boolean().default(false), notes: nullableText(5000) }) },
  visas: { table: "visa_applications", order: "appointment_date", schema: z.object({ trip_id: nullableUuid, country: z.string().trim().min(1).max(120), visa_type: nullableText(120), status: z.enum(["researching","preparing","appointment_booked","submitted","additional_documents_requested","approved","rejected","withdrawn"]).default("researching"), application_date: nullableDate, appointment_date: nullableDate, submission_date: nullableDate, decision_date: nullableDate, valid_from: nullableDate, valid_until: nullableDate, application_reference: nullableText(240), notes: nullableText(5000) }) },
  "packing-lists": { table: "packing_lists", order: "created_at", schema: z.object({ trip_id: nullableUuid, title: z.string().trim().min(1).max(240), template_name: nullableText(120) }) },
  "packing-items": { table: "packing_items", order: "created_at", schema: z.object({ packing_list_id: z.uuid(), title: z.string().trim().min(1).max(240), category: z.enum(["documents","clothes","electronics","health","toiletries","sports","work","other"]).default("other"), quantity: z.preprocess(blank, z.coerce.number().positive().nullable().optional()), packed: z.boolean().default(false), required: z.boolean().default(false), notes: nullableText(5000) }) },
  "visa-requirements": { table: "visa_requirements", order: "created_at", schema: z.object({ visa_application_id: z.uuid(), title: z.string().trim().min(1).max(240), completed: z.boolean().default(false), notes: nullableText(5000) }) },
  renewals: { table: "personal_renewals", order: "due_date", schema: z.object({ title: z.string().trim().min(1).max(240), category: nullableText(120), due_date: nullableDate, lead_time_days: z.coerce.number().int().min(0).max(730).default(30), cost: z.preprocess(blank, z.coerce.number().nonnegative().nullable().optional()), currency, status: z.enum(["upcoming","in_progress","renewed","expired","canceled"]).default("upcoming"), document_id: nullableUuid, subscription_id: nullableUuid, notes: nullableText(5000) }) },
  admin: { table: "personal_admin_items", order: "due_date", schema: z.object({ title: z.string().trim().min(1).max(240), category: z.string().trim().min(1).max(120).default("other"), status: z.enum(["todo","waiting","appointment_booked","submitted","completed","canceled"]).default("todo"), due_date: nullableDate, next_action: nullableText(1000), document_id: nullableUuid, trip_id: nullableUuid, waiting_item_id: nullableUuid, notes: nullableText(5000) }) },
  dates: { table: "important_dates", order: "date", schema: z.object({ title: z.string().trim().min(1).max(240), date: z.iso.date(), recurrence: z.enum(["yearly","monthly","none"]).nullable().optional(), person_reference: nullableText(240), reminder_lead_days: z.coerce.number().int().min(0).max(730).default(7), calendar_event_id: nullableUuid, notes: nullableText(5000) }) },
  routines: { table: "personal_routines", order: "created_at", schema: z.object({ title: z.string().trim().min(1).max(240), frequency: z.enum(["daily","weekly"]).default("weekly"), days: z.array(z.coerce.number().int().min(0).max(6)).max(7).default([]), time_of_day: nullableText(10), category: nullableText(120), active: z.boolean().default(true), goal_id: nullableUuid }) },
  "routine-completions": { table: "routine_completions", order: "completed_on", schema: z.object({ routine_id: z.uuid(), completed_on: nullableDate }) },
} as const;
type Resource = keyof typeof resources;
function isResource(value: string): value is Resource { return value in resources; }

export async function GET(_: Request, context: { params: Promise<{ resource: string }> }) {
  try { const resource = (await context.params).resource; if (!isResource(resource)) return NextResponse.json({ error: "Unknown life collection." }, { status: 404 }); const { supabase, userId } = await requireUser(); const config = resources[resource]; let query = supabase.from(config.table).select("*").eq("user_id", userId).order(config.order, { ascending: true }).limit(100); if (resource === "trips" || resource === "documents") query = query.is("archived_at", null); const { data, error } = await query; if (error) throw error; return NextResponse.json({ records: data ?? [] }, { headers: { "Cache-Control": "private, no-store" } }); } catch (error) {
    if (isMissingOptionalSchema(error)) {
      return NextResponse.json({ records: [], schemaStatus: "unavailable", schemaDependency: "V7 life schema" });
    }
    return apiError(error, "Life records could not be loaded.");
  }
}

export async function POST(request: Request, context: { params: Promise<{ resource: string }> }) {
  try { const resource = (await context.params).resource; if (!isResource(resource)) return NextResponse.json({ error: "Unknown life collection." }, { status: 404 }); const parsed = resources[resource].schema.safeParse(await request.json()); if (!parsed.success) return NextResponse.json({ error: "Check the highlighted life details and try again." }, { status: 422 }); const { supabase, userId } = await requireUser(); const { data, error } = await supabase.from(resources[resource].table).insert({ ...parsed.data, user_id: userId } as never).select("*").single(); if (error) throw error; await supabase.from("action_audit_log").insert({ user_id: userId, actor: "user", action_type: `life_${resource}_created`, entity_type: resource, entity_id: data.id, summary: `Created ${resource.slice(0, -1)}.` } as never); return NextResponse.json({ record: data }, { status: 201 }); } catch (error) { return apiError(error, "Life record could not be saved."); }
}
