import { NextResponse } from "next/server";
import { z } from "zod";
import { apiError } from "@/lib/api";
import { requireUser } from "@/lib/supabase/server";

const blank = (value: unknown) => typeof value === "string" && !value.trim() ? null : value;
const nullableUuid = z.preprocess(blank, z.uuid().nullable().optional());
const currency = z.string().trim().length(3).transform((value) => value.toUpperCase()).default("MAD");
const resources = {
  suppliers: { table: "supplier_records", sort: "updated_at", schema: z.object({ company_id: z.uuid(), name: z.string().trim().min(1).max(240), contact_reference: z.preprocess(blank, z.string().max(500).nullable().optional()), lead_time_days: z.preprocess(blank, z.coerce.number().int().nonnegative().nullable().optional()), minimum_order_value: z.preprocess(blank, z.coerce.number().nonnegative().nullable().optional()), currency, payment_terms: z.preprocess(blank, z.string().max(500).nullable().optional()), notes: z.preprocess(blank, z.string().max(5000).nullable().optional()), active: z.boolean().default(true) }) },
  "supplier-orders": { table: "supplier_orders", sort: "updated_at", schema: z.object({ company_id: z.uuid(), supplier_id: z.uuid(), status: z.enum(["draft", "ordered", "partially_received", "received", "canceled"]).default("draft"), reference: z.preprocess(blank, z.string().max(160).nullable().optional()), total_value: z.preprocess(blank, z.coerce.number().nonnegative().nullable().optional()), currency, notes: z.preprocess(blank, z.string().max(5000).nullable().optional()) }) },
  roadmap: { table: "product_roadmap_items", sort: "updated_at", schema: z.object({ company_id: z.uuid(), project_id: nullableUuid, title: z.string().trim().min(1).max(240), type: z.enum(["feature", "improvement", "bug", "infrastructure", "experiment"]), status: z.enum(["backlog", "planned", "in_progress", "testing", "shipped", "paused"]).default("backlog"), priority: z.enum(["low", "medium", "high", "critical"]).default("medium"), horizon: z.enum(["now", "next", "later"]), github_issue_ref: z.preprocess(blank, z.string().max(100).nullable().optional()), github_pr_ref: z.preprocess(blank, z.string().max(100).nullable().optional()), business_impact: z.preprocess(blank, z.string().max(2000).nullable().optional()), target_date: z.preprocess(blank, z.iso.date().nullable().optional()) }) },
  incidents: { table: "incidents", sort: "updated_at", schema: z.object({ company_id: z.uuid(), deployment_id: nullableUuid, title: z.string().trim().min(1).max(240), severity: z.enum(["minor", "major", "critical"]), status: z.enum(["detected", "investigating", "resolved"]).default("detected"), customer_impact: z.preprocess(blank, z.string().max(2000).nullable().optional()), revenue_impact: z.preprocess(blank, z.coerce.number().nonnegative().nullable().optional()), currency: z.preprocess(blank, currency.nullable().optional()), github_issue_ref: z.preprocess(blank, z.string().max(100).nullable().optional()), notes: z.preprocess(blank, z.string().max(5000).nullable().optional()) }) },
  support: { table: "support_cases", sort: "created_at", schema: z.object({ company_id: z.uuid(), order_id: nullableUuid, product_id: nullableUuid, customer_reference: z.preprocess(blank, z.string().max(160).nullable().optional()), category: z.enum(["payment", "delivery", "product", "refund", "account", "website", "other"]), priority: z.enum(["low", "medium", "high", "critical"]).default("medium"), status: z.enum(["open", "investigating", "resolved", "closed"]).default("open"), summary: z.string().trim().min(1).max(5000) }) },
} as const;
const resourceSchema = z.enum(["suppliers", "supplier-orders", "roadmap", "incidents", "support"]);

async function ownedCompany(supabase: Awaited<ReturnType<typeof requireUser>>["supabase"], userId: string, companyId: string) { const company = await supabase.from("companies").select("id").eq("id", companyId).eq("user_id", userId).maybeSingle(); if (company.error) throw company.error; return Boolean(company.data); }

export async function GET(_: Request, { params }: { params: Promise<{ resource: string }> }) { try { const resource = resourceSchema.parse((await params).resource); const { supabase, userId } = await requireUser(); const company = await supabase.from("companies").select("id").eq("user_id", userId).eq("active", true).maybeSingle(); if (company.error) throw company.error; if (!company.data) return NextResponse.json({ records: [], state: "not_configured" }); const result = await supabase.from(resources[resource].table).select("*").eq("user_id", userId).eq("company_id", company.data.id).order(resources[resource].sort, { ascending: false }).limit(50); if (result.error) throw result.error; return NextResponse.json({ records: result.data ?? [] }); } catch (error) { return apiError(error, "Founder records could not be loaded."); } }
export async function POST(request: Request, { params }: { params: Promise<{ resource: string }> }) { try { const resource = resourceSchema.parse((await params).resource); const input = resources[resource].schema.parse(await request.json()); const { supabase, userId } = await requireUser(); if (!await ownedCompany(supabase, userId, input.company_id)) return NextResponse.json({ error: "Company is not available in your workspace." }, { status: 422 }); const result = await supabase.from(resources[resource].table).insert({ ...input, user_id: userId } as never).select("*").single(); if (result.error) throw result.error; return NextResponse.json({ record: result.data }, { status: 201 }); } catch (error) { return apiError(error, "Founder record could not be created."); } }
