import { NextResponse } from "next/server";
import { apiError } from "@/lib/api";
import { requireUser } from "@/lib/supabase/server";

import { legacyResources as resources, legacyResourceSchema as resourceSchema } from "@/lib/founder-os/legacy";
import { isResource } from "@/lib/founder-os/resources";
import { GET as operatingGET, POST as operatingPOST } from "@/app/api/operating/[resource]/route";
import { NextRequest } from "next/server";
import { validateLegacyReferences } from "@/lib/founder-os/legacy-repository";
async function ownedCompany(supabase: Awaited<ReturnType<typeof requireUser>>["supabase"], userId: string, companyId: string) { const company = await supabase.from("companies").select("id").eq("id", companyId).eq("user_id", userId).maybeSingle(); if (company.error) throw company.error; return Boolean(company.data); }

export async function GET(request: NextRequest, { params }: { params: Promise<{ resource: string }> }) { try { const key = (await params).resource; if (isResource(key)) return operatingGET(request, { params }); if (!resourceSchema.safeParse(key).success) return NextResponse.json({ error: "Unknown resource." }, { status: 404 }); const resource = resourceSchema.parse(key); const { supabase, userId } = await requireUser(); const result = await supabase.from(resources[resource].table).select("*").eq("user_id", userId).order(resources[resource].sort, { ascending: false }).limit(50); if (result.error) throw result.error; return NextResponse.json({ records: result.data ?? [] }); } catch (error) { return apiError(error, "Founder records could not be loaded."); } }
export async function POST(request: NextRequest, { params }: { params: Promise<{ resource: string }> }) { try { const key = (await params).resource; if (isResource(key)) return operatingPOST(request, { params }); if (!resourceSchema.safeParse(key).success) return NextResponse.json({ error: "Unknown resource." }, { status: 404 }); const resource = resourceSchema.parse(key); const input = resources[resource].schema.parse(await request.json()); const { supabase, userId } = await requireUser(); if (!await ownedCompany(supabase, userId, input.company_id)) return NextResponse.json({ error: "Company is not available in your workspace." }, { status: 422 }); await validateLegacyReferences(supabase, userId, input); const result = await supabase.from(resources[resource].table).insert({ ...input, user_id: userId } as never).select("*").single(); if (result.error) throw result.error; return NextResponse.json({ record: result.data }, { status: 201 }); } catch (error) { return apiError(error, "Founder record could not be created."); } }
