import { createHash } from "node:crypto";
import { cookies } from "next/headers";
import { NextResponse } from "next/server";
import { z } from "zod";
import { apiError } from "@/lib/api";
import { assistantTools,executeAssistantTool } from "@/lib/ai-tools";
import { requireUser } from "@/lib/supabase/server";

const inputSchema=z.object({message:z.string().trim().min(1).max(4000),conversationId:z.uuid().or(z.literal("")).default("")});
type Output={type:string;name?:string;arguments?:string;call_id?:string;content?:{type:string;text?:string}[]};type Response={id:string;output?:Output[];output_text?:string;error?:{message?:string}};
async function respond(body:Record<string,unknown>){const response=await fetch("https://api.openai.com/v1/responses",{method:"POST",headers:{Authorization:`Bearer ${process.env.OPENAI_API_KEY}`,"Content-Type":"application/json"},body:JSON.stringify(body)});if(!response.ok)throw new Error("OPENAI_UNAVAILABLE");return response.json() as Promise<Response>}
export async function POST(request:Request){try{if(!process.env.OPENAI_API_KEY)return NextResponse.json({error:"The assistant is not configured."},{status:503});const input=inputSchema.parse(await request.json());const{supabase,userId}=await requireUser();const cookieStore=await cookies();let conversationId=input.conversationId??cookieStore.get("dcc_ai_conversation")?.value;if(conversationId){const owned=await supabase.from("ai_conversations").select("id").eq("id",conversationId).eq("user_id",userId).maybeSingle();if(!owned.data)conversationId=""}if(!conversationId){const created=await supabase.from("ai_conversations").insert({user_id:userId,title:input.message.slice(0,80)}).select("id").single();if(created.error)throw created.error;conversationId=created.data.id;cookieStore.set("dcc_ai_conversation",conversationId,{httpOnly:true,sameSite:"lax",secure:process.env.NODE_ENV==="production",path:"/",maxAge:2592000})}await supabase.from("ai_messages").insert({user_id:userId,conversation_id:conversationId,role:"user",content:input.message});const history=await supabase.from("ai_messages").select("role,content").eq("user_id",userId).eq("conversation_id",conversationId).in("role",["user","assistant"]).order("created_at").limit(30);if(history.error)throw history.error;
 const safety=createHash("sha256").update(userId).digest("hex");let result=await respond({model:process.env.OPENAI_MODEL??"gpt-5-mini",instructions:"You are the concise planning assistant inside Daily Command Center. Use tools for workspace facts; never invent records. Never request or pass user_id. For any create, update, complete, delete, or calendar operation, summarize the exact proposed change and ask for explicit confirmation first. Only set confirmed=true after the user's current message clearly confirms that exact change.",input:(history.data??[]).map((message)=>({role:message.role,content:message.content})),tools:assistantTools,parallel_tool_calls:false,safety_identifier:safety,store:false});
 for(let round=0;round<5;round++){const calls=(result.output??[]).filter((item)=>item.type==="function_call"&&item.name&&item.call_id);if(!calls.length)break;const outputs=[];for(const call of calls){let output;try{output=await executeAssistantTool({client:supabase,userId},call.name!,JSON.parse(call.arguments??"{}"));}catch(error){output={error:error instanceof Error?error.message:"Tool failed."}}await supabase.from("ai_messages").insert({user_id:userId,conversation_id:conversationId,role:"tool",content:JSON.stringify(output),tool_name:call.name,tool_metadata:{call_id:call.call_id}});outputs.push({type:"function_call_output",call_id:call.call_id,output:JSON.stringify(output)})}result=await respond({model:process.env.OPENAI_MODEL??"gpt-5-mini",instructions:"Continue the Daily Command Center request using the tool results. Do not claim a write succeeded unless the tool output proves it.",input:[...(result.output??[]),...outputs],tools:assistantTools,parallel_tool_calls:false,safety_identifier:safety,store:false})}
 const text=result.output_text??((result.output??[]).flatMap((item)=>item.content??[]).filter((item)=>item.type==="output_text").map((item)=>item.text).join("\n")||"No answer was returned.");await supabase.from("ai_messages").insert({user_id:userId,conversation_id:conversationId,role:"assistant",content:text});return NextResponse.json({text,conversationId});
 }catch(error){if(error instanceof Error&&error.message==="OPENAI_UNAVAILABLE")return NextResponse.json({error:"The assistant is temporarily unavailable."},{status:502});return apiError(error,"The assistant could not respond.")}}
