import { NextResponse } from "next/server";
import { z } from "zod";
import { apiError } from "@/lib/api";
import { requireUser } from "@/lib/supabase/server";

const tables: Record<string, string> = { trips: "trips", segments: "trip_segments", reservations: "travel_reservations", documents: "personal_documents", "trip-document-links": "trip_document_links", visas: "visa_applications", "visa-requirements": "visa_requirements", renewals: "personal_renewals", admin: "personal_admin_items", dates: "important_dates", routines: "personal_routines", "packing-lists": "packing_lists", "packing-items": "packing_items" };
const editableFields: Record<string, readonly string[]> = { trips: ["title", "destination_country", "destination_city", "start_date", "end_date", "purpose", "status", "budget", "currency", "notes", "archived_at"], segments: ["title", "type", "location", "starts_at", "ends_at", "notes", "calendar_event_id"], reservations: ["trip_id", "type", "provider", "name", "location", "confirmation_reference", "status", "payment_status", "amount", "currency", "check_in", "check_out", "airline", "flight_number", "departure_airport", "arrival_airport", "departure_at", "arrival_at", "terminal", "gate", "checked_baggage", "cabin_baggage", "notes"], documents: ["type", "label", "country", "issued_at", "expires_at", "verified_at", "notes", "archived_at"], "trip-document-links": ["required", "notes"], visas: ["country", "visa_type", "status", "application_date", "appointment_date", "submission_date", "decision_date", "valid_from", "valid_until", "application_reference", "notes"], "visa-requirements": ["title", "completed", "completed_at", "notes"], renewals: ["title", "category", "due_date", "lead_time_days", "cost", "currency", "status", "document_id", "subscription_id", "notes", "completed_at"], admin: ["title", "category", "status", "due_date", "next_action", "document_id", "trip_id", "waiting_item_id", "notes", "completed_at"], dates: ["title", "date", "recurrence", "person_reference", "reminder_lead_days", "calendar_event_id", "notes"], routines: ["title", "frequency", "days", "time_of_day", "category", "active", "goal_id"], "packing-lists": ["title", "template_name"], "packing-items": ["title", "category", "quantity", "packed", "required", "notes"] };
export async function PATCH(request: Request, context: { params: Promise<{ resource: string; id: string }> }) { try { const { resource, id } = await context.params; const table = tables[resource]; if (!table) return NextResponse.json({ error: "Unknown life collection." }, { status: 404 }); const recordId = z.uuid().parse(id); const submitted = await request.json() as Record<string, unknown>; const allowed = editableFields[resource] ?? []; const values = Object.fromEntries(Object.entries(submitted).filter(([key]) => allowed.includes(key))); if (!Object.keys(values).length || Object.keys(values).length !== Object.keys(submitted).length) return NextResponse.json({ error: "This life update contains unsupported fields." }, { status: 422 }); const { supabase, userId } = await requireUser(); const { data, error } = await supabase.from(table).update(values as never).eq("id", recordId).eq("user_id", userId).select("*").maybeSingle(); if (error) throw error; if (!data) return NextResponse.json({ error: "This life record is not available." }, { status: 404 }); await supabase.from("action_audit_log").insert({ user_id: userId, actor: "user", action_type: `life_${resource}_updated`, entity_type: resource, entity_id: recordId, summary: `Updated ${resource.slice(0, -1)}.` } as never); return NextResponse.json({ record: data }); } catch (error) { return apiError(error, "Life record could not be updated."); } }

export async function DELETE(_: Request, context: { params: Promise<{ resource: string; id: string }> }) { try { const { resource, id } = await context.params; const table = tables[resource]; if (!table) return NextResponse.json({ error: "Unknown life collection." }, { status: 404 }); const recordId = z.uuid().parse(id); const { supabase, userId } = await requireUser(); const { data, error } = await supabase.from(table).delete().eq("id", recordId).eq("user_id", userId).select("id").maybeSingle(); if (error) throw error; if (!data) return NextResponse.json({ error: "This life record is not available." }, { status: 404 }); await supabase.from("action_audit_log").insert({ user_id: userId, actor: "user", action_type: `life_${resource}_deleted`, entity_type: resource, entity_id: recordId, summary: `Removed ${resource.slice(0, -1)}.` } as never); return NextResponse.json({ deleted: true }); } catch (error) { return apiError(error, "Life record could not be removed."); } }
