"use client";
import Link from "next/link";
import { useCallback, useState } from "react";
import { Button } from "@/components/ui/button";
import { Modal } from "@/components/ui/modal";
import { KnowledgeEntityLinksPanel, KnowledgeRelationsPanel } from "@/features/knowledge/knowledge-links";
import { useDeferredEffect } from "@/lib/use-deferred-effect";
type Row=Record<string,unknown>;
const title=(row:Row)=>String(row.title??row.id);
export function KnowledgeLibrary({kind,id}:{kind:"collections"|"briefs";id?:string}){const[items,setItems]=useState<Row[]>([]),[current,setCurrent]=useState<Row|null>(null),[open,setOpen]=useState(false),[error,setError]=useState(""),[schemaUnavailable,setSchemaUnavailable]=useState(false);const load=useCallback(async()=>{const r=await fetch(`/api/knowledge/${kind}`,{cache:"no-store"}),b=await r.json();if(!r.ok){setError(b.error??"Knowledge records could not be loaded.");return}setSchemaUnavailable(b.schemaStatus==="unavailable");setItems(b.items??[]);if(id)setCurrent((b.items??[]).find((row:Row)=>row.id===id)??null)},[kind,id]);useDeferredEffect(useCallback(()=>{void load()},[load]));const singular=kind==="collections"?"collection":"brief";const archive=async()=>{if(!current)return;const r=await fetch(`/api/knowledge/${kind}/${current.id}`,{method:"DELETE"});if(!r.ok)setError(`This ${singular} could not be archived.`);else await load()};if(id&&!current)return <main className="domain-page"><p className="dataset-note">{schemaUnavailable?"This detail is unavailable until the V9 knowledge schema is installed.":error||`Loading ${singular}…`}</p></main>;return <main className="domain-page knowledge-page"><header className="page-header"><div><p className="eyebrow">Knowledge library</p><h1>{id?title(current!):kind}</h1><p>{kind==="collections"?"Group references without duplicating research.":"Keep a current, evidence-based research summary."}</p></div><div className="strategy-actions"><Link className="button button--outline" href="/knowledge">Knowledge</Link>{!schemaUnavailable?<Button intent="brand" onClick={()=>setOpen(true)}>{id?`Edit ${singular}`:`New ${singular}`}</Button>:null}</div></header>{error?<p role="alert" className="field-error">{error}</p>:null}{schemaUnavailable?<section className="data-surface empty-state"><h2>Knowledge is not configured</h2><p>This environment is missing the V9 knowledge schema. These records will be available after that dependency is installed.</p></section>:id&&current?<LibraryDetail kind={kind} item={current} onChanged={load} onArchive={archive}/>:<section className="knowledge-section data-surface"><p className="eyebrow">{kind}</p><div className="signal-stack">{items.length?items.map(item=><Link className="signal-row" key={String(item.id)} href={`/knowledge/${kind}/${item.id}`}><span><strong>{title(item)}</strong><small>{String(item.status??item.description??"No description")}</small></span></Link>):<p className="dataset-note">No {kind} yet.</p>}</div></section>}{open?<LibraryForm kind={kind} item={current} onClose={()=>setOpen(false)} onSave={async values=>{const target=current?`/api/knowledge/${kind}/${current.id}`:`/api/knowledge/${kind}`;const r=await fetch(target,{method:current?"PATCH":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(values)});if(!r.ok){setError(`${singular} could not be saved.`);return}setOpen(false);await load()}}/>:null}</main>}
function LibraryForm({kind,item,onClose,onSave}:{kind:"collections"|"briefs";item:Row|null;onClose:()=>void;onSave:(value:Row)=>Promise<void>}){const[title,setTitle]=useState(String(item?.title??"")),[description,setDescription]=useState(String(item?.description??item?.summary??""));return <Modal open onClose={onClose} title={`${item?"Edit":"New"} ${kind==="collections"?"collection":"research brief"}`}><form className="simple-form" onSubmit={e=>{e.preventDefault();void onSave(kind==="collections"?{title,description}:{title,summary:description,status:item?.status??"draft"})}}><label>Title<input required value={title} onChange={e=>setTitle(e.target.value)}/></label><label>{kind==="collections"?"Description":"Summary"}<textarea rows={5} value={description} onChange={e=>setDescription(e.target.value)}/></label><div className="modal__actions"><Button emphasis="ghost" onClick={onClose}>Cancel</Button><Button intent="brand" type="submit">Save</Button></div></form></Modal>}
function LibraryDetail({kind,item,onChanged,onArchive}:{kind:"collections"|"briefs";item:Row;onChanged:()=>Promise<void>;onArchive:()=>Promise<void>}){const[entries,setEntries]=useState<Row[]>([]),[add,setAdd]=useState(false),[type,setType]=useState("topic"),[records,setRecords]=useState<Row[]>([]),[chosen,setChosen]=useState("");const load=useCallback(async()=>{if(kind!=="collections")return;const r=await fetch("/api/knowledge/collection_items",{cache:"no-store"}),b=await r.json();if(r.ok)setEntries((b.items??[]).filter((x:Row)=>x.collection_id===item.id))},[item.id,kind]);useDeferredEffect(useCallback(()=>{void load()},[load]));const lookup=async(value:string)=>{setType(value);const resource=({topic:"topics",source:"sources",finding:"findings",brief:"briefs",note:"notes",file:"files",decision:"decisions"}as Record<string,string>)[value];if(["notes","files","decisions"].includes(resource)){setRecords([]);return}const r=await fetch(`/api/knowledge/${resource}`,{cache:"no-store"});const b=await r.json();if(r.ok)setRecords(b.items??[])};return <>
  <section className="knowledge-section data-surface"><p className="eyebrow">{kind==="collections"?"Collection items":"Deterministic rollup"}</p>{kind==="collections"?<><div className="strategy-actions"><Button onClick={()=>{setAdd(true);void lookup("topic")}}>Add item</Button><Button emphasis="ghost" onClick={()=>void onArchive()}>Archive</Button></div><div className="signal-stack">{entries.length?entries.map(entry=><article className="signal-row" key={String(entry.id)}><span><strong>{String(entry.item_type)}</strong><small>{String(entry.item_id)}</small></span><Button emphasis="ghost" onClick={async()=>{await fetch(`/api/knowledge/collection_items/${entry.id}`,{method:"DELETE"});await load()}}>Remove</Button></article>):<p className="dataset-note">No references in this collection.</p>}</div>{add?<Modal open onClose={()=>setAdd(false)} title="Add collection item"><form className="simple-form" onSubmit={async e=>{e.preventDefault();if(!chosen)return;await fetch("/api/knowledge/collection_items",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({collection_id:item.id,item_type:type,item_id:chosen})});setAdd(false);await load()}}><label>Item type<select value={type} onChange={e=>void lookup(e.target.value)}>{["topic","source","finding","brief","note","file","decision"].map(value=><option key={value}>{value}</option>)}</select></label><label>Owned record<select value={chosen} onChange={e=>setChosen(e.target.value)}><option value="">Select a record</option>{records.map(record=><option key={String(record.id)} value={String(record.id)}>{title(record)}</option>)}</select></label><div className="modal__actions"><Button emphasis="ghost" onClick={()=>setAdd(false)}>Cancel</Button><Button intent="brand" type="submit" disabled={!chosen}>Add item</Button></div></form></Modal>:null}</>:<><p>Finding count, supporting sources, contradictions, open questions, and stale sources appear from linked topic evidence when a topic is attached.</p><div className="strategy-actions">{["current","outdated","archived"].map(status=><Button key={status} emphasis="outline" onClick={async()=>{await fetch(`/api/knowledge/briefs/${item.id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({status})});await onChanged()}}>Mark {status}</Button>)}</div></>}</section>
  {kind==="briefs"?<><KnowledgeRelationsPanel originType="brief" originId={String(item.id)}/><KnowledgeEntityLinksPanel originType="brief" originId={String(item.id)}/></>:null}
</>;}
