import { z } from "zod";
const blank = (value: unknown) => typeof value === "string" && !value.trim() ? null : value;
const nullableUuid = z.preprocess(blank, z.uuid().nullable().optional());
const currency = z.string().trim().length(3).transform((value) => value.toUpperCase()).default("MAD");
export const legacyResources = {
  suppliers: { table: "supplier_records", sort: "updated_at", schema: z.object({ company_id: z.uuid(), name: z.string().trim().min(1).max(240), contact_reference: z.preprocess(blank, z.string().max(500).nullable().optional()), lead_time_days: z.preprocess(blank, z.coerce.number().int().nonnegative().nullable().optional()), minimum_order_value: z.preprocess(blank, z.coerce.number().nonnegative().nullable().optional()), currency, payment_terms: z.preprocess(blank, z.string().max(500).nullable().optional()), notes: z.preprocess(blank, z.string().max(5000).nullable().optional()), active: z.boolean().default(true) }) },
  "supplier-orders": { table: "supplier_orders", sort: "updated_at", schema: z.object({ company_id: z.uuid(), supplier_id: z.uuid(), status: z.enum(["draft", "ordered", "partially_received", "received", "canceled"]).default("draft"), reference: z.preprocess(blank, z.string().max(160).nullable().optional()), total_value: z.preprocess(blank, z.coerce.number().nonnegative().nullable().optional()), currency, notes: z.preprocess(blank, z.string().max(5000).nullable().optional()) }) },
  roadmap: { table: "product_roadmap_items", sort: "updated_at", schema: z.object({ company_id: z.uuid(), project_id: nullableUuid, title: z.string().trim().min(1).max(240), type: z.enum(["feature", "improvement", "bug", "infrastructure", "experiment"]), status: z.enum(["backlog", "planned", "in_progress", "testing", "shipped", "paused"]).default("backlog"), priority: z.enum(["low", "medium", "high", "critical"]).default("medium"), horizon: z.enum(["now", "next", "later"]), github_issue_ref: z.preprocess(blank, z.string().max(100).nullable().optional()), github_pr_ref: z.preprocess(blank, z.string().max(100).nullable().optional()), business_impact: z.preprocess(blank, z.string().max(2000).nullable().optional()), target_date: z.preprocess(blank, z.iso.date().nullable().optional()) }) },
  incidents: { table: "incidents", sort: "updated_at", schema: z.object({ company_id: z.uuid(), deployment_id: nullableUuid, title: z.string().trim().min(1).max(240), severity: z.enum(["minor", "major", "critical"]), status: z.enum(["detected", "investigating", "resolved"]).default("detected"), customer_impact: z.preprocess(blank, z.string().max(2000).nullable().optional()), revenue_impact: z.preprocess(blank, z.coerce.number().nonnegative().nullable().optional()), currency: z.preprocess(blank, currency.nullable().optional()), github_issue_ref: z.preprocess(blank, z.string().max(100).nullable().optional()), notes: z.preprocess(blank, z.string().max(5000).nullable().optional()) }) },
  support: { table: "support_cases", sort: "created_at", schema: z.object({ company_id: z.uuid(), order_id: nullableUuid, product_id: nullableUuid, customer_reference: z.preprocess(blank, z.string().max(160).nullable().optional()), category: z.enum(["payment", "delivery", "product", "refund", "account", "website", "other"]), priority: z.enum(["low", "medium", "high", "critical"]).default("medium"), status: z.enum(["open", "investigating", "resolved", "closed"]).default("open"), summary: z.string().trim().min(1).max(5000) }) },
} as const;
export const legacyResourceSchema = z.enum(["suppliers", "supplier-orders", "roadmap", "incidents", "support"]);


export function legacyDefinition(key: keyof typeof legacyResources) {
 const config = legacyResources[key];
 return { ...config, name: key, label: key === "suppliers" ? "name" : key === "support" ? "summary" : key === "supplier-orders" ? "reference" : "title", allowedOperations: ["list", "retrieve", "create", "update", "close"], defaultSort: config.sort, searchFields: key === "suppliers" ? ["name"] : key === "support" ? ["summary"] : key === "supplier-orders" ? ["reference"] : ["title"], filterFields: ["company_id", ...(key === "suppliers" ? ["active"] : ["status"])] };
}
