import { z } from "zod";

export type Field = { key: string; label: string; kind: "text" | "textarea" | "number" | "date" | "boolean" | "select" | "relation" | "url"; required?: boolean; options?: string[]; table?: string; title?: string; min?: number; max?: number };
export type Resource = { table: string; title: string; description: string; fields: Field[]; label: string; route: string; archive?: string };
const text = (key: string, label: string, required = false): Field => ({ key, label, kind: "text", required });
const note = (key: string, label: string): Field => ({ key, label, kind: "textarea" });
const date = (key: string, label: string): Field => ({ key, label, kind: "date" });
const num = (key: string, label: string, min = 0, max?: number): Field => ({ key, label, kind: "number", min, max });
const select = (key: string, label: string, options: string[]): Field => ({ key, label, kind: "select", options, required: true });
const bool = (key: string, label: string): Field => ({ key, label, kind: "boolean" });
const link = (key: string, label: string, table: string, title = "title", required = false): Field => ({ key, label, kind: "relation", table, title, required });
const company = link("company_id", "Business", "companies", "name");
const project = link("project_id", "Project", "projects", "name");
const task = link("task_id", "Linked task", "tasks");
const owner = text("owner_label", "Owner");
const currency = text("currency", "Currency (ISO code)", true);
const impact = select("impact", "Impact", ["medium", "low", "high", "critical"]);
export const endpointTables = { task: "tasks", project: "projects", issue: "quality_incidents", decision: "decisions", risk: "operating_risks", person: "team_people", business: "companies", system: "operational_systems", obligation: "financial_obligations", commitment: "operating_commitments", sop: "operational_sops", process: "process_templates", run: "process_runs", client: "clients", opportunity: "opportunities", supplier: "supplier_records", product: "product_catalog_refs", campaign: "campaigns", calendar_event: "calendar_events", integration: "integrations", tool_system: "operational_systems", approval: "action_proposals", strategic_milestone: "strategic_milestones", experiment: "growth_experiments", forecast: "founder_forecasts", content: "content_items", asset: "asset_metadata" } as const;
export const resources = {
  decisions: { table: "decisions", title: "Decision Journal", route: "/decisions", label: "title", archive: "deleted_at", description: "Make the decision, record the expectation, then return to review the outcome.", fields: [text("title", "Decision title", true), { ...note("decision", "What is being decided?"), required: true }, company, project, owner, date("decision_date", "Decision date"), date("deadline", "Decision deadline"), select("status", "Status", ["proposed", "under_review", "decided", "implemented", "validated", "reversed", "archived", "active", "review_due", "superseded"]), select("impact", "Impact", ["medium", "low", "high", "critical"]), select("confidence", "Confidence", ["medium", "low", "high"]), select("reversibility", "Reversibility", ["reversible", "costly", "irreversible"]), note("reasoning", "Rationale"), note("assumptions", "Assumptions"), note("expected_outcome", "Expected outcome"), text("expected_metric", "Expected metric"), date("review_date", "Review date"), num("financial_exposure", "Financial exposure"), currency, bool("founder_required", "Founder decision required")] },
  issues: { table: "quality_incidents", title: "Critical issues", route: "/issues", label: "title", description: "Active threats to execution, linked to the work that resolves them.", fields: [text("title", "Issue", true), { ...note("description", "What happened?"), required: true }, select("status", "Status", ["open", "investigating", "mitigating", "blocked", "resolved", "closed", "corrective_action", "monitoring", "archived"]), select("severity", "Reported severity", ["medium", "low", "high", "critical"]), impact, select("urgency", "Urgency", ["normal", "soon", "immediate"]), company, project, owner, date("target_resolution_date", "Resolve by"), num("revenue_exposure", "Revenue exposure"), currency, note("customer_exposure", "Customer impact"), note("operational_exposure", "Operational impact"), bool("founder_required", "Founder intervention required"), link("corrective_task_id", "Corrective task", "tasks"), link("system_id", "Affected system", "operational_systems", "name"), note("root_cause", "Why did it happen?"), note("corrective_action", "Resolution / what did we do?"), note("preventive_action", "What will prevent recurrence?"), note("detection_gap", "What should have detected it earlier?"), bool("postmortem_required", "Postmortem required")] },
  "risk-register": { table: "operating_risks", title: "Risk register", route: "/risks/register", label: "title", description: "Track uncertainty, early warnings, mitigation and the next review.", fields: [text("title", "Risk", true), select("category", "Category", ["operational", "financial", "technical", "security", "customer", "supplier", "legal", "reputation", "strategic", "personal", "travel", "training"]), note("description", "Description"), select("status", "Status", ["identified", "monitoring", "mitigated", "materialized", "closed", "accepted"]), num("probability", "Probability (1–5)", 1, 5), num("impact", "Impact (1–5)", 1, 5), num("exposure", "Financial exposure"), currency, text("early_warning", "Early warning signal"), note("mitigation", "Mitigation"), note("contingency", "Contingency"), date("review_date", "Review date"), owner, company, project, link("issue_id", "Linked issue", "quality_incidents"), link("decision_id", "Linked decision", "decisions")] },
  dependencies: { table: "operational_dependencies", title: "Dependencies", route: "/dependencies", label: "dependency_label", description: "The source depends on the dependency. Waiting and blocked edges propagate downstream.", fields: [select("source_type", "Source type", Object.keys(endpointTables)), text("source_id", "Source record ID", true), select("dependency_type", "Depends on type", Object.keys(endpointTables)), text("dependency_id", "Depends on record ID", true), text("dependency_label", "Dependency label", true), select("state", "State", ["ready", "waiting", "blocked", "unavailable", "unknown"]), note("notes", "Downstream impact")] },
  businesses: { table: "companies", title: "Businesses", route: "/business-pulse/businesses", label: "name", description: "The same companies used by Founder, Commerce and linked projects.", fields: [text("name", "Business name", true), text("industry", "Business type"), select("lifecycle_status", "Business status", ["operating", "planning", "paused", "closed"]), owner, note("description", "Description"), note("strategic_objectives", "Strategic objectives"), bool("active", "Active"), currency, link("primary_project_id", "Primary project", "projects", "name")] },
  infrastructure: { table: "operational_systems", title: "Infrastructure", route: "/infrastructure", label: "name", description: "Operational systems and their continuity. Billing stays in linked subscriptions. Store access metadata only; never credentials.", fields: [text("name", "System", true), text("provider", "Provider"), select("system_type", "Category", ["other", "domain", "saas", "hosting", "database", "payments", "analytics", "api", "email", "storage", "monitoring", "automation", "ai"]), text("purpose", "Purpose", true), select("status", "Status", ["unknown", "active", "degraded", "unavailable", "deprecated"]), select("criticality", "Criticality", ["medium", "low", "high", "critical"]), company, owner, { key: "external_url", label: "System URL", kind: "url" }, { key: "repository_url", label: "Repository URL", kind: "url" }, select("environment", "Environment", ["production", "staging", "development"]), link("subscription_id", "Billing subscription", "subscriptions", "name"), date("renewal_date", "Service / domain expiry"), bool("auto_renew", "Auto renew"), select("backup_status", "Backup status", ["unknown", "verified", "failed", "not_configured"]), date("last_verified_date", "Health last verified"), project, link("risk_id", "Linked risk", "operating_risks"), text("billing_contact", "Billing contact"), select("billing_frequency", "Billing frequency", ["unknown", "monthly", "quarterly", "annual", "usage", "one_time"]), num("cost", "Recorded cost"), currency, text("backup_provider", "Backup provider"), text("domain_name", "Domain name"), text("registrar", "Registrar"), text("dns_owner", "DNS owner"), bool("production_dependency", "Production depends on this system"), text("branch", "Branch"), text("deployment_provider", "Deployment provider"), text("current_version", "Current version"), select("migration_status", "Migration status", ["unknown", "current", "pending", "blocked"]), note("notes", "Operational notes (no secrets)")] },
  "system-health": { table: "system_health_checks", title: "Technical health evidence", route: "/infrastructure/health", label: "name", description: "Dated component observations, not live provider status. Record metadata only; never credentials.", fields: [link("system_id", "System", "operational_systems", "name", true), text("name", "Component name", true), select("component", "Component", ["production", "database", "authentication", "payments", "external_api", "webhook", "cron", "storage", "monitoring", "backup", "migration"]), select("status", "Observed status", ["unknown", "ok", "attention", "failed"]), {...note("reason", "Evidence / explanation"), required:true}, {...date("checked_on", "Checked on"), required:true}, text("source_reference", "Evidence reference (no secrets)")] },
  access: { table: "system_access_records", title: "Access ownership", route: "/infrastructure/access", label: "person_label", description: "Metadata only. Track responsible people, backup ownership and recovery without storing credentials.", fields: [link("system_id", "System", "operational_systems", "name", true), text("person_label", "Person / team", true), link("person_id", "Team member", "team_people", "name"), select("access_level", "Access level", ["member", "admin", "owner", "read_only"]), bool("two_factor_enabled", "2FA enabled"), bool("recovery_path_exists", "Recovery path exists"), bool("backup_admin", "Is a backup admin"), date("last_audit_date", "Last access audit")] },
  kpis: { table: "kpi_definitions", title: "KPI definitions", route: "/business-pulse/kpis", label: "name", description: "Manual observations for external metrics; orders and revenue are calculated from commerce transactions.", fields: [text("name", "KPI name", true), company, select("category", "Category", ["revenue", "customers", "orders", "growth", "marketing", "operations", "finance", "product", "technology", "team"]), text("unit", "Unit", true), select("direction", "Direction of success", ["higher", "lower", "target_range", "informational"]), note("description", "Description"), owner, select("aggregation", "Aggregation (manual observations)", ["latest", "sum", "average", "min", "max", "count"]), num("target", "Target / range minimum", -1e15), num("target_max", "Range maximum", -1e15), num("warning_threshold", "Warning threshold", -1e15), num("critical_threshold", "Critical threshold", -1e15), select("source", "Source", ["manual", "commerce_orders", "commerce_revenue", "commerce_customers"]), text("source_reference", "Source / methodology"), select("frequency", "Frequency", ["monthly", "weekly", "daily"]), bool("active", "Active")] },
  "kpi-observations": { table: "kpi_observations", title: "KPI observations", route: "/business-pulse/observations", label: "observed_on", description: "Only external/manual KPIs need observations. Transactional KPIs are calculated automatically.", fields: [link("kpi_id", "KPI", "kpi_definitions", "name", true), { ...date("observed_on", "Observed on"), required: true }, { ...num("value", "Value", -1e15), required: true }, text("source_reference", "Evidence / source reference")] },
  wealth: { table: "personal_balance_entries", title: "Personal wealth", route: "/life/wealth", label: "name", description: "Personal assets and liabilities, separated by currency. Values are your estimates, not live market valuations.", fields: [text("name", "Asset / liability", true), select("kind", "Kind", ["asset", "liability"]), select("category", "Category", ["cash", "bank", "investment", "crypto", "vehicle", "property", "business_equity", "receivable", "loan", "credit", "tax", "obligation", "other"]), { ...num("amount", "Value"), required: true }, currency, bool("liquid", "Liquid asset"), text("owner_label", "Owner"), select("liquidity_class", "Liquidity class", ["unknown", "immediate", "short_term", "illiquid"]), date("due_date", "Liability due date"), num("payment_amount", "Payment amount"), note("interest_notes", "Interest metadata"), bool("material", "Major personal obligation"), { ...date("valued_on", "Valuation date"), required: true }, note("notes", "Valuation source / assumptions")] },
  relationships: { table: "operating_relationships", title: "Relationships", route: "/relationships", label: "name", description: "Context around clients, suppliers and team members. Link existing identities rather than recreating them.", fields: [text("name", "Relationship label", true), select("relationship_type", "Type", ["partner", "customer", "supplier", "employee", "contractor", "agency", "advisor", "contact"]), text("organization", "Organization"), text("role", "Role"), owner, company, link("client_id", "Existing client", "clients", "name"), link("supplier_id", "Existing supplier", "supplier_records", "name"), link("person_id", "Existing team member", "team_people", "name"), select("importance", "Importance", ["medium", "low", "high", "critical"]), select("status", "Health", ["unknown", "healthy", "attention", "inactive"]), date("last_interaction", "Last interaction"), date("next_followup", "Next follow-up"), note("notes", "Relationship context")] },
  commitments: { table: "operating_commitments", title: "Commitments", route: "/commitments", label: "title", description: "Promises across domains: what you owe and what others owe you.", fields: [text("title", "Promise", true), text("person_label", "Who", true), select("direction", "Direction", ["owed_to_me", "owed_by_me"]), select("status", "Status", ["open", "fulfilled", "cancelled"]), date("due_date", "Due date"), date("follow_up_date", "Follow-up date"), select("importance", "Importance", ["medium", "low", "high", "critical"]), select("source", "Captured from", ["manual", "email", "whatsapp", "call", "meeting"]), text("source_reference", "Communication reference"), company, project, task, link("waiting_id", "Waiting item", "waiting_items"), link("relationship_id", "Relationship", "operating_relationships", "name"), note("notes", "Expected outcome")] },
  experiments: { table: "growth_experiments", title: "Experiments", route: "/experiments", label: "name", description: "Compare measured outcomes with a defined baseline and target before drawing a conclusion.", fields: [text("name", "Experiment", true), text("hypothesis", "Hypothesis", true), text("target_metric", "Target metric", true), note("expected_outcome", "Expected outcome"), select("status", "Status", ["idea", "planned", "running", "paused", "completed", "cancelled"]), select("confidence", "Confidence", ["medium", "low", "high"]), select("outcome_result", "Outcome result", ["SUPPORTED", "PARTIALLY_SUPPORTED", "NOT_SUPPORTED", "INCONCLUSIVE"]), company, project, owner, date("start_date", "Start date"), date("end_date", "Review / end date"), num("baseline", "Baseline", -1e15), num("target_value", "Target", -1e15), num("actual_value", "Actual", -1e15), select("direction", "Direction of success", ["higher", "lower"]), num("cost_estimate", "Cost estimate"), currency, link("decision_id", "Linked decision", "decisions"), link("kpi_id", "Linked KPI", "kpi_definitions", "name"), link("risk_id", "Linked risk", "operating_risks"), note("result", "Conclusion / findings"), note("lesson", "Lesson learned"), note("next_action", "Next action")] },
  forecasts: { table: "founder_forecasts", title: "Forecast journal", route: "/forecasts", label: "prediction", description: "Record calibrated predictions across business and operations, then resolve against outcomes to expose systematic estimation bias.", fields: [text("prediction", "Prediction statement", true), select("domain", "Domain", ["general", "revenue", "growth", "product", "delivery", "supplier", "team", "operations", "finance", "personal"]), company, project, owner, { ...date("created_date", "Prediction date"), required: true }, { ...date("resolution_date", "Resolution date"), required: true }, { ...note("predicted_outcome", "Predicted outcome"), required: true }, select("confidence", "Confidence", ["medium", "low", "high"]), note("assumptions", "Key assumptions"), select("resolution", "Resolution status", ["unresolved", "correct", "partially_correct", "incorrect"]), note("actual_result", "Actual outcome"), note("calibration_notes", "Calibration notes (why right or wrong)"), link("decision_id", "Linked decision", "decisions"), link("experiment_id", "Linked experiment", "growth_experiments", "name"), link("kpi_id", "Linked KPI", "kpi_definitions", "name")] },
  mobility: { table: "trips", title: "Mobility", route: "/travel/mobility", label: "title", archive: "archived_at", description: "Track entered stay limits and dates. This arithmetic does not verify immigration eligibility or rolling visa rules.", fields: [text("title", "Stay", true), text("destination_country", "Country"), text("destination_city", "City"), select("status", "Status", ["planning", "idea", "booked", "in_progress", "completed", "canceled"]), date("start_date", "Entry date"), date("end_date", "Expected departure"), date("actual_departure", "Actual departure"), text("visa_type", "Visa type"), date("visa_start", "Visa start"), date("insurance_expiry", "Insurance expiry"), date("administrative_deadline", "Administrative deadline"), select("administrative_status", "Administrative status", ["unknown", "pending", "ready", "blocked"]), bool("passport_required", "Passport required"), link("passport_document_id", "Passport document", "personal_documents", "label"), note("accommodation_notes", "Accommodation / local logistics"), date("visa_expiry", "Visa expiry"), num("allowed_stay_days", "Documented allowed stay (days)", 1, 3650), text("stay_source", "Source of stay allowance"), note("notes", "Passport / insurance / requirements")] },
  documents: { table: "personal_documents", title: "Document metadata", route: "/life/documents", label: "label", archive: "archived_at", description: "Track document validity and verification. Supporting files remain in the existing private document vault.", fields: [text("label", "Document name", true), select("type", "Type", ["other", "passport", "visa", "business_license", "national_id", "residence_permit", "travel_insurance", "vaccination_certificate", "driving_permit", "insurance", "bank_document", "vehicle_document", "membership", "certificate", "contract"]), text("country", "Country"), date("issued_at", "Issue date"), date("expires_at", "Expiry date"), text("issuer", "Issuer"), text("storage_reference", "Storage reference (no document numbers)"), text("owner_label", "Owner"), select("verification_status", "Verification status", ["unverified", "verified", "needs_review"]), {...num("reminder_days", "Remind within days", 7, 180), required: true}, note("notes", "Renewal / verification notes")] },
  assets: { table: "asset_metadata", title: "Asset intelligence", route: "/assets", label: "name", description: "Reusable business assets and IP. Track status, last use, reuse potential and maintenance deadlines.", fields: [text("name", "Asset name", true), select("type", "Type", ["other", "image", "video", "logo", "brand", "contract", "presentation", "spreadsheet", "report", "creative", "technical"]), select("value_category", "Value category", ["core", "differentiating", "supporting", "exploratory", "dormant"]), select("reuse_potential", "Reuse potential", ["high", "medium", "low"]), select("status", "Status", ["draft", "active", "review", "expired", "archived"]), company, project, owner, date("last_used_date", "Last used date"), date("review_date", "Review date"), date("expiry_date", "Expiry date"), select("maintenance_requirement", "Maintenance requirement", ["none", "periodic_review", "continuous_update", "license_renewal"]), date("maintenance_due_date", "Maintenance due date"), link("sop_id", "Linked SOP", "operational_sops", "title"), link("attachment_id", "Existing file", "attachments", "file_name"), link("content_id", "Content item", "content_items"), link("parent_asset_id", "Parent asset", "asset_metadata", "name"), text("location_reference", "Location / storage reference"), text("version", "Version"), text("source", "Source"), note("notes", "Usage and context")] },
  "training-plans": { table: "training_plans", title: "Training plans", route: "/fitness/plans", label: "name", description: "Your training methodology and thresholds. The system compares logged work with your plan; it does not diagnose health.", fields: [text("name", "Training phase", true), select("status", "Status", ["active", "planned", "completed", "archived"]), text("methodology", "Methodology / source", true), date("start_date", "Start date"), date("end_date", "End date"), date("race_date", "Race / milestone"), num("weekly_sessions", "Weekly session target", 0, 100), num("weekly_minutes", "Weekly duration target", 0, 10080), num("maximum_weekly_increase", "Volume increase warning (%)", 0, 300), num("minimum_sleep_hours", "Your sleep review threshold (hours)", 0, 24), note("notes", "Progression / recovery interpretation")] },
  recovery: { table: "training_observations", title: "Recovery observations", route: "/fitness/recovery", label: "observed_on", description: "Optional self-reported observations. Missing data stays unknown; no clinical interpretation is generated.", fields: [{ ...date("observed_on", "Observation date"), required: true }, num("sleep_hours", "Sleep hours", 0, 24), num("resting_hr", "Resting heart rate", 20, 240), num("body_weight", "Body weight (kg)", 1, 500), select("recovery", "Self-reported recovery", ["unknown", "good", "fair", "poor"]), note("notes", "Context")] },
} satisfies Record<string, Resource>;
export type ResourceKey = keyof typeof resources;
export const isResource = (key: string): key is ResourceKey => Object.hasOwn(resources, key);
export function resourceSchema(key: ResourceKey, partial = false) {
  const shape: Record<string, z.ZodType> = { source_inbox_id: z.uuid().nullable().optional() };
  for (const field of resources[key].fields as Field[]) {
    let schema: z.ZodType = field.kind === "number" ? z.number().finite().min(field.min ?? 0).max(field.max ?? 1e15)
      : field.kind === "boolean" ? z.boolean()
      : field.kind === "date" ? z.iso.date()
      : field.kind === "relation" || field.key.endsWith("_id") ? z.uuid()
      : field.kind === "select" ? z.enum(field.options as [string, ...string[]])
      : field.kind === "url" ? z.url().refine(v => /^https?:\/\//i.test(v), "Use an HTTP or HTTPS URL.")
      : z.string().trim().min(field.required ? 1 : 0).max(field.kind === "textarea" ? 10000 : 240);
    if (field.key === "currency") schema = z.string().regex(/^[A-Z]{3}$/, "Use a three-letter uppercase currency code.");
    if (!field.required) schema = schema.nullable().optional();
    if (partial) schema = schema.optional();
    shape[field.key] = schema;
  }
  return z.object(shape).strict();
}

// Every URL resolves through this allowlist. Deletion is limited to link/observation records.
export function resourceDefinition(key: ResourceKey) {
  const config: Resource = resources[key];
  const archiveValues: Partial<Record<ResourceKey, Record<string, unknown>>> = {
    decisions: { status: "archived" }, issues: { status: "archived" }, "risk-register": { status: "closed" }, businesses: { active: false },
    infrastructure: { status: "deprecated" }, kpis: { active: false }, relationships: { status: "inactive" },
    commitments: { status: "cancelled" }, experiments: { status: "cancelled" }, assets: { status: "archived" }, "training-plans": { status: "archived" },
  };
  const removable = ["dependencies", "access", "kpi-observations", "recovery", "system-health", "forecasts"].includes(key);
  return { ...config, name: key, schema: resourceSchema(key), allowedOperations: ["list", "retrieve", "create", "update", ...(removable ? ["delete"] : config.archive || archiveValues[key] ? ["archive"] : [])],
    defaultSort: "updated_at", searchFields: [config.label], filterFields: config.fields.filter(f => f.kind === "select").map(f => f.key),
    removeMode: removable ? "delete" : config.archive || archiveValues[key] ? "archive" : null,
    archiveValues: key === "decisions" ? { status: "archived" } : config.archive ? { [config.archive]: new Date().toISOString() } : archiveValues[key] };
}
