import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import type {SupabaseClient} from '@supabase/supabase-js';
import {cashPosition,calculateReceivablesAging,evaluateCollectionPriority,buildForecastEntries,buildCashflowForecast,reconcileForecastToActual,calculateRunway,evaluateCashBuffer,calculateBudgetVariance,calculateConcentration,buildGrossToCashBridge,evaluateInvestmentAffordability,applyFinancialScenario,buildFinancialRisks,rankNextFinancialMove,buildMonthlyFinanceReview,type FinancialRow,type ForecastEntry} from '../src/lib/financial-control';
import {validateFinancialRecord,financialTargets,financialViews} from '../src/lib/financial-schema';
import {financialOwned,saveFinancialRecord} from '../src/lib/financial-server';
import {expandedFinancialConditions} from '../src/lib/financial-conditions';
import {financialNotificationCandidates,financialAutomationDue,financialAutomationTypes} from '../src/lib/financial-notifications';
import {financialAssistantTools,financialWrites,executeFinancialTool} from '../src/lib/financial-ai';
import {notificationRoute,preferenceAllows} from '../src/lib/v4-notifications';
const today='2026-09-09',id='11111111-1111-4111-8111-111111111111',other='22222222-2222-4222-8222-222222222222';
const row=(v:Record<string,unknown>={}):FinancialRow=>({id,currency:'MAD',...v});
const entry=(v:Partial<ForecastEntry>={}):ForecastEntry=>({key:'invoice:1',sourceType:'invoice',sourceId:id,title:'Invoice',amount:100,currency:'MAD',date:today,direction:'in',confidence:'expected',route:'/finance/invoices',assumption:'Due date',...v});
const account=row({name:'Operating',status:'active'}),snapshot=row({cash_account_id:id,balance:1000,as_of:today+'T08:00:00Z'});
test('cash uses explicit latest owner-loaded snapshot',()=>{assert.equal(cashPosition([account],[snapshot,row({...snapshot,balance:500,as_of:'2026-08-01'})],today)[0].balance,1000);});
test('missing cash remains unknown',()=>assert.equal(cashPosition([account],[],today)[0].balance,null));
test('manual cash permits explicit zero',()=>assert.equal(cashPosition([account],[row({...snapshot,balance:0})],today)[0].balance,0));
test('inactive account excluded',()=>assert.deepEqual(cashPosition([row({...account,status:'inactive'})],[snapshot],today),[]));
test('future snapshot excluded',()=>assert.equal(cashPosition([account],[row({...snapshot,as_of:'2027-01-01'})],today)[0].balance,null));
test('cash snapshot currency cannot leak into other account',()=>assert.equal(cashPosition([account],[row({...snapshot,currency:'EUR'})],today)[0].balance,null));
test('stale balance threshold respected',()=>assert.equal(cashPosition([account],[row({...snapshot,as_of:'2026-09-01'})],today,7)[0].stale,true));
test('configured longer stale threshold respected',()=>assert.equal(cashPosition([account],[row({...snapshot,as_of:'2026-09-01'})],today,14)[0].stale,false));
for(const [due,expected] of [['2026-09-10','Current'],['2026-09-08','1–30'],['2026-08-09','31–60'],['2026-07-10','61–90'],['2026-05-01','90+'],[null,'Undated']])test('receivables aging '+expected,()=>assert.equal(calculateReceivablesAging([row({status:'sent',due_date:due,amount_remaining:120})],today)[0].aging,expected));
for(const status of ['draft','paid','cancelled'])test('receivable excludes '+status,()=>assert.equal(calculateReceivablesAging([row({status,amount_remaining:100})],today).length,0));
test('partial invoice uses remaining not total',()=>assert.equal(buildForecastEntries({invoices:[row({status:'partial',total_amount:1000,amount_remaining:200,due_date:today})]},today)[0].amount,200));
test('promise caps at remaining balance',()=>{const entries=buildForecastEntries({invoices:[row({status:'sent',amount_remaining:100,due_date:today})],promises:[row({id:other,invoice_id:id,amount:200,promised_date:today,status:'open'})]},today);assert.equal(entries.length,1);assert.equal(entries[0].amount,100);});
test('promise and invoice remainder do not double count',()=>{const entries=buildForecastEntries({invoices:[row({status:'sent',amount_remaining:100,due_date:today})],promises:[row({id:other,invoice_id:id,amount:40,promised_date:today,status:'open'})]},today);assert.equal(entries.reduce((n,e)=>n+e.amount,0),100);assert.equal(entries[0].confidence,'committed');});
test('overdue invoice without promise has unknown date',()=>assert.equal(buildForecastEntries({invoices:[row({status:'sent',amount_remaining:100,due_date:'2026-08-01'})]},today)[0].date,null));
test('overdue obligation included immediately',()=>assert.equal(buildForecastEntries({obligations:[row({status:'committed',amount:20,due_at:'2026-08-01'})]},today)[0].date,today));
test('expense reference is not proof of paid obligation',()=>assert.equal(buildForecastEntries({obligations:[row({status:'committed',amount:20,due_at:today,expense_id:other})]},today).length,1));
for(const status of ['paid','deferred','cancelled'])test('outflow excludes '+status+' obligation',()=>assert.equal(buildForecastEntries({obligations:[row({status,amount:100,due_at:today})]},today).length,0));
test('supplier delivery is not invented payment date',()=>assert.equal(buildForecastEntries({supplierOrders:[row({status:'ordered',total_value:100,expected_at:today})]},today)[0].date,null));
test('supplier obligation suppresses duplicate order amount',()=>assert.equal(buildForecastEntries({supplierOrders:[row({status:'ordered',total_value:100})],obligations:[row({id:other,status:'committed',amount:100,due_at:today,source_type:'supplier_order',source_id:id})]},today).length,1));
test('subscription monthly recurring forecast',()=>assert.equal(buildForecastEntries({subscriptions:[row({status:'active',billing_cycle:'monthly',next_billing_date:today,amount:20})]},today).length,3));
test('subscription expense does not prove settlement',()=>assert.equal(buildForecastEntries({subscriptions:[row({status:'active',billing_cycle:'yearly',next_billing_date:today,amount:20})],expenses:[row({subscription_id:id,expense_date:today})]},today).length,1));
test('subscription obligation reconciles same renewal once',()=>assert.equal(buildForecastEntries({subscriptions:[row({status:'active',billing_cycle:'yearly',next_billing_date:today,amount:20})],obligations:[row({id:other,status:'committed',amount:20,due_at:today,source_type:'subscription',source_id:id})]},today).length,1));
test('pipeline is possible not committed cash',()=>assert.equal(buildForecastEntries({opportunities:[row({stage:'proposal',estimated_value:400,expected_close_date:today})]},today)[0].confidence,'possible'));
test('forecast excludes possible by default',()=>assert.equal(buildCashflowForecast({MAD:100},[entry({confidence:'possible'})],today)[0].buckets[0].closing,100));
test('forecast missing opening never becomes fake balance',()=>assert.equal(buildCashflowForecast({},[entry()],today)[0].buckets[0].closing,null));
test('forecast currencies stay separate',()=>assert.deepEqual(buildCashflowForecast({MAD:100,EUR:50},[entry()],today).map(f=>[f.currency,f.buckets[0].closing]),[['EUR',50],['MAD',200]]));
for(const [date,bucket] of [['2026-09-09',0],['2026-10-09',1],['2026-11-08',2],['2026-12-08',2]] as const)test('forecast date bucket '+date,()=>assert.equal(buildCashflowForecast({MAD:0},[entry({date})],today)[0].buckets[bucket].inflows,100));
test('forecast after day90 excluded',()=>assert.equal(buildCashflowForecast({MAD:0},[entry({date:'2026-12-09'})],today)[0].buckets[2].closing,0));
test('forecast same-day cash dip conservative',()=>assert.equal(buildCashflowForecast({MAD:50},[entry(),entry({key:'out',direction:'out'})],today)[0].lowest,-50));
test('reconciliation consumes actual only once across recurring rows',()=>{const r=reconcileForecastToActual([entry(),entry({key:'next',date:'2026-10-09'})],[{sourceType:'invoice',sourceId:id,currency:'MAD',amount:120}]);assert.equal(r.length,1);assert.equal(r[0].amount,80);});
test('reconciliation never crosses currency',()=>assert.equal(reconcileForecastToActual([entry()],[{sourceType:'invoice',sourceId:id,currency:'EUR',amount:100}])[0].amount,100));
for(const [overdue,priority] of [[0,'Routine'],[5,'Follow up'],[45,'High priority'],[95,'Critical']] as const)test('collection priority '+priority,()=>assert.equal(evaluateCollectionPriority({overdueDays:overdue,amount:100}),priority));
test('missed promise plus cash need critical',()=>assert.equal(evaluateCollectionPriority({overdueDays:0,amount:100,promiseMissed:true,cashNeed:true}),'Critical'));
test('runway insufficient history unavailable',()=>assert.equal(calculateRunway(100,[],true).state,'unavailable'));
test('runway incomplete settlement unavailable',()=>assert.equal(calculateRunway(100,Array(3).fill({inflow:0,outflow:10}),false).state,'unavailable'));
test('runway unknown cash unavailable',()=>assert.equal(calculateRunway(null,Array(3).fill({inflow:0,outflow:10}),true).state,'unavailable'));
test('valid runway uses net cash burn',()=>assert.equal(calculateRunway(100,Array(3).fill({inflow:10,outflow:30}),true).months,5));
test('positive cashflow does not return infinite runway',()=>{const r=calculateRunway(100,Array(3).fill({inflow:30,outflow:10}),true);assert.equal(r.state,'cashflow_positive');assert.equal(r.months,null);});
for(const [cash,state] of [[null,'Unknown'],[50,'Below target'],[110,'Near target'],[150,'Above target']] as const)test('buffer '+state,()=>assert.equal(evaluateCashBuffer(cash,100),state));
test('no buffer policy unknown',()=>assert.equal(evaluateCashBuffer(100,null),'Unknown'));
const budget=row({amount:1000,period_start:'2026-09-01',period_end:'2026-09-30'});
test('budget incurred and future committed separated',()=>{const b=calculateBudgetVariance(budget,[row({amount:100,expense_date:today})],[row({amount:200,status:'committed',due_at:today})]);assert.equal(b.recordedExpenses,100);assert.equal(b.committed,200);assert.equal(b.paid,0);assert.equal(b.remaining,700);});
test('paid expense-linked obligation not counted twice',()=>{const b=calculateBudgetVariance(budget,[row({amount:100,expense_date:today})],[row({amount:100,status:'paid',paid_at:today,expense_id:id})]);assert.equal(b.remaining,900);assert.equal(b.paid,100);});
test('budget excludes foreign currency',()=>assert.equal(calculateBudgetVariance(budget,[row({amount:100,expense_date:today,currency:'EUR'})],[]).remaining,1000));
test('budget scope isolates projects',()=>assert.equal(calculateBudgetVariance(row({...budget,scope_type:'project',scope_id:id}),[row({amount:100,expense_date:today,project_id:other})],[]).remaining,1000));
test('concentration uses currency-specific denominators',()=>assert.deepEqual(calculateConcentration([{entity:id,currency:'MAD',amount:10},{entity:other,currency:'EUR',amount:10}]).map(c=>c.share),[1,1]));
test('unknown client remains part of concentration denominator',()=>assert.equal(calculateConcentration([{entity:id,currency:'MAD',amount:50},{entity:null,currency:'MAD',amount:50}])[0].share,.5));
test('gross-to-cash never adds payments to invoice revenue',()=>{const b=buildGrossToCashBridge([row({total_amount:100,amount_remaining:40,status:'partial'})],[row({amount:60})],[])[0];assert.equal(b.invoiced,100);assert.equal(b.collected,60);assert.equal(b.netIncome,null);});
for(const [cash,low,buffer,result] of [[null,100,10,'Insufficient data'],[100,30,20,'Would breach buffer'],[100,100,20,'Affordable now']] as const)test('affordability '+result,()=>assert.equal(evaluateInvestmentAffordability(20,cash,low,buffer),result));
test('scenario does not mutate live entries',()=>{const entries=[entry()],before=JSON.stringify(entries);const changed=applyFinancialScenario(entries,row({collection_delay_days:14,inflow_change_percent:-50}),today);assert.equal(changed[0].amount,50);assert.equal(changed[0].date,'2026-09-23');assert.equal(JSON.stringify(entries),before);});
test('scenario keeps other currencies unchanged',()=>assert.equal(applyFinancialScenario([entry({currency:'EUR'})],row({inflow_change_percent:-100}),today)[0].amount,100));
test('scenario includes pipeline only on explicit opt-in',()=>{const e=entry({sourceType:'opportunity',confidence:'possible'});assert.equal(applyFinancialScenario([e],row({}),today).length,0);assert.equal(applyFinancialScenario([e],row({include_pipeline:true}),today)[0].confidence,'expected');});
test('scenario hiring costs remain hypothetical',()=>{const e=applyFinancialScenario([],row({monthly_cost:100,setup_cost:50,starts_at:today}),today);assert.equal(e.length,3);assert.equal(e[0].amount,150);assert(e.every(r=>r.sourceType==='scenario'));});
test('monthly review uses period dates',()=>assert.equal(buildMonthlyFinanceReview({payments:[row({amount:100,payment_date:today}),row({amount:50,payment_date:'2026-08-01'})]},'2026-09-01','2026-09-30').bridge[0].collected,100));
test('risk queue ranking bounded deterministic',()=>{const risks=Array.from({length:20},(_,i)=>({key:String(i),title:'Review',evidence:'Stored',currency:'MAD',amount:1,date:today,severity:'important' as const,score:i,route:'/financial-control',action:'Review'}));assert.equal(rankNextFinancialMove(risks).length,12);assert.equal(rankNextFinancialMove(risks)[0].score,19);});
test('completed obligations resolve derived risk',()=>{const risks=buildFinancialRisks({cash:[],forecasts:[],receivables:[],settings:[],obligations:[row({status:'paid',amount:100,due_at:today})],promises:[],today});assert.equal(risks.length,0);});
test('budget breach is an actionable condition',()=>assert(expandedFinancialConditions({budgets:[row({...budget,status:'active'})],expenses:[row({amount:1500,expense_date:today})]}, {},[],[],today).some(r=>r.title==='Budget exceeded')));
test('resolved subscription usage no renewal warning',()=>assert.equal(expandedFinancialConditions({subscriptions:[row({status:'active',next_billing_date:today})],subscription_reviews:[row({subscription_id:id,status:'keep'})]}, {},[],[],today).length,0));
for(const status of ['active','inactive','archived'])test('account lifecycle '+status,()=>assert.equal(validateFinancialRecord('accounts',{name:'Cash',type:'cash',currency:'MAD',status}).status,status));
for(const status of ['planned','committed','due','paid','deferred','cancelled'])test('obligation lifecycle '+status,()=>assert.equal(validateFinancialRecord('obligations',{title:'Rent',amount:100,currency:'MAD',due_at:today,status,category:'Office',paid_at:status==='paid'?today:null}).status,status));
for(const status of ['idea','considering','approved','scheduled','spent','cancelled'])test('investment lifecycle '+status,()=>assert.equal(validateFinancialRecord('investments',{title:'Equipment',amount:100,currency:'MAD',status}).status,status));
for(const status of ['open','met','missed','cancelled'])test('promise lifecycle '+status,()=>assert.equal(validateFinancialRecord('promises',{invoice_id:id,amount:100,currency:'MAD',promised_date:today,status}).status,status));
test('arbitrary browser owner denied by strict schema',()=>assert.throws(()=>validateFinancialRecord('accounts',{name:'Cash',type:'cash',currency:'MAD',user_id:other})));
test('budget reversed dates rejected',()=>assert.throws(()=>validateFinancialRecord('budgets',{name:'Q',amount:100,currency:'MAD',period_start:'2026-10-01',period_end:today})));
test('paid obligation requires payment date',()=>assert.throws(()=>validateFinancialRecord('obligations',{title:'Rent',amount:100,currency:'MAD',due_at:today,status:'paid',category:'Office'})));
test('money fractional precision rejected',()=>assert.throws(()=>validateFinancialRecord('investments',{title:'X',amount:1.001,currency:'MAD'})));
test('unknown currency rejected',()=>assert.throws(()=>validateFinancialRecord('accounts',{name:'X',type:'cash',currency:'mixed'})));
test('future snapshot rejected',()=>assert.throws(()=>validateFinancialRecord('snapshots',{cash_account_id:id,currency:'MAD',balance:100,as_of:'2099-01-01T00:00:00Z',request_id:other})));
function missingClient(){const calls:Array<[string,unknown]>=[];const chain={select(){return this;},eq(field:string,value:unknown){calls.push([field,value]);return this;},maybeSingle:async()=>({data:null,error:null})};return {calls,client:{from:()=>chain} as unknown as SupabaseClient};}
for(const type of Object.keys(financialTargets))test('owner validation rejects inaccessible '+type,async()=>{const m=missingClient();await assert.rejects(financialOwned(m.client,id,type,other),/unavailable/);assert(m.calls.some(([field,value])=>field==='user_id'&&value===id));});
test('cash snapshots cannot be updated',async()=>{const m=missingClient();await assert.rejects(saveFinancialRecord(m.client,id,'snapshots',{cash_account_id:id,currency:'MAD',balance:10,as_of:'2026-01-01T00:00:00Z',request_id:other},id),/append-only/);});
for(const name of Object.keys(financialWrites))test('AI write confirmation blocks '+name,async()=>{const m=missingClient();const r=await executeFinancialTool(m.client,id,name,{record:{},confirmed:false});assert.equal(r.confirmation_required,true);assert.equal(m.calls.length,0);});
test('financial AI declarations use canonical schema and no duplicate names',()=>assert.equal(new Set(financialAssistantTools.map(t=>t.name)).size,financialAssistantTools.length));
for(const type of financialAutomationTypes)test('financial automation available '+type,()=>assert(financialAutomationDue(type,{time:'08:00'},'UTC',null,new Date('2026-10-01T10:00:00Z'))!==undefined));
test('automation respects configured weekday',()=>assert.equal(financialAutomationDue('daily_cash_review',{days:[1]},'UTC',null,new Date('2026-09-09T10:00:00Z')),null));
test('automation respects timezone',()=>assert.equal(financialAutomationDue('daily_cash_review',{time:'09:00'},'America/New_York',null,new Date('2026-09-09T12:00:00Z')),null));
test('quarter review only on quarter start',()=>assert.equal(financialAutomationDue('quarterly_finance_review',{},'UTC',null,new Date('2026-09-09T12:00:00Z')),null));
test('automation does not run twice local day',()=>assert.equal(financialAutomationDue('daily_cash_review',{},'UTC','2026-09-09T09:00:00Z',new Date('2026-09-09T12:00:00Z')),null));
test('notification uses existing financial route',()=>assert.equal(notificationRoute('finance','financial_cashflow'),'/financial-control/cashflow'));
test('preferences off honored',()=>assert.equal(preferenceAllows(false,'low','critical'),false));
test('important only suppresses attention',()=>assert.equal(preferenceAllows(true,'high','attention'),false));
test('all includes info',()=>assert.equal(preferenceAllows(true,'low','info'),true));
test('financial noise filtered',()=>assert.equal(financialNotificationCandidates([{key:'a',title:'X',evidence:'Y',currency:'MAD',amount:null,date:null,severity:'attention',score:1,route:'/financial-control',action:'Review'}]).length,0));
const css=readFileSync('src/features/financial-control/financial-control.css','utf8');
for(const width of [390,430])test('financial mobile structural contract '+width,()=>{assert.match(css,/@media\(max-width:600px\)/);assert.match(css,/grid-template-columns:minmax\(0,1fr\)/);assert.match(css,/min-height:44px/);assert.match(css,/overflow-wrap:anywhere/);});
test('financial views expose all planning routes',()=>{for(const view of ['cashflow','budgets','scenarios','collections','review/monthly','review/quarterly'])assert(financialViews.some(v=>v===view));});
test('migration uses financial dedupe and owner policies',()=>{const sql=readFileSync('supabase/migrations/20260909021007_v15_financial_planning_cashflow_operating_system.sql','utf8');assert.match(sql,/financial_notification_condition_once/);assert.match(sql,/financial_automation_slot_once/);assert.match(sql,/enable row level security/);assert.match(sql,/financial_validate_links/);assert.match(sql,/financial_audit_change/);});
