import test from 'node:test';
import assert from 'node:assert/strict';
import { financeHistory, financeSnapshot, renewingSubscriptions, type FinanceRecords } from '../src/lib/finance-dashboard';
const records: FinanceRecords={clients:[],invoices:[{id:'one',status:'partial',currency:'MAD',amount_remaining:75,due_date:'2026-09-10'},{id:'draft',status:'draft',currency:'MAD',amount_remaining:900,due_date:'2026-09-01'},{id:'usd',status:'sent',currency:'USD',amount_remaining:300,due_date:'2026-09-01'},{id:'paid',status:'paid',currency:'MAD',amount_remaining:0,due_date:'2026-09-01'}],payments:[{id:'p1',currency:'MAD',amount:25,payment_date:'2026-09-01'},{id:'p2',currency:'MAD',amount:100,payment_date:'2026-08-31'},{id:'p3',currency:'USD',amount:900,payment_date:'2026-09-01'}],expenses:[{id:'e1',currency:'MAD',amount:40,expense_date:'2026-09-20'}],subscriptions:[{id:'s1',status:'active',currency:'MAD',next_billing_date:'2026-10-01'},{id:'s2',status:'paused',currency:'MAD',next_billing_date:'2026-10-01'},{id:'s3',status:'active',currency:'MAD',next_billing_date:'2026-12-01'}]};
test('cash summary isolates currency, dates, partial balances and drafts',()=>{const snapshot=financeSnapshot(records,'MAD','2026-09','2026-09-27');assert.deepEqual(snapshot.metrics,{expected:75,received:25,outstanding:75,overdue:75,expenses:40,net:-15});assert.deepEqual(snapshot.overdue.map(row=>row.id),['one']);});
test('historical month changes cash flow without inventing historic outstanding balances',()=>{const snapshot=financeSnapshot(records,'MAD','2026-08','2026-09-27');assert.equal(snapshot.metrics.received,100);assert.equal(snapshot.metrics.outstanding,75);assert.equal(snapshot.metrics.expected,0);});
test('history handles year boundary and zero months',()=>{const history=financeHistory(records,'MAD','2026-02',3);assert.deepEqual(history.map(row=>row.month),['2025-12','2026-01','2026-02']);assert.ok(history.every(row=>row.received===0&&row.expenses===0));});
test('history reconciles received and expenses',()=>{const history=financeHistory(records,'MAD','2026-09',3);assert.deepEqual(history.map(row=>row.received),[0,100,25]);assert.equal(history[2].expenses,40);});
test('renewals include only active subscriptions in next 30 days',()=>{assert.deepEqual(renewingSubscriptions(records,'MAD','2026-09-27').map(row=>row.id),['s1']);});
