import test from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { buildFounderState, daysUntil, dependencyImpact, experimentOutcome, expiryWindow, issuePriority, kpiEvaluation, mobilityState, waitingStatus, wealthSummary } from "../src/lib/founder-os/intelligence";
import { resourceSchema, resources } from "../src/lib/founder-os/resources";
import { metricPeriods } from "../src/lib/founder-os/pulse";
import { parseDomainInput } from "../src/lib/domains";
const today = "2026-09-22";
const issue = { id: "issue-1", title: "Catalog sync blocked", severity: "critical", impact: "critical", urgency: "immediate", status: "open", company_id: "company-1" };
test("empty Founder State creates no work and no fabricated scores", () => { const s = buildFounderState({}, today); assert.equal(s.status, "clear"); assert.deepEqual(s.attention, []); assert.equal(s.changes, null); });
test("unavailable and truncated sources never count as healthy", () => { for (const status of ["unavailable", "limited"] as const) assert.equal(buildFounderState({}, today, [{ source: "issues", status, count: 0 }]).status, "incomplete"); });
test("critical issue derives priority with visible reasons", () => { const s = buildFounderState({ issues: [issue] }, today); assert.equal(s.status, "critical"); assert.equal(s.attention[0].title, issue.title); assert.ok(s.attention[0].reasons.includes("Immediate response required")); });
test("low-impact overdue tasks are not critical attention", () => { const s = buildFounderState({ tasks: [{ id: "task", title: "Tidy labels", status: "planned", priority: "low", due_date: "2020-01-01" }] }, today); assert.deepEqual(s.attention, []); });
test("due dates use calendar-day arithmetic and unknown dates stay unknown", () => { assert.equal(daysUntil("2026-09-23T23:59:00Z", today), 1); assert.equal(daysUntil(null, today), null); assert.equal(daysUntil("invalid", today), null); });
test("waiting status resolves received requests before checking deadlines", () => { assert.equal(waitingStatus({ id: "w", status: "received", expected_by: "2020-01-01" }, today), "received"); assert.equal(waitingStatus({ id: "w", expected_by: "2026-09-21" }, today), "overdue"); assert.equal(waitingStatus({ id: "w", expected_by: today }, today), "due_soon"); assert.equal(waitingStatus({ id: "w" }, today), "waiting"); });
test("expiry windows include exact boundaries and expired records", () => { assert.equal(expiryWindow("2026-09-21", today), "expired"); assert.equal(expiryWindow("2026-09-29", today), 7); assert.equal(expiryWindow("2026-10-22", today), 30); assert.equal(expiryWindow(null, today), "unknown"); });
test("dependency traversal is cycle safe, deduplicated and excludes ready edges", () => { const edges = [{ id: "1", source_type: "task", source_id: "a", dependency_type: "system", dependency_id: "s", state: "blocked" }, { id: "2", source_type: "project", source_id: "p", dependency_type: "task", dependency_id: "a", state: "waiting" }, { id: "3", source_type: "system", source_id: "s", dependency_type: "project", dependency_id: "p", state: "blocked" }, { id: "4", source_type: "task", source_id: "b", dependency_type: "system", dependency_id: "s", state: "ready" }]; assert.deepEqual(dependencyImpact(edges, "system", "s"), ["task:a", "project:p"]); });
test("issue priority requires impact as well as urgency for critical", () => { assert.equal(issuePriority({ id: "i", severity: "low", urgency: "immediate" }, 0, today).severity, "medium"); assert.equal(issuePriority({ ...issue, urgency: "normal" }, 0, today).severity, "high"); assert.equal(issuePriority({ ...issue, urgency: "normal" }, 2, today).severity, "critical"); });
test("all important Founder UI signals are produced from recorded facts", () => { const s = buildFounderState({ issues: [issue], waiting: [{ id: "w", title: "Supplier answer", status: "waiting", importance: "high", expected_by: "2026-09-20" }], documents: [{ id: "d", label: "Passport", expires_at: "2026-09-21" }], systems: [{ id: "s", name: "Domain", status: "active", criticality: "critical", owner_label: "Owner", renewal_date: "2026-09-24" }], decisions: [{ id: "d", title: "Pricing review", status: "implemented", review_date: today }] }, today); for (const type of ["UNRESOLVED_INCIDENT", "WAITING_OVERDUE", "DOCUMENT_EXPIRING", "INFRA_RENEWAL_SOON", "DECISION_REVIEW_DUE"]) assert.ok(s.signals.some(signal => signal.type === type)); assert.ok(s.attention.length <= 5); });
test("rank is deterministic for same inputs and limits founder attention", () => { const issues = Array.from({ length: 8 }, (_, i) => ({ ...issue, id: String(i) })); assert.deepEqual(buildFounderState({ issues }, today).attention, buildFounderState({ issues: [...issues].reverse() }, today).attention); assert.equal(buildFounderState({ issues }, today).attention.length, 5); });
test("closed issues do not surface and dismissals do not manufacture resolution", () => { const previous = buildFounderState({ issues: [issue] }, today).signals; const s = buildFounderState({ issues: [issue] }, today, [], previous, [previous[0].id]); assert.equal(s.signals.length, 0); assert.deepEqual(s.changes, []); assert.equal(buildFounderState({ issues: [{ ...issue, status: "closed" }] }, today).signals.length, 0); });
test("changes need a baseline; missing sources cannot resolve previous signals", () => { const previous = buildFounderState({ issues: [issue] }, today).signals; assert.equal(buildFounderState({}, today, [], previous).changes?.[0].change, "no longer detected"); assert.deepEqual(buildFounderState({}, today, [{ source: "issues", status: "unavailable", count: 0 }], previous).changes, []); });
test("founder bottleneck requires explicitly recorded owed-by-me direction", () => { const waiting = Array.from({ length: 3 }, (_, i) => ({ id: String(i), status: "waiting", direction: "owed_by_me" })); assert.ok(buildFounderState({ waiting }, today).signals.some(s => s.type === "FOUNDER_BOTTLENECK")); assert.equal(buildFounderState({ waiting: waiting.map(r => ({ ...r, direction: "owed_to_me" })) }, today).signals.length, 0); });
test("KPI direction, zero baseline and missing metrics are handled transparently", () => { assert.equal(kpiEvaluation({ id: "k", direction: "lower", critical_threshold: 10 }, 11, 0).status, "critical"); assert.equal(kpiEvaluation({ id: "k", direction: "higher", critical_threshold: 10 }, 11, 0).status, "within_thresholds"); assert.equal(kpiEvaluation({ id: "k", target: 10 }, null, 5).status, "unknown"); assert.equal(kpiEvaluation({ id: "k", target: 10 }, 8, 0).change, null); assert.equal(kpiEvaluation({ id: "k", target: 10 }, 8, 5).variance, -20); });
test("metric periods use UTC calendar boundaries including leap years", () => { assert.equal(metricPeriods("monthly", "2024-03-01").previous, "2024-02-01T00:00:00.000Z"); assert.equal(metricPeriods("weekly", today).start, "2026-09-21T00:00:00.000Z"); });
test("wealth currencies and liabilities remain separated", () => { const result = wealthSummary([{ id: "a", kind: "asset", amount: 100, currency: "MAD", liquid: true }, { id: "b", kind: "liability", amount: 30, currency: "MAD" }, { id: "c", kind: "asset", amount: 500, currency: "EUR", category: "business_equity" }]); assert.equal(result.MAD.net, 70); assert.equal(result.EUR.net, 500); assert.equal(result.MAD.liquid, 100); });
test("mobility counts entry day, stops completed stays and leaves missing limits unknown", () => { assert.deepEqual(mobilityState({ id: "t", start_date: "2026-09-04", allowed_stay_days: 90 }, today), { used: 19, remaining: 71, visaDays: null }); assert.equal(mobilityState({ id: "t", start_date: "2026-09-04", end_date: "2026-09-10", status: "completed", allowed_stay_days: 90 }, today).used, 7); assert.equal(mobilityState({ id: "t", start_date: "2026-09-30", allowed_stay_days: 90 }, today).remaining, null); });
test("experiments cannot claim success without actual, target and completion", () => { assert.equal(experimentOutcome({ id: "e", actual_value: 10 }), "Insufficient outcome data"); assert.equal(experimentOutcome({ id: "e", target_value: 10, actual_value: 12, status: "running" }), "Awaiting completed experiment"); assert.equal(experimentOutcome({ id: "e", target_value: 10, actual_value: 12, status: "completed", direction: "lower" }), "Defined target not met"); });
test("strict resource validation rejects secrets, owner injection, invalid links and NaN", () => { assert.equal(resourceSchema("wealth").safeParse({ user_id: "someone", name: "Cash" }).success, false); assert.equal(resourceSchema("access", true).safeParse({ password: "secret" }).success, false); assert.equal(resourceSchema("access", true).safeParse({ system_id: "invalid" }).success, false); assert.equal(resourceSchema("wealth", true).safeParse({ amount: NaN }).success, false); assert.equal(resourceSchema("infrastructure", true).safeParse({ external_url: "javascript:alert(1)" }).success, false); });
test("decision and waiting validation extends the canonical entity API", () => { assert.equal(parseDomainInput("decisions", { title: "New choice", decision: "Proposed choice", status: "proposed", expected_outcome: "Qualified leads", review_date: today }).success, true); assert.equal(parseDomainInput("waiting", { title: "Supplier", blocking_revenue: true, direction: "owed_by_me" }).success, true); });
test("canonical operational tables are reused", () => { assert.equal(resources.issues.table, "quality_incidents"); assert.equal(resources.infrastructure.table, "operational_systems"); assert.equal(resources.businesses.table, "companies"); assert.equal(resources.experiments.table, "growth_experiments"); assert.equal(resources.mobility.table, "trips"); });
test("migration includes RLS, ownership guards, audit and proposed memory only", () => { const sql = readFileSync("supabase/migrations/20260923010000_founder_state_operating_layer.sql", "utf8"); for (const table of ["operating_risks", "operating_commitments", "system_access_records", "kpi_definitions", "kpi_observations", "personal_balance_entries", "operating_relationships"]) { assert.ok(sql.includes(`alter table public.${table} enable row level security`)); assert.ok(sql.includes(`on public.${table} for all to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id)`)); } assert.ok(sql.includes("Referenced record must belong to the same owner")); assert.ok(sql.includes("public.activity_log")); assert.ok(sql.includes("'proposed','weak'")); assert.doesNotMatch(sql, /drop table|disable row level security|security definer/i); });

import { attentionReview, monthlyWealth, trainingReview } from "../src/lib/founder-os/review";
import { parseCapture } from "../src/lib/capture";
test("time accounting excludes unfinished sessions and does not invent categories", () => { const r = attentionReview([{ id: "1", started_at: today, ended_at: today, duration_seconds: 3600 }, { id: "2", started_at: today, duration_seconds: 7200 }], [], "2026-09-01", today); assert.equal(r.recordedHours, 1); assert.equal(r.categories.unclassified, 1); assert.deepEqual(r.suggestions, []); });
test("automation suggestions require repeated observed time and declared recurrence", () => { const sessions = Array.from({ length: 5 }, (_, i) => ({ id: String(i), task_id: "t", started_at: today, ended_at: today, duration_seconds: 1800 })); const task = { id: "t", title: "Report", priority: "low", recurrence_frequency: "daily" }; assert.equal(attentionReview(sessions, [task], today, today).suggestions.length, 1); assert.equal(attentionReview(sessions, [{ ...task, recurrence_frequency: null }], today, today).suggestions.length, 0); });
test("training thresholds are user defined, use matched weekdays, and require data", () => { const rows = [{ id: "a", activity_date: "2026-09-22", activity_type: "Running", duration_seconds: 3600, perceived_exertion: 5 }, { id: "b", activity_date: "2026-09-15", activity_type: "Running", duration_seconds: 1800 }]; const p = { id: "p", name: "Base", status: "active", methodology: "My plan", maximum_weekly_increase: 20 }; const r = trainingReview(rows, [], [p], today); assert.equal(r.change, 100); assert.equal(r.load, 300); assert.equal(r.flags.length, 1); assert.equal(trainingReview(rows, [], [], today).flags.length, 0); });
test("monthly valuations carry forward once per entry without currency blending", () => { const values = [{ id: "1", entry_id: "a", valued_on: "2026-08-01", kind: "asset", currency: "MAD", amount: 100 }, { id: "2", entry_id: "a", valued_on: "2026-09-01", kind: "asset", currency: "MAD", amount: 150 }, { id: "3", entry_id: "b", valued_on: "2026-08-01", kind: "liability", currency: "EUR", amount: 20 }]; assert.deepEqual(monthlyWealth(values)[1].net, { EUR: -20, MAD: 150 }); });
test("new capture prefixes preserve intent for explicit triage", () => { for (const kind of ["issue", "risk", "commitment", "contact", "experiment", "knowledge"] as const) assert.equal(parseCapture(`${kind} review supplier`).kind, kind); assert.equal(parseCapture("waiting for supplier").kind, "waiting"); });
test("KPI deterioration is connected to Founder State with threshold evidence", () => { const s = buildFounderState({ kpis: [{ id: "k", name: "Qualified leads", direction: "higher", critical_threshold: 20, current_value: 12, previous_value: 25, frequency: "monthly", source: "manual" }] }, today); assert.equal(s.attention[0].type, "KPI_CRITICAL"); assert.match(s.attention[0].reasons[0], /critical threshold 20/); });
test("a successful deployment supersedes an earlier failed one", () => { const deployments = [{ id: "1", company_id: "c", status: "failed", created_at: "2026-09-20" }, { id: "2", company_id: "c", status: "ready", created_at: "2026-09-21" }]; assert.deepEqual(buildFounderState({ deployments }, today).signals, []); });
test("financial risks keep the existing financial model evidence", () => { const s = buildFounderState({ financialRisks: [{ id: "f", title: "Reserve breach", evidence: "Projected cash 10; required reserve 20", severity: "critical", amount: 10, currency: "MAD", action: "Review forecast", route: "/financial-control" }] }, today); assert.equal(s.status, "critical"); assert.equal(s.signals[0].reasons[0], "Projected cash 10; required reserve 20"); });

test("configured training flags appear as review evidence, not a health diagnosis", () => {
  const state = buildFounderState({ trainingSignals: [{ id: "volume", title: "Review training and recovery", reason: "Logged duration exceeds your plan threshold." }] }, today);
  assert.equal(state.signals[0].type, "TRAINING_REVIEW");
  assert.equal(state.signals[0].severity, "medium");
  assert.equal(state.attention.length, 0);
});

test("Founder reminders ignore low-priority conditions and keep stable dedupe keys", async () => {
  const { founderNotificationCandidates } = await import("../src/lib/founder-os/notifications");
  const signals = buildFounderState({ issues: [issue], waiting: [{ id: "w", title: "Low impact wait", expected_by: "2020-01-01" }] }, today).signals;
  const candidates = founderNotificationCandidates(signals);
  assert.equal(candidates.length, 1);
  assert.equal(candidates[0].severity, "critical");
  assert.equal(candidates[0].entityType, "founder_signal");
  assert.deepEqual(candidates, founderNotificationCandidates(signals));
});

test("Today receives a bounded signal preview while preserving the real total", async () => {
  const { compactFounderState } = await import("../src/lib/founder-os/intelligence");
  const state = buildFounderState({ issues: Array.from({ length: 200 }, (_, index) => ({ ...issue, id: `issue-${index}` })) }, today);
  const compact = compactFounderState(state);
  assert.equal(compact.signalCount, 200);
  assert.equal(compact.attention.length, 3);
  assert.equal(compact.signals.length, 0);
  assert.ok(JSON.stringify(compact).length < 5000);
});
test('personal material obligations enter high-priority attention and reminders', async () => {
 const data={wealth:[{id:'due',name:'Tax payment',kind:'liability',amount:500,currency:'MAD',material:true,due_date:'2026-09-25'}]};
 const state=buildFounderState(data,today);
 assert.equal(state.attention[0]?.type,'LARGE_OBLIGATION_SOON');
 const {founderNotificationCandidates}=await import('../src/lib/founder-os/notifications');
 assert.ok(founderNotificationCandidates(state.signals).some(s=>s.dedupeKey.includes('LARGE_OBLIGATION_SOON')));
});
