"use client";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { useCallback,useMemo,useState } from "react";
import { Button } from "@/components/ui/button";
import { DomainPage } from "@/features/domains/domain-page";
import { useDeferredEffect } from "@/lib/use-deferred-effect";
type Row=Record<string,unknown>&{id:string};type Data={items:Row[];dueSoon:Row[];awaitingApproval:Row[];scheduled:Row[];recentlyPublished:Row[]};const stages=["idea","brief","copy","designing","review","approved","scheduled","published"];
export function ContentCommandCenter({initialView="kanban"}:{initialView?:string}){const[data,setData]=useState<Data|null>(null);const[view,setView]=useState(initialView);const[error,setError]=useState("");const router=useRouter();const chooseView=(name:string)=>{setView(name);router.replace(`/content?view=${name}`,{scroll:false})};const load=useCallback(async()=>{try{const response=await fetch("/api/content",{cache:"no-store"});const body=await response.json();if(!response.ok)throw new Error(body.error);setData(body)}catch(reason){setError(reason instanceof Error?reason.message:"Content could not be loaded.")}},[]);useDeferredEffect(useCallback(()=>{void load()},[load]));const grouped=useMemo(()=>Object.fromEntries(stages.map((stage)=>[stage,data?.items.filter((item)=>item.status===stage)??[]])),[data]);return <div><div className="domain-page"><header className="page-header"><div><p className="eyebrow">Creative operations</p><h1>Content command</h1><p>Move campaigns from idea to published without losing the client, deadline, or prompt behind the work.</p></div><Link className="button button--outline button--neutral" href="/campaigns">Campaigns</Link></header><div className="domain-toolbar"><div className="view-switch" aria-label="Content view">{["kanban","list","calendar"].map((name)=><button className={view===name?"active":""} onClick={()=>chooseView(name)} key={name}>{name[0].toUpperCase()+name.slice(1)}</button>)}</div><span className="status">{data?.items.length??0} active</span></div>{error?<div className="inline-error" role="alert"><p>{error}</p><Button emphasis="outline" onClick={()=>void load()}>Try again</Button></div>:!data?<div className="empty-state"><span>···</span><h2>Loading the pipeline</h2></div>:view==="kanban"?<div className="content-board">{stages.map((stage)=><section key={stage}><header><strong>{stage}</strong><span>{grouped[stage].length}</span></header>{grouped[stage].map((item)=><Link href={`/content/${item.id}`} className="content-ticket" key={item.id}><span className="content-preview" aria-hidden="true"/><strong>{String(item.title)}</strong><small>{String((item.clients as {name?:string}|null)?.name??item.platform??"Unassigned")}</small><em>{item.due_date?`Due ${item.due_date}`:String(item.approval_status??"")}</em></Link>)}</section>)}</div>:view==="calendar"?<div className="timeline-list">{data.items.filter((item)=>item.due_date||item.publish_date).map((item)=><Link href={`/content/${item.id}`} className="signal-row" key={item.id}><span><strong>{String(item.due_date??String(item.publish_date).slice(0,10))}</strong>{String(item.title)} · {String(item.status)}</span></Link>)}</div>:<div className="data-surface">{data.items.map((item)=><Link href={`/content/${item.id}`} className="data-row" key={item.id}><strong>{String(item.title)}</strong><span>{String(item.status)}</span><span>{String(item.due_date??item.publish_date??"—")}</span></Link>)}</div>}</div><DomainPage domain="content" embedded/></div>}
