"use client";

import Link from "next/link";
import { useRouter } from "next/navigation";
import { useCallback,useState } from "react";
import { AttachmentSection } from "@/components/attachment-section";
import { Button } from "@/components/ui/button";
import { Modal } from "@/components/ui/modal";
import { useToast } from "@/components/toast-provider";
import { useDeferredEffect } from "@/lib/use-deferred-effect";
import { DecisionResearchPanel } from "@/features/knowledge/decision-research-panel";

type Row=Record<string,unknown>&{id:string};
type Data={decision:Row;alternatives:Row[]};
const replacementDefaults={title:"",decision:"",reasoning:"",impact:"medium",confidence:"medium",review_date:""};

export function DecisionWorkspace({id}:{id:string}){
  const[data,setData]=useState<Data|null>(null);const[error,setError]=useState("");const[alternativeOpen,setAlternativeOpen]=useState(false);const[supersedeOpen,setSupersedeOpen]=useState(false);const[busy,setBusy]=useState(false);const[alt,setAlt]=useState({title:"",reason_rejected:""});const[replacement,setReplacement]=useState(replacementDefaults);const{showToast}=useToast();const router=useRouter();
  const load=useCallback(async()=>{try{const response=await fetch(`/api/decisions/${id}`,{cache:"no-store"});const body=await response.json();if(!response.ok)throw new Error(body.error);setData(body)}catch(reason){setError(reason instanceof Error?reason.message:"Decision could not be loaded.")}},[id]);
  useDeferredEffect(useCallback(()=>{void load()},[load]));
  async function saveAlternative(event:React.FormEvent){event.preventDefault();setBusy(true);const response=await fetch(`/api/decisions/${id}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(alt)});if(response.ok){setAlternativeOpen(false);setAlt({title:"",reason_rejected:""});showToast("Alternative added.");await load()}else{const body=await response.json();setError(body.error)}setBusy(false)}
  async function supersede(event:React.FormEvent){event.preventDefault();setBusy(true);const response=await fetch(`/api/decisions/${id}/supersede`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...replacement,review_date:replacement.review_date||null})});const body=await response.json();if(response.ok){showToast("Replacement decision created.");setSupersedeOpen(false);router.push(`/decisions/${body.decision.id}`)}else setError(body.error??"Decision could not be superseded.");setBusy(false)}
  if(error)return <div className="empty-state"><span>!</span><h2>Decision unavailable</h2><p>{error}</p><Button emphasis="outline" onClick={()=>{setError("");void load()}}>Try again</Button></div>;
  if(!data)return <div className="empty-state"><span>···</span><h2>Loading decision</h2></div>;
  const d=data.decision;
  return <div className="detail-page"><Link className="back-link" href="/decisions">← Back to decisions</Link><header className="detail-header"><div><p className="eyebrow">{String(d.impact)} impact · {String(d.confidence)} confidence</p><h1>{String(d.title)}</h1><p>{String(d.decision)}</p></div><div className="detail-actions"><Button emphasis="outline" onClick={()=>setAlternativeOpen(true)}>Add alternative</Button>{d.status!=="superseded"?<Button intent="brand" onClick={()=>setSupersedeOpen(true)}>Supersede decision</Button>:null}</div></header><div className="detail-grid"><section><p className="eyebrow">Reasoning</p><h2>{String(d.reasoning??"No reasoning recorded.")}</h2><p className="eyebrow version-heading">Alternatives considered</p>{data.alternatives.length?data.alternatives.map((item)=><div className="signal-row" key={item.id}><span><strong>{String(item.title)}</strong>{String(item.reason_rejected??"No rejection reason recorded")}</span></div>):<p className="dataset-note">No alternatives recorded.</p>}</section><aside><p className="eyebrow">Review</p><div className="signal-row"><span><strong>{String(d.status)}</strong>{d.review_date?`Review ${String(d.review_date)}`:"No review date"}</span></div>{d.superseded_by_decision_id?<Link className="button button--outline button--neutral" href={`/decisions/${d.superseded_by_decision_id}`}>Open replacement</Link>:null}</aside></div><DecisionResearchPanel decisionId={id}/><AttachmentSection entityType="decision" entityId={id} title="Decision files"/>
  <Modal open={alternativeOpen} onClose={()=>setAlternativeOpen(false)} title="Add rejected alternative"><form className="simple-form" onSubmit={saveAlternative} noValidate><label htmlFor="alternative-title">Alternative</label><input id="alternative-title" required value={alt.title} onChange={(event)=>setAlt({...alt,title:event.target.value})}/><label htmlFor="alternative-reason">Why it was rejected</label><textarea className="resize-none" id="alternative-reason" rows={4} value={alt.reason_rejected} onChange={(event)=>setAlt({...alt,reason_rejected:event.target.value})}/><div className="modal__actions"><Button emphasis="ghost" onClick={()=>setAlternativeOpen(false)}>Cancel</Button><Button intent="brand" type="submit" disabled={busy}>{busy?"Adding…":"Add alternative"}</Button></div></form></Modal>
  <Modal open={supersedeOpen} onClose={()=>setSupersedeOpen(false)} title="Create replacement decision" description="The current decision remains in history and will link to this replacement."><form className="simple-form" onSubmit={supersede} noValidate><label htmlFor="replacement-title">Decision title</label><input id="replacement-title" required value={replacement.title} onChange={(event)=>setReplacement({...replacement,title:event.target.value})}/><label htmlFor="replacement-decision">Outcome</label><textarea className="resize-none" id="replacement-decision" rows={4} required value={replacement.decision} onChange={(event)=>setReplacement({...replacement,decision:event.target.value})}/><label htmlFor="replacement-reasoning">Reasoning</label><textarea className="resize-none" id="replacement-reasoning" rows={4} value={replacement.reasoning} onChange={(event)=>setReplacement({...replacement,reasoning:event.target.value})}/><label htmlFor="replacement-impact">Impact</label><select id="replacement-impact" value={replacement.impact} onChange={(event)=>setReplacement({...replacement,impact:event.target.value})}>{["low","medium","high","critical"].map((value)=><option key={value}>{value}</option>)}</select><label htmlFor="replacement-confidence">Confidence</label><select id="replacement-confidence" value={replacement.confidence} onChange={(event)=>setReplacement({...replacement,confidence:event.target.value})}>{["low","medium","high"].map((value)=><option key={value}>{value}</option>)}</select><label htmlFor="replacement-review">Review date</label><input id="replacement-review" type="date" value={replacement.review_date} onChange={(event)=>setReplacement({...replacement,review_date:event.target.value})}/><div className="modal__actions"><Button emphasis="ghost" onClick={()=>setSupersedeOpen(false)}>Cancel</Button><Button intent="brand" type="submit" disabled={busy}>{busy?"Creating…":"Create replacement"}</Button></div></form></Modal></div>;
}
