"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { createClient } from "@/lib/supabase/client";
import { Button } from "@/components/ui/button";

export default function LoginPage() {
  const router = useRouter();
  const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [showPassword, setShowPassword] = useState(false); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  async function signIn(event: React.FormEvent) { event.preventDefault(); setError(""); setBusy(true); try { const supabase = createClient(); const { error: authError } = await supabase.auth.signInWithPassword({ email, password }); if (authError) throw authError; router.replace("/today"); router.refresh(); } catch (value) { setError(value instanceof Error ? value.message : "Sign in failed. Check your details and try again."); setBusy(false); } }
  async function google() { setBusy(true); try { const supabase = createClient(); await supabase.auth.signInWithOAuth({ provider: "google", options: { redirectTo: `${window.location.origin}/auth/callback` } }); } catch { setError("Google sign-in could not start. Check the Supabase OAuth configuration."); setBusy(false); } }
  return <main className="login-page"><section className="login-story"><span className="brand__mark">DC</span><p className="eyebrow">Daily command center</p><h1>Begin with<br /><em>what matters.</em></h1><p>A private operating system for your commitments, context, relationships, and attention.</p><blockquote>“The day is easier when the next move is already clear.”</blockquote></section><section className="login-panel"><div><p className="eyebrow">Private workspace</p><h2>Welcome back</h2><p>Sign in to open your daily brief.</p></div><Button emphasis="outline" onClick={google} disabled={busy}>Continue with Google</Button><div className="login-divider"><span>or use email</span></div><form onSubmit={signIn} noValidate><label htmlFor="email">Email</label><input id="email" type="email" autoComplete="email" value={email} onChange={(event) => setEmail(event.target.value)} aria-invalid={Boolean(error)} aria-describedby={error ? "login-error" : undefined} /><label htmlFor="password">Password</label><div className="password-field"><input id="password" type={showPassword ? "text" : "password"} autoComplete="current-password" value={password} onChange={(event) => setPassword(event.target.value)} aria-invalid={Boolean(error)} aria-describedby={error ? "login-error" : undefined} /><button type="button" onClick={() => setShowPassword((value) => !value)} aria-label={showPassword ? "Hide password" : "Show password"} aria-pressed={showPassword}>{showPassword ? "Hide" : "Show"}</button></div>{error ? <p className="field-error" id="login-error" role="alert">{error}</p> : null}<Button intent="brand" type="submit" disabled={busy}>{busy ? "Signing in…" : "Sign in"}</Button></form><p className="login-help">Magic-link access can be enabled in Supabase Auth settings.</p></section></main>;
}
