import { NextResponse } from "next/server";
import { z } from "zod";
import { apiError } from "@/lib/api";
import { isReactivationCandidate } from "@/lib/business";
import { requireUser } from "@/lib/supabase/server";

async function candidates() { const { supabase, userId } = await requireUser(); const [clients, projects, opportunities, invoices, payments, feedback] = await Promise.all([
  supabase.from("clients").select("id,name,last_contact_at").eq("user_id", userId).is("deleted_at", null), supabase.from("projects").select("id,client_id,status,updated_at").eq("user_id", userId).is("deleted_at", null), supabase.from("opportunities").select("id,client_id,stage").eq("user_id", userId).is("archived_at", null), supabase.from("invoices").select("client_id,amount_remaining").eq("user_id", userId).is("deleted_at", null), supabase.from("payments").select("client_id,amount").eq("user_id", userId).is("deleted_at", null), supabase.from("insight_feedback").select("insight_key,action,snoozed_until").eq("user_id", userId).eq("insight_type", "v5_reactivation")
]); const failure=[clients,projects,opportunities,invoices,payments,feedback].find((item)=>item.error);if(failure?.error)throw failure.error; const now=new Date(); const dismissed=new Set((feedback.data??[]).filter((item)=>item.action==="dismissed"||item.action==="snoozed"&&item.snoozed_until&&new Date(item.snoozed_until)>now).map((item)=>item.insight_key)); return { supabase,userId, rows:(clients.data??[]).flatMap((client)=>{const projectRows=(projects.data??[]).filter((project)=>project.client_id===client.id);const open=(opportunities.data??[]).filter((opportunity)=>opportunity.client_id===client.id&&!['won','lost'].includes(String(opportunity.stage))).length;const received=(payments.data??[]).filter((payment)=>payment.client_id===client.id).reduce((sum,payment)=>sum+Number(payment.amount??0),0);const balance=(invoices.data??[]).filter((invoice)=>invoice.client_id===client.id).reduce((sum,invoice)=>sum+Number(invoice.amount_remaining??0),0);const completed=projectRows.filter((project)=>['completed','archived'].includes(String(project.status))).sort((a,b)=>String(b.updated_at).localeCompare(String(a.updated_at)))[0];const key=`reactivation:${client.id}:${completed?.updated_at??""}`;if(dismissed.has(key)||!isReactivationCandidate({received,activeProjects:projectRows.filter((project)=>['active','planning','in_progress'].includes(String(project.status))).length,openOpportunities:open,lastContactAt:client.last_contact_at,unresolvedBalance:balance,lastCompletedAt:completed?.updated_at,now}))return[];return[{id:client.id,name:client.name,key,lastCompletedAt:completed?.updated_at,reason:"Completed paid work with no active project, open opportunity, recent contact, or unresolved balance."}]}).slice(0,5) } }
export async function GET(){try{const result=await candidates();return NextResponse.json({candidates:result.rows})}catch(error){return apiError(error,"Reactivation candidates could not be loaded.")}}
export async function POST(request:Request){try{const input=z.object({clientId:z.uuid(),action:z.enum(["create_opportunity","dismiss","snooze"])}).parse(await request.json());const result=await candidates();const candidate=result.rows.find((row)=>row.id===input.clientId);if(!candidate)return NextResponse.json({error:"This client is not currently eligible for reactivation."},{status:409});if(input.action==="create_opportunity"){const{data,error}=await result.supabase.from("opportunities").insert({user_id:result.userId,client_id:candidate.id,title:`Follow up with ${candidate.name}`,stage:"new",source:"existing_client"} as never).select("*").single();if(error)throw error;return NextResponse.json({opportunity:data})}const{error}=await result.supabase.from("insight_feedback").insert({user_id:result.userId,insight_key:candidate.key,insight_type:"v5_reactivation",action:input.action==="dismiss"?"dismissed":"snoozed",snoozed_until:input.action==="snooze"?new Date(Date.now()+30*86400000).toISOString():null} as never);if(error)throw error;return NextResponse.json({ok:true})}catch(error){return apiError(error,"Reactivation action could not be completed.")}}
