"use client";

import { useCallback, useState } from "react";
import { Button } from "@/components/ui/button";
import { useDeferredEffect } from "@/lib/use-deferred-effect";

type Values = { default_currency: string; internal_hourly_cost: string; default_proposal_validity_days: string; default_tax_rate: string; business_name: string; proposal_number_prefix: string };
const empty: Values = { default_currency: "MAD", internal_hourly_cost: "", default_proposal_validity_days: "", default_tax_rate: "", business_name: "", proposal_number_prefix: "" };
export default function BusinessSettingsPage() {
  const [values, setValues] = useState<Values>(empty); const [saving, setSaving] = useState(false); const [error, setError] = useState(""); const [saved, setSaved] = useState(false);
  const load = useCallback(async () => { try { const response = await fetch("/api/business/settings", { cache: "no-store" }); const body = await response.json(); if (!response.ok) throw new Error(body.error); setValues(Object.fromEntries(Object.entries(empty).map(([key, fallback]) => [key, body.record?.[key] == null ? fallback : String(body.record[key])])) as Values); } catch (reason) { setError(reason instanceof Error ? reason.message : "Business settings could not be loaded."); } }, []);
  useDeferredEffect(useCallback(() => { void load(); }, [load]));
  const update = (key: keyof Values, value: string) => setValues((current) => ({ ...current, [key]: value }));
  const save = async (event: React.FormEvent) => { event.preventDefault(); setSaving(true); setError(""); setSaved(false); try { const response = await fetch("/api/business/settings", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify(values) }); const body = await response.json(); if (!response.ok) throw new Error(body.error); setSaved(true); } catch (reason) { setError(reason instanceof Error ? reason.message : "Business settings could not be saved."); } finally { setSaving(false); } };
  return <div className="domain-page"><header className="page-header"><div><p className="eyebrow">Settings · Business</p><h1>Business settings</h1><p>Defaults inform commercial work and transparent, tracked-time profitability estimates.</p></div></header><form className="simple-form data-surface business-settings" onSubmit={save} noValidate><label>Default currency<input value={values.default_currency} maxLength={3} onChange={(event) => update("default_currency", event.target.value.toUpperCase())}/></label><label>Internal hourly cost<input type="number" min="0" step="0.01" value={values.internal_hourly_cost} onChange={(event) => update("internal_hourly_cost", event.target.value)}/><small>Used only for estimated time cost based on tracked hours.</small></label><label>Default proposal validity (days)<input type="number" min="1" max="365" value={values.default_proposal_validity_days} onChange={(event) => update("default_proposal_validity_days", event.target.value)}/></label><label>Default tax rate (%)<input type="number" min="0" max="100" step="0.01" value={values.default_tax_rate} onChange={(event) => update("default_tax_rate", event.target.value)}/></label><label>Business name<input value={values.business_name} onChange={(event) => update("business_name", event.target.value)}/></label><label>Proposal number prefix<input value={values.proposal_number_prefix} maxLength={30} onChange={(event) => update("proposal_number_prefix", event.target.value)}/></label>{error ? <p className="field-error" role="alert">{error}</p> : null}{saved ? <p className="success-note" role="status">Business settings saved.</p> : null}<Button type="submit" intent="brand" disabled={saving}>{saving ? "Saving…" : "Save settings"}</Button></form></div>;
}
