import { NextResponse } from "next/server";
import { z } from "zod";
import { apiError } from "@/lib/api";
import { requireUser } from "@/lib/supabase/server";
const ownedTables: Record<string, string>={goal:"goals",project:"projects",opportunity:"opportunities",proposal:"proposals",campaign:"campaigns",roadmap:"product_roadmap_items",trip:"trips",personal_admin:"personal_admin_items",planning_period:"planning_periods",commitment:"strategic_commitments",milestone:"strategic_milestones",decision:"decisions"};
async function verifyOwned(supabase: Awaited<ReturnType<typeof requireUser>>["supabase"],userId:string,type:string,id:string){const table=ownedTables[type];if(!table)throw new Error("This source type is not available.");const{data,error}=await supabase.from(table).select("id").eq("id",id).eq("user_id",userId).maybeSingle();if(error)throw error;if(!data)throw new Error("Choose a record from your own workspace.");}
async function verifyRelations(supabase: Awaited<ReturnType<typeof requireUser>>["supabase"],userId:string,resource:string,values:Record<string,unknown>){if(resource==="commitments"||resource==="milestones"){const type=values.source_type;const id=values.source_id;if((type===null||type===undefined)!==(id===null||id===undefined))throw new Error("Choose both a source type and source record.");if(typeof type==="string"&&typeof id==="string")await verifyOwned(supabase,userId,type,id);}
if(resource==="commitments"&&typeof values.planning_period_id==="string")await verifyOwned(supabase,userId,"planning_period",values.planning_period_id);
if(resource==="milestones"&&typeof values.commitment_id==="string")await verifyOwned(supabase,userId,"commitment",values.commitment_id);
if(resource==="dependencies"){if(typeof values.commitment_id!=="string"||typeof values.depends_on_type!=="string"||typeof values.depends_on_id!=="string")throw new Error("Choose both sides of this dependency.");await verifyOwned(supabase,userId,"commitment",values.commitment_id);await verifyOwned(supabase,userId,String(values.depends_on_type),values.depends_on_id);}
if(resource==="gates"){for(const[key,type]of [["decision_id","decision"],["commitment_id","commitment"],["milestone_id","milestone"]] as const)if(typeof values[key]==="string")await verifyOwned(supabase,userId,type,values[key] as string);}}
const resources={periods:{table:"planning_periods",schema:z.object({title:z.string().trim().min(1).max(240),type:z.enum(["week","month","quarter","custom"]),starts_at:z.iso.date(),ends_at:z.iso.date(),status:z.enum(["draft","active","completed","archived"]).default("draft"),theme:z.string().trim().max(240).nullable().optional(),notes:z.string().trim().max(10000).nullable().optional()})},commitments:{table:"strategic_commitments",schema:z.object({planning_period_id:z.uuid(),title:z.string().trim().min(1).max(240),description:z.string().trim().max(10000).nullable().optional(),priority:z.number().int().min(1).max(5).default(3),status:z.enum(["planned","committed","at_risk","completed","dropped"]).default("planned"),target_date:z.iso.date().nullable().optional(),source_type:z.enum(["goal","project","opportunity","proposal","campaign","roadmap","trip","personal_admin"]).nullable().optional(),source_id:z.uuid().nullable().optional(),confidence:z.number().min(0).max(1).nullable().optional(),notes:z.string().trim().max(10000).nullable().optional()})},milestones:{table:"strategic_milestones",schema:z.object({title:z.string().trim().min(1).max(240),milestone_date:z.iso.date().nullable().optional(),status:z.enum(["upcoming","at_risk","reached","missed","canceled"]).default("upcoming"),commitment_id:z.uuid().nullable().optional(),source_type:z.string().trim().max(80).nullable().optional(),source_id:z.uuid().nullable().optional(),notes:z.string().trim().max(10000).nullable().optional()})},dependencies:{table:"strategic_dependencies",schema:z.object({commitment_id:z.uuid(),depends_on_type:z.enum(["commitment","milestone","project","goal","trip"]),depends_on_id:z.uuid(),relation_type:z.enum(["blocks","depends_on","related"]).default("depends_on"),status:z.enum(["open","blocked","resolved"]).default("open"),notes:z.string().trim().max(10000).nullable().optional()})},gates:{table:"decision_gates",schema:z.object({title:z.string().trim().min(1).max(240),decision_id:z.uuid().nullable().optional(),commitment_id:z.uuid().nullable().optional(),milestone_id:z.uuid().nullable().optional(),due_date:z.iso.date().nullable().optional(),status:z.enum(["open","resolved","canceled"]).default("open"),notes:z.string().trim().max(10000).nullable().optional()})},scenarios:{table:"strategic_scenarios",schema:z.object({title:z.string().trim().min(1).max(240),description:z.string().trim().max(10000).nullable().optional(),assumptions:z.array(z.string().trim().min(1).max(500)).max(50).default([])})}} as const;
export async function GET(_:Request,{params}:{params:Promise<{resource:string}>}){try{const resource=(await params).resource as keyof typeof resources;const config=resources[resource];if(!config)return NextResponse.json({error:"Unknown strategy collection."},{status:404});const{supabase,userId}=await requireUser();const{data,error}=await supabase.from(config.table).select("*").eq("user_id",userId).order("created_at",{ascending:false});if(error)throw error;return NextResponse.json({records:data??[]})}catch(error){return apiError(error,"Strategy records could not be loaded.")}}
export async function POST(request:Request,{params}:{params:Promise<{resource:string}>}){try{const resource=(await params).resource as keyof typeof resources;const config=resources[resource];if(!config)return NextResponse.json({error:"Unknown strategy collection."},{status:404});const parsed=config.schema.safeParse(await request.json());if(!parsed.success)return NextResponse.json({error:"Check the planning details and try again."},{status:422});const values=parsed.data;if("starts_at" in values&&"ends_at" in values&&values.ends_at<values.starts_at)return NextResponse.json({error:"End date must not be before start date."},{status:422});const{supabase,userId}=await requireUser();await verifyRelations(supabase,userId,resource,values);const{data,error}=await supabase.from(config.table).insert({...values,user_id:userId} as never).select("*").single();if(error)throw error;return NextResponse.json({record:data},{status:201})}catch(error){return apiError(error,"Strategy record could not be saved.")}}
