import { NextResponse } from "next/server";
import { z } from "zod";
import { apiError } from "@/lib/api";
import { requireUser } from "@/lib/supabase/server";
const ownedTables:Record<string,string>={goal:"goals",project:"projects",opportunity:"opportunities",proposal:"proposals",campaign:"campaigns",roadmap:"product_roadmap_items",trip:"trips",personal_admin:"personal_admin_items",planning_period:"planning_periods",commitment:"strategic_commitments",milestone:"strategic_milestones",decision:"decisions"};
async function verifyOwned(supabase:Awaited<ReturnType<typeof requireUser>>["supabase"],userId:string,type:string,id:string){const table=ownedTables[type];if(!table)throw new Error("This source type is not available.");const{data,error}=await supabase.from(table).select("id").eq("id",id).eq("user_id",userId).maybeSingle();if(error)throw error;if(!data)throw new Error("Choose a record from your own workspace.");}
const tables:Record<string,string>={periods:"planning_periods",commitments:"strategic_commitments",milestones:"strategic_milestones",dependencies:"strategic_dependencies",gates:"decision_gates",scenarios:"strategic_scenarios"};
const editable:Record<string,string[]>={periods:["title","type","starts_at","ends_at","status","theme","notes"],commitments:["planning_period_id","title","description","priority","status","target_date","source_type","source_id","confidence","notes"],milestones:["commitment_id","title","milestone_date","status","source_type","source_id","notes"],dependencies:["commitment_id","depends_on_type","depends_on_id","relation_type","status","notes"],gates:["decision_id","commitment_id","milestone_id","title","due_date","status","notes"],scenarios:["title","description","assumptions"]};
export async function PATCH(request:Request,{params}:{params:Promise<{resource:string;id:string}>}){try{const{resource,id}=await params;const table=tables[resource];if(!table)return NextResponse.json({error:"Unknown strategy collection."},{status:404});const recordId=z.uuid().parse(id);const submitted=await request.json() as Record<string,unknown>;const values=Object.fromEntries(Object.entries(submitted).filter(([key])=>editable[resource]?.includes(key)));if(!Object.keys(values).length||Object.keys(values).length!==Object.keys(submitted).length)return NextResponse.json({error:"This strategy update contains unsupported fields."},{status:422});if("starts_at"in values&&"ends_at"in values&&String(values.ends_at)<String(values.starts_at))return NextResponse.json({error:"End date must not be before start date."},{status:422});const{supabase,userId}=await requireUser();
if(resource==="commitments"||resource==="milestones"){const type=values.source_type,idValue=values.source_id;if((type===null)!==(idValue===null))return NextResponse.json({error:"Choose both a source type and source record."},{status:422});if(typeof type==="string"&&typeof idValue==="string")await verifyOwned(supabase,userId,type,idValue);if(resource==="commitments"&&typeof values.planning_period_id==="string")await verifyOwned(supabase,userId,"planning_period",values.planning_period_id);if(resource==="milestones"&&typeof values.commitment_id==="string")await verifyOwned(supabase,userId,"commitment",values.commitment_id);}
if(resource==="gates"){for(const[key,type]of [["decision_id","decision"],["commitment_id","commitment"],["milestone_id","milestone"]] as const)if(typeof values[key]==="string")await verifyOwned(supabase,userId,type,values[key] as string);}
if(resource==="dependencies"){if(typeof values.commitment_id==="string")await verifyOwned(supabase,userId,"commitment",values.commitment_id);if(typeof values.depends_on_type==="string"&&typeof values.depends_on_id==="string")await verifyOwned(supabase,userId,values.depends_on_type,values.depends_on_id);}
const{data,error}=await supabase.from(table).update(values as never).eq("id",recordId).eq("user_id",userId).select("*").maybeSingle();if(error)throw error;if(!data)return NextResponse.json({error:"This strategy record is not available."},{status:404});return NextResponse.json({record:data})}catch(error){return apiError(error,"Strategy record could not be updated.")}}
export async function DELETE(_:Request,{params}:{params:Promise<{resource:string;id:string}>}){try{const{resource,id}=await params;const table=tables[resource];if(!table)return NextResponse.json({error:"Unknown strategy collection."},{status:404});const{supabase,userId}=await requireUser();const{data,error}=await supabase.from(table).delete().eq("id",z.uuid().parse(id)).eq("user_id",userId).select("id").maybeSingle();if(error)throw error;if(!data)return NextResponse.json({error:"This strategy record is not available."},{status:404});return NextResponse.json({deleted:true})}catch(error){return apiError(error,"Strategy record could not be removed.")}}
