import { NextResponse } from "next/server";
import { z } from "zod";
import { apiError } from "@/lib/api";
import { promptVariables,renderPrompt } from "@/lib/v2";
import { requireUser } from "@/lib/supabase/server";
const action=z.discriminatedUnion("action",[z.object({action:z.literal("version"),prompt_text:z.string().trim().min(1).max(20000),change_note:z.string().max(1000).optional().nullable()}),z.object({action:z.literal("restore"),version_id:z.uuid()}),z.object({action:z.literal("use"),variables:z.record(z.string(),z.string()).default({}),rating:z.number().int().min(1).max(5).optional()})]);
export async function GET(_:Request,{params}:{params:Promise<{id:string}>}){try{const{id}=await params;const{supabase,userId}=await requireUser();const[prompt,versions,variables]=await Promise.all([supabase.from("prompts").select("*").eq("id",id).eq("user_id",userId).is("deleted_at",null).maybeSingle(),supabase.from("prompt_versions").select("*").eq("prompt_id",id).eq("user_id",userId).order("version_number",{ascending:false}),supabase.from("prompt_variables").select("*").eq("prompt_id",id).eq("user_id",userId)]);if(prompt.error||versions.error||variables.error)throw prompt.error??versions.error??variables.error;if(!prompt.data)return NextResponse.json({error:"Prompt not found."},{status:404});return NextResponse.json({prompt:prompt.data,versions:versions.data??[],variables:variables.data??[],detectedVariables:promptVariables(String(prompt.data.prompt_text??prompt.data.prompt??""))})}catch(error){return apiError(error,"Prompt could not be loaded.")}}
export async function POST(request:Request,{params}:{params:Promise<{id:string}>}){try{const{id}=await params;const input=action.parse(await request.json());const{supabase,userId}=await requireUser();const owned=await supabase.from("prompts").select("*").eq("id",id).eq("user_id",userId).is("deleted_at",null).maybeSingle();if(owned.error)throw owned.error;if(!owned.data)return NextResponse.json({error:"Prompt not found."},{status:404});if(input.action==="use"){const rendered=renderPrompt(String(owned.data.prompt_text??owned.data.prompt),input.variables);if(rendered.missing.length)return NextResponse.json({error:`Complete variables: ${rendered.missing.join(", ")}`},{status:400});await supabase.from("prompts").update({usage_count:Number(owned.data.usage_count??0)+1,last_used_at:new Date().toISOString(),rating:input.rating??owned.data.rating}).eq("id",id).eq("user_id",userId);return NextResponse.json({rendered:rendered.text})}if(input.action==="restore"){const version=await supabase.from("prompt_versions").select("prompt_text").eq("id",input.version_id).eq("prompt_id",id).eq("user_id",userId).maybeSingle();if(version.error)throw version.error;if(!version.data)return NextResponse.json({error:"Version not found."},{status:404});await createVersion(supabase,userId,id,String(owned.data.prompt_text??owned.data.prompt),"Snapshot before restore");const saved=await supabase.from("prompts").update({prompt_text:version.data.prompt_text,prompt:version.data.prompt_text}).eq("id",id).eq("user_id",userId).select("*").single();if(saved.error)throw saved.error;return NextResponse.json({prompt:saved.data})}await createVersion(supabase,userId,id,String(owned.data.prompt_text??owned.data.prompt),input.change_note);const saved=await supabase.from("prompts").update({prompt_text:input.prompt_text,prompt:input.prompt_text}).eq("id",id).eq("user_id",userId).select("*").single();if(saved.error)throw saved.error;return NextResponse.json({prompt:saved.data})}catch(error){return apiError(error,"Prompt action could not be completed.")}}
async function createVersion(client:Awaited<ReturnType<typeof requireUser>>["supabase"],userId:string,promptId:string,text:string,note?:string|null){const latest=await client.from("prompt_versions").select("version_number").eq("prompt_id",promptId).eq("user_id",userId).order("version_number",{ascending:false}).limit(1).maybeSingle();if(latest.error)throw latest.error;const saved=await client.from("prompt_versions").insert({user_id:userId,prompt_id:promptId,version_number:Number(latest.data?.version_number??0)+1,prompt_text:text,change_note:note??null});if(saved.error)throw saved.error}
