"use client";

import Link from "next/link";
import { FormEvent, useCallback, useState } from "react";
import { Button } from "@/components/ui/button";
import { Modal } from "@/components/ui/modal";
import { SearchInput } from "@/components/ui/search-input";
import { useDeferredEffect } from "@/lib/use-deferred-effect";

type Item={id:string;title:string;status:string;priority?:number;target_date?:string|null;milestone_date?:string|null;starts_at?:string;ends_at?:string;theme?:string|null;notes?:string|null;description?:string|null;planning_period_id?:string;source_type?:string|null;source_id?:string|null;confidence?:number|null;commitment_id?:string|null;milestone_id?:string|null;decision_id?:string|null;due_date?:string|null;relation_type?:string;depends_on_type?:string;blocked?:boolean};
type Source={id:string;label:string};type Data={activePeriod:Item|null;commitments:Item[];nextMove:Item|null;atRisk:Item[];capacity:{state:string;reason:string};milestones:Item[];horizons:Record<"30"|"60"|"90",Item[]>;decisionGates:Item[];dependencies?:Item[];schemaStatus?:"available"|"unavailable";schemaDependency?:string};type Dialog={kind:"period"|"commitment"|"milestone"|"gate"|"dependency";item?:Item}|null;
const sourceTypes=[["goal","Goal"],["project","Project"],["opportunity","Opportunity"],["proposal","Proposal"],["campaign","Campaign"],["roadmap","Founder roadmap item"],["trip","Trip"],["personal_admin","Personal admin"]] as const;
const dependencyTypes=[["commitment","Commitment"],["milestone","Milestone"],["project","Project"],["goal","Goal"],["trip","Trip"]] as const;
const words=(value:string|undefined|null)=>value?value.replaceAll("_"," "):"Not set";

export function ControlTower(){const[data,setData]=useState<Data|null>(null),[error,setError]=useState(""),[dialog,setDialog]=useState<Dialog>(null),[aux,setAux]=useState<Record<string,Item[]>>({}),[saving,setSaving]=useState(false);
const load=useCallback(async()=>{try{const response=await fetch("/api/strategy",{cache:"no-store"}),body=await response.json() as Data&{error?:string};if(!response.ok)throw new Error(body.error??"Control Tower could not be loaded.");setData(body);setError("")}catch(reason){setError(reason instanceof Error?reason.message:"Control Tower could not be loaded.")}},[]);
useDeferredEffect(useCallback(()=>{void load()},[load]));
const open=useCallback(async(kind:NonNullable<Dialog>["kind"],item?:Item)=>{try{const names=["periods","commitments","milestones","gates"] as const;const result=await Promise.all(names.map(async name=>{const response=await fetch(`/api/strategy/${name}`,{cache:"no-store"}),body=await response.json() as {records?:Item[];error?:string};if(!response.ok)throw new Error(body.error??"Strategy records could not be loaded.");return[name,body.records??[]] as const}));setAux(Object.fromEntries(result));setDialog({kind,item})}catch(reason){setError(reason instanceof Error?reason.message:"Strategy records could not be loaded.")}},[]);
const mutate=useCallback(async(resource:string,values:Record<string,unknown>,id?:string)=>{setSaving(true);setError("");try{const response=await fetch(`/api/strategy/${resource}${id?`/${id}`:""}`,{method:id?"PATCH":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(values)}),body=await response.json() as {error?:string};if(!response.ok)throw new Error(body.error??"Strategy record could not be saved.");setDialog(null);await load()}catch(reason){setError(reason instanceof Error?reason.message:"Strategy record could not be saved.")}finally{setSaving(false)}},[load]);
const lifecycle=useCallback(async(resource:string,item:Item,status:string)=>{await mutate(resource,{status},item.id)},[mutate]);
if(error&&!data)return <main className="domain-page"><section className="inline-error" role="alert"><p>{error}</p><Button emphasis="outline" onClick={()=>void load()}>Try again</Button></section></main>;
if(!data)return <main className="domain-page"><div className="empty-state"><span>···</span><h2>Reading your strategic horizon</h2></div></main>;
if(data.schemaStatus==="unavailable")return <main className="domain-page strategy-page"><header className="page-header"><div><p className="eyebrow">Strategic planning</p><h1>Control Tower.</h1><p>Commit to what matters, see what is constrained, and act before plans drift.</p></div></header><section className="data-surface empty-state"><h2>Strategic planning is not configured</h2><p>This environment is missing the V8 strategic planning schema. Existing workspace areas remain available; planning actions are disabled here until that dependency is installed.</p></section></main>;
return <main className="domain-page strategy-page"><header className="page-header"><div><p className="eyebrow">Strategic planning</p><h1>Control Tower.</h1><p>Commit to what matters, see what is constrained, and act before plans drift.</p></div><div className="strategy-actions"><Link className="button button--ghost" href="/portfolio">Portfolio</Link><Link className="button button--ghost" href="/plan/90-days">90 days</Link><Link className="button button--ghost" href="/plan/week">Plan week</Link><Link className="button button--ghost" href="/plan/month">Plan month</Link><Link className="button button--ghost" href="/plan/quarter">Plan quarter</Link><Link className="button button--ghost" href="/strategy/scenarios">Scenarios</Link><Button intent="brand" onClick={()=>void open("period")}>{data.activePeriod?"New planning period":"Plan this week"}</Button><Button emphasis="outline" onClick={()=>void open("commitment")}>New commitment</Button></div></header>{error?<p className="field-error" role="alert">{error}</p>:null}
<section className="strategy-active-period data-surface"><div><p className="eyebrow">Active period</p>{data.activePeriod?<><h2>{data.activePeriod.title}</h2><p>{data.activePeriod.starts_at} – {data.activePeriod.ends_at}{data.activePeriod.theme?` · ${data.activePeriod.theme}`:""}</p></>:<><h2>No active planning period.</h2><p>Choose a real horizon before committing work.</p></>}</div>{data.activePeriod?<div className="strategy-row-actions"><Button emphasis="ghost" onClick={()=>void open("period",data.activePeriod!)}>Edit</Button><Button emphasis="ghost" onClick={()=>void lifecycle("periods",data.activePeriod!,"completed")}>Complete</Button><Button emphasis="ghost" onClick={()=>void lifecycle("periods",data.activePeriod!,"archived")}>Archive</Button></div>:null}</section>
{data.activePeriod?<><section className="strategy-hero"><p className="eyebrow">Next strategic move</p>{data.nextMove?<><h2>{data.nextMove.title}</h2><p>{data.nextMove.blocked?"A recorded dependency is blocking this commitment.":data.nextMove.target_date?`Target date ${data.nextMove.target_date}.`:`Highest-ranked current commitment in ${data.activePeriod.title}.`}</p><Button emphasis="outline" onClick={()=>void open("commitment",data.nextMove!)}>Review commitment</Button></>:<p>No current commitment needs a strategic move.</p>}</section>
<Section title="Current commitments" note={`${data.commitments.length} visible · ${data.activePeriod.title}`} action={<Button emphasis="ghost" onClick={()=>void open("commitment")}>New</Button>}><Rows items={data.commitments} empty="No commitments yet." onEdit={item=>open("commitment",item)} onLife={(item,status)=>lifecycle("commitments",item,status)}/></Section>
<Section title="Dependencies" note="Relationships, not a graph" action={<Button emphasis="ghost" onClick={()=>void open("dependency")}>Add dependency</Button>}><Dependencies items={data.dependencies??[]} empty="No dependencies recorded." onRemove={async item=>{setSaving(true);try{const response=await fetch(`/api/strategy/dependencies/${item.id}`,{method:"DELETE"});if(!response.ok)throw new Error("Dependency could not be removed.");await load()}catch(reason){setError(reason instanceof Error?reason.message:"Dependency could not be removed.")}finally{setSaving(false)}}}/></Section>
<Section title="At risk" note="Only evidence-backed planning risks"><Rows items={data.atRisk} empty="No current strategic risks." onEdit={item=>open("commitment",item)}/></Section><Section title="Capacity" note={words(data.capacity.state)}><p className="strategy-capacity"><strong>{words(data.capacity.state)}</strong><span>{data.capacity.reason}</span></p></Section>
<Section title="Major milestones" action={<Button emphasis="ghost" onClick={()=>void open("milestone")}>New milestone</Button>}><Rows items={data.milestones.slice(0,5)} empty="No upcoming milestones." onEdit={item=>open("milestone",item)} onLife={(item,status)=>lifecycle("milestones",item,status)}/></Section>
<Section title="30 / 60 / 90 days"><div className="strategy-horizons">{(["30","60","90"] as const).map(h=><div key={h}><p className="eyebrow">Next {h} days</p><Rows items={data.horizons[h].slice(0,3)} empty="Nothing recorded."/></div>)}</div></Section>
<Section title="Decisions required" action={<Button emphasis="ghost" onClick={()=>void open("gate")}>Add decision gate</Button>}><Rows items={data.decisionGates} empty="No blocking decisions." onEdit={item=>open("gate",item)} onLife={(item,status)=>lifecycle("gates",item,status)}/></Section></>:null}
<StrategyDialog dialog={dialog} aux={aux} saving={saving} onClose={()=>setDialog(null)} onSave={mutate}/></main>}

function Section({title,note,action,children}:{title:string;note?:string;action?:React.ReactNode;children:React.ReactNode}){return <section className="data-surface strategy-section"><header><div><p className="eyebrow">{title}</p>{note?<small>{note}</small>:null}</div>{action}</header>{children}</section>}
function Rows({items,empty,onEdit,onLife}:{items:Item[];empty:string;onEdit?:(item:Item)=>void;onLife?:(item:Item,status:string)=>void}){return items.length?<div className="signal-stack">{items.map(item=><div className="signal-row strategy-row" key={item.id}><span><strong>{item.title}</strong>{[words(item.status),item.target_date??item.milestone_date??item.due_date??null,item.blocked?"Blocked":null].filter(Boolean).join(" · ")}</span>{onEdit?<div className="strategy-row-actions"><Button emphasis="ghost" onClick={()=>onEdit(item)}>Edit</Button>{onLife&&item.status==="planned"?<Button emphasis="ghost" onClick={()=>onLife(item,"committed")}>Commit</Button>:null}{onLife&&item.status==="committed"?<Button emphasis="ghost" onClick={()=>onLife(item,"at_risk")}>At risk</Button>:null}{onLife&&item.status==="at_risk"?<Button emphasis="ghost" onClick={()=>onLife(item,item.milestone_date?"reached":"completed")}>Resolve</Button>:null}{onLife&&["completed","dropped","reached","missed","canceled"].includes(item.status)?<Button emphasis="ghost" onClick={()=>onLife(item,item.milestone_date?"upcoming":"planned")}>Restore</Button>:null}</div>:null}</div>)}</div>:<p className="dataset-note">{empty}</p>}
function Dependencies({items,empty,onRemove}:{items:Item[];empty:string;onRemove:(item:Item)=>void}){return items.length?<div className="signal-stack">{items.map(item=><div className="signal-row strategy-row" key={item.id}><span><strong>{words(item.relation_type)}</strong>{` · ${words(item.depends_on_type)} · ${words(item.status)}`}</span><Button emphasis="ghost" onClick={()=>onRemove(item)}>Remove</Button></div>)}</div>:<p className="dataset-note">{empty}</p>}

function StrategyDialog({dialog,aux,saving,onClose,onSave}:{dialog:Dialog;aux:Record<string,Item[]>;saving:boolean;onClose:()=>void;onSave:(resource:string,values:Record<string,unknown>,id?:string)=>Promise<void>}){if(!dialog)return null;const item=dialog.item;const submit=(event:FormEvent<HTMLFormElement>,resource:string)=>{event.preventDefault();const raw=Object.fromEntries(new FormData(event.currentTarget)),nil=(name:string)=>String(raw[name]??"").trim()||null,values:Record<string,unknown>={...raw};if(resource==="periods"){values.theme=nil("theme");values.notes=nil("notes")}if(resource==="commitments"){values.priority=Number(raw.priority);values.target_date=nil("target_date");values.description=nil("description");values.notes=nil("notes");values.confidence=nil("confidence")?Number(raw.confidence):null;values.source_type=nil("source_type");values.source_id=nil("source_id")}if(resource==="milestones"){values.milestone_date=nil("milestone_date");values.notes=nil("notes");values.commitment_id=nil("commitment_id");values.source_type=nil("source_type");values.source_id=nil("source_id")}if(resource==="gates"){values.decision_id=nil("decision_id");values.commitment_id=nil("commitment_id");values.milestone_id=nil("milestone_id");values.due_date=nil("due_date");values.notes=nil("notes")}if(resource==="dependencies")values.notes=nil("notes");void onSave(resource,values,item?.id)};
if(dialog.kind==="period")return <Modal open onClose={onClose} title={item?"Edit planning period":"New planning period"} description="A period is a real horizon, not a generated plan."><form className="simple-form" onSubmit={event=>submit(event,"periods")}><label>Title<input name="title" required defaultValue={item?.title}/></label><div className="strategy-form-grid"><label>Type<select name="type" defaultValue={(item as Item&{type?:string})?.type??"week"}>{["week","month","quarter","custom"].map(value=><option value={value} key={value}>{words(value)}</option>)}</select></label><label>Status<select name="status" defaultValue={item?.status??"draft"}>{["draft","active","completed","archived"].map(value=><option value={value} key={value}>{words(value)}</option>)}</select></label></div><div className="strategy-form-grid"><label>Start date<input name="starts_at" type="date" required defaultValue={item?.starts_at}/></label><label>End date<input name="ends_at" type="date" required defaultValue={item?.ends_at}/></label></div><label>Theme (optional)<input name="theme" defaultValue={item?.theme??""}/></label><label>Notes (optional)<textarea name="notes" rows={3} defaultValue={item?.notes??""}/></label><Actions saving={saving} onClose={onClose} label={item?"Save changes":"Create period"}/></form></Modal>;
if(dialog.kind==="commitment")return <Modal open onClose={onClose} title={item?"Edit commitment":"New commitment"} description="Commitments are strategic outcomes, not ordinary tasks."><form className="simple-form" onSubmit={event=>submit(event,"commitments")}><label>Title<input name="title" required defaultValue={item?.title}/></label><label>Planning period<select name="planning_period_id" required defaultValue={item?.planning_period_id??""}><option value="">Choose a period</option>{(aux.periods??[]).map(period=><option value={period.id} key={period.id}>{period.title}</option>)}</select></label><div className="strategy-form-grid"><label>Priority<select name="priority" defaultValue={String(item?.priority??3)}>{[1,2,3,4,5].map(value=><option value={value} key={value}>{value}</option>)}</select></label><label>Status<select name="status" defaultValue={item?.status??"planned"}>{["planned","committed","at_risk","completed","dropped"].map(value=><option value={value} key={value}>{words(value)}</option>)}</select></label></div><div className="strategy-form-grid"><label>Target date<input name="target_date" type="date" defaultValue={item?.target_date??""}/></label><label>Confidence (0–1)<input name="confidence" min="0" max="1" step="0.1" type="number" defaultValue={item?.confidence??""}/></label></div><label>Description<textarea name="description" rows={3} defaultValue={item?.description??""}/></label><SourceFields initialType={item?.source_type??""} initialId={item?.source_id??""}/><label>Notes<textarea name="notes" rows={3} defaultValue={item?.notes??""}/></label><Actions saving={saving} onClose={onClose} label={item?"Save changes":"Create commitment"}/></form></Modal>;
if(dialog.kind==="milestone")return <Modal open onClose={onClose} title={item?"Edit milestone":"New milestone"} description="Milestones make a major date and its state explicit."><form className="simple-form" onSubmit={event=>submit(event,"milestones")}><label>Title<input name="title" required defaultValue={item?.title}/></label><div className="strategy-form-grid"><label>Date<input name="milestone_date" type="date" defaultValue={item?.milestone_date??""}/></label><label>Status<select name="status" defaultValue={item?.status??"upcoming"}>{["upcoming","at_risk","reached","missed","canceled"].map(value=><option value={value} key={value}>{words(value)}</option>)}</select></label></div><label>Related commitment<select name="commitment_id" defaultValue={item?.commitment_id??""}><option value="">None</option>{(aux.commitments??[]).map(commitment=><option value={commitment.id} key={commitment.id}>{commitment.title}</option>)}</select></label><SourceFields initialType={item?.source_type??""} initialId={item?.source_id??""}/><label>Notes<textarea name="notes" rows={3} defaultValue={item?.notes??""}/></label><Actions saving={saving} onClose={onClose} label={item?"Save changes":"Create milestone"}/></form></Modal>;
if(dialog.kind==="gate")return <Modal open onClose={onClose} title={item?"Edit decision gate":"Add decision gate"} description="A gate records the decision that must be made before work proceeds."><form className="simple-form" onSubmit={event=>submit(event,"gates")}><label>Decision required<input name="title" required defaultValue={item?.title}/></label><SourceField name="decision_id" type="decision" title="Existing decision (optional)" initialId={item?.decision_id??""}/><div className="strategy-form-grid"><label>Blocks commitment<select name="commitment_id" defaultValue={item?.commitment_id??""}><option value="">None</option>{(aux.commitments??[]).map(row=><option value={row.id} key={row.id}>{row.title}</option>)}</select></label><label>Blocks milestone<select name="milestone_id" defaultValue={item?.milestone_id??""}><option value="">None</option>{(aux.milestones??[]).map(row=><option value={row.id} key={row.id}>{row.title}</option>)}</select></label></div><div className="strategy-form-grid"><label>Due date<input name="due_date" type="date" defaultValue={item?.due_date??""}/></label><label>Status<select name="status" defaultValue={item?.status??"open"}>{["open","resolved","canceled"].map(value=><option value={value} key={value}>{words(value)}</option>)}</select></label></div><label>Notes<textarea name="notes" rows={3} defaultValue={item?.notes??""}/></label><Actions saving={saving} onClose={onClose} label={item?"Save changes":"Create decision gate"}/></form></Modal>;
return <Modal open onClose={onClose} title="Add dependency" description="Keep the relationship explicit without turning your plan into a graph."><form className="simple-form" onSubmit={event=>submit(event,"dependencies")}><SourceField name="commitment_id" type="commitment" title="Commitment"/><label>Relationship<select name="relation_type" defaultValue="depends_on"><option value="blocks">Blocks</option><option value="depends_on">Depends on</option><option value="related">Related</option></select></label><DependencyTarget/><label>Notes (optional)<textarea name="notes" rows={3}/></label><input name="status" type="hidden" value="open" readOnly/><Actions saving={saving} onClose={onClose} label="Add dependency"/></form></Modal>}
function Actions({saving,onClose,label}:{saving:boolean;onClose:()=>void;label:string}){return <div className="modal__actions"><Button emphasis="ghost" onClick={onClose}>Cancel</Button><Button type="submit" intent="brand" disabled={saving}>{saving?"Saving…":label}</Button></div>}
function SourceFields({initialType,initialId}:{initialType:string;initialId:string}){const[type,setType]=useState(initialType);return <><label>Source type<select name="source_type" value={type} onChange={event=>setType(event.target.value)}><option value="">No source</option>{sourceTypes.map(([value,title])=><option value={value} key={value}>{title}</option>)}</select></label>{type?<SourceField name="source_id" type={type} title="Source" initialId={initialId}/>:<input name="source_id" type="hidden" value="" readOnly/>}</>}
function DependencyTarget(){const[type,setType]=useState("commitment");return <><label>Target type<select name="depends_on_type" value={type} onChange={event=>setType(event.target.value)}>{dependencyTypes.map(([value,title])=><option value={value} key={value}>{title}</option>)}</select></label><SourceField name="depends_on_id" type={type} title="Target"/></>}
function SourceField({name,type,title,initialId=""}:{name:string;type:string;title:string;initialId?:string}){const[query,setQuery]=useState(""),[records,setRecords]=useState<Source[]>([]),[selected,setSelected]=useState<Source|null>(initialId?{id:initialId,label:"Selected record"}:null),[loading,setLoading]=useState(false);const search=async()=>{setLoading(true);try{const response=await fetch(`/api/strategy/sources?type=${encodeURIComponent(type)}&q=${encodeURIComponent(query)}`,{cache:"no-store"}),body=await response.json() as {records?:Source[]};setRecords(response.ok?body.records??[]:[])}finally{setLoading(false)}};return <fieldset className="strategy-source"><legend>{title}</legend><input type="hidden" name={name} value={selected?.id??""} readOnly/><div className="strategy-source__search"><SearchInput label={`Search ${title}`} containerClassName="search-control--full" value={query} onChange={event=>setQuery(event.target.value)} onClear={()=>{setQuery("");setRecords([])}} placeholder={`Search ${title.toLowerCase()}`}/><Button emphasis="outline" onClick={()=>void search()}>{loading?"…":"Search"}</Button></div>{selected?<p className="dataset-note">Selected: {selected.label} <button type="button" className="text-button" onClick={()=>setSelected(null)}>Clear</button></p>:null}{records.length?<div className="strategy-source__results" role="listbox" aria-label={`${title} results`}>{records.map(record=><button type="button" role="option" aria-selected={selected?.id===record.id} key={record.id} onClick={()=>{setSelected(record);setRecords([])}}>{record.label}</button>)}</div>:query&&!loading?<p className="dataset-note">No matching records in your workspace.</p>:null}</fieldset>}
