"use client";

import Link from "next/link";
import { useCallback, useState } from "react";
import { Button } from "@/components/ui/button";
import { useDeferredEffect } from "@/lib/use-deferred-effect";

type Item = { id: string; title: string; domain?: string; health?: string; status?: string; targetDate?: string | null; nextMilestone?: string | null; blocked?: boolean; kind?: string; route?: string; progress?: number; reason?: string; target_date?: string | null; planning_period_id?: string };
type SchemaState = { schemaStatus?: "available" | "unavailable"; schemaDependency?: string };
function words(value: string | undefined) { return value?.replaceAll("_", " ") ?? "Not set"; }
function Unavailable({ title = "Strategic planning is unavailable" }: { title?: string }) { return <section className="data-surface empty-state"><h2>{title}</h2><p>This workspace is missing the optional V8 strategic planning schema. Planning actions will be available after that dependency is installed.</p></section>; }

export function PortfolioPage() {
  type Data = SchemaState & { items: Item[]; goals: Item[]; risks: Array<Item & { evidence: string; impact: string }>; capacity: { state: string; reason: string }; tradeoff: { next: { state: string }; suggestReview: boolean } };
  const [data, setData] = useState<Data | null>(null), [error, setError] = useState(""), [filter, setFilter] = useState("all");
  const load = useCallback(async () => { try { const r = await fetch("/api/strategy/portfolio", { cache: "no-store" }), body = await r.json(); if (!r.ok) throw new Error(body.error); setData(body); } catch (reason) { setError(reason instanceof Error ? reason.message : "Portfolio could not be loaded."); } }, []);
  useDeferredEffect(useCallback(() => { void load(); }, [load]));
  const items = data?.items?.filter(item => filter === "all" || item.domain === filter) || [];
  return <main className="domain-page strategy-page"><header className="page-header"><div><p className="eyebrow">Strategic portfolio</p><h1>Portfolio.</h1><p>The few cross-domain records that materially shape your current horizon.</p></div><Link className="button button--outline" href="/control-tower">Control Tower</Link></header>{error ? <p className="field-error">{error}</p> : null}{data?.schemaStatus === "unavailable" ? <Unavailable title="Strategic Portfolio is unavailable" /> : <><div className="strategy-filters" role="group" aria-label="Portfolio filters">{[["all", "All"], ["work", "Work"], ["business", "Business"], ["founder", "Founder"], ["life", "Life"]].map(([value, title]) => <button type="button" aria-pressed={filter === value} key={value} onClick={() => setFilter(value)}>{title}</button>)}</div>{!data ? <div className="empty-state"><span>···</span><h2>Reading your portfolio</h2></div> : <><section className="strategy-hero"><p className="eyebrow">Capacity consequence</p><h2>{words(data.capacity.state)}</h2><p>{data.capacity.reason} Adding one more commitment would move this to {words(data.tradeoff.next.state)}.</p>{data.tradeoff.suggestReview ? <p>Consider reviewing lower-priority commitments before adding more. Nothing is changed automatically.</p> : null}</section><section className="strategy-section data-surface"><header><div><p className="eyebrow">Major active records</p><small>Ordered by documented risk, deadline, blocking, and valid value.</small></div></header><div className="portfolio-list">{items.length ? items.map(item => <Link className="portfolio-row" href={item.route ?? "/control-tower"} key={item.domain + "-" + item.id}><div><p className="eyebrow">{item.domain}</p><h2>{item.title}</h2><small>{words(item.status)}{item.blocked ? " · Blocked" : ""}</small></div><div><strong>{words(item.health)}</strong><small>{item.targetDate ?? "No recorded deadline"}{item.nextMilestone ? " · " + item.nextMilestone : ""}</small></div></Link>) : <p className="dataset-note">No portfolio items match this filter.</p>}</div></section><section className="strategy-section data-surface"><header><div><p className="eyebrow">Strategic goal health</p><small>Derived from linked commitments, milestones, dates, and recent activity.</small></div><Link href="/goals">Open goals</Link></header><div className="signal-stack">{data.goals.map(goal => <div className="signal-row" key={goal.id}><span><strong>{goal.title}</strong>{goal.progress}% · {words(goal.health)} · {goal.reason}</span></div>)}</div></section><section className="strategy-section data-surface"><header><div><p className="eyebrow">Strategic risks</p><small>Bounded, evidence-backed risks only.</small></div></header><div className="signal-stack">{data.risks.map(risk => <Link className="signal-row" href={risk.route ?? "/control-tower"} key={risk.id}><span><strong>{risk.title}</strong>{risk.evidence} Impact: {risk.impact}</span></Link>)}</div></section></>}</>}</main>;
}

export function NinetyDayPlanPage() {
  const [data, setData] = useState<(SchemaState & { horizons: Record<"30" | "60" | "90", Item[]> }) | null>(null), [error, setError] = useState("");
  const load = useCallback(async () => { try { const r = await fetch("/api/strategy/90-days", { cache: "no-store" }), body = await r.json(); if (!r.ok) throw new Error(body.error); setData(body); } catch (reason) { setError(reason instanceof Error ? reason.message : "90-day plan could not be loaded."); } }, []);
  useDeferredEffect(useCallback(() => { void load(); }, [load]));
  return <main className="domain-page strategy-page"><header className="page-header"><div><p className="eyebrow">Strategic horizon</p><h1>90 days.</h1><p>Stored commitments, milestones, decisions, and major events—without invented dates.</p></div>{data?.schemaStatus !== "unavailable" ? <Link className="button button--outline" href="/control-tower">New commitment</Link> : null}</header>{error ? <p className="field-error">{error}</p> : null}{data?.schemaStatus === "unavailable" ? <Unavailable title="The 90-day plan is unavailable" /> : !data ? <div className="empty-state"><span>···</span><h2>Reading the horizon</h2></div> : <div className="ninety-plan">{(["30", "60", "90"] as const).map(period => <section className="strategy-section data-surface" key={period}><header><div><p className="eyebrow">Next {period} days</p><small>{period === "30" ? "Urgent execution" : period === "60" ? "Upcoming important work" : "Strategic future work"}</small></div></header>{data.horizons[period].length ? <div className="signal-stack">{data.horizons[period].map(item => <Link className="signal-row" href={item.route ?? "/control-tower"} key={item.kind + "-" + item.id}><span><strong>{item.title}</strong>{item.kind} · {item.targetDate}</span></Link>)}</div> : <p className="dataset-note">Nothing dated in this horizon.</p>}</section>)}</div>}</main>;
}

export function WeeklyPlanningPage() {
  type Data = SchemaState & { periods: Item[]; commitments: Item[]; milestones: Item[]; gates: Item[]; events: Item[]; capacity: { state: string; reason: string } };
  const [data, setData] = useState<Data | null>(null), [error, setError] = useState(""), [period, setPeriod] = useState(""), [selected, setSelected] = useState<string[]>([]), [saving, setSaving] = useState(false);
  const load = useCallback(async () => { try { const r = await fetch("/api/strategy/week", { cache: "no-store" }), body = await r.json(); if (!r.ok) throw new Error(body.error); setData(body); setPeriod(current => current || body.periods?.find((row: Item) => row.status === "active")?.id || body.periods?.[0]?.id || ""); } catch (reason) { setError(reason instanceof Error ? reason.message : "Weekly planning could not be loaded."); } }, []);
  useDeferredEffect(useCallback(() => { void load(); }, [load]));
  const confirm = async () => { if (!period) { setError("Create a weekly planning period before confirming."); return; } setSaving(true); try { const r = await fetch("/api/strategy/week", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ periodId: period, commitmentIds: selected }) }), body = await r.json(); if (!r.ok) throw new Error(body.error); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Weekly plan could not be confirmed."); } finally { setSaving(false); } };
  return <main className="domain-page strategy-page"><header className="page-header"><div><p className="eyebrow">Weekly planning</p><h1>This week.</h1><p>Review constraints before choosing the commitments that deserve this week.</p></div>{data?.schemaStatus !== "unavailable" ? <Link className="button button--outline" href="/control-tower">New period</Link> : null}</header>{error ? <p className="field-error">{error}</p> : null}{data?.schemaStatus === "unavailable" ? <Unavailable title="Weekly planning is unavailable" /> : !data ? <div className="empty-state"><span>···</span><h2>Preparing weekly inputs</h2></div> : <><section className="strategy-section data-surface"><label>Weekly period<select value={period} onChange={event => setPeriod(event.target.value)}><option value="">Choose a weekly period</option>{data.periods.map(row => <option key={row.id} value={row.id}>{row.title} · {row.status}</option>)}</select></label></section><section className="strategy-section data-surface"><header><div><p className="eyebrow">1–5. Review the week</p><small>Unfinished commitments, deadlines, calendar load, and open decision gates.</small></div></header><div className="weekly-inputs"><p><strong>{data.commitments.length}</strong> unfinished commitments to review</p><p><strong>{data.events.length}</strong> important meetings this week</p><p><strong>{data.milestones.length}</strong> upcoming milestones</p><p><strong>{data.gates.length}</strong> unresolved decision gates</p></div></section><section className="strategy-section data-surface"><header><div><p className="eyebrow">6. Select this week’s commitments</p><small>Three to seven is a useful range. Carry-forward is always explicit.</small></div><small>{selected.length} selected</small></header><div className="weekly-selection">{data.commitments.map(item => <label key={item.id}><input type="checkbox" checked={selected.includes(item.id)} onChange={event => setSelected(current => event.target.checked ? [...current, item.id] : current.filter(id => id !== item.id))} /><span><strong>{item.title}</strong><small>{item.planning_period_id ? "Carry-forward candidate" : "Not assigned"} · {item.target_date ?? "No deadline"}</small></span></label>)}</div>{selected.length > 7 ? <p className="field-error">This selection may exceed your weekly capacity. Review lower-priority commitments before confirming.</p> : null}</section><section className="strategy-section data-surface"><p className="eyebrow">7. Confirm plan</p><h2>{words(data.capacity.state)}</h2><p className="dataset-note">{data.capacity.reason}</p><Button intent="brand" disabled={saving || !period} onClick={() => void confirm()}>{saving ? "Confirming…" : "Confirm this week"}</Button></section></>}</main>;
}

export function PeriodPlanningPage({ type }: { type: "month" | "quarter" }) {
  type Data = SchemaState & { periods: Item[]; commitments: Item[]; milestones: Item[]; gates: Item[]; events: Item[]; goals: Item[]; capacity: { state: string; reason: string } };
  const label = type === "month" ? "This month" : "This quarter";
  const [data, setData] = useState<Data | null>(null), [period, setPeriod] = useState(""), [selected, setSelected] = useState<string[]>([]), [error, setError] = useState(""), [saving, setSaving] = useState(false);
  const load = useCallback(async () => { try { const response = await fetch(`/api/strategy/period-plan?type=${type}`, { cache: "no-store" }), body = await response.json(); if (!response.ok) throw new Error(body.error); setData(body); setPeriod(current => current || body.periods?.find((row: Item) => row.status === "active")?.id || body.periods?.[0]?.id || ""); } catch (reason) { setError(reason instanceof Error ? reason.message : "Planning inputs could not be loaded."); } }, [type]);
  useDeferredEffect(useCallback(() => { void load(); }, [load]));
  const confirm = async () => { if (!period) { setError(`Create a ${type} planning period before confirming.`); return; } setSaving(true); try { const response = await fetch(`/api/strategy/period-plan?type=${type}`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ periodId: period, commitmentIds: selected }) }), body = await response.json(); if (!response.ok) throw new Error(body.error); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Plan could not be confirmed."); } finally { setSaving(false); } };
  return <main className="domain-page strategy-page"><header className="page-header"><div><p className="eyebrow">{type} planning</p><h1>{label}.</h1><p>{type === "month" ? "Choose a small set of meaningful priorities after reviewing constraints." : "Connect goals, portfolio work, milestones, risk, and decisions without creating a second OKR system."}</p></div>{data?.schemaStatus !== "unavailable" ? <Link className="button button--outline" href="/control-tower">New period</Link> : null}</header>{error ? <p className="field-error">{error}</p> : null}{data?.schemaStatus === "unavailable" ? <Unavailable title={`${label} planning is unavailable`} /> : !data ? <div className="empty-state"><span>···</span><h2>Preparing planning inputs</h2></div> : <><section className="strategy-section data-surface"><label>{type[0].toUpperCase() + type.slice(1)} period<select value={period} onChange={event => setPeriod(event.target.value)}><option value="">Choose a {type} period</option>{data.periods.map(item => <option key={item.id} value={item.id}>{item.title} · {item.status}</option>)}</select></label></section><section className="strategy-section data-surface"><header><div><p className="eyebrow">Review</p><small>Unfinished commitments are candidates, never automatic carry-forward.</small></div></header><div className="weekly-inputs"><p><strong>{data.commitments.length}</strong> unfinished commitments</p><p><strong>{data.milestones.length}</strong> major milestones</p><p><strong>{data.gates.length}</strong> decisions required</p><p><strong>{data.events.length}</strong> known constraints</p>{type === "quarter" ? <p><strong>{data.goals.length}</strong> active goals</p> : null}</div></section><section className="strategy-section data-surface"><header><div><p className="eyebrow">Choose priorities</p><small>Three to ten meaningful priorities keeps the plan usable.</small></div><small>{selected.length} selected</small></header><div className="weekly-selection">{data.commitments.map(item => <label key={item.id}><input type="checkbox" checked={selected.includes(item.id)} onChange={event => setSelected(current => event.target.checked ? [...current, item.id] : current.filter(id => id !== item.id))} /><span><strong>{item.title}</strong><small>{item.planning_period_id ? "Carry-forward candidate" : "Unassigned"} · {item.target_date ?? "No deadline"}</small></span></label>)}</div>{selected.length > 10 ? <p className="field-error">This plan is likely too broad. Review lower-priority commitments before confirming.</p> : null}</section><section className="strategy-section data-surface"><p className="eyebrow">Capacity and confirmation</p><h2>{words(data.capacity.state)}</h2><p className="dataset-note">{data.capacity.reason}</p><Button intent="brand" disabled={saving || !period} onClick={() => void confirm()}>{saving ? "Confirming…" : `Confirm ${type}`}</Button></section></>}</main>;
}

export function ScenariosPage() {
  type Data = SchemaState & { scenarios: Array<{ id: string; title: string; assumptions?: string[] }>; impact: Record<string, unknown> };
  const [data, setData] = useState<Data | null>(null), [title, setTitle] = useState(""), [assumption, setAssumption] = useState(""), [error, setError] = useState("");
  const load = useCallback(async () => { try { const response = await fetch("/api/strategy/scenarios", { cache: "no-store" }), body = await response.json(); if (!response.ok) throw new Error(body.error); setData(body); } catch (reason) { setError(reason instanceof Error ? reason.message : "Scenarios could not be loaded."); } }, []);
  useDeferredEffect(useCallback(() => { void load(); }, [load]));
  const create = async () => { if (!title.trim()) { setError("Give the scenario a title."); return; } const response = await fetch("/api/strategy/scenarios", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ title, assumptions: assumption.trim() ? [assumption.trim()] : [] }) }); if (!response.ok) { const body = await response.json(); setError(body.error ?? "Scenario could not be saved."); return; } setTitle(""); setAssumption(""); await load(); };
  return <main className="domain-page strategy-page"><header className="page-header"><div><p className="eyebrow">Hypothetical planning</p><h1>Scenarios.</h1><p>Compare recorded planning impact without changing live commitments, dates, or source records.</p></div><Link className="button button--outline" href="/control-tower">Control Tower</Link></header>{error ? <p className="field-error">{error}</p> : null}{data?.schemaStatus === "unavailable" ? <Unavailable title="Strategic Scenarios are unavailable" /> : <><section className="strategy-section data-surface"><p className="eyebrow">New scenario</p><label>Title<input value={title} onChange={event => setTitle(event.target.value)} placeholder="What if launch moves two weeks?" /></label><label>Assumption<input value={assumption} onChange={event => setAssumption(event.target.value)} placeholder="One explicit assumption" /></label><Button intent="brand" onClick={() => void create()}>Create scenario</Button></section>{!data ? <div className="empty-state"><span>···</span><h2>Reading scenario context</h2></div> : <section className="strategy-section data-surface"><header><div><p className="eyebrow">Recorded scenarios</p><small>Impact uses only current stored planning data.</small></div></header><div className="portfolio-list">{data.scenarios.length ? data.scenarios.map(item => <article className="portfolio-row" key={item.id}><div><p className="eyebrow">Scenario</p><h2>{item.title}</h2><small>{item.assumptions?.join(" · ") || "No assumptions recorded"}</small></div><div><strong>Hypothetical</strong><small>Open to compare impact</small></div></article>) : <p className="dataset-note">No scenarios yet. Scenarios never apply changes automatically.</p>}</div></section>}</>}</main>;
}
