"use client";
import { useCallback, useState } from "react";
import { AttachmentSection } from "@/components/attachment-section";
import { Button } from "@/components/ui/button";
import { Modal } from "@/components/ui/modal";
import { documentExpiryStatus } from "@/lib/life";
import { useDeferredEffect } from "@/lib/use-deferred-effect";
type Document = { id: string; label: string; type: string; country: string | null; issued_at: string | null; expires_at: string | null; notes: string | null };
export function DocumentsWorkspace() { const [records, setRecords] = useState<Document[] | null>(null); const [open, setOpen] = useState(false); const [selected, setSelected] = useState<Document | null>(null); const [error, setError] = useState(""); const load = useCallback(async () => { try { const response = await fetch("/api/life/documents", { cache: "no-store" }); const body = await response.json() as { records: Document[]; error?: string }; if (!response.ok) throw new Error(body.error ?? "Documents could not be loaded."); setRecords(body.records); setError(""); } catch (reason) { setError(reason instanceof Error ? reason.message : "Documents could not be loaded."); } }, []); useDeferredEffect(useCallback(() => { void load(); }, [load])); return <div className="domain-page life-page"><header className="page-header"><div><p className="eyebrow">Life · private documents</p><h1>Documents.</h1><p>Track validity and keep private supporting files alongside the document, without storing document numbers.</p></div><Button onClick={() => setOpen(true)}>Add document</Button></header>{error ? <section className="inline-error" role="alert"><p>{error}</p><Button emphasis="outline" onClick={() => void load()}>Try again</Button></section> : null}<section className="data-surface document-list">{records === null ? <p className="dataset-note">Loading documents…</p> : records.length ? records.map((document) => <button className="document-row" type="button" onClick={() => setSelected(document)} key={document.id}><span><strong>{document.label}</strong><small>{document.type.replaceAll("_", " ")}{document.country ? ` · ${document.country}` : ""}</small></span><span className={`life-status life-status--${documentExpiryStatus(document.expires_at)}`}>{document.expires_at ? `Expires ${document.expires_at}` : "No expiry"}</span></button>) : <div className="empty-state"><span>□</span><h2>No personal documents</h2><p>Track passports, insurance, permits, memberships, and other private documents.</p><Button onClick={() => setOpen(true)}>Add document</Button></div>}</section>{open ? <DocumentModal onClose={() => setOpen(false)} onSaved={async () => { setOpen(false); await load(); }} /> : null}<Modal open={Boolean(selected)} onClose={() => setSelected(null)} title={selected?.label ?? "Document"} description="Files are private and opened only through short-lived signed access.">{selected ? <><p className="dataset-note">{selected.expires_at ? `Expiry: ${selected.expires_at}` : "No expiry date tracked"}</p><AttachmentSection entityType="personal_document" entityId={selected.id} title="Private files"/><div className="modal__actions"><Button emphasis="ghost" onClick={() => setSelected(null)}>Done</Button></div></> : null}</Modal></div>; }
function DocumentModal({ onClose, onSaved }: { onClose: () => void; onSaved: () => Promise<void> }) { const [label, setLabel] = useState(""); const [type, setType] = useState("other"); const [expires, setExpires] = useState(""); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const save = async () => { if (!label.trim()) { setError("Enter a document name."); return; } setBusy(true); try { const response = await fetch("/api/life/documents", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ label, type, expires_at: expires || null }) }); const body = await response.json() as { error?: string }; if (!response.ok) throw new Error(body.error ?? "Document could not be saved."); await onSaved(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Document could not be saved."); } finally { setBusy(false); } }; return <Modal open onClose={onClose} title="Add document" description="Do not enter document or account numbers here."><form className="form-stack life-form" noValidate onSubmit={(event) => { event.preventDefault(); void save(); }}><label htmlFor="document-label">Document name</label><input id="document-label" autoFocus value={label} onChange={(event) => setLabel(event.target.value)} /><label htmlFor="document-type">Type</label><select id="document-type" value={type} onChange={(event) => setType(event.target.value)}><option value="passport">Passport</option><option value="national_id">National ID</option><option value="driving_permit">Driving permit</option><option value="travel_insurance">Travel insurance</option><option value="insurance">Insurance</option><option value="certificate">Certificate</option><option value="other">Other</option></select><label htmlFor="document-expiry">Expiry date</label><input id="document-expiry" type="date" value={expires} onChange={(event) => setExpires(event.target.value)} />{error ? <p className="field-error" role="alert">{error}</p> : null}<div className="modal__actions"><Button emphasis="ghost" type="button" onClick={onClose}>Cancel</Button><Button type="submit" disabled={busy}>{busy ? "Saving…" : "Save document"}</Button></div></form></Modal>; }
