"use client";

import Link from "next/link";
import { useCallback, useState, type ReactNode } from "react";
import { Button } from "@/components/ui/button";
import { Modal } from "@/components/ui/modal";
import { useDeferredEffect } from "@/lib/use-deferred-effect";

type Signal = { id: string; title: string; message: string; route: string; kind: string };
type Profile = { home_country: string | null; home_city: string | null; default_currency: string; preferred_timezone: string | null; passport_country: string | null };
type Data = { schemaStatus?: "available" | "unavailable"; schemaDependency?: string; profile: Profile | null; nextAction: Signal | null; attention: Signal[]; trips: Array<{ id: string; title: string; destination_city: string | null; destination_country: string | null; start_date: string | null; status: string }>; documents: Array<{ id: string; label: string; expires_at: string | null }>; renewals: Array<{ id: string; title: string; due_date: string | null; status: string }>; admin: Array<{ id: string; title: string; due_date: string | null; status: string }>; dates: Array<{ id: string; title: string; date: string }>; goals: Array<{ id: string; title: string; period: string | null; progress: number | null; target_date: string | null }>; routines: Array<{ id: string; title: string }>; completedRoutineIds: string[]; fitness: { sessions: number; targets: Array<{ target_value: number; target_type: string }> } };

export function LifeDashboard() {
  const [data, setData] = useState<Data | null>(null); const [error, setError] = useState(""); const [create, setCreate] = useState<"trips" | "documents" | "renewals" | "admin" | "dates" | "routines" | null>(null); const [profileOpen, setProfileOpen] = useState(false);
  const load = useCallback(async () => { try { const response = await fetch("/api/life", { cache: "no-store" }); const body = await response.json() as Data & { error?: string }; if (!response.ok) throw new Error(body.error ?? "Life overview could not be loaded."); setData(body); setError(""); } catch (reason) { setError(reason instanceof Error ? reason.message : "Life overview could not be loaded."); } }, []);
  const completeRoutine = async (routineId: string) => { try { const response = await fetch("/api/life/routine-completions", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ routine_id: routineId }) }); const body = await response.json() as { error?: string }; if (!response.ok) throw new Error(body.error ?? "Routine could not be marked done."); setData((current) => current ? { ...current, completedRoutineIds: [...new Set([...current.completedRoutineIds, routineId])] } : current); } catch (reason) { setError(reason instanceof Error ? reason.message : "Routine could not be marked done."); } };
  useDeferredEffect(useCallback(() => { void load(); }, [load]));
  if (error) return <div className="domain-page"><section className="inline-error" role="alert"><p>{error}</p><Button emphasis="outline" onClick={() => void load()}>Try again</Button></section></div>;
  if (!data) return <div className="domain-page"><div className="empty-state"><span>···</span><h2>Preparing your life overview</h2></div></div>;
  if (data.schemaStatus === "unavailable") return <main className="domain-page life-page"><header className="page-header"><div><p className="eyebrow">Personal operating system</p><h1>Life.</h1><p>A private, calm view of what needs preparation, renewal, or attention.</p></div></header><section className="data-surface empty-state"><h2>Life is not configured</h2><p>This environment is missing the V7 life schema. Existing workspace areas remain available; personal planning actions are disabled here until that dependency is installed.</p></section></main>;
  const trip = data.trips[0];
  return <div className="domain-page life-page"><header className="page-header"><div><p className="eyebrow">Personal operating system</p><h1>Life.</h1><p>A private, calm view of what needs preparation, renewal, or attention.</p></div><div className="life-header-actions"><Button onClick={() => setCreate("trips")}>New trip</Button><Button emphasis="outline" onClick={() => setCreate("admin")}>New admin item</Button><Button emphasis="ghost" onClick={() => setProfileOpen(true)}>Personal context</Button></div></header>
    <section className="life-hero"><div><p className="eyebrow">Next personal action</p>{data.nextAction ? <><h2>{data.nextAction.title}</h2><p>{data.nextAction.message}</p><Link className="button button--outline button--neutral" href={data.nextAction.route}>Review</Link></> : <><h2>You’re clear for now.</h2><p>Life signals will appear here when preparation or follow-through matters.</p></>}</div><div className="life-hero__ledger"><Signal label="Next trip" value={trip ? trip.title : "None planned"} note={trip?.start_date ?? "Add travel when you are ready."}/><Signal label="Documents" value={`${data.documents.length} tracked`} note={data.documents.find((item) => item.expires_at)?.expires_at ? `Next expiry ${data.documents.find((item) => item.expires_at)?.expires_at}` : "No expiry tracked"}/><Signal label="Fitness this week" value={`${data.fitness.sessions} session${data.fitness.sessions === 1 ? "" : "s"}`} note={data.fitness.targets.length ? `${data.fitness.targets.length} active target${data.fitness.targets.length === 1 ? "" : "s"}` : "No active target"}/></div></section>
    <Section label="Needs attention" action="Review all" href="#attention">{data.attention.length ? <div className="signal-stack" id="attention">{data.attention.map((signal) => <Link className="signal-row" href={signal.route} key={signal.id}><span><strong>{signal.title}</strong>{signal.message}</span><small>Review →</small></Link>)}</div> : <p className="dataset-note">No personal items need attention right now.</p>}</Section>
    <div className="life-columns"><Section label="Travel" action="Open travel" href="/travel"><LifeRows items={data.trips.slice(0, 3)} empty="No upcoming trips." secondary={(item) => [item.destination_city, item.destination_country, item.start_date].filter(Boolean).join(" · ")}/></Section><Section label="Documents" action="Manage documents" href="/documents"><LifeRows items={data.documents.slice(0, 4)} empty="No personal documents tracked." secondary={(item) => item.expires_at ? `Expires ${item.expires_at}` : "No expiry"}/><Button emphasis="ghost" onClick={() => setCreate("documents")}>Add document</Button></Section></div>
    <div className="life-columns"><Section label="Renewals" action="View renewals" href="#renewals"><LifeRows items={data.renewals.slice(0, 4)} empty="No renewals tracked." secondary={(item) => item.due_date ? `Due ${item.due_date}` : "No date"}/><Button emphasis="ghost" onClick={() => setCreate("renewals")}>Add renewal</Button></Section><Section label="Personal admin" action="Review admin" href="#admin"><LifeRows items={data.admin.slice(0, 4)} empty="No personal admin items." secondary={(item) => item.due_date ? `Due ${item.due_date}` : item.status.replaceAll("_", " ")}/></Section></div>
    <div className="life-columns"><Section label="Fitness" action="Open fitness" href="/fitness"><p className="life-metric">{data.fitness.sessions} session{data.fitness.sessions === 1 ? "" : "s"} this week</p><p className="dataset-note">{data.fitness.targets.length ? `${data.fitness.targets.length} active target${data.fitness.targets.length === 1 ? "" : "s"}.` : "No active fitness target."}</p></Section><Section label="Goals" action="Open goals" href="/goals"><LifeRows items={data.goals.slice(0, 4)} empty="No active personal goals." secondary={(item) => [item.period, item.progress != null ? `${item.progress}%` : null, item.target_date].filter(Boolean).join(" · ") || "Active"}/></Section></div>
    <div className="life-columns"><Section label="Important dates" action="Add date" onAction={() => setCreate("dates")}><LifeRows items={data.dates.slice(0, 4)} empty="No dates tracked." secondary={(item) => item.date}/></Section><Section label="Routines" action="Add routine" onAction={() => setCreate("routines")}>{data.routines.length ? <div className="signal-stack">{data.routines.slice(0, 5).map((routine) => { const done = data.completedRoutineIds.includes(routine.id); return <div className="signal-row" key={routine.id}><span><strong>{routine.title}</strong>{done ? "Done this week" : "Due when you choose"}</span><Button emphasis="ghost" disabled={done} onClick={() => void completeRoutine(routine.id)}>{done ? "Done" : "Mark done"}</Button></div>; })}</div> : <p className="dataset-note">No active routines.</p>}</Section></div>
    <LifeCreateModal kind={create} onClose={() => setCreate(null)} onSaved={async () => { setCreate(null); await load(); }}/>{profileOpen ? <ProfileModal profile={data.profile} onClose={() => setProfileOpen(false)} onSaved={async () => { setProfileOpen(false); await load(); }} /> : null}
  </div>;
}

function Signal({ label, value, note }: { label: string; value: string; note: string }) { return <div><span>{label}</span><strong>{value}</strong><small>{note}</small></div>; }
function Section({ label, action, href, onAction, children }: { label: string; action?: string; href?: string; onAction?: () => void; children: ReactNode }) { return <section className="data-surface life-section"><header><div><p className="eyebrow">{label}</p></div>{action ? href ? <Link className="button button--ghost" href={href}>{action}</Link> : <Button emphasis="ghost" onClick={onAction}>{action}</Button> : null}</header>{children}</section>; }
function LifeRows<T extends { id: string; title?: string; label?: string }>({ items, empty, secondary }: { items: T[]; empty: string; secondary: (item: T) => string }) { return items.length ? <div className="signal-stack">{items.map((item) => <div className="signal-row" key={item.id}><span><strong>{item.title ?? item.label}</strong>{secondary(item)}</span></div>)}</div> : <p className="dataset-note">{empty}</p>; }

function LifeCreateModal({ kind, onClose, onSaved }: { kind: "trips" | "documents" | "renewals" | "admin" | "dates" | "routines" | null; onClose: () => void; onSaved: () => Promise<void> }) {
  const [title, setTitle] = useState(""); const [date, setDate] = useState(""); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  if (!kind) return null; const labels = { trips: "trip", documents: "document", renewals: "renewal", admin: "admin item", dates: "important date", routines: "routine" }; const save = async () => { if (!title.trim()) { setError(`Enter a ${labels[kind]} name.`); return; } const payload: Record<string, unknown> = kind === "trips" ? { title, start_date: date || null } : kind === "documents" ? { label: title, type: "other", expires_at: date || null } : kind === "renewals" ? { title, due_date: date || null } : kind === "admin" ? { title, due_date: date || null } : kind === "dates" ? { title, date: date || undefined, recurrence: "none" } : { title, frequency: "weekly", days: [1,2,3,4,5] }; if (kind === "dates" && !date) { setError("Choose the date to remember."); return; } setBusy(true); try { const response = await fetch(`/api/life/${kind}`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) }); const body = await response.json() as { error?: string }; if (!response.ok) throw new Error(body.error ?? "Life record could not be saved."); await onSaved(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Life record could not be saved."); } finally { setBusy(false); } };
  return <Modal open onClose={onClose} title={`New ${labels[kind]}`} description="This stays private to your workspace."><form className="form-stack life-form" noValidate onSubmit={(event) => { event.preventDefault(); void save(); }}><label htmlFor="life-title">Name</label><input id="life-title" autoFocus value={title} onChange={(event) => setTitle(event.target.value)} aria-invalid={Boolean(error)} />{kind !== "routines" ? <><label htmlFor="life-date">{kind === "documents" ? "Expiry date" : kind === "trips" ? "Start date" : "Date"}</label><input id="life-date" type="date" value={date} onChange={(event) => setDate(event.target.value)} /></> : null}{error ? <p className="field-error" role="alert">{error}</p> : null}<div className="modal__actions"><Button emphasis="ghost" type="button" onClick={onClose}>Cancel</Button><Button type="submit" disabled={busy}>{busy ? "Saving…" : `Save ${labels[kind]}`}</Button></div></form></Modal>;
}
function ProfileModal({ profile, onClose, onSaved }: { profile: Profile | null; onClose: () => void; onSaved: () => Promise<void> }) { const [country, setCountry] = useState(profile?.home_country ?? ""); const [city, setCity] = useState(profile?.home_city ?? ""); const [currency, setCurrency] = useState(profile?.default_currency ?? "MAD"); const [timezone, setTimezone] = useState(profile?.preferred_timezone ?? ""); const [passportCountry, setPassportCountry] = useState(profile?.passport_country ?? ""); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const save = async () => { setBusy(true); try { const response = await fetch("/api/life/profile", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ home_country: country, home_city: city, default_currency: currency, preferred_timezone: timezone, passport_country: passportCountry }) }); const body = await response.json() as { error?: string }; if (!response.ok) throw new Error(body.error ?? "Personal context could not be saved."); await onSaved(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Personal context could not be saved."); } finally { setBusy(false); } }; return <Modal open onClose={onClose} title="Personal context" description="Keep this light. Do not enter document numbers or other sensitive identifiers."><form className="form-stack life-form" onSubmit={(event) => { event.preventDefault(); void save(); }}><label htmlFor="life-home-country">Home country</label><input id="life-home-country" value={country} onChange={(event) => setCountry(event.target.value)} /><label htmlFor="life-home-city">Home city</label><input id="life-home-city" value={city} onChange={(event) => setCity(event.target.value)} /><label htmlFor="life-currency">Default currency</label><input id="life-currency" maxLength={3} value={currency} onChange={(event) => setCurrency(event.target.value.toUpperCase())} /><label htmlFor="life-timezone">Preferred timezone</label><input id="life-timezone" placeholder="Africa/Casablanca" value={timezone} onChange={(event) => setTimezone(event.target.value)} /><label htmlFor="life-passport-country">Passport country</label><input id="life-passport-country" value={passportCountry} onChange={(event) => setPassportCountry(event.target.value)} />{error ? <p className="field-error" role="alert">{error}</p> : null}<div className="modal__actions"><Button emphasis="ghost" type="button" onClick={onClose}>Cancel</Button><Button type="submit" disabled={busy}>{busy ? "Saving…" : "Save context"}</Button></div></form></Modal>; }
