"use client";

import Link from "next/link";
import { useCallback, useState } from "react";
import { Button } from "@/components/ui/button";
import { Modal } from "@/components/ui/modal";
import { useDeferredEffect } from "@/lib/use-deferred-effect";

type Trip = { id: string; title: string; destination_city: string | null; destination_country: string | null; start_date: string | null; end_date: string | null; purpose: string | null; status: string; notes: string | null };
type Data = { records: Trip[] };
export function TravelWorkspace() { const [data, setData] = useState<Data | null>(null); const [error, setError] = useState(""); const [open, setOpen] = useState(false); const load = useCallback(async () => { try { const response = await fetch("/api/life/trips", { cache: "no-store" }); const body = await response.json() as Data & { error?: string }; if (!response.ok) throw new Error(body.error ?? "Trips could not be loaded."); setData(body); setError(""); } catch (reason) { setError(reason instanceof Error ? reason.message : "Trips could not be loaded."); } }, []); useDeferredEffect(useCallback(() => { void load(); }, [load])); return <div className="domain-page life-page"><header className="page-header"><div><p className="eyebrow">Life · travel</p><h1>Trips.</h1><p>Keep preparation, travel records, and private documents together without guessing at live travel data.</p></div><Button onClick={() => setOpen(true)}>New trip</Button></header>{error ? <section className="inline-error" role="alert"><p>{error}</p><Button emphasis="outline" onClick={() => void load()}>Try again</Button></section> : null}<section className="data-surface travel-list">{!data ? <p className="dataset-note">Loading trips…</p> : data.records.length ? data.records.map((trip) => <Link className="travel-row" href={`/travel/${trip.id}`} key={trip.id}><span><p className="eyebrow">{trip.status.replaceAll("_", " ")}</p><h2>{trip.title}</h2><p>{[trip.destination_city, trip.destination_country].filter(Boolean).join(", ") || "Destination not set"}</p></span><small>{trip.start_date ? `${trip.start_date}${trip.end_date ? ` → ${trip.end_date}` : ""}` : "Dates to plan"}</small></Link>) : <div className="empty-state"><span>↗</span><h2>No trips yet</h2><p>Create a trip to collect its plan, bookings, documents, packing, tasks, expenses, and notes.</p><Button onClick={() => setOpen(true)}>Create trip</Button></div>}</section>{open ? <TripModal onClose={() => setOpen(false)} onSaved={async () => { setOpen(false); await load(); }} /> : null}</div>; }
function TripModal({ onClose, onSaved }: { onClose: () => void; onSaved: () => Promise<void> }) { const [title, setTitle] = useState(""); const [city, setCity] = useState(""); const [country, setCountry] = useState(""); const [start, setStart] = useState(""); const [end, setEnd] = useState(""); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const save = async () => { if (!title.trim()) { setError("Enter a trip title."); return; } if (start && end && end < start) { setError("Return date must be after departure."); return; } setBusy(true); try { const response = await fetch("/api/life/trips", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ title, destination_city: city || null, destination_country: country || null, start_date: start || null, end_date: end || null, status: "planning" }) }); const body = await response.json() as { error?: string }; if (!response.ok) throw new Error(body.error ?? "Trip could not be saved."); await onSaved(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Trip could not be saved."); } finally { setBusy(false); } }; return <Modal open onClose={onClose} title="New trip" description="Travel details remain private. Live flight status is never inferred."><form className="form-stack life-form" noValidate onSubmit={(event) => { event.preventDefault(); void save(); }}><label htmlFor="trip-title">Trip title</label><input id="trip-title" autoFocus value={title} onChange={(event) => setTitle(event.target.value)} /><label htmlFor="trip-city">Destination city</label><input id="trip-city" value={city} onChange={(event) => setCity(event.target.value)} /><label htmlFor="trip-country">Destination country</label><input id="trip-country" value={country} onChange={(event) => setCountry(event.target.value)} /><label htmlFor="trip-start">Departure date</label><input id="trip-start" type="date" value={start} onChange={(event) => setStart(event.target.value)} /><label htmlFor="trip-end">Return date</label><input id="trip-end" type="date" value={end} onChange={(event) => setEnd(event.target.value)} />{error ? <p className="field-error" role="alert">{error}</p> : null}<div className="modal__actions"><Button emphasis="ghost" type="button" onClick={onClose}>Cancel</Button><Button type="submit" disabled={busy}>{busy ? "Saving…" : "Create trip"}</Button></div></form></Modal>; }
