export type TravelTrip = { id:string; title:string; destination_city:string|null; destination_country:string|null; start_date:string|null; end_date:string|null; status:string; notes:string|null; budget:number|null; currency:string };
export type TravelDetail = { trip:TravelTrip; segments:{id:string;title:string;type:string;starts_at:string|null;location:string|null}[]; reservations:{id:string;name:string;type:string;status:string;amount:number|null;currency:string}[]; documentLinks:{id:string;personal_documents:{label:string}|null}[]; packingLists:{id:string;title:string;packing_items:{id:string;title:string;packed:boolean}[]}[]; expenses:{id:string;description:string;amount:number;currency:string;category?:string}[]; notes:{id:string;title:string;content?:string}[] };
export function sampleTrips():TravelTrip[] {return [
 ['marrakech','Marrakech Weekend','Marrakech','Morocco','2026-10-14','2026-10-17','booked',1200],
 ['barcelona','Barcelona','Barcelona','Spain','2026-11-03','2026-11-10','planning',2400],
 ['istanbul','Istanbul','Istanbul','Türkiye','2026-12-12','2026-12-20','planning',2000],
 ['toubkal','Toubkal Adventure','Imlil','Morocco','2026-09-05','2026-09-12','completed',1350],
 ['paris','Paris','Paris','France','2026-06-01','2026-06-07','completed',1800],
 ['lisbon','Lisbon','Lisbon','Portugal','2026-03-15','2026-03-20','completed',1100],
].map(([id,title,city,country,start,end,status,budget])=>({id:String(id),title:String(title),destination_city:String(city),destination_country:String(country),start_date:String(start),end_date:String(end),status:String(status),budget:Number(budget),currency:'USD',notes:id==='marrakech'?'A long weekend in Marrakech to explore the medina, enjoy the food, and relax at a riad. Focus on local experiences, with a day trip to the Atlas Mountains.':`A little time to explore ${city}, discover local favourites, and enjoy a change of pace.`}));}
export function sampleDetails():Record<string,TravelDetail>{return Object.fromEntries(sampleTrips().map(trip=>[trip.id,{trip,segments:[{id:trip.id+'s1',title:'Depart for '+trip.destination_city,type:'flight',starts_at:trip.start_date+'T10:30:00Z',location:'Airport departure'},{id:trip.id+'s2',title:'Check in and settle in',type:'hotel',starts_at:trip.start_date+'T15:00:00Z',location:'Your accommodation'},{id:trip.id+'s3',title:'Explore the old town',type:'activity',starts_at:trip.start_date+'T17:00:00Z',location:trip.destination_city},{id:trip.id+'s4',title:'Local food & walking tour',type:'activity',starts_at:trip.start_date+'T19:00:00Z',location:'City centre'}],reservations:[{id:trip.id+'b1',name:'Flight to '+trip.destination_city,type:'flight',status:'booked',amount:300,currency:'USD'},{id:trip.id+'b2',name:trip.id==='marrakech'?'Riad El Fenn':'Boutique city stay',type:'hotel',status:'booked',amount:480,currency:'USD'},{id:trip.id+'b3',name:'Airport transfer',type:'other',status:'booked',amount:45,currency:'USD'}],documentLinks:[{id:'d1',personal_documents:{label:'Passport'}},{id:'d2',personal_documents:{label:'Travel insurance'}},{id:'d3',personal_documents:{label:'Booking confirmations'}}],packingLists:[{id:trip.id+'p',title:'Travel essentials',packing_items:['Passport','Travel insurance','Power adapter','Walking shoes','Sunscreen','Camera'].map((title,i)=>({id:trip.id+'p'+i,title,packed:[0,1,4].includes(i)}))}],expenses:[{id:'e1',description:'Accommodation deposit',category:'Accommodation',amount:180,currency:'USD'},{id:'e2',description:'Flight deposit',category:'Flights',amount:120,currency:'USD'}],notes:[{id:'n1',title:'Places to explore',content:'Save a little room for spontaneous discoveries. Book the walking tour before departure.'}]}]));}
export function tripArtwork(trip:TravelTrip){const text=(trip.title+' '+trip.destination_city).toLowerCase();return ['marrakech','barcelona','istanbul','toubkal','paris','lisbon'].find(city=>text.includes(city))||null;}
export function tripGroup(trip:TravelTrip){return trip.status==='completed'?'Past':trip.status==='booked'||trip.status==='in_progress'?'Upcoming':'Planning';}
export function tripMoney(amount:number,currency:string){return new Intl.NumberFormat('en-US',{style:'currency',currency,maximumFractionDigits:0}).format(amount);}
export function tripDate(date:string|null){return date?new Intl.DateTimeFormat('en',{month:'short',day:'numeric',year:'numeric',timeZone:'UTC'}).format(new Date(date.slice(0,10)+'T12:00:00Z')):'Dates to plan';}
