'use client';
import Link from 'next/link';
import Image from 'next/image';
import {useMemo,useState,type ReactNode} from 'react';
import {Area,AreaChart,Bar,BarChart,CartesianGrid,Line,LineChart,ResponsiveContainer,Tooltip,XAxis,YAxis} from 'recharts';
import {ArrowDown,ArrowLeftRight,ArrowRight,ArrowUp,ArrowUpRight,CalendarDays,ChartNoAxesColumnIncreasing,CheckCircle2,ChevronRight,CircleAlert,Coins,FileText,Info,Plus,RefreshCw,Rocket,ShieldCheck,Wallet,X,type LucideIcon} from 'lucide-react';
import {StyledSelect} from '@/components/ui/styled-select';
import {Modal} from '@/components/ui/modal';
import {Button} from '@/components/ui/button';
import {financialViews,type FinancialResource} from '@/lib/financial-schema';
import {applyFinancialScenario,buildCashflowForecast,type FinancialRow,type ForecastEntry} from '@/lib/financial-control';
import {cashMovementHistory,reserveCoverage} from '@/lib/cash-planning';
import type {loadFinancialControl} from '@/lib/financial-server';
import './cash-planning-dashboard.css';
type Overview=Awaited<ReturnType<typeof loadFinancialControl>>&{schemaStatus?:'available'|'unavailable'};
const money=(value:number|null|undefined,currency:string)=>value==null?'Not available':new Intl.NumberFormat('en',{style:'currency',currency,maximumFractionDigits:0}).format(value);
const words=(value:unknown)=>String(value??'').replaceAll('_',' ').replace(/^./,char=>char.toUpperCase());
const date=(value:string|null)=>value?new Date(`${value.slice(0,10)}T12:00:00`).toLocaleDateString('en',{month:'short',day:'numeric'}):'No date';
function Panel({icon:Icon,title,subtitle,action,children,className=''}:{icon:LucideIcon;title:string;subtitle:string;action?:ReactNode;children:ReactNode;className?:string}){return <section className={`cash-planning__panel ${className}`}><header><span className="cash-planning__icon"><Icon size={23}/></span><div><h2>{title}</h2><p>{subtitle}</p></div>{action}</header>{children}</section>;}
function ViewLink({href,label='View all'}:{href:string;label?:string}){return <Link className="cash-planning__view" href={href}>{label}</Link>;}
export function CashPlanningDashboard({data,error,onRetry,onCreate}:{data:Overview|null;error:string;onRetry:()=>void;onCreate:(resource:FinancialResource,row?:FinancialRow)=>void}){
 const [currency,setCurrency]=useState('USD'),[months,setMonths]=useState('6'),[horizon,setHorizon]=useState('90'),[scenarioId,setScenarioId]=useState(''),[dismissed,setDismissed]=useState(false),[detail,setDetail]=useState<'cash'|'30'|'60'|'90'|'movement'|'basis'|null>(null);
 const ready=data&&data.schemaStatus!=='unavailable'?data:null;
 const currencies=useMemo(()=>Array.from(new Set(['USD',...Object.keys(ready?.opening??{}),...(ready?.entries??[]).map(row=>row.currency),...[...(ready?.data.settings??[]),...(ready?.data.payments??[]),...(ready?.data.obligations??[]),...(ready?.data.scenarios??[])].map(row=>String(row.currency).trim())])).sort(),[ready]);
 const forecast=ready?.forecasts.find(row=>row.currency===currency),cash=ready?.opening[currency]??null,accounts=ready?.cash.filter(row=>row.currency===currency)??[],reserve=ready?.buffer.find(row=>row.currency===currency)?.target??null,coverage=reserveCoverage(cash,reserve);
 const history=ready?cashMovementHistory(ready.data.payments,ready.data.obligations,currency,ready.today,Number(months)):[];
 const scenarios=ready?.data.scenarios.filter(row=>row.status==='active'&&String(row.currency).trim()===currency)??[];
 const scenario=scenarios.find(row=>row.id===scenarioId),projection=ready&&scenario?buildCashflowForecast(ready.opening,applyFinancialScenario(ready.entries,scenario,ready.today),ready.today).find(row=>row.currency===currency):undefined;
 const series=[{label:'Now',base:cash,scenario:scenario?cash:null},...[30,60,90].filter(day=>day<=Number(horizon)).map((day,index)=>({label:`${day} days`,base:forecast?.buckets[index]?.closing??null,scenario:projection?.buckets[index]?.closing??null}))];
 const entries=(ready?.entries??[]).filter(row=>row.currency===currency&&row.confidence!=='possible').sort((a,b)=>String(a.date??'9999').localeCompare(String(b.date??'9999')));
 const risks=ready?.risks.filter(row=>!row.currency||row.currency===currency)??[],next=risks[0];
 const inflow=forecast?.buckets[0]?.inflows??0,outflow=forecast?.buckets[0]?.outflows??0;
 const metricSeries=(index:number)=>[{value:cash},...(forecast?.buckets.slice(0,index+1).map(bucket=>({value:bucket.closing}))??[])];
 const modalEntries=detail==='movement'?forecast?.buckets[0]?.items??[]:['30','60','90'].includes(detail??'')?forecast?.buckets.slice(0,Number(detail)/30).flatMap(bucket=>bucket.items)??[]:[];
 return <div className="cash-planning"><header className="cash-planning__heading"><div><nav aria-label="Breadcrumb"><Link href="/business">BUSINESS</Link><span>/</span><strong>FINANCIAL CONTROL</strong></nav><h1>Financial Control</h1><p>Recorded money, explicit commitments, and decisions ahead.</p></div><Link className="cash-planning__records" href="/finance"><FileText size={17}/>Finance records</Link></header>
 <nav className="cash-planning__nav" aria-label="Financial Control"><Link href="/finance?view=planning" aria-current="page">Overview</Link>{['accounts','cashflow','collections','obligations','budgets','scenarios','risks'].map(view=><Link key={view} href={`/financial-control/${view}`}>{words(view)}</Link>)}<details><summary><ChevronRight size={14}/>More Financial Views</summary><div>{financialViews.filter(view=>!['accounts','cashflow','collections','obligations','budgets','scenarios','risks'].includes(view)).map(view=><Link key={view} href={`/financial-control/${view}`}>{words(view.replace('review/',''))}</Link>)}</div></details><div className="cash-planning__currency"><StyledSelect label="Planning currency" value={currency} onChange={value=>{setCurrency(value);setScenarioId('');}} options={currencies.map(value=>({value,label:value}))}/></div></nav>
 {error?<section className="cash-planning__empty" role="alert"><CircleAlert size={28}/><h2>Financial data unavailable</h2><p>{error}</p><Button onClick={onRetry}>Try again</Button></section>:!data?<div className="cash-planning__empty" role="status"><span className="loading-spinner"/><p>Loading your financial picture…</p></div>:!ready?<div className="cash-planning__empty"><Coins size={30}/><h2>Cash planning is not configured yet</h2><p>Your finance records are available. Planning requires the financial-control data tables.</p><Link href="/finance">Open Finance records</Link></div>:<>
 {!dismissed?<section className="cash-planning__next"><span className="cash-planning__rocket"><Rocket size={35}/></span><div><span className="cash-planning__eyebrow">NEXT FINANCIAL MOVE</span><h2>{next?.title??(cash===null?'Start with a recorded cash balance.':'Keep your financial picture up to date.')}</h2><p>{next?.evidence??(cash===null?'Add your cash accounts to see your current position and enable forecasting, planning, and risk analysis.':'Review account balances and upcoming commitments before your next financial decision.')}</p></div><Image unoptimized width={190} height={110} src="/images/finance/planning-cards.png" alt="" className="cash-planning__illustration"/><Link className="cash-planning__primary" href={next?.route??'/financial-control/accounts'}>{next?.action??'Manage cash accounts'}<ArrowRight size={16}/></Link><button className="cash-planning__dismiss" aria-label="Dismiss next financial move" onClick={()=>setDismissed(true)}><X size={16}/></button></section>:<button className="cash-planning__restore" onClick={()=>setDismissed(false)}><Rocket size={14}/>Show next financial move</button>}
 <section className="cash-planning__metrics" aria-label="Cash and forecast summary">{[{key:'cash',title:'Cash position',value:cash,icon:Wallet,tone:'green',caption:accounts.some(row=>row.stale)?'Balance needs refresh':'Manually recorded balance'},...[30,60,90].map((day,index)=>({key:String(day),title:`${day}-day outlook`,value:forecast?.buckets[index]?.closing??null,icon:CalendarDays,tone:['purple','blue','pink'][index],caption:'Committed + expected cash'}))].map(({key,title,value,icon:Icon,tone,caption},index)=><button key={key} className={`cash-planning__metric tone-${tone}`} onClick={()=>setDetail(key as 'cash'|'30'|'60'|'90')}><span className="cash-planning__icon"><Icon size={23}/></span><div><span>{title}</span><strong>{money(value,currency)}</strong><small>{value===null?'Record an opening balance':caption}</small></div>{value!==null&&index>0?<div className="cash-planning__spark" aria-hidden="true"><ResponsiveContainer width="100%" height="100%"><AreaChart data={metricSeries(index-1)}><Area dataKey="value" stroke="currentColor" fill="currentColor" fillOpacity={.07} strokeWidth={1.5} isAnimationActive={false}/></AreaChart></ResponsiveContainer></div>:null}</button>)}<button className="cash-planning__metric tone-orange" onClick={()=>setDetail('movement')}><span className="cash-planning__icon"><ArrowLeftRight size={23}/></span><div><span>Money in / money out</span><strong>{money(inflow-outflow,currency)}</strong><small>Next 30 days</small><p>In {money(inflow,currency)}<br/>Out {money(outflow,currency)}</p></div></button></section>
 <div className="cash-planning__middle"><Panel icon={ChartNoAxesColumnIncreasing} title="Cash flow overview" subtitle="Received payments vs settled obligations" action={<><div className="cash-planning__legend"><span>Inflow (received)</span><span>Outflow (paid)</span></div><StyledSelect label="Cash flow period" value={months} onChange={setMonths} options={[{value:'3',label:'Last 3 months'},{value:'6',label:'Last 6 months'},{value:'12',label:'Last 12 months'}]}/></>}><div className="cash-planning__chart" role="img" aria-label={`Cash movement in ${currency==='USD'?'$':currency}. ${history.map(row=>`${row.month}: received ${row.inflow}, paid ${row.outflow}`).join('; ')}`}><ResponsiveContainer width="100%" height="100%"><BarChart data={history} margin={{top:8,right:4,left:0,bottom:0}}><CartesianGrid vertical={false} stroke="var(--planning-line)" strokeDasharray="3 3"/><XAxis dataKey="label" axisLine={false} tickLine={false} tick={{fontSize:11,fill:'var(--planning-muted)'}}/><YAxis ticks={history.some(row=>row.inflow||row.outflow)?undefined:[0]} width={68} axisLine={false} tickLine={false} tick={{fontSize:10,fill:'var(--planning-muted)'}} tickFormatter={value=>`${currency==='USD'?'$':currency} ${value>=1000?`${value/1000}K`:value}`}/><Tooltip formatter={(value,name)=>[money(Number(value),currency),name==='inflow'?'Received':'Paid obligations']} contentStyle={{borderRadius:10,border:'1px solid #e7e4f6'}}/><Bar dataKey="inflow" fill="#9161ff" radius={[3,3,0,0]} maxBarSize={29}/><Bar dataKey="outflow" fill="#9cc8ff" radius={[3,3,0,0]} maxBarSize={29}/></BarChart></ResponsiveContainer></div>{!history.some(row=>row.inflow||row.outflow)&&<p className="cash-planning__chart-note">Record payments and paid obligations to build your cash history.</p>}</Panel>
 <Panel icon={Coins} title="Accounts snapshot" subtitle="Your current cash position and reserve status" action={<ViewLink href="/financial-control/accounts" label="Manage"/>}><button className="cash-planning__balance-value" onClick={()=>setDetail('cash')}>{money(cash,currency)}<small>{accounts.length?`${accounts.length} active ${accounts.length===1?'account':'accounts'} · recorded balance`:'No recorded cash balance'}</small></button><div className="cash-planning__reserve-bar" role="img" aria-label={coverage===null?'Reserve coverage unavailable':`${coverage}% reserve coverage`}><span style={{width:`${Math.min(100,coverage??0)}%`}}/></div><div className="cash-planning__reserve-stats"><Link href="/financial-control/settings"><Coins size={24}/><span><strong>{money(reserve,currency)}</strong><small>Target reserve</small></span></Link><Link href="/financial-control/runway"><ShieldCheck size={24}/><span><strong>{coverage===null?'Not configured':`${coverage}%`}</strong><small>Reserve coverage</small></span></Link></div>{cash===null&&<button className="cash-planning__text-action" onClick={()=>onCreate(accounts.length?'snapshots':'accounts')}><Plus size={14}/>{accounts.length?'Record a balance':'Add a cash account'}</button>}</Panel></div>
 <div className="cash-planning__bottom"><Panel icon={FileText} title="Commitments & obligations" subtitle="Upcoming payments and collections" action={<ViewLink href="/financial-control/calendar"/>}><div className="cash-planning__table"><table><thead><tr><th>Type</th><th>Description</th><th>Due date</th><th>Amount</th><th>Status</th></tr></thead><tbody>{entries.slice(0,5).map(entry=><tr key={entry.key}><td>{entry.direction==='in'?<ArrowDown className="is-green" size={18} aria-label="Inflow"/>:<ArrowUp className="is-red" size={18} aria-label="Outflow"/>}</td><td><Link href={entry.route}>{entry.title}</Link></td><td>{date(entry.date)}</td><td>{money(entry.amount,currency)}</td><td><span className={`cash-planning__badge ${entry.direction==='in'?'is-green':'is-orange'}`}>{entry.date&&entry.date<ready.today?'Overdue':words(entry.confidence)}</span></td></tr>)}</tbody></table></div>{!entries.length&&<div className="cash-planning__panel-empty"><FileText size={25}/><strong>No commitments recorded</strong><p>Add an obligation to include upcoming payments in your forecast.</p><button onClick={()=>onCreate('obligations')}>Add obligation<Plus size={14}/></button></div>}</Panel>
 <Panel icon={CircleAlert} title="Financial risks" subtitle="Based on current records and upcoming obligations" className="cash-planning__risks" action={<ViewLink href="/financial-control/risks"/>}>{risks.length?risks.slice(0,3).map(risk=><Link key={risk.key} href={risk.route} className={`cash-planning__risk severity-${risk.severity}`}><CircleAlert size={22}/><span><strong>{risk.title}</strong><small>{risk.evidence}</small></span><ChevronRight size={15}/></Link>):<div className={`cash-planning__risk ${cash===null?'is-unknown':'is-clear'}`}>{cash===null?<Info size={26}/>:<CheckCircle2 size={28}/>}<span><strong>{cash===null?'Record balances to assess cash risk.':'No high-confidence financial risks detected.'}</strong><small>{cash===null?'Cash coverage cannot be assessed without an opening balance.':'Based on the records and commitments currently available.'}</small></span></div>}<Link className="cash-planning__watch" href="/financial-control/obligations"><ClockIcon/><span><strong>Keep an eye on</strong><small>{entries.filter(entry=>entry.direction==='out'&&entry.date&&entry.date>=ready.today).length} recorded upcoming payments · {currency}</small></span><ChevronRight size={15}/></Link></Panel>
 <Panel icon={ChartNoAxesColumnIncreasing} title="Scenarios & planning" subtitle="Explore different outcomes and plan ahead" action={<ViewLink href="/financial-control/scenarios"/>}><div className="cash-planning__scenario-controls"><StyledSelect label="Scenario outlook horizon" value={horizon} onChange={setHorizon} options={[{value:'30',label:'30-day outlook'},{value:'60',label:'30 / 60-day outlook'},{value:'90',label:'30 / 60 / 90-day outlook'}]}/>{scenarios.length>0&&<StyledSelect label="Compare scenario" value={scenarioId} onChange={setScenarioId} options={[{value:'',label:'Base plan'},...scenarios.map(row=>({value:row.id,label:String(row.title)}))]}/>}</div>{cash!==null?<><div className="cash-planning__scenario-chart" role="img" aria-label={`Base cash forecast in ${currency==='USD'?'$':currency}: ${series.map(row=>`${row.label} ${row.base??'unavailable'}`).join(', ')}${scenario?`; compared with ${scenario.title}`:''}`}><ResponsiveContainer width="100%" height="100%"><LineChart data={series} margin={{top:10,left:4,right:8,bottom:0}}><CartesianGrid vertical={false} stroke="var(--planning-line)"/><XAxis dataKey="label" tick={{fontSize:10,fill:'var(--planning-muted)'}} axisLine={false} tickLine={false}/><Tooltip formatter={(value,name)=>[money(Number(value),currency),name==='base'?'Base plan':String(scenario?.title??'Scenario')]} contentStyle={{borderRadius:9,border:'1px solid #eee'}}/><Line dataKey="base" stroke="#864bff" strokeWidth={2} dot={false} isAnimationActive={false}/>{scenario&&<Line dataKey="scenario" stroke="#16b88c" strokeDasharray="4 4" dot={false} strokeWidth={2} isAnimationActive={false}/>}</LineChart></ResponsiveContainer></div><div className="cash-planning__scenario-total"><span>Base plan<strong>{money(series.at(-1)?.base,currency)}</strong></span>{scenario&&<span>{String(scenario.title)}<strong>{money(series.at(-1)?.scenario,currency)}</strong></span>}</div></>:<div className="cash-planning__panel-empty"><ChartNoAxesColumnIncreasing size={27}/><strong>Your outlook starts with a balance</strong><p>Record current cash to see your 30 / 60 / 90-day projection.</p></div>}<button className="cash-planning__text-action" onClick={()=>onCreate('scenarios')}><Plus size={14}/>Create a scenario</button><p className="cash-planning__chart-note">Hypothetical scenarios never change your live records.</p></Panel></div>
 <footer className="cash-planning__footer"><button onClick={()=>setDetail('basis')}><Info size={14}/>Data basis & assumptions</button><span>{currency} only · no currency conversion · as of {date(ready.today)}</span><button onClick={onRetry}><RefreshCw size={13}/>Refresh</button></footer>
 </>}
 <Modal open={Boolean(detail)} onClose={()=>setDetail(null)} title={detail==='cash'?'Recorded cash accounts':detail==='basis'?'Data basis & assumptions':detail==='movement'?'Money in / money out':`${detail}-day cash outlook`} description={detail==='cash'?'Manually recorded balances. No money is moved.':detail==='basis'?'How to read this financial overview.':'Dated committed and expected entries. Possible pipeline is excluded.'}><div className="cash-planning__details">{detail==='basis'?ready?.limitations.map(text=><p key={text}>{text}</p>):detail==='cash'?<>{accounts.length?accounts.map(account=><div key={account.id}><Wallet size={20}/><span><strong>{account.name}</strong><small>{account.asOf?`Recorded ${date(account.asOf)}${account.stale?' · Needs refresh':''}`:'No balance recorded'}</small></span><b>{money(account.balance,currency)}</b></div>):<p>No active {currency} cash accounts recorded.</p>}<Link className="cash-planning__primary" href="/financial-control/accounts">Manage accounts<ArrowUpRight size={15}/></Link></>:<><strong className="cash-planning__detail-total">{money(detail==='movement'?inflow-outflow:forecast?.buckets[Number(detail)/30-1]?.closing,currency)}</strong>{modalEntries.length?modalEntries.map((entry:ForecastEntry)=><Link key={entry.key} href={entry.route}><span><strong>{entry.title}</strong><small>{date(entry.date)} · {entry.confidence}</small></span><b>{entry.direction==='out'?'−':'+'}{money(entry.amount,currency)}</b></Link>):<p>No dated commitments in this horizon.</p>}<Link href="/financial-control/cashflow">Open full cash-flow forecast<ArrowUpRight size={14}/></Link></>}</div></Modal>
 </div>;
}
function ClockIcon(){return <CalendarDays size={22}/>;}
