'use client';
import Link from 'next/link';
import {useCallback,useEffect,useRef,useState} from 'react';
import {Button} from '@/components/ui/button';
import {Modal} from '@/components/ui/modal';
import {useToast} from '@/components/toast-provider';
import {useDeferredEffect} from '@/lib/use-deferred-effect';
import {financialViews,validateFinancialRecord,type FinancialResource} from '@/lib/financial-schema';
import {applyFinancialScenario,buildCashflowForecast,evaluateInvestmentAffordability,evaluateCollectionPriority,type FinancialRow} from '@/lib/financial-control';
import type {loadFinancialControl} from '@/lib/financial-server';
import {financialFields,type FinancialField} from './financial-fields';
type Overview=Awaited<ReturnType<typeof loadFinancialControl>>;
const words=(v:unknown)=>String(v??'').replaceAll('_',' ');
const money=(n:number|null|undefined,c:string)=>n==null?'Unavailable':`${c} ${n.toLocaleString('en',{minimumFractionDigits:2,maximumFractionDigits:2})}`;
const resourceViews:Record<string,FinancialResource>={accounts:'accounts',promises:'promises',obligations:'obligations',budgets:'budgets',scenarios:'scenarios',investments:'investments',settings:'settings',links:'links'};
export function FinancialWorkspace({view='home'}:{view?:string}) {
 const [data,setData]=useState<Overview|null>(null),[error,setError]=useState(''),[editor,setEditor]=useState<{resource:FinancialResource;row?:FinancialRow}|null>(null);const {showToast}=useToast();
 const load=useCallback(async()=>{try{const r=await fetch('/api/financial-control',{cache:'no-store'}),b=await r.json();if(!r.ok)throw new Error(b.error??'Financial Control could not load.');setData(b);setError('');}catch(e){setError(e instanceof Error?e.message:'Financial Control could not load.');}},[]);
 useDeferredEffect(useCallback(()=>{void load();},[load]));
 const resource=resourceViews[view];
 return <main className="domain-page financial-page"><header className="page-header"><div><p className="eyebrow">Financial planning & cash control</p><h1>{view==='home'?'Financial Control.':words(view.replace('review/',''))+'.'}</h1><p>Recorded money, explicit commitments, and decisions ahead.</p></div><div className="detail-actions"><Link className="button button--outline" href="/finance">Finance records</Link>{resource?<Button intent="brand" onClick={()=>setEditor({resource})}>New {words(resource==='accounts'?'cash account':resource==='settings'?'currency policy':resource.replace(/s$/,''))}</Button>:null}</div></header><nav className="financial-nav" aria-label="Financial Control"><Link href="/financial-control" aria-current={view==='home'?'page':undefined}>Overview</Link>{['accounts','cashflow','collections','obligations','budgets','scenarios','risks'].map(v=><Link key={v} href={'/financial-control/'+v} aria-current={v===view?'page':undefined}>{words(v)}</Link>)}<details><summary>More financial views</summary><div>{financialViews.filter(v=>!['accounts','cashflow','collections','obligations','budgets','scenarios','risks'].includes(v)).map(v=><Link key={v} href={'/financial-control/'+v}>{words(v.replace('review/',''))}</Link>)}</div></details></nav>
 {error?<section className="empty-state"><h2>Financial data unavailable</h2><p role="alert">{error}</p><Button onClick={()=>void load()}>Try again</Button></section>:!data?<p role="status">Loading financial context…</p>:<>
 {view==='home'?<><section className="financial-next"><p className="eyebrow">Next financial move</p>{data.nextMove?<><h2>{data.nextMove.title}</h2><p>{data.nextMove.evidence}</p><Link className="button button--outline" href={data.nextMove.route}>{data.nextMove.action}</Link></>:<><h2>{data.cash.length?'No urgent financial condition detected.':'Start with a recorded cash balance.'}</h2><Link href="/financial-control/accounts">Manage cash accounts</Link></>}</section><Cash data={data}/><Forecast data={data}/><section><h2>Money in / money out</h2><EntryList data={data} direction="in" limit={4}/><EntryList data={data} direction="out" limit={4}/></section><Risks data={data}/></>:null}
 {view==='accounts'?<><Cash data={data}/><Records rows={data.data.accounts} resource="accounts" edit={setEditor}/><Button emphasis="outline" onClick={()=>setEditor({resource:'snapshots'})}>Record cash balance</Button><section><h2>Balance history</h2><p className="dataset-note">Manual snapshots are append-only. Recording a balance does not move money.</p>{data.data.snapshots.slice(0,50).map(s=><article className="financial-row" key={s.id}><strong>{String(data.data.accounts.find(a=>a.id===s.cash_account_id)?.name??'Account')}</strong><span>{money(Number(s.balance),String(s.currency))}</span><small>{String(s.as_of)} · {String(s.source)}</small></article>)}</section></>:null}
 {view==='cashflow'?<Forecast data={data}/>:null}
 {['inflows','outflows','calendar'].includes(view)?<EntryList data={data} direction={view==='calendar'?undefined:view==='inflows'?'in':'out'}/>:null}
 {['receivables','collections'].includes(view)?<section><h2>{view==='collections'?'Collection attention':'Receivables aging'}</h2><p className="dataset-note">Outstanding amounts come from the canonical invoice ledger. Follow-up never sends automatically.</p>{[...data.receivables].sort((a,b)=>(b.overdueDays??0)-(a.overdueDays??0)).map(i=><article className="financial-row" key={i.id}><strong>{String(i.title??i.invoice_number??'Invoice')}</strong><span>{money(i.outstanding,String(i.currency))} · {i.aging}</span><small>{evaluateCollectionPriority({amount:i.outstanding,overdueDays:i.overdueDays})}</small><div className="financial-actions"><Link className="button button--outline" href={'/finance/invoices?record='+i.id}>Open invoice</Link><Link className="button button--ghost" href="/followups">Create follow-up</Link><Button emphasis="ghost" onClick={()=>setEditor({resource:'promises',row:{id:'',invoice_id:i.id,currency:i.currency,amount:i.outstanding}})}>Record promise</Button></div></article>)}</section>:null}
 {view==='links'?<FinancialLinks rows={data.data.links} refresh={load}/>:null}
 {resource&&!['links','accounts','budgets','scenarios','investments'].includes(view)?<Records rows={data.data[resource]??[]} resource={resource} edit={setEditor}/>:null}
 {view==='budgets'?<><Records rows={data.data.budgets} resource="budgets" edit={setEditor}/><Button emphasis="outline" onClick={()=>setEditor({resource:'budget_lines'})}>Add budget line</Button>{data.budgets.map(b=><section key={b.id}><h2>{String(b.name)}</h2><Metrics currency={String(b.currency)} values={{Budget:b.variance.budget,'Recorded expenses':b.variance.recordedExpenses,'Future committed':b.variance.committed,'Explicit paid':b.variance.paid,Remaining:b.variance.remaining}}/><p className="dataset-note">{b.variance.paidBasis}</p></section>)}</>:null}
 {view==='subscriptions'?<><h2>Recurring cost and usage review</h2><Button emphasis="outline" onClick={()=>setEditor({resource:'subscription_reviews'})}>Review subscription</Button>{data.data.subscriptions.map(s=><article className="financial-row" key={s.id}><strong>{String(s.name)}</strong><span>{money(Number(s.amount),String(s.currency))} · {words(s.billing_cycle)} · next {String(s.next_billing_date??'date unavailable')}</span><small>{words(data.data.subscription_reviews.find(r=>r.subscription_id===s.id)?.status??'unknown')} usage</small><Link href={'/finance/subscriptions?record='+s.id}>Open subscription</Link></article>)}<Records rows={data.data.subscription_reviews} resource="subscription_reviews" edit={setEditor}/></>:null}
 {view==='expenses'?<section><h2>Recorded expense intelligence</h2><p>Expenses describe incurred cost. They do not prove payment settlement.</p>{Object.entries(data.data.expenses.reduce<Record<string,number>>((a,e)=>{const k=String(e.currency)+' · '+String(e.category??'Uncategorized');a[k]=(a[k]??0)+Number(e.amount);return a;},{})).map(([k,v])=><p key={k}>{k}: {v.toLocaleString('en')}</p>)}{data.data.expenses.filter(e=>!e.project_id&&!e.client_id).slice(0,10).map(e=><article className="financial-row" key={e.id}><strong>{String(e.description)}</strong><span>Unallocated to a project/client · {money(Number(e.amount),String(e.currency))}</span><Link href={'/finance/expenses?record='+e.id}>Review expense</Link></article>)}</section>:null}
 {view==='runway'?<section><h2>Runway / buffer</h2>{data.runway.map(r=><article className="financial-row" key={r.currency}><strong>{r.currency} · {r.state==='cashflow_positive'?'Current trailing period is cashflow positive.':r.months!==null?`${r.months.toFixed(1)} months estimated runway`:'Runway unavailable'}</strong><span>Gross monthly cash outflow {money(r.grossOutflow,r.currency)} · Net burn {money(r.netBurn,r.currency)}</span><small>Trailing three full months. Requires verified complete cash settlement history.</small></article>)}{data.buffer.map(b=><p key={b.currency}>{b.currency}: {b.state} · reserve {money(b.target,b.currency)}</p>)}<Link href="/financial-control/settings">Configure buffer and data coverage</Link></section>:null}
 {view==='profitability'?<section><h2>Gross-to-cash bridge</h2>{data.bridge.map(b=><section key={b.currency}><Metrics currency={b.currency} values={{Invoiced:b.invoiced,Collected:b.collected,Outstanding:b.outstanding,'Recorded expenses':b.recordedExpenses}}/><p>{b.basis}</p></section>)}<p>Accounting net income and recognized revenue are unavailable from these records.</p></section>:null}
 {view==='working-capital'?<section><h2>Operational working-capital view</h2><Cash data={data}/>{data.inventory.map(i=><article className="financial-row" key={i.id}><strong>{String(i.name)}</strong><span>Inventory at known cost: {money(i.value,String(i.currency))}</span><small>Snapshot: {String(i.asOf??'Unavailable')}</small></article>)}<EntryList data={data} direction="out"/><p>Current assets/liabilities are incomplete; this is not formal accounting working capital.</p></section>:null}
 {view==='concentration'?<section><h2>Client collections concentration</h2>{data.concentration.map(c=><article key={c.currency+c.entity} className="financial-row"><strong>{String(data.data.clients.find(x=>x.id===c.entity)?.name??'Client')}</strong><span>{money(c.amount,c.currency)} · {(c.share*100).toFixed(1)}% · {c.state}</span></article>)}<h2>Expected cash inflow concentration</h2>{data.inflowConcentration.map(c=><p key={c.currency+c.entity}>{String(data.data.clients.find(x=>x.id===c.entity)?.name??'Client')} · {c.currency} · {(c.share*100).toFixed(1)}%</p>)}</section>:null}
 {view==='scenarios'?<><p className="financial-caution">Hypothetical. Scenario assumptions never change invoices, balances, expenses, or live plans.</p><Records rows={data.data.scenarios} resource="scenarios" edit={setEditor}/>{data.data.scenarios.filter(s=>s.status==='active').map(s=><section key={s.id}><h2>{String(s.title)}</h2><Forecast data={data} scenario={s}/></section>)}</>:null}
 {['investments','allocation'].includes(view)?<><Records rows={data.data.investments} resource="investments" edit={setEditor}/>{data.data.investments.filter(i=>!['spent','cancelled'].includes(String(i.status))).map(i=>{const c=String(i.currency),f=buildCashflowForecast(data.opening,data.entries.filter(e=>!(e.sourceType==='investment'&&e.sourceId===i.id)),data.today).find(f=>f.currency===c),buffer=data.buffer.find(b=>b.currency===c)?.target??null;return <article className="financial-row" key={i.id}><strong>{String(i.title)}</strong><span>{money(Number(i.amount),c)} · {words(i.priority)} · {String(i.target_date??'No date')}</span><small>{evaluateInvestmentAffordability(Number(i.amount),data.opening[c]??null,f?.lowest??null,buffer)} — review only, never automatic approval.</small></article>})}</>:null}
 {view==='risks'?<Risks data={data}/>:null}
 {view==='goals'?<section><h2>Financial goals</h2><p>Use existing Goals for cash reserves, collections, or spending targets, then link the goal to a budget or investment.</p><Link className="button button--outline" href="/goals">Open Goals</Link><Link className="button button--ghost" href="/financial-control/links">Link financial context</Link></section>:null}
 {view.startsWith('review/')?<section><h2>{view.endsWith('monthly')?'Monthly':'Quarterly'} finance review</h2><p>{(view.endsWith('monthly')?data.monthly:data.quarterly).start} – {data.today}</p><Cash data={data}/>{(view.endsWith('monthly')?data.monthly:data.quarterly).bridge.map(b=><Metrics key={b.currency} currency={b.currency} values={{Invoiced:b.invoiced,Collected:b.collected,'Recorded expenses':b.recordedExpenses,Outstanding:b.outstanding}}/>)}<Risks data={data}/><Link href="/decisions">Record a financial decision</Link><p className="dataset-note">{data.monthly.basis}</p></section>:null}
 <footer className="financial-basis"><p className="eyebrow">Data basis</p>{data.limitations.map(t=><p key={t}>{t}</p>)}</footer></>}
 {editor?<FinancialEditor key={editor.resource+String(editor.row?.id)} resource={editor.resource} row={editor.row} onClose={()=>setEditor(null)} onSaved={async()=>{setEditor(null);showToast('Financial record saved.');await load();}}/>:null}</main>;
}
function Cash({data}:{data:Overview}){return <section><h2>Cash position</h2>{data.cash.length?data.cash.map(a=><article className="financial-row" key={a.id}><strong>{a.name}</strong><span>{money(a.balance,a.currency)}</span><small>{a.asOf?`Manually recorded ${new Date(a.asOf).toLocaleString()}${a.stale?' · Balance needs refresh':''}`:'Balance not recorded'}</small></article>):<p>No cash accounts yet. Record balances to establish a cash forecast.</p>}</section>;}
function Metrics({currency,values}:{currency:string;values:Record<string,number|null>}){return <dl className="financial-metrics">{Object.entries(values).map(([k,v])=><div key={k}><dt>{k}</dt><dd>{money(v,currency)}</dd></div>)}</dl>;}
function Forecast({data,scenario}:{data:Overview;scenario?:FinancialRow}){const forecast=scenario?buildCashflowForecast(data.opening,applyFinancialScenario(data.entries,scenario,data.today),data.today):data.forecasts;return <section><h2>30 / 60 / 90 day outlook</h2>{forecast.map(f=><div key={f.currency}><p>{f.currency} · lowest projected {money(f.lowest,f.currency)}</p><div className="financial-buckets">{f.buckets.map((b,n)=><article key={b.start}><p className="eyebrow">{n*30+1}–{(n+1)*30} days</p><small>{b.start} – {b.end}</small><Metrics currency={f.currency} values={{Opening:b.opening,Inflows:b.inflows,Outflows:b.outflows,Closing:b.closing}}/></article>)}</div>{f.undated.length?<p className="dataset-note">{f.undated.length} entries have no expected date and are excluded.</p>:null}</div>)}</section>;}
function EntryList({data,direction,limit}:{data:Overview;direction?:'in'|'out';limit?:number}){return <div>{data.entries.filter(e=>!direction||e.direction===direction).slice(0,limit??data.entries.length).map(e=><article className="financial-row" key={e.key}><strong>{e.title}</strong><span>{money(e.amount,e.currency)} · {e.direction==='in'?'Inflow':'Outflow'} · {e.confidence}</span><small>{e.date??'Date unavailable'} · {e.assumption}</small><Link href={e.route}>Open source</Link></article>)}</div>;}
function Risks({data}:{data:Overview}){return <section><h2>Financial risks</h2>{data.risks.length?data.risks.slice(0,12).map(r=><article className="financial-row" key={r.key}><strong>{r.title} · {r.severity}</strong><span>{r.evidence}</span><small>{money(r.amount,r.currency)}</small><Link href={r.route}>{r.action}</Link></article>):<p>No high-confidence financial risk detected from current records.</p>}</section>;}
function Records({rows,resource,edit}:{rows:FinancialRow[];resource:FinancialResource;edit:(v:{resource:FinancialResource;row:FinancialRow})=>void}){return <section>{rows.length?rows.map(r=><article id={'record-'+r.id} className="financial-row" key={r.id}><strong>{String(r.title??r.name??r.category??r.currency??words(resource))}</strong><span>{r.amount!=null?money(Number(r.amount),String(r.currency??'')):''} · {words(r.status)}</span><small>{String(r.due_at??r.target_date??r.promised_date??r.period_end??'')}{r.notes?` · ${String(r.notes)}`:''}</small>{resource!=='links'?<Button emphasis="ghost" onClick={()=>edit({resource,row:r})}>Edit</Button>:<span>Context reference saved</span>}</article>):<p className="dataset-note">No {words(resource)} recorded yet.</p>}</section>;}
function FinancialEditor({resource,row,onClose,onSaved}:{resource:FinancialResource;row?:FinancialRow;onClose:()=>void;onSaved:()=>Promise<void>}) {
 const [values,setValues]=useState<Record<string,unknown>>(()=>Object.fromEntries(financialFields[resource].map(f=>[f.key,row?.[f.key]??(f.options?f.options[0]:f.type==='checkbox'?false:['collection_delay_days','inflow_change_percent','outflow_change_percent','monthly_cost','setup_cost'].includes(f.key)?0:f.key==='stale_days'?7:f.key==='concentration_threshold'?.5:'')])));
 const [error,setError]=useState(''),[busy,setBusy]=useState(false);const request=useRef(crypto.randomUUID());
 async function save(e:React.FormEvent){e.preventDefault();if(busy)return;setBusy(true);setError('');try{const input:Record<string,unknown>={};for(const f of financialFields[resource]){const value=values[f.key];input[f.key]=value===''?(f.required?'':null):f.type==='number'?Number(value):f.type==='datetime-local'?new Date(String(value)).toISOString():value;}if(resource==='snapshots')input.request_id=request.current;const parsed=validateFinancialRecord(resource,input);const r=await fetch('/api/financial-control/'+resource+(row?.id?'/'+row.id:''),{method:row?.id?'PATCH':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(parsed)});const b=await r.json();if(!r.ok)throw new Error(b.error??'Save failed.');await onSaved();}catch(e){setError(e instanceof Error?e.message:'Check the form and try again.');}finally{setBusy(false);}}
 return <Modal open onClose={busy?()=>{}:onClose} title={`${row?.id?'Edit':'New'} ${words(resource)}`} description={resource==='scenarios'?'Hypothetical assumptions only. No live records will change.':undefined}><form noValidate className="simple-form financial-form" onSubmit={save}>{financialFields[resource].map(f=><FinancialInput key={f.key} field={f} values={values} change={v=>setValues(old=>({...old,[f.key]:v}))}/>)}{error?<p role="alert" className="field-error">{error}</p>:null}<div className="modal__actions"><Button disabled={busy} emphasis="ghost" onClick={onClose}>Cancel</Button><Button disabled={busy} intent="brand" type="submit">{busy?'Saving…':'Save'}</Button></div></form></Modal>;
}
function FinancialInput({field:f,values,change}:{field:FinancialField;values:Record<string,unknown>;change:(v:unknown)=>void}){const value=values[f.key];if(f.type==='reference'){const type=f.reference==='dynamic'?String(values[f.key==='source_id'?'source_type':f.key==='scope_id'?'scope_type':f.key==='origin_id'?'origin_type':'target_type']??''):f.reference!;return <FinancialReference key={f.key+type} field={f} type={type} value={String(value??'')} change={change}/>;}return <label>{f.label}{f.options?<select value={String(value??'')} onChange={e=>change(e.target.value)}>{f.options.map(o=><option key={o} value={o}>{words(o)||'None'}</option>)}</select>:f.type==='textarea'?<textarea className="resize-none" rows={4} value={String(value??'')} onChange={e=>change(e.target.value)}/>:f.type==='checkbox'?<input type="checkbox" checked={Boolean(value)} onChange={e=>change(e.target.checked)}/>:<input type={f.type??'text'} step={f.type==='number'?'any':undefined} required={f.required} value={String(value??'')} onChange={e=>change(e.target.value)}/>} {f.help?<small>{f.help}</small>:null}</label>;}
function FinancialReference({field,type,value,change}:{field:FinancialField;type:string;value:string;change:(v:unknown)=>void}){const [query,setQuery]=useState(''),[items,setItems]=useState<{id:string;label:string}[]>([]),[error,setError]=useState('');useEffect(()=>{if(!type||type==='custom')return;const controller=new AbortController();const timer=setTimeout(async()=>{try{const r=await fetch('/api/financial-control/options?type='+type+'&q='+encodeURIComponent(query),{signal:controller.signal});const b=await r.json();if(!r.ok)throw new Error(b.error);setItems(b.items);setError('');}catch(e){if(!controller.signal.aborted)setError(e instanceof Error?e.message:'Records unavailable');}},250);return()=>{clearTimeout(timer);controller.abort();};},[type,query]);return <fieldset><legend>{field.label}</legend><label>Search records<input value={query} onChange={e=>setQuery(e.target.value)}/></label>{query?<Button emphasis="ghost" onClick={()=>setQuery('')}>Clear search</Button>:null}<label>Select record<select value={value} onChange={e=>change(e.target.value)}><option value="">None</option>{value&&!items.some(i=>i.id===value)?<option value={value}>Previously selected record</option>:null}{items.map(i=><option key={i.id} value={i.id}>{i.label}</option>)}</select></label>{!items.length?<p>No records available.</p>:null}{error?<p className="field-error">{error}</p>:null}</fieldset>;}

function FinancialLinks({rows,refresh}:{rows:FinancialRow[];refresh:()=>Promise<void>}){const[removing,setRemoving]=useState<FinancialRow|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');return <section><h2>Linked financial context</h2>{rows.map(row=>{const origin=row.origin as FinancialRow|null,target=row.target as FinancialRow|null;return <article className="financial-row" key={row.id}><strong>{String(origin?.title??'Unavailable financial record')}</strong><small>{words(row.target_type)}</small>{target?<Link href={String(target.route)}>{String(target.title??'Open record')}</Link>:<span>Related record unavailable</span>}<Button emphasis="ghost" onClick={()=>setRemoving(row)}>Remove link</Button></article>})}{removing?<Modal open title="Remove context link?" onClose={()=>!busy&&setRemoving(null)} description="Both records remain unchanged. Only this relationship is removed."><div className="modal__actions"><Button disabled={busy} onClick={()=>setRemoving(null)}>Keep link</Button><Button disabled={busy} onClick={async()=>{setBusy(true);try{const r=await fetch('/api/financial-control/links/'+removing.id,{method:'DELETE'});if(!r.ok)throw new Error('Link could not be removed.');setRemoving(null);await refresh();}catch(e){setError(e instanceof Error?e.message:'Remove failed.');}finally{setBusy(false);}}}>Remove link</Button></div>{error?<p role="alert">{error}</p>:null}</Modal>:null}</section>;}
