import type { FinancialResource } from '@/lib/financial-schema';
export type FinancialField={key:string;label:string;type?:'number'|'date'|'datetime-local'|'textarea'|'checkbox'|'reference';options?:string[];reference?:string;required?:boolean;help?:string};
const name:FinancialField={key:'name',label:'Name',required:true},title:FinancialField={key:'title',label:'Title',required:true},amount:FinancialField={key:'amount',label:'Amount',type:'number',required:true},currency:FinancialField={key:'currency',label:'Currency (three letters)',required:true},notes:FinancialField={key:'notes',label:'Notes',type:'textarea'};
const status=(options:string[]):FinancialField=>({key:'status',label:'Status',options});
const ref=(key:string,label:string,reference:string,required=false):FinancialField=>({key,label,reference,required,type:'reference'});
const priority:FinancialField={key:'priority',label:'Priority',options:['low','medium','high','critical']};
export const financialFields:Record<FinancialResource,FinancialField[]>={
 accounts:[name,{key:'type',label:'Account type',options:['bank','cash','processor','wallet','other']},currency,status(['active','inactive','archived']),notes],
 snapshots:[ref('cash_account_id','Cash account','account',true),currency,{key:'balance',label:'Recorded balance',type:'number',required:true},{key:'as_of',label:'Balance as of',type:'datetime-local',required:true},notes],
 obligations:[title,amount,currency,{key:'due_at',label:'Due date',type:'date',required:true},status(['planned','committed','due','paid','deferred','cancelled']),{key:'criticality',label:'Criticality',options:['optional','standard','critical']},{key:'category',label:'Category',required:true},{key:'can_delay',label:'Can delay',type:'checkbox'},{key:'paid_at',label:'Actual paid date',type:'date',help:'Only record a payment that already occurred. This does not create a ledger payment.'},ref('expense_id','Reconciled expense','expense'),{key:'source_type',label:'Source type',options:['','supplier_order','subscription','investment','project','process']},ref('source_id','Source record','dynamic'),ref('owner_person_id','Review owner','person'),notes],
 budgets:[name,amount,currency,{key:'period_start',label:'Period start',type:'date',required:true},{key:'period_end',label:'Period end',type:'date',required:true},{key:'scope_type',label:'Scope',options:['custom','company','project','campaign','roadmap','process']},ref('scope_id','Scope record','dynamic'),{key:'category',label:'Expense category (optional)'},status(['draft','active','closed','archived']),ref('owner_person_id','Budget owner','person'),notes],
 budget_lines:[ref('budget_id','Budget','budget',true),{key:'category',label:'Category',required:true},amount],
 scenarios:[title,{key:'type',label:'Scenario type',options:['base','best','stress','custom']},currency,{key:'collection_delay_days',label:'Collection delay (days)',type:'number'},{key:'inflow_change_percent',label:'Inflow change (%)',type:'number'},{key:'outflow_change_percent',label:'Outflow change (%)',type:'number'},{key:'monthly_cost',label:'Hypothetical monthly cost',type:'number'},{key:'setup_cost',label:'One-time setup/emergency cost',type:'number'},{key:'starts_at',label:'Cost start date',type:'date'},{key:'include_pipeline',label:'Include possible pipeline (hypothetical)',type:'checkbox'},status(['active','archived']),notes],
 investments:[title,amount,currency,{key:'target_date',label:'Target date',type:'date'},priority,status(['idea','considering','approved','scheduled','spent','cancelled']),ref('commitment_id','Strategic commitment','commitment'),ref('expense_id','Reconciled expense','expense'),notes],
 promises:[ref('invoice_id','Invoice','invoice',true),amount,currency,{key:'promised_date',label:'Promised date',type:'date',required:true},status(['open','met','missed','cancelled']),notes],
 settings:[currency,{key:'buffer_amount',label:'Fixed minimum cash buffer',type:'number'},{key:'buffer_months',label:'Or months of baseline costs',type:'number'},{key:'baseline_monthly_cost',label:'Known baseline monthly cost',type:'number'},{key:'cash_history_complete_from',label:'Verified complete cash settlement history from',type:'date',help:'Only confirm if all cash inflows are in Payments and all cash outflows are represented by paid obligations. Expenses alone are insufficient.'},{key:'stale_days',label:'Balance stale after days',type:'number'},{key:'concentration_threshold',label:'Concentration threshold (0–1)',type:'number'},notes],
 subscription_reviews:[ref('subscription_id','Subscription','subscription',true),status(['unknown','keep','review','cancel_candidate']),{key:'reviewed_at',label:'Usage reviewed on',type:'date'},{key:'criticality',label:'Criticality',options:['optional','standard','critical']},ref('owner_person_id','Review owner','person'),notes],
 links:[{key:'origin_type',label:'Financial record type',options:['account','budget','obligation','scenario','investment']},ref('origin_id','Financial record','dynamic',true),{key:'target_type',label:'Link to',options:['decision','goal','commitment','milestone','period','gate','topic','source','finding','brief','person','process','client','project','campaign','supplier','supplier_order','product','opportunity']},ref('target_id','Related record','dynamic',true)],
};
