'use client';
import Link from 'next/link';
import {useEffect,useMemo,useRef,useState,useSyncExternalStore,type ReactNode} from 'react';
import {Activity,ArrowRight,BookOpen,CalendarDays,CheckCircle2,ChevronRight,CircleAlert,Database,Download,FileText,Lightbulb,Plus,Search,ShieldCheck,Sparkles,Target,TriangleAlert,User,X,type LucideIcon} from 'lucide-react';
import {Area,AreaChart,CartesianGrid,Cell,Pie,PieChart,ResponsiveContainer,Tooltip,XAxis,YAxis} from 'recharts';
import {StyledSelect} from '@/components/ui/styled-select';
import type {Risk} from '@/lib/intelligence/types';
import {filterRisks,riskArea,riskTheme,riskTrend,risksCsv,severityColors,type RiskHistory} from '@/lib/intelligence/risk-dashboard';
import './risks-dashboard.css';

type RiskData={risks:Risk[];evaluatedAt:string;riskHistory:RiskHistory[];riskHistoryAvailable:boolean};
const label=(value:string)=>value.charAt(0).toUpperCase()+value.slice(1);
const date=(value?:string|null)=>value?new Date(value).toLocaleDateString('en',{month:'short',day:'numeric',year:'numeric'}):'Not recorded';
const subscribeMobile=(fn:()=>void)=>{const media=window.matchMedia('(max-width: 950px)');media.addEventListener('change',fn);return()=>media.removeEventListener('change',fn);};
function Badge({severity}:{severity:string}){return <span className={`rd-badge rd-${severity}`}><i/>{label(severity)}</span>;}
function IconBox({icon:Icon,tone='purple'}:{icon:LucideIcon;tone?:string}){return <span className={`rd-icon tone-${tone}`}><Icon size={23}/></span>;}
function Panel({title,subtitle,icon:Icon,action,children}:{title:string;subtitle?:string;icon:LucideIcon;action?:ReactNode;children:ReactNode}){return <section className="rd-panel"><header><IconBox icon={Icon}/><div><h2>{title}</h2>{subtitle&&<p>{subtitle}</p>}</div>{action}</header>{children}</section>;}
function Score({risk,large=false}:{risk:Risk;large?:boolean}) {
  const value = Math.min(100, Math.max(0, risk.score ?? 0));
  return large ? <div className="rd-score-ring" role="img" aria-label={`Priority score ${risk.score ?? 'unavailable'} out of 100`}>
    <div className="rd-score-ring__chart" aria-hidden="true"><ResponsiveContainer width="100%" height="100%"><PieChart margin={{top:0,right:0,bottom:0,left:0}} accessibilityLayer={false}>
      <Pie data={[{value:100}]} dataKey="value" cx="50%" cy="50%" innerRadius="80%" outerRadius="98%" stroke="none" fill="var(--rd-score-track)" isAnimationActive={false}/>
      <Pie data={[{value},{value:100-value}]} dataKey="value" cx="50%" cy="50%" innerRadius="80%" outerRadius="98%" startAngle={90} endAngle={-270} cornerRadius={20} stroke="none" isAnimationActive={false}><Cell fill={severityColors[risk.severity]}/><Cell fill="transparent"/></Pie>
    </PieChart></ResponsiveContainer></div>
    <div className="rd-score-ring__value"><strong>{risk.score ?? '—'}</strong><small>/ 100</small></div>
  </div> : <div className={`rd-score rd-score-${risk.severity}`}><small>Risk score</small><strong>{risk.score??'—'}<span>/100</span></strong><progress max={100} value={value} style={{accentColor:severityColors[risk.severity]}}/></div>;
}
export function RisksDashboard(){
 const [data,setData]=useState<RiskData|null>(null),[error,setError]=useState(''),[attempt,setAttempt]=useState(0);
 const [search,setSearch]=useState(''),[severity,setSeverity]=useState('all'),[area,setArea]=useState('all'),[sort,setSort]=useState('newest'),[period,setPeriod]=useState('30'),[selected,setSelected]=useState<string|null>(null),[allEvidence,setAllEvidence]=useState(false),[exported,setExported]=useState(false);
 const detailRef=useRef<HTMLElement>(null),trigger=useRef<HTMLElement|null>(null);
 const mobile=useSyncExternalStore(subscribeMobile,()=>window.matchMedia('(max-width: 950px)').matches,()=>false);
 useEffect(()=>{const controller=new AbortController();fetch('/api/intelligence/overview',{cache:'no-store',signal:controller.signal}).then(async r=>{const json=await r.json();if(!r.ok)throw new Error(json.error??'Unable to load risks.');return json;}).then(setData).catch(e=>{if(e.name!=='AbortError')setError(e.message);});return()=>controller.abort();},[attempt]);
 const risks=useMemo(()=>data?.risks??[],[data]);
 const rows=useMemo(()=>filterRisks(risks,search,severity,area,sort),[risks,search,severity,area,sort]);
 const selectedRisk=risks.find(r=>r.key===selected);
 const areas=[...new Set(risks.map(r=>riskArea(r.entityType)))];
 const distribution=['low','medium','high','critical'].map(name=>({name,value:risks.filter(r=>r.severity===name).length}));
 const trend=riskTrend(data?.riskHistory??[],Number(period),data?.evaluatedAt??new Date().toISOString());
 const group=(fn:(r:Risk)=>string)=>Object.entries(risks.reduce<Record<string,number>>((all,r)=>{const key=fn(r);all[key]=(all[key]??0)+1;return all;},{})).sort((a,b)=>b[1]-a[1]);
 const themes=group(r=>riskTheme(r.entityType)),affected=group(r=>riskArea(r.entityType));
 const open=(risk:Risk)=>{trigger.current=document.activeElement as HTMLElement;setSelected(risk.key);setAllEvidence(false);};
 useEffect(()=>{if(!selected)return;detailRef.current?.querySelector<HTMLButtonElement>('[aria-label="Close risk details"]')?.focus({preventScroll:true});const listener=(e:KeyboardEvent)=>{if(e.key==='Escape')setSelected(null);if(e.key==='Tab'&&window.matchMedia('(max-width: 950px)').matches){const items=[...detailRef.current?.querySelectorAll<HTMLElement>('button,a[href],select')??[]].filter(el=>!el.hasAttribute('disabled'));if(e.shiftKey&&document.activeElement===items[0]){e.preventDefault();items.at(-1)?.focus();}else if(!e.shiftKey&&document.activeElement===items.at(-1)){e.preventDefault();items[0]?.focus();}}};document.addEventListener('keydown',listener);return()=>{document.removeEventListener('keydown',listener);trigger.current?.focus({preventScroll:true});};},[selected]);
 const exportCsv=()=>{const url=URL.createObjectURL(new Blob(['\uFEFF'+risksCsv(rows)],{type:'text/csv;charset=utf-8;'}));const a=document.createElement('a');a.href=url;a.download=`risk-signals-${new Date().toISOString().slice(0,10)}.csv`;a.click();URL.revokeObjectURL(url);setExported(true);};
 const metrics=[{name:'Total signals',value:risks.length,icon:Activity,tone:'purple',filter:'all'},{name:'Critical',value:distribution[3].value,icon:TriangleAlert,tone:'critical',filter:'critical'},{name:'High',value:distribution[2].value,icon:Target,tone:'high',filter:'high'},...(distribution[1].value?[{name:'Medium',value:distribution[1].value,icon:CircleAlert,tone:'medium',filter:'medium'}]:[]),{name:'Low',value:distribution[0].value,icon:ShieldCheck,tone:'low',filter:'low'},{name:'Affected areas',value:areas.length,icon:Database,tone:'blue',filter:'all'}];
 return <div className="risks-dashboard"><header className="rd-heading"><div><nav aria-label="Breadcrumb"><span>INTELLIGENCE</span><span>/</span><strong>RISKS</strong></nav><h1>Risks</h1><p>Calm, evidence-based signals from your current workspace.</p></div><div className="rd-heading-actions"><button onClick={exportCsv} disabled={!data||!!error}><Download size={17}/>Export</button><Link className="rd-primary" href="/risks?view=register&new=1"><Plus size={18}/>Add risk signal</Link></div></header>
 <div className={`rd-layout ${selectedRisk?'has-detail':''}`}><div className="rd-content" inert={mobile&&Boolean(selectedRisk)}><nav className="rd-tabs" aria-label="Risk views"><Link aria-current="page" href="/risks">Signals</Link><Link href="/risks?view=register">Register</Link><Link href="/risks?view=patterns">Executive patterns</Link></nav>
 {error?<div className="rd-empty" role="alert"><CircleAlert/><h2>Risk signals unavailable</h2><p>{error}</p><button onClick={()=>{setError('');setData(null);setAttempt(n=>n+1);}}>Try again</button></div>:!data?<div className="rd-empty" role="status">Reviewing your current workspace…</div>:<>
 <section className="rd-metrics" aria-label="Risk summary" style={{gridTemplateColumns:`repeat(${metrics.length},minmax(0,1fr))`}}>{metrics.map(m=><button key={m.name} className="rd-metric" onClick={()=>{setSeverity(m.filter);if(m.name==='Affected areas')setArea('all');}}><IconBox icon={m.icon} tone={m.tone}/><div><small>{m.name}</small><strong>{m.value}</strong><span>Current workspace</span></div></button>)}</section>
 <div className="rd-filters"><label><Search size={18}/><input placeholder="Search risks, projects, clients…" aria-label="Search risks" value={search} onChange={e=>setSearch(e.target.value)}/></label><StyledSelect label="Filter risk severity" value={severity} onChange={setSeverity} options={[{value:'all',label:'All severity'},...['low','medium','high','critical'].map(value=>({value,label:label(value)}))]}/><StyledSelect label="Filter impacted area" value={area} onChange={setArea} options={[{value:'all',label:'All areas'},...areas.map(value=>({value,label:value}))]}/><StyledSelect label="Sort risk signals" value={sort} onChange={setSort} options={[{value:'newest',label:'Sort: Newest'},{value:'score',label:'Sort: Highest score'},{value:'title',label:'Sort: Name'}]}/></div>
 <section className="rd-signals" aria-label="Risk signals">{rows.map(r=><article key={r.key} className={`rd-risk ${selected===r.key?'is-selected':''}`} onClick={()=>open(r)}><IconBox icon={r.entityType==='project'?Target:Database}/><div className="rd-risk-copy"><button onClick={e=>{e.stopPropagation();open(r);}} aria-expanded={selected===r.key} aria-label={`View risk: ${r.title}`}><h2>{r.title}</h2></button><p>{r.reason}</p><div className="rd-chips">{r.evidence.slice(0,2).map((e,i)=><span key={i}>{e.label}</span>)}{r.evidence.length>2&&<button onClick={e=>{e.stopPropagation();open(r);setAllEvidence(true);}}>+{r.evidence.length-2} more</button>}</div></div><Badge severity={r.severity}/><Score risk={r}/><div className="rd-area"><small>Impacted area</small><span><Database size={14}/>{riskArea(r.entityType)}</span><small>Updated {date(r.updatedAt)}</small></div><Link onClick={e=>e.stopPropagation()} href={r.route} className="rd-action">{r.recommendedAction}<ArrowRight size={15}/></Link><button className="rd-expand" aria-label={`Open ${r.title} details`} onClick={e=>{e.stopPropagation();open(r);}}><ChevronRight size={17}/></button></article>)}{!rows.length&&<div className="rd-empty"><ShieldCheck size={31}/><h2>{risks.length?'No signals match your filters':'No meaningful risks detected'}</h2><p>{risks.length?'Try another severity, area, or search term.':'Signals will appear when current workspace evidence warrants attention.'}</p>{risks.length>0&&<button onClick={()=>{setSearch('');setSeverity('all');setArea('all');}}>Clear filters</button>}</div>}</section>
 <div className="rd-charts"><Panel title="Risk trend" subtitle="Saved workspace signal snapshots" icon={Sparkles} action={<StyledSelect label="Risk trend period" value={period} onChange={setPeriod} options={[{value:'7',label:'Last 7 days'},{value:'30',label:'Last 30 days'},{value:'90',label:'Last 90 days'}]}/>}><div className="rd-trend">{trend.length?<ResponsiveContainer width="100%" height="100%"><AreaChart data={trend} margin={{left:-25,right:10,top:12,bottom:0}}><CartesianGrid stroke="#eeeefa"/><XAxis dataKey="date" tickFormatter={v=>new Date(v).toLocaleDateString('en',{month:'short',day:'numeric'})} tick={{fontSize:10,fill:'#7b87ac'}} axisLine={false} tickLine={false}/><YAxis allowDecimals={false} tick={{fontSize:10,fill:'#7b87ac'}} axisLine={false} tickLine={false}/><Tooltip labelFormatter={v=>date(String(v))}/><Area dataKey="total" name="Recorded signals" stroke="#8650ff" fill="#ece3ff" strokeWidth={2} dot={{r:3}} isAnimationActive={false}/></AreaChart></ResponsiveContainer>:<div className="rd-trend-empty"><Activity size={25}/><strong>{data.riskHistoryAvailable?'No saved snapshots in this period':'History is unavailable'}</strong><p>Current signals are shown above. A trend appears when dated snapshots are available.</p></div>}</div>{trend.length>0&&<p className="rd-chart-note">Recorded dates only; days without snapshots are not treated as zero.</p>}</Panel><Panel title="Risk by severity" icon={Sparkles}><div className="rd-distribution"><div className="rd-donut" role="img" aria-label={distribution.map(d=>`${d.name}: ${d.value}`).join(', ')}><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={risks.length?distribution:[{name:'empty',value:1}]} dataKey="value" innerRadius="72%" outerRadius="96%" stroke="none" isAnimationActive={false}>{(risks.length?distribution:[{name:'empty'}]).map(d=><Cell key={d.name} fill={severityColors[d.name]??'#e7e9f2'}/>)}</Pie></PieChart></ResponsiveContainer><div><strong>{risks.length}</strong><span>Signals</span></div></div><div className="rd-legend">{distribution.map(d=><button key={d.name} onClick={()=>setSeverity(d.name)}><i style={{background:severityColors[d.name]}}/>{label(d.name)}<strong>{d.value}</strong><span>{risks.length?Math.round(d.value/risks.length*100):0}%</span></button>)}</div></div></Panel></div>
 <div className="rd-bottom"><Panel title="Top risk themes" subtitle="Recurring themes across your workspace" icon={FileText}>{themes.length?themes.map(([name,count],i)=><div className="rd-rank" key={name}><span>{i+1}</span><strong>{name}</strong><progress value={count} max={risks.length}/><b>{count}</b><small>{Math.round(count/risks.length*100)}%</small></div>):<p className="rd-muted">No recurring themes detected.</p>}</Panel><Panel title="Most affected areas" subtitle="Areas with the most current signals" icon={Database}>{affected.length?affected.map(([name,count],i)=><button className="rd-rank" key={name} onClick={()=>setArea(name)}><span>{i+1}</span><strong>{name}</strong><progress value={count} max={risks.length}/><b>{count}</b><small>{Math.round(count/risks.length*100)}%</small></button>):<p className="rd-muted">No affected areas.</p>}</Panel></div><footer className="rd-footer"><span>Evaluated {date(data.evaluatedAt)} · Scores reflect rule-based priority, not probability.</span><span role="status">{exported?'Filtered signals exported as CSV.':`${rows.length} of ${risks.length} signals`}</span></footer>
 </>}
 </div>{selectedRisk&&<><button className="rd-scrim" aria-label="Close risk overview" onClick={()=>setSelected(null)}/><aside ref={detailRef} className="rd-detail" role={mobile?'dialog':'region'} aria-modal={mobile?true:undefined} aria-label={`${selectedRisk.title} risk details`}><header><IconBox icon={selectedRisk.entityType==='project'?Target:Database}/><div><h2>{selectedRisk.title}</h2><p>{selectedRisk.reason}</p></div><button aria-label="Close risk details" onClick={()=>setSelected(null)}><X size={18}/></button></header><div className="rd-detail-badge"><Badge severity={selectedRisk.severity}/></div><div className="rd-detail-stats"><section><Score risk={selectedRisk} large/><span>Risk score<small>Rule-based priority</small></span></section><section><small>Impacted area</small><div><IconBox icon={Database}/><span><strong>{riskArea(selectedRisk.entityType)}</strong><small>1 {selectedRisk.entityType}</small></span></div></section></div><section className="rd-evidence"><header><IconBox icon={FileText}/><h3>Evidence <span>{selectedRisk.evidence.length}</span></h3>{selectedRisk.evidence.length>3&&<button onClick={()=>setAllEvidence(!allEvidence)}>{allEvidence?'Show less':'View all'}<ArrowRight size={13}/></button>}</header>{selectedRisk.evidence.slice(0,allEvidence?undefined:3).map((item,i)=><Link key={i} href={selectedRisk.route}><IconBox icon={i===0?Activity:i===1?CheckCircle2:FileText}/><span><strong>{item.label}</strong><small>{item.value??'Derived from current workspace records'}</small></span><ChevronRight size={15}/></Link>)}</section><section className="rd-why"><BookOpen size={23}/><div><h3>Why this matters</h3><p>{selectedRisk.entityType==='client'?'Unresolved commitments can delay client work and weaken trust. Review the evidence and confirm what needs follow-up.':selectedRisk.entityType==='project'?'Delivery signals help identify blocked or overdue work before it affects the next milestone.':selectedRisk.entityType==='fitness'?'Review your remaining target against the time and capacity available.':'Unresolved signals can affect planned outcomes. Review the source before deciding what to change.'}</p></div></section><section className="rd-next"><header><IconBox icon={Lightbulb}/><div><h3>Recommended next action</h3><p>{selectedRisk.recommendedAction}</p></div></header><Link className="rd-primary" href={selectedRisk.route}>{selectedRisk.recommendedAction}<ArrowRight size={16}/></Link></section><div className="rd-detail-meta"><div><IconBox icon={User}/><span>Ownership<Link href={selectedRisk.route}>See source record</Link></span></div><div><IconBox icon={CalendarDays}/><span>Source updated<strong>{date(selectedRisk.updatedAt)}</strong></span></div></div></aside></>}</div></div>;
}
