"use client";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { useState, type FormEvent } from "react";
import { UserRound, ShieldCheck, Bell, Link2, Building2, Target, Sun, Moon, CalendarDays, ChevronRight, Pencil, LockKeyhole, Check, Globe2, Clock3, Monitor, ArrowUpRight, Mail } from "lucide-react";
import { Modal } from "@/components/ui/modal";
import { Button } from "@/components/ui/button";
import { useSettingsProfile } from "./settings-shell";
import { setTheme, useTheme } from "@/lib/theme-store";
import { createClient } from "@/lib/supabase/client";

const cards = [
  { title: "Personal information", detail: "Manage your name and personal details used across Daily Command.", icon: UserRound, tone: "violet", href: "", action: "Edit" },
  { title: "Account security", detail: "Update your password and review your sign-in details to keep your account secure.", icon: ShieldCheck, tone: "blue", href: "/settings/security", action: "Manage" },
  { title: "Notifications", detail: "Choose which signals deserve your attention and how serious they need to be.", icon: Bell, tone: "orange", href: "/settings/notifications", action: "Configure" },
  { title: "Connected apps", detail: "Connect your calendar, mail, files, code, and fitness services.", icon: Link2, tone: "green", href: "/settings/integrations", action: "Manage" },
  { title: "Business preferences", detail: "Configure your business operating preferences and workspace defaults.", icon: Building2, tone: "violet", href: "/settings/workspace", action: "Manage" },
  { title: "Chief of Staff settings", detail: "Review autonomy, action safety, and how Daily Command supports you.", icon: Target, tone: "pink", href: "/settings/chief-of-staff", action: "Manage" },
  { title: "Appearance", detail: "Choose a comfortable theme for your workspace, day or night.", icon: Sun, tone: "amber", href: "/settings/appearance", action: "Customize" },
  { title: "Calendar integration", detail: "Connect and manage your calendar to power your schedule and daily planning.", icon: CalendarDays, tone: "blue", href: "/settings/integrations", action: "Manage" },
];
async function saveProfile(values: Record<string, string | number>) {
  const response = await fetch("/api/settings/profile", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify(values) });
  const body = await response.json(); if (!response.ok) throw new Error(body.error || "Your changes could not be saved.");
}
function Heading({ title, detail }: { title: string; detail: string }) { return <div className="settings-section-heading"><h2>{title}</h2><p>{detail}</p></div>; }
function Feedback({ error, message }: { error: string; message: string }) { return <>{error && <p className="field-error" role="alert">{error}</p>}{message && <p className="settings-saved" role="status"><Check size={16}/>{message}</p>}</>; }
export function ProfileSettings() {
  const profile = useSettingsProfile(); const router = useRouter();
  const [editing, setEditing] = useState(false); const [name, setName] = useState(profile.name); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [message, setMessage] = useState("");
  const open = () => { setName(profile.name); setError(""); setEditing(true); };
  async function save(event: FormEvent) { event.preventDefault(); if (busy) return; setBusy(true); setError(""); try { await saveProfile({display_name:name}); setEditing(false); setMessage("Your profile has been updated."); router.refresh(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Could not save profile."); } finally { setBusy(false); } }
  return <><section className="settings-profile-banner"><div className="settings-avatar">{profile.name.split(/\s+/).slice(0,2).map(part=>part[0]).join("").toUpperCase()}</div><div className="settings-profile-name"><h2>{profile.name}</h2><p>{profile.email}</p><span className="settings-account-tag"><UserRound size={14}/>Personal workspace</span></div><div className="settings-banner-actions"><Button onClick={open}><Pencil size={17}/>Edit profile</Button><Link className="settings-button settings-button--accent" href="/settings/security"><LockKeyhole size={17}/>Change password</Link></div></section><Feedback error="" message={message}/><Heading title="Settings center" detail="Everything you need to customize your experience with Daily Command."/><div className="settings-center-grid">{cards.map(({title,detail,icon:Icon,tone,href,action})=>{const content=<><span className={`settings-icon ${tone}`}><Icon size={29}/></span><span className="settings-center-copy"><strong>{title}</strong><small>{detail}</small></span><span className="settings-card-action">{action}</span><ChevronRight size={17}/></>;return href?<Link className="settings-center-card" href={href} key={title}>{content}</Link>:<button className="settings-center-card" onClick={open} key={title}>{content}</button>})}</div><Modal open={editing} onClose={()=>{if(!busy)setEditing(false)}} title="Edit personal information" description="Your name appears throughout your workspace."><form className="settings-form" onSubmit={save}><label>Full name<input value={name} onChange={event=>setName(event.target.value)} required maxLength={100} autoComplete="name"/></label><label>Email address<input value={profile.email} readOnly type="email"/><small>Your sign-in email is managed by your authentication provider.</small></label><Feedback error={error} message=""/><div className="settings-form-actions"><Button type="button" onClick={()=>setEditing(false)} disabled={busy}>Cancel</Button><Button type="submit" intent="brand" disabled={busy}>{busy?"Saving…":"Save changes"}</Button></div></form></Modal></>;
}
export function PreferencesSettings() {
  const profile = useSettingsProfile(); const router = useRouter();
  const [timezone,setTimezone]=useState(profile.timezone); const [week,setWeek]=useState(profile.weekStartsOn); const [busy,setBusy]=useState(false); const [error,setError]=useState(""); const [message,setMessage]=useState("");
  const dirty=timezone!==profile.timezone||week!==profile.weekStartsOn;
  async function save(event:FormEvent){event.preventDefault(); if(busy)return;setBusy(true);setError("");setMessage("");try{await saveProfile({timezone,week_starts_on:week});router.refresh();setMessage("Your preferences have been saved.")}catch(reason){setError(reason instanceof Error?reason.message:"Could not save preferences.")}finally{setBusy(false)}}
  return <><Heading title="Preferences" detail="Set the personal defaults that make your workspace feel familiar."/><section className="settings-panel"><div className="settings-panel-heading"><span className="settings-icon blue"><Globe2 size={24}/></span><div><h3>Regional preferences</h3><p>Your saved profile defaults for time and weekly planning.</p></div></div><form className="settings-form" onSubmit={save}><div className="settings-form-grid"><label>Time zone<input list="settings-timezones" value={timezone} onChange={event=>{setTimezone(event.target.value);setMessage("")}} required/><datalist id="settings-timezones">{[...new Set([profile.timezone,"Africa/Casablanca","Europe/London","Europe/Paris","America/New_York","America/Los_Angeles","Asia/Dubai","Asia/Singapore","UTC"])].map(zone=><option value={zone} key={zone}/>)}</datalist><small>Use an IANA time zone, such as Africa/Casablanca.</small></label><label>First day of the week<select value={week} onChange={event=>{setWeek(Number(event.target.value));setMessage("")}}>{["Sunday","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"].map((day,index)=><option value={index} key={day}>{day}</option>)}</select><small>Saved to your profile for weekly planning.</small></label></div><Feedback error={error} message={message}/><div className="settings-form-footer"><small>{dirty?"You have unsaved changes.":"Your preferences are up to date."}</small><Button intent="brand" type="submit" disabled={!dirty||busy}>{busy?"Saving…":"Save preferences"}</Button></div></form></section><div className="settings-center-grid"><Link className="settings-center-card" href="/settings/notifications"><span className="settings-icon orange"><Bell/></span><span className="settings-center-copy"><strong>Protect your attention</strong><small>Fine-tune the signals that matter to you.</small></span><ChevronRight/></Link><Link className="settings-center-card" href="/settings/chief-of-staff"><span className="settings-icon pink"><Target/></span><span className="settings-center-copy"><strong>Your Chief of Staff</strong><small>Choose your level of assistance and autonomy.</small></span><ChevronRight/></Link></div></>;
}
export function AppearanceSettings() {
  const theme=useTheme(); const [message,setMessage]=useState("");
  return <><Heading title="Appearance" detail="A workspace that feels comfortable, wherever your day takes you."/><section className="settings-panel"><div className="settings-panel-heading"><span className="settings-icon amber"><Sun size={24}/></span><div><h3>Workspace theme</h3><p>Choose your preferred look. Changes apply immediately on this browser.</p></div></div><div className="settings-theme-options" role="group" aria-label="Workspace theme">{(["light","dark"] as const).map(value=><button key={value} className={`settings-theme-choice ${theme===value?"selected":""}`} aria-pressed={theme===value} onClick={()=>{setTheme(value);setMessage(`${value==="light"?"Light":"Dark"} theme applied.`)}}><span className={`settings-theme-swatch ${value}`}>{value==="light"?<Sun size={46}/>:<Moon size={46}/>}</span><span><strong>{value==="light"?"Light":"Dark"}</strong><small>{value==="light"?"Clear, calm, and bright":"A softer view for low light"}</small></span><span className="settings-theme-check">{theme===value?<Check size={19}/>:null}</span></button>)}</div><Feedback error="" message={message}/></section><section className="settings-panel settings-info-row"><Monitor size={25}/><div><h3>Designed for your screen</h3><p>Your layout adapts automatically to desktop, tablet, and mobile. System reduced-motion preferences are respected.</p></div></section></>;
}
export function SecuritySettings() {
  const profile=useSettingsProfile(); const [current,setCurrent]=useState(""); const [password,setPassword]=useState(""); const [confirm,setConfirm]=useState(""); const [busy,setBusy]=useState(false); const [error,setError]=useState(""); const [message,setMessage]=useState("");
  const emailProvider=profile.providers.includes("email");
  async function save(event:FormEvent){event.preventDefault();if(busy)return;setError("");setMessage("");if(password!==confirm){setError("The new passwords do not match.");return;}if(password===current){setError("Choose a password different from your current password.");return;}setBusy(true);try{const client=createClient();const verified=await client.auth.signInWithPassword({email:profile.email,password:current});if(verified.error)throw new Error("Your current password could not be verified.");const result=await client.auth.updateUser({password});if(result.error)throw result.error;setCurrent("");setPassword("");setConfirm("");setMessage("Your password has been updated.");}catch(reason){setError(reason instanceof Error?reason.message:"Your password could not be updated.")}finally{setBusy(false)}}
  return <><Heading title="Security" detail="Keep your account protected and understand how you sign in."/><div className="settings-security-summary"><section className="settings-panel settings-info-row"><span className="settings-icon blue"><ShieldCheck/></span><div><h3>Sign-in method</h3><p>{profile.providers.length?profile.providers.map(provider=>provider==="email"?"Email & password":provider[0].toUpperCase()+provider.slice(1)).join(", "):"Managed authentication"}</p></div></section><section className="settings-panel settings-info-row"><span className="settings-icon violet"><Clock3/></span><div><h3>Last sign-in</h3><p>{profile.lastSignIn?new Date(profile.lastSignIn).toLocaleDateString("en",{month:"long",day:"numeric",year:"numeric",timeZone:profile.timezone}):"Not available"}</p></div></section></div><section className="settings-panel"><div className="settings-panel-heading"><span className="settings-icon violet"><LockKeyhole size={24}/></span><div><h3>Change password</h3><p>Use a unique password that you don’t use for other accounts.</p></div></div>{emailProvider?<form className="settings-form" onSubmit={save}><label>Current password<input type="password" autoComplete="current-password" required value={current} onChange={event=>setCurrent(event.target.value)}/></label><div className="settings-form-grid"><label>New password<input type="password" autoComplete="new-password" minLength={12} required value={password} onChange={event=>setPassword(event.target.value)}/><small>Use at least 12 characters.</small></label><label>Confirm new password<input type="password" autoComplete="new-password" minLength={12} required value={confirm} onChange={event=>setConfirm(event.target.value)}/></label></div><Feedback error={error} message={message}/><div className="settings-form-footer"><small>Your current password is verified before saving.</small><Button type="submit" intent="brand" disabled={busy}>{busy?"Updating…":"Update password"}</Button></div></form>:<div className="settings-provider-note"><ShieldCheck size={24}/><div><h3>Your sign-in provider manages your password</h3><p>Change your password in your provider’s account settings. Daily Command never stores that password.</p>{profile.providers.includes("google")&&<a className="settings-button" href="https://myaccount.google.com/security" target="_blank" rel="noopener noreferrer">Google account security<ArrowUpRight size={16}/></a>}</div></div>}</section><section className="settings-panel settings-info-row"><span className="settings-icon green"><Mail/></span><div><h3>Account email</h3><p>{profile.email}</p><small>Managed by your sign-in provider.</small></div></section></>;
}
