"use client";

import { useCallback, useState } from "react";
import { Button } from "@/components/ui/button";
import { Modal } from "@/components/ui/modal";
import { useDeferredEffect } from "@/lib/use-deferred-effect";

type Product = { id: string; name: string; sku: string | null; category: string | null; currency: string; unit_cost: number | null; active: boolean; latest_inventory: { available_stock: number | null; reserved_stock: number | null; reorder_level: number | null; captured_at: string } | null };
const numberValue = (value: string) => value.trim() === "" ? null : Number(value);

export function FounderProducts() {
  const [products, setProducts] = useState<Product[] | null>(null); const [query, setQuery] = useState(""); const [editing, setEditing] = useState<Product | "new" | null>(null); const [stockProduct, setStockProduct] = useState<Product | null>(null); const [error, setError] = useState("");
  const load = useCallback(async () => { try { const response = await fetch("/api/founder/products", { cache: "no-store" }); const body = await response.json() as { products?: Product[]; error?: string }; if (!response.ok) throw new Error(body.error ?? "Products could not be loaded."); setProducts(body.products ?? []); setError(""); } catch (reason) { setError(reason instanceof Error ? reason.message : "Products could not be loaded."); } }, []);
  useDeferredEffect(useCallback(() => { void load(); }, [load]));
  const visible = (products ?? []).filter((product) => `${product.name} ${product.sku ?? ""} ${product.category ?? ""}`.toLocaleLowerCase().includes(query.toLocaleLowerCase()));
  return <div className="domain-page founder-page"><header className="page-header"><div><p className="eyebrow">Founder operations</p><h1>Products & inventory</h1><p>Normalized product references and manual inventory snapshots. They do not alter an external store.</p></div><Button onClick={() => setEditing("new")}>New product</Button></header>{error ? <section className="inline-error" role="alert"><p>{error}</p><Button emphasis="outline" onClick={() => void load()}>Try again</Button></section> : null}<section className="data-surface form-stack"><label htmlFor="product-search">Search products</label><input id="product-search" placeholder="Name, SKU, or category" value={query} onChange={(event) => setQuery(event.target.value)} />{products === null ? <p className="dataset-note">Loading products…</p> : visible.length ? visible.map((product) => <article className="founder-product-row" key={product.id}><div><strong>{product.name}</strong><span>{product.sku ? `${product.sku} · ` : ""}{product.category ?? "Uncategorized"} · {product.active ? "Active" : "Inactive"}</span><small>{product.latest_inventory ? `${product.latest_inventory.available_stock ?? "—"} available · captured ${new Date(product.latest_inventory.captured_at).toLocaleDateString()}` : "No inventory snapshot"}</small></div><div className="integration-actions"><Button emphasis="ghost" onClick={() => setStockProduct(product)}>Update stock</Button><Button emphasis="outline" onClick={() => setEditing(product)}>Edit</Button></div></article>) : <p className="dataset-note">No matching products. Add a normalized reference or adjust your search.</p>}</section>{editing ? <ProductModal product={editing === "new" ? null : editing} onClose={() => setEditing(null)} onSaved={async () => { setEditing(null); await load(); }} /> : null}{stockProduct ? <InventoryModal product={stockProduct} onClose={() => setStockProduct(null)} onSaved={async () => { setStockProduct(null); await load(); }} /> : null}</div>;
}

function ProductModal({ product, onClose, onSaved }: { product: Product | null; onClose: () => void; onSaved: () => Promise<void> }) { const [name, setName] = useState(product?.name ?? ""); const [sku, setSku] = useState(product?.sku ?? ""); const [category, setCategory] = useState(product?.category ?? ""); const [currency, setCurrency] = useState(product?.currency ?? "MAD"); const [cost, setCost] = useState(product?.unit_cost?.toString() ?? ""); const [error, setError] = useState(""); const [busy, setBusy] = useState(false); const save = async () => { setBusy(true); try { const response = await fetch("/api/founder/products", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ id: product?.id, name, sku, category, currency, unit_cost: numberValue(cost), active: product?.active ?? true }) }); const body = await response.json() as { error?: string }; if (!response.ok) throw new Error(body.error ?? "Product could not be saved."); await onSaved(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Product could not be saved."); } finally { setBusy(false); } }; return <Modal open onClose={onClose} title={product ? "Edit product" : "New product"} description="Only normalized reference fields are stored."><form className="form-stack" onSubmit={(event) => { event.preventDefault(); if (!name.trim()) { setError("Enter a product name."); return; } void save(); }}><label htmlFor="product-name">Name</label><input id="product-name" value={name} onChange={(event) => setName(event.target.value)} autoFocus /><label htmlFor="product-sku">SKU</label><input id="product-sku" value={sku} onChange={(event) => setSku(event.target.value)} /><label htmlFor="product-category">Category</label><input id="product-category" value={category} onChange={(event) => setCategory(event.target.value)} /><label htmlFor="product-currency">Currency</label><input id="product-currency" value={currency} maxLength={3} onChange={(event) => setCurrency(event.target.value.toUpperCase())} /><label htmlFor="product-cost">Unit cost</label><input id="product-cost" inputMode="decimal" value={cost} onChange={(event) => setCost(event.target.value)} />{error ? <p className="field-error" role="alert">{error}</p> : null}<div className="integration-actions"><Button type="submit" disabled={busy}>{busy ? "Saving…" : "Save"}</Button><Button type="button" emphasis="ghost" onClick={onClose}>Cancel</Button></div></form></Modal>; }
function InventoryModal({ product, onClose, onSaved }: { product: Product; onClose: () => void; onSaved: () => Promise<void> }) { const latest = product.latest_inventory; const [available, setAvailable] = useState(latest?.available_stock?.toString() ?? ""); const [reserved, setReserved] = useState(latest?.reserved_stock?.toString() ?? ""); const [reorder, setReorder] = useState(latest?.reorder_level?.toString() ?? ""); const [error, setError] = useState(""); const [busy, setBusy] = useState(false); const save = async () => { setBusy(true); try { const response = await fetch("/api/founder/products", { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ product_id: product.id, available_stock: numberValue(available), reserved_stock: numberValue(reserved), reorder_level: numberValue(reorder) }) }); const body = await response.json() as { error?: string }; if (!response.ok) throw new Error(body.error ?? "Inventory snapshot could not be recorded."); await onSaved(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Inventory snapshot could not be recorded."); } finally { setBusy(false); } }; return <Modal open onClose={onClose} title={`Update stock · ${product.name}`} description="This records a manual snapshot; it does not change an external store."><form className="form-stack" onSubmit={(event) => { event.preventDefault(); void save(); }}><label htmlFor="stock-available">Available stock</label><input id="stock-available" inputMode="decimal" value={available} onChange={(event) => setAvailable(event.target.value)} autoFocus /><label htmlFor="stock-reserved">Reserved stock</label><input id="stock-reserved" inputMode="decimal" value={reserved} onChange={(event) => setReserved(event.target.value)} /><label htmlFor="stock-reorder">Reorder level</label><input id="stock-reorder" inputMode="decimal" value={reorder} onChange={(event) => setReorder(event.target.value)} />{error ? <p className="field-error" role="alert">{error}</p> : null}<div className="integration-actions"><Button type="submit" disabled={busy}>{busy ? "Recording…" : "Record snapshot"}</Button><Button type="button" emphasis="ghost" onClick={onClose}>Cancel</Button></div></form></Modal>; }
