"use client";
import { useCallback, useState } from "react";
import { useDeferredEffect } from "@/lib/use-deferred-effect";
import { Button } from "@/components/ui/button";

type Item = { id:string; title:string; state:string; is_draft:boolean; is_merged:boolean; labels:string[]; milestone:string|null; branch:string|null; html_url:string|null; created_at_provider:string|null; repository:{title:string;url:string|null}|null; related:{incident:{title:string;severity:string}|null;roadmap:{title:string;business_impact:string|null}|null} };
type Data={health:{openIssues:number;openPullRequests:number;awaitingReview:number;merged:number};issues:Item[];pullRequests:Item[];deployments:Array<{id:string;status:string;completed_at:string|null;commit_message:string|null}>};
export function FounderDevelopment(){const[data,setData]=useState<Data|null>(null);const[error,setError]=useState("");const load=useCallback(async()=>{try{const response=await fetch("/api/founder/development",{cache:"no-store"});const body=await response.json() as Data&{error?:string};if(!response.ok)throw new Error(body.error??"Development health could not be loaded.");setData(body);setError("")}catch(reason){setError(reason instanceof Error?reason.message:"Development health could not be loaded.")}},[]);useDeferredEffect(useCallback(()=>{void load()},[load]));if(error)return <div className="domain-page"><section className="inline-error" role="alert"><p>{error}</p><Button emphasis="outline" onClick={()=>void load()}>Try again</Button></section></div>;if(!data)return <div className="domain-page"><div className="empty-state"><span>···</span><h2>Loading development health</h2></div></div>;return <div className="domain-page founder-page"><header className="page-header"><div><p className="eyebrow">Founder development</p><h1>Development health</h1><p>Only synchronized GitHub metadata is shown. Review state remains unavailable when GitHub has not supplied it.</p></div></header><section className="metric-ledger metric-ledger--four"><Metric value={data.health.openIssues} label="Open issues"/><Metric value={data.health.openPullRequests} label="Open pull requests"/><Metric value={data.health.awaitingReview} label="Awaiting review"/><Metric value={data.health.merged} label="Recent merges"/></section><section className="data-surface founder-section"><p className="eyebrow">Issues</p>{data.issues.length?data.issues.slice(0,20).map(item=><WorkCard item={item} key={item.id}/>):<p className="dataset-note">No synchronized issue detail yet. Connect GitHub and run a sync.</p>}</section><section className="data-surface founder-section"><p className="eyebrow">Pull requests</p>{data.pullRequests.length?data.pullRequests.slice(0,20).map(item=><WorkCard item={item} key={item.id}/>):<p className="dataset-note">No synchronized pull request detail yet.</p>}</section><section className="data-surface founder-section"><p className="eyebrow">Release readiness</p>{data.deployments.length?data.deployments.map(item=><div className="signal-row" key={item.id}><span><strong>{item.status}</strong>{item.commit_message??"No commit summary"} · {item.completed_at?new Date(item.completed_at).toLocaleString():"Time unavailable"}</span></div>):<p className="dataset-note">Deployment source is not connected.</p>}</section></div>}
function WorkCard({item}:{item:Item}){const body=<span><strong>{item.title}</strong>{item.repository?.title??"Repository unavailable"} · {item.state}{item.is_draft?" · draft":""}{item.is_merged?" · merged":""}{item.branch?` · ${item.branch}`:""}{item.labels?.length?` · ${item.labels.join(", ")}`:""}{item.milestone?` · ${item.milestone}`:""}{item.related.incident?` · linked ${item.related.incident.severity} incident`:item.related.roadmap?.business_impact?` · ${item.related.roadmap.business_impact}`:""}</span>;return item.html_url?<a className="signal-row" href={item.html_url} target="_blank" rel="noreferrer">{body}</a>:<div className="signal-row">{body}</div>}
function Metric({value,label}:{value:number;label:string}){return <div><strong>{value}</strong><span>{label}</span></div>}
