import { NextResponse } from "next/server";
import { z } from "zod";
import { apiError } from "@/lib/api";
import { listGoogleCalendars,syncGoogleCalendar } from "@/lib/integrations/google-calendar";
import { requireUser } from "@/lib/supabase/server";

export async function GET(){try{const{supabase,userId}=await requireUser();const result=await listGoogleCalendars(supabase,userId);return NextResponse.json({connected:true,calendars:result.calendars,selectedCalendar:result.integration.provider_metadata?.calendar_id??"primary",lastSyncedAt:result.integration.last_synced_at??null})}catch(error){const message=error instanceof Error?error.message:"";if(message==="Google Calendar is not connected.")return NextResponse.json({connected:false,calendars:[],selectedCalendar:null,lastSyncedAt:null});return apiError(error,"Google Calendar status could not be loaded.")}}
export async function POST(){try{const{supabase,userId}=await requireUser();return NextResponse.json(await syncGoogleCalendar(supabase,userId))}catch(error){return apiError(error,"Google Calendar could not be synchronized.")}}
export async function PATCH(request:Request){try{const input=z.object({calendarId:z.string().min(1).max(1000),timezone:z.string().min(1).max(120).optional()}).parse(await request.json());const{supabase,userId}=await requireUser();const current=await supabase.from("integrations").select("provider_metadata").eq("user_id",userId).eq("provider","google").eq("status","connected").maybeSingle();if(!current.data)return NextResponse.json({error:"Google Calendar is not connected."},{status:409});const metadata={...(current.data.provider_metadata as Record<string,unknown>),calendar_id:input.calendarId,...(input.timezone?{timezone:input.timezone}:{})};const saved=await supabase.from("integrations").update({provider_metadata:metadata}).eq("user_id",userId).eq("provider","google").select("id").single();if(saved.error)throw saved.error;return NextResponse.json({selectedCalendar:input.calendarId})}catch(error){return apiError(error,"Sync calendar could not be changed.")}}
export async function DELETE(){try{const{supabase,userId}=await requireUser();const result=await supabase.from("integrations").update({status:"disconnected",access_token_encrypted:null,refresh_token_encrypted:null,expires_at:null}).eq("user_id",userId).eq("provider","google");if(result.error)throw result.error;return new NextResponse(null,{status:204})}catch(error){return apiError(error,"Google Calendar could not be disconnected.")}}
