"use client";

import { useCallback, useEffect, useRef, useState } from "react";
import { CalendarDays, Check, ChevronDown, Clock3, Minus, Plus, Save, Settings2, Target, Trash2 } from "lucide-react";
import { StyledSelect } from "@/components/ui/styled-select";
import { defaultMissionSettings, missionEndDate, missionGoalKeys, missionGoalLabels, type MissionAction, type MissionLog, type MissionSettings } from "@/lib/revenue-mission";
import { useDeferredEffect } from "@/lib/use-deferred-effect";
import "./mission-settings-card.css";

type StoredLog = MissionLog;
type MissionRecordOption = { type: "lead" | "opportunity" | "proposal" | "payment" | "task" | "calendar_event" | "followup"; id: string; label: string };
type MissionRecordLink = { record_type: MissionRecordOption["type"]; record_id: string };
type ClientOption = { id: string; name: string; company: string | null };
const dateToday = () => new Date().toISOString().slice(0, 10);
const statusOptions = [{value:"not_started",label:"Not started"},{value:"in_progress",label:"In progress"},{value:"completed",label:"Completed"},{value:"blocked",label:"Blocked"}];
export function MissionSettingsCard({ onSaved, onSettings, startRequest }: { onSaved: () => void; onSettings: (settings: MissionSettings) => void; startRequest: number }) {
  const startInput = useRef<HTMLInputElement>(null);
  const [settings, setSettings] = useState<MissionSettings>(defaultMissionSettings);
  const [logDate, setLogDate] = useState(dateToday);
  const [logs, setLogs] = useState<Record<string, StoredLog>>({});
  const [newAction, setNewAction] = useState("");
  const [editing, setEditing] = useState(false);
  useEffect(() => { if (startRequest) { const timer = window.setTimeout(() => { setEditing(true); document.getElementById("mission-settings")?.scrollIntoView({ behavior: "smooth", block: "start" }); window.setTimeout(() => startInput.current?.focus(), 300); }, 0); return () => window.clearTimeout(timer); } }, [startRequest]);
  const [busy, setBusy] = useState(false);
  const [message, setMessage] = useState("");
  const [settingsError, setSettingsError] = useState("");
  const [logError, setLogError] = useState("");
  const [clients, setClients] = useState<ClientOption[]>([]);
  const [linkedIds, setLinkedIds] = useState<string[]>([]);
  const [selectedClient, setSelectedClient] = useState("");
  const [clientError, setClientError] = useState("");
  const [records, setRecords] = useState<MissionRecordOption[]>([]);
  const [recordLinks, setRecordLinks] = useState<MissionRecordLink[]>([]);
  const [recordType, setRecordType] = useState<MissionRecordOption["type"]>("lead");
  const [selectedRecord, setSelectedRecord] = useState("");
  const [recordError, setRecordError] = useState("");
  const endDate = missionEndDate(settings.start_date, settings.duration_days);
  const loadSettings = useCallback(async () => { try { const response = await fetch("/api/growth/mission/settings", { cache: "no-store" }); const body = await response.json(); if (!response.ok) throw new Error(body.error ?? "Settings unavailable"); const next = body.settings as MissionSettings; setSettings(next); onSettings(next); setSettingsError(""); } catch (error) { setSettingsError(error instanceof Error ? error.message : "Settings unavailable"); } }, [onSettings]);
  const loadLogs = useCallback(async (day: string) => { try { const response = await fetch(`/api/growth/mission/logs?date=${encodeURIComponent(day)}`, { cache: "no-store" }); const body = await response.json(); if (!response.ok) throw new Error(body.error ?? "Logs unavailable"); setLogs(Object.fromEntries((body.logs as StoredLog[]).map(item => [item.action_id,item]))); setLogError(""); } catch (error) { setLogError(error instanceof Error ? error.message : "Logs unavailable"); setLogs({}); } }, []);
  const loadClients = useCallback(async () => { try { const response = await fetch("/api/growth/mission/clients", { cache: "no-store" }); const body = await response.json(); if (!response.ok) throw new Error(body.error ?? "Clients unavailable"); setClients(body.clients as ClientOption[]); setLinkedIds(body.linked_ids as string[]); setClientError(""); } catch (error) { setClientError(error instanceof Error ? error.message : "Clients unavailable"); } }, []);
  useDeferredEffect(useCallback(() => { void loadSettings(); }, [loadSettings]));
  useDeferredEffect(useCallback(() => { void loadLogs(logDate); }, [loadLogs, logDate]));
  useDeferredEffect(useCallback(() => { void loadClients(); }, [loadClients]));
  const loadRecords = useCallback(async () => { try { const response = await fetch("/api/growth/mission/records", { cache: "no-store" }); const body = await response.json(); if (!response.ok) throw new Error(body.error ?? "Records unavailable"); setRecords(body.records); setRecordLinks(body.links); setRecordError(""); } catch (error) { setRecordError(error instanceof Error ? error.message : "Records unavailable"); } }, []);
  useDeferredEffect(useCallback(() => { void loadRecords(); }, [loadRecords]));
  async function setRecordLink(record_type: MissionRecordOption["type"], record_id: string, linked: boolean) { setBusy(true); setRecordError(""); try { const response = await fetch("/api/growth/mission/records", { method: linked ? "POST" : "DELETE", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ record_type, record_id }) }); const body = await response.json(); if (!response.ok) throw new Error(body.error ?? "Could not update mission record"); await loadRecords(); setSelectedRecord(""); onSaved(); } catch (error) { setRecordError(error instanceof Error ? error.message : "Could not update mission record"); } finally { setBusy(false); } }
  const setGoal = (key: keyof MissionSettings["pace_goals"], value: number) => setSettings(current => ({ ...current, pace_goals: { ...current.pace_goals, [key]: Number.isFinite(value) ? value : 0 } }));
  const updateAction = (id: string, change: Partial<MissionAction>) => setSettings(current => ({ ...current, daily_actions: current.daily_actions.map(item => item.id === id ? { ...item, ...change } : item) }));
  const addAction = () => { const title = newAction.trim(); if (!title) return; const id = `custom_${Date.now().toString(36)}`; setSettings(current => ({ ...current, daily_actions: [...current.daily_actions, { id, title, daily_target: 1, active: true }] })); setNewAction(""); setEditing(true); };
  async function saveSettings() { setBusy(true); setMessage(""); try { const response = await fetch("/api/growth/mission/settings", { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify(settings) }); const body = await response.json(); if (!response.ok) throw new Error(body.error ?? "Could not save settings"); const saved = body.settings as MissionSettings; setSettings(saved); onSettings(saved); setMessage("Mission plan saved."); setSettingsError(""); setEditing(false); onSaved(); } catch (error) { setSettingsError(error instanceof Error ? error.message : "Could not save settings"); } finally { setBusy(false); } }
  function updateLog(id: string, change: Partial<StoredLog>) { setLogs(current => ({ ...current, [id]: { ...(current[id] ?? { log_date: logDate, action_id: id, quantity: 0, status: "not_started", note: "" }), ...change } })); }
  async function saveLog(id: string) { const log = logs[id] ?? { log_date: logDate, action_id: id, quantity: 0, status: "not_started", note: "" }; setBusy(true); setMessage(""); try { const response = await fetch("/api/growth/mission/logs", { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify(log) }); const body = await response.json(); if (!response.ok) throw new Error(body.error ?? "Could not save log"); setMessage(`Saved ${settings.daily_actions.find(item => item.id === id)?.title ?? "daily action"} for ${logDate}.`); setLogError(""); onSaved(); } catch (error) { setLogError(error instanceof Error ? error.message : "Could not save log"); } finally { setBusy(false); } }
  async function setClientLink(clientId: string, linked: boolean) { setBusy(true); setClientError(""); try { const response = await fetch("/api/growth/mission/clients", { method: linked ? "POST" : "DELETE", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ client_id: clientId }) }); const body = await response.json(); if (!response.ok) throw new Error(body.error ?? "Could not update client link"); await loadClients(); setSelectedClient(""); onSaved(); } catch (error) { setClientError(error instanceof Error ? error.message : "Could not update client link"); } finally { setBusy(false); } }
  return <section className={`rm-settings-card ${editing ? "is-editing" : ""}`} id="mission-settings" aria-labelledby="rm-settings-title"><div className="rm-settings-card__header"><span className="rm-settings-card__icon"><Settings2 size={20}/></span><div><p>Mission control</p><h2 id="rm-settings-title">Timeline &amp; settings</h2><span>Plan the mission, set your pace, and log what actually happened.</span></div><button type="button" className="rm-settings-card__edit" onClick={() => setEditing(current => !current)} aria-expanded={editing}>{editing ? "Close editing" : "Edit plan"}<ChevronDown size={15}/></button></div>
    {settingsError && <p className="rm-settings-card__error" role="alert">{settingsError}</p>}{message && <p className="rm-settings-card__success" role="status"><Check size={15}/>{message}</p>}
    <div className="rm-settings-card__timeline"><div><span className="rm-settings-card__step"><CalendarDays size={18}/></span><label>Mission starts<input ref={startInput} type="date" value={settings.start_date ?? ""} disabled={!editing} onChange={event => setSettings(current => ({ ...current, start_date: event.target.value || null }))}/></label></div><div className="rm-settings-card__duration"><span className="rm-settings-card__step"><Clock3 size={18}/></span><label>Duration<strong>{settings.duration_days} days</strong></label><div className="rm-settings-card__stepper"><button type="button" aria-label="Remove one day" disabled={!editing} onClick={() => setSettings(current => ({ ...current, duration_days: Math.max(1,current.duration_days-1) }))}><Minus size={15}/></button><button type="button" aria-label="Add one day" disabled={!editing} onClick={() => setSettings(current => ({ ...current, duration_days: Math.min(365,current.duration_days+1) }))}><Plus size={15}/></button></div></div><div><span className="rm-settings-card__step"><Target size={18}/></span><label>Mission finishes<strong>{endDate ? new Date(`${endDate}T12:00:00Z`).toLocaleDateString("en", { month: "short", day: "numeric", year: "numeric" }) : "Set a start date"}</strong></label></div></div>
    <div className="rm-settings-card__section"><div className="rm-settings-card__section-head"><div><h3>30-day pace goals</h3><p>These targets drive the funnel, progress bars, and pace table. Changing the duration recalculates the daily pace.</p></div></div><div className="rm-settings-card__goals">{missionGoalKeys.map(key => <label key={key}><span>{missionGoalLabels[key]}</span><span className="rm-settings-card__goal-input">{key === "revenue_usd" && <i>$</i>}<input type="number" min={key === "revenue_usd" ? 0 : 1} max={key === "revenue_usd" ? 1000000000 : 1000000} step={key === "revenue_usd" ? .01 : 1} value={settings.pace_goals[key]} onChange={event => setGoal(key, Number(event.target.value))}/></span></label>)}</div></div>
    <div className="rm-settings-card__section"><div className="rm-settings-card__section-head"><div><h3>Daily action plan</h3><p>Choose what to do each day and how many to aim for. You can pause or add actions.</p></div></div><div className="rm-settings-card__actions">{settings.daily_actions.map(action => <div key={action.id} className={!action.active ? "is-paused" : ""}><label className="rm-settings-card__action-name"><input type="checkbox" checked={action.active} onChange={event => updateAction(action.id,{active:event.target.checked})}/><input aria-label="Action name" value={action.title} onChange={event => updateAction(action.id,{title:event.target.value})}/></label><label>per day<input type="number" min={1} max={100000} value={action.daily_target} onChange={event => updateAction(action.id,{daily_target:Number(event.target.value)})}/></label><button type="button" aria-label={`Remove ${action.title}`} onClick={() => setSettings(current => ({...current,daily_actions:current.daily_actions.filter(item => item.id !== action.id)}))}><Trash2 size={15}/></button></div>)}</div><div className="rm-settings-card__add"><input aria-label="New daily action" placeholder="Add a daily action…" value={newAction} onChange={event => setNewAction(event.target.value)} onKeyDown={event => { if(event.key === "Enter") { event.preventDefault(); addAction(); } }}/><button type="button" onClick={addAction} disabled={!newAction.trim()}><Plus size={16}/> Add action</button></div></div>
    <div className="rm-settings-card__save-row"><span>Goal and timeline changes take effect when you save.</span><button type="button" className="rm-settings-card__primary" onClick={() => void saveSettings()} disabled={busy}><Save size={16}/>{busy ? "Saving…" : "Save mission plan"}</button></div>
    <div className="rm-settings-card__section rm-settings-card__clients"><div className="rm-settings-card__section-head"><div><h3>Clients in this mission</h3><p>Only linked clients count toward the First 10K goal. Existing workspace clients stay out until linked.</p></div><strong>{linkedIds.length} linked</strong></div>{clientError && <p className="rm-settings-card__error" role="alert">{clientError}</p>}<div className="rm-settings-card__client-picker"><StyledSelect label="Choose client to link" value={selectedClient} onChange={setSelectedClient} options={[{ value:"", label:"Choose a client…" }, ...clients.filter(client => !linkedIds.includes(client.id)).map(client => ({value:client.id,label:client.company ? `${client.name} · ${client.company}` : client.name}))]}/><button type="button" disabled={!selectedClient || busy} onClick={() => void setClientLink(selectedClient,true)}><Plus size={16}/> Link client</button></div><div className="rm-settings-card__linked-list">{linkedIds.length ? linkedIds.map(id => { const client = clients.find(item => item.id === id); return client ? <div key={id}><span><strong>{client.name}</strong>{client.company && <small>{client.company}</small>}</span><button type="button" disabled={busy} onClick={() => void setClientLink(id,false)}>Remove</button></div> : null; }) : <p>No clients linked yet. Mission client progress starts at zero.</p>}</div></div>
    <div className="rm-settings-card__section rm-settings-card__clients"><div className="rm-settings-card__section-head"><div><h3>Sales records in this mission</h3><p>Link sales records and activity to this mission. Linked tasks, meetings, and follow-ups update the cards when their status changes.</p></div><strong>{recordLinks.length} linked</strong></div>{recordError && <p className="rm-settings-card__error" role="alert">{recordError}</p>}<div className="rm-settings-card__client-picker"><StyledSelect label="Record type" value={recordType} onChange={value => { setRecordType(value as MissionRecordOption["type"]); setSelectedRecord(""); }} options={[{value:"lead",label:"Leads"},{value:"opportunity",label:"Opportunities"},{value:"proposal",label:"Proposals"},{value:"payment",label:"Payments"},{value:"task",label:"Video audit tasks"},{value:"calendar_event",label:"Sales meetings"},{value:"followup",label:"Follow-ups"}]}/><StyledSelect label="Choose record to link" value={selectedRecord} onChange={setSelectedRecord} options={[{value:"",label:"Choose a record…"},...records.filter(record => record.type === recordType && !recordLinks.some(link => link.record_type === record.type && link.record_id === record.id)).map(record => ({value:record.id,label:record.label}))]}/><button type="button" disabled={!selectedRecord || busy} onClick={() => void setRecordLink(recordType, selectedRecord, true)}><Plus size={16}/> Link record</button></div><div className="rm-settings-card__linked-list">{recordLinks.length ? recordLinks.map(link => { const record = records.find(item => item.type === link.record_type && item.id === link.record_id); return <div key={`${link.record_type}:${link.record_id}`}><span><strong>{record?.label ?? "Record no longer available"}</strong><small>{link.record_type}</small></span><button type="button" disabled={busy} onClick={() => void setRecordLink(link.record_type, link.record_id, false)}>Remove</button></div>; }) : <p>No sales records linked. Funnel and cash totals start at zero.</p>}</div></div>
    <div className="rm-settings-card__section rm-settings-card__log"><div className="rm-settings-card__section-head"><div><h3>Daily log &amp; status</h3><p>Record the quantity completed and set the status for each action on a specific day.</p></div><label>Log date<input type="date" value={logDate} onChange={event => setLogDate(event.target.value)}/></label></div>{logError && <p className="rm-settings-card__error" role="alert">{logError}</p>}<div className="rm-settings-card__log-list">{settings.daily_actions.filter(action => action.active).map(action => { const log = logs[action.id]; return <div key={action.id}><div className="rm-settings-card__log-title"><strong>{action.title}</strong><small>Target {action.daily_target} / day</small></div><label>Done<input aria-label={`${action.title} quantity`} type="number" min={0} max={100000} value={log?.quantity ?? 0} onChange={event => updateLog(action.id,{quantity:Number(event.target.value)})}/></label><StyledSelect className="rm-settings-card__status" label={`${action.title} status`} value={log?.status ?? "not_started"} onChange={value => updateLog(action.id,{status:value as MissionLog["status"]})} options={statusOptions}/><input aria-label={`${action.title} note`} placeholder="Note (optional)" value={log?.note ?? ""} onChange={event => updateLog(action.id,{note:event.target.value})}/><button type="button" onClick={() => void saveLog(action.id)} disabled={busy}>Save</button></div>; })}</div></div>
  </section>;
}
