"use client";

import Link from "next/link";
import { useCallback, useMemo, useState } from "react";
import { ArrowRight, BarChart3, Bell, CalendarDays, Check, ChevronDown, CircleDollarSign, Clock3, FileText, Filter, Heart, Lightbulb, Mail, MessageSquare, MoreHorizontal, Play, Plus, RefreshCw, Send, Target, Trophy, Users, Video, Zap } from "lucide-react";
import { StyledSelect } from "@/components/ui/styled-select";
import { MissionSettingsCard } from "./mission-settings-card";
import { defaultMissionSettings, missionDay, type MissionSettings, type MissionLog } from "@/lib/revenue-mission";
import { useDeferredEffect } from "@/lib/use-deferred-effect";
import { subscribeToWorkspaceMutations } from "@/lib/workspace-mutations";
import "./revenue-mission.css";

type ActionCard = MissionSettings["daily_actions"][number];
type Opportunity = { id: string; title: string; stage: string; estimated_value: number | null; estimated_value_usd: number; currency: string; updated_at: string; next_action: string | null; next_action_date: string | null; source: string | null };
type Mission = { prospects: number; contacted: number; meetings: number; clients: number; revenueUsd: number; revenueTargetUsd: number | null; prospectsToday: number; outreachToday: number; videoAuditsToday: number; videoAudits: number; videoAuditsWeek: number; missionDay: number | null; replies: number; proposals: number; signedRevenueUsd: number; pipelineUsd: number; followupsDue: number; followupsCompletedToday: number; repliesToday: number; meetingsToday: number; staleOpportunities: number; bestSource: string | null; weekReview: { prospects: number; outreach: number; replies: number; meetings: number; proposals: number; clients: number }; opportunities: Opportunity[] };
const number = (value: number) => new Intl.NumberFormat("en-US", { maximumFractionDigits: 0 }).format(value);
const money = (value: number) => `$${number(value)}`;
const progress = (value: number, goal: number) => Math.min(100, Math.round(value / Math.max(goal, 1) * 100));
const stages = ["Prospects", "Contacted", "Replies", "Meetings", "Proposals", "Clients"];
const stageIcons = [Users, Send, MessageSquare, CalendarDays, FileText, Trophy];

export function RevenueMission() {
  const [data, setData] = useState<Mission | null>(null);
  const [settings, setSettings] = useState<MissionSettings>(defaultMissionSettings);
  const [todayLogs, setTodayLogs] = useState<Record<string, MissionLog>>({});
  const [error, setError] = useState("");
  const [period, setPeriod] = useState<"This week" | "Mission to date">("This week");
  const [metric, setMetric] = useState("All metrics");
  const [selected, setSelected] = useState<Opportunity | null>(null);
  const [showAll, setShowAll] = useState(false);
  const [startRequest, setStartRequest] = useState(0);
  const [logAction, setLogAction] = useState<ActionCard | null>(null);
  const [quickQuantity, setQuickQuantity] = useState(0);
  const [quickStatus, setQuickStatus] = useState<MissionLog["status"]>("not_started");
  const [quickNote, setQuickNote] = useState("");
  const [quickBusy, setQuickBusy] = useState(false);
  const [quickError, setQuickError] = useState("");
  function openQuickLog(action: ActionCard) { const existing = todayLogs[action.id]; setLogAction(action); setQuickQuantity(existing?.quantity ?? 0); setQuickStatus(existing?.status ?? "not_started"); setQuickNote(existing?.note ?? ""); setQuickError(""); }
  async function saveQuickLog() { if (!logAction) return; setQuickBusy(true); setQuickError(""); try { const response = await fetch("/api/growth/mission/logs", { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ log_date: new Date().toISOString().slice(0,10), action_id: logAction.id, quantity: quickQuantity, status: quickStatus, note: quickNote }) }); const body = await response.json(); if (!response.ok) throw new Error(body.error ?? "Could not save progress"); setLogAction(null); await load(); } catch (reason) { setQuickError(reason instanceof Error ? reason.message : "Could not save progress"); } finally { setQuickBusy(false); } }
  const load = useCallback(async () => { try { const response = await fetch("/api/today/mission", { cache: "no-store" }); const body = await response.json(); if (!response.ok) throw new Error(body.error ?? "Mission could not be loaded."); setData(body as Mission); setError(""); const plan = await fetch("/api/growth/mission/settings", {cache:"no-store"}); if (plan.ok) { const result = await plan.json(); setSettings(result.settings as MissionSettings); } const logs = await fetch(`/api/growth/mission/logs?date=${new Date().toISOString().slice(0,10)}`, {cache:"no-store"}); if (logs.ok) { const result = await logs.json(); setTodayLogs(Object.fromEntries((result.logs as MissionLog[]).map(item=>[item.action_id,item]))); } } catch (reason) { setError(reason instanceof Error ? reason.message : "Mission could not be loaded."); } }, []);
  useDeferredEffect(useCallback(() => { void load(); return subscribeToWorkspaceMutations(["clients", "projects", "followups", "invoices", "tasks", "finance", "payments"], () => void load()); }, [load]));
  const goals = settings.pace_goals;
  const duration = settings.duration_days;
  const day = missionDay(settings.start_date, new Date().toISOString().slice(0,10), duration);
  const stageGoals = [goals.prospects,goals.contacted,goals.replies,goals.meetings,goals.proposals,goals.clients];
  const values = useMemo(() => data ? [data.prospects, data.contacted, data.replies, data.meetings, data.proposals, data.clients] : [0,0,0,0,0,0], [data]);
  const revenueGoal = goals.revenue_usd || data?.revenueTargetUsd || 0;
  const paceMetrics = data ? [{label:"Prospects",value:data.prospects,goal:goals.prospects},{label:"Contacted",value:data.contacted,goal:goals.contacted},{label:"Videos",value:data.videoAudits,goal:goals.videos},{label:"Replies",value:data.replies,goal:goals.replies},{label:"Meetings",value:data.meetings,goal:goals.meetings},{label:"Proposals",value:data.proposals,goal:goals.proposals},{label:"Clients",value:data.clients,goal:goals.clients},{label:"Revenue",value:data.revenueUsd,goal:revenueGoal}] : [];
  const overall = paceMetrics.length ? Math.round(paceMetrics.reduce((sum,item)=>sum+progress(item.value,item.goal),0)/paceMetrics.length) : 0;
  const expectedProgress = day ? Math.round(day / duration * 100) : 0;
  const onTrack = day !== null && overall >= Math.max(0, expectedProgress - 5);
  const bottleneck = !settings.start_date ? "Mission not started" : paceMetrics.filter(item=>item.goal>0).sort((a,b)=>a.value/a.goal-b.value/b.goal)[0]?.label ?? "Prospects";
  const recovery = !settings.start_date ? { title: "Set a start date", detail: "Start the timeline to track pace and daily progress." } : !data?.prospects ? { title: "Link your first prospect", detail: "Choose which sales records belong to this phase." } : bottleneck === "Videos" ? { title: "Record the next audit", detail: "Log completed personalized videos in today’s actions." } : bottleneck === "Revenue" ? { title: "Collect the next payment", detail: "Link a paid invoice to move the cash goal." } : bottleneck === "Contacted" ? { title: "Contact more prospects", detail: "Move linked prospects into active outreach." } : bottleneck === "Replies" ? { title: "Follow up on outreach", detail: "Reconnect with prospects waiting to respond." } : bottleneck === "Meetings" ? { title: "Complete a sales meeting", detail: "Log completed meetings in today’s actions." } : bottleneck === "Prospects" ? { title: "Find more prospects", detail: "Link leads or log new prospects in today’s actions." } : bottleneck === "Proposals" ? { title: "Prepare a proposal", detail: "Move a qualified opportunity forward." } : { title: "Advance the next client", detail: "Follow the strongest open opportunity." };
  const shownOpportunities = showAll ? data?.opportunities ?? [] : data?.opportunities.slice(0,4) ?? [];
  const rows = [
    { label:"Prospects", current:data?.prospects ?? 0, goal:goals.prospects }, { label:"Contacted", current:data?.contacted ?? 0, goal:goals.contacted },
    { label:"Videos", current:data?.videoAudits ?? 0, goal:goals.videos }, { label:"Replies", current:data?.replies ?? 0, goal:goals.replies },
    { label:"Meetings", current:data?.meetings ?? 0, goal:goals.meetings }, { label:"Proposals", current:data?.proposals ?? 0, goal:goals.proposals },
    { label:"Clients", current:data?.clients ?? 0, goal:goals.clients }, { label:"Revenue (USD)", current:data?.revenueUsd ?? 0, goal:revenueGoal },
  ].filter(row => metric === "All metrics" || row.label === metric);
  const actionIcons: Record<string, typeof Users> = { prospects: Users, outreach: Send, audits: Video, followups: RefreshCw, replies: Mail, inbound_replies: MessageSquare, meetings: CalendarDays };
  const automaticToday: Record<string, number> = { prospects: data?.prospectsToday ?? 0, outreach: data?.outreachToday ?? 0, audits: data?.videoAuditsToday ?? 0, followups: data?.followupsCompletedToday ?? 0, inbound_replies: data?.repliesToday ?? 0, meetings: data?.meetingsToday ?? 0 };
  const targets = settings.daily_actions.filter(action=>action.active).map((action)=>{
    const current = Math.max(todayLogs[action.id]?.quantity ?? 0, automaticToday[action.id] ?? 0);
    const status = todayLogs[action.id]?.status === "blocked" ? "blocked" : current >= action.daily_target ? "completed" : current > 0 ? "in_progress" : "not_started";
    return {...action,current,goal:action.daily_target,icon:actionIcons[action.id] ?? Zap,status};
  });

  return <main className="revenue-mission-page">
    <nav className="revenue-mission__breadcrumb" aria-label="Breadcrumb"><Link href="/growth">Growth</Link><span>›</span><span>Revenue</span><span>›</span><strong>Phase 1 — First 10K</strong></nav>
    {error && <div className="revenue-mission__error" role="alert">{error} <button onClick={() => void load()}>Try again</button></div>}
    <div className="revenue-mission__layout"><div className="revenue-mission__main">
      <section className="rm-hero"><div className="rm-hero__content"><div className="rm-eyebrow"><span className="rm-icon rm-icon--violet"><Target size={18}/></span><span>Revenue mission</span><span className="rm-day"><CalendarDays size={14}/>{day ? `Day ${day} / ${duration}` : `${duration}-day mission`}</span></div><h1>Phase 1 — First 10K</h1><h2>Build the first predictable revenue engine.</h2><p>Get your first client and reach {money(revenueGoal || data?.revenueTargetUsd || 0)} through medical centers (radiology).</p><div className="rm-hero__progress"><div className="rm-track"><span style={{width:`${overall}%`}}/></div><b>{data ? `${overall}%` : "—"}</b></div><small>{data ? `${paceMetrics.filter(item=>item.value>0).length} of ${paceMetrics.length} mission targets underway` : "Loading mission progress"} · {duration}-day goal</small>{!settings.start_date && <button type="button" className="rm-hero__start" onClick={() => setStartRequest(value => value + 1)}><CalendarDays size={16}/> Set start date <ArrowRight size={16}/></button>}</div><blockquote>“Discipline today creates freedom tomorrow.”</blockquote><div className="rm-health"><div><span className="rm-icon rm-icon--green"><Heart size={22}/></span><p><small>Mission Health</small><strong>{!settings.start_date ? "Not started" : onTrack ? "On track" : "Behind pace"}</strong><em>{!settings.start_date ? "Choose a start date to begin tracking." : onTrack ? "Progress is meeting the current pace." : "Focus on the largest gap to today’s target."}</em></p></div><div><span className="rm-icon rm-icon--rose"><Target size={22}/></span><p><small>Current Bottleneck</small><strong>{bottleneck}</strong><em>{!settings.start_date ? "Your pipeline will begin once the mission starts." : "Focus on the next conversion step."}</em></p></div><div><span className="rm-icon rm-icon--green"><Lightbulb size={22}/></span><p><small>Recovery Action</small><strong>{recovery.title}</strong><em>{recovery.detail}</em></p></div></div></section>
      <div className="rm-summary"><article><span className="rm-icon rm-icon--violet"><CircleDollarSign size={20}/></span><small>Cash Collected</small><strong>{money(data?.revenueUsd ?? 0)} <i>/ {money(revenueGoal)}</i></strong><div className="rm-track"><span style={{width:`${progress(data?.revenueUsd ?? 0,revenueGoal)}%`}}/></div></article><article><span className="rm-icon rm-icon--blue"><BarChart3 size={20}/></span><small>Accepted Value</small><strong>{money(data?.signedRevenueUsd ?? 0)}</strong><em>Accepted proposals</em></article><article><span className="rm-icon rm-icon--violet"><Users size={20}/></span><small>Clients</small><strong>{data?.clients ?? "—"} <i>/ {goals.clients}</i></strong><div className="rm-track"><span style={{width:`${progress(data?.clients ?? 0,goals.clients)}%`}}/></div></article><article><span className="rm-icon rm-icon--violet"><FileText size={20}/></span><small>Pipeline Value</small><strong>{money(data?.pipelineUsd ?? 0)}</strong><em>Open opportunities</em></article></div>
      <section className="rm-panel"><div className="rm-panel__heading"><span className="rm-icon rm-icon--violet"><Filter size={19}/></span><div><h2>Sales Funnel</h2><p>Track your conversion at each stage from prospect to client.</p></div></div><div className="rm-funnel">{stages.map((label,index)=>{const Icon=stageIcons[index];return <div className="rm-funnel__step" key={label}><span className={`rm-icon rm-icon--${["violet","blue","orange","rose","violet","green"][index]}`}><Icon size={20}/></span><small>{label}</small><strong>{data ? values[index] : "—"} <i>/ {stageGoals[index]}</i></strong><div className="rm-track"><span style={{width:`${progress(values[index],stageGoals[index])}%`}}/></div>{index<5&&<span className="rm-funnel__arrow"><ArrowRight size={17}/></span>}</div>})}</div><div className="rm-conversions">{[1,2,3,4,5].map(index=><span key={index}>{values[index-1] ? `${Math.round(values[index]/values[index-1]*100)}%` : "—"}<small>to {stages[index].toLowerCase()}</small></span>)}</div></section>
      <section className="rm-panel"><div className="rm-panel__heading"><span className="rm-icon rm-icon--violet"><Zap size={19}/></span><div><h2>Today’s Revenue Actions</h2><p>Complete these actions to stay on track with your mission.</p></div><Link className="rm-text-link" href="/tasks">View tasks <ArrowRight size={15}/></Link></div><div className="rm-actions">{targets.map((action)=><button type="button" onClick={() => openQuickLog(action)} key={action.id} aria-label={`Log progress for ${action.title}`}><span className="rm-icon rm-icon--violet"><action.icon size={18}/></span><strong>{action.title}</strong><div className="rm-track"><span style={{width:`${progress(action.current,action.goal)}%`}}/></div><small title={`Status: ${action.status.replaceAll("_"," ")}`}>{action.current} / {action.goal} · Log progress</small></button>)}</div></section>
      <section className="rm-panel"><div className="rm-panel__heading"><span className="rm-icon rm-icon--violet"><Target size={19}/></span><div><h2>Active Opportunities</h2><p>Current pipeline of medical centers and opportunities.</p></div><Link className="rm-outline" href="/growth/pipeline"><Plus size={16}/> Add opportunity</Link></div><div className="rm-table-wrap"><table><thead><tr><th>Center / Contact</th><th>Stage</th><th>Value (USD)</th><th>Last activity</th><th>Next action</th><th>Due</th><th>Lead source</th><th></th></tr></thead><tbody>{shownOpportunities.length ? shownOpportunities.map(row=><tr key={row.id} onClick={()=>setSelected(row)} tabIndex={0} onKeyDown={event=>{if(event.key==="Enter")setSelected(row)}}><td><strong>{row.title}</strong></td><td><span className="rm-stage">{row.stage}</span></td><td>{money(row.estimated_value_usd)}</td><td>{new Date(row.updated_at).toLocaleDateString("en",{month:"short",day:"numeric"})}</td><td>{row.next_action || "Add next action"}</td><td>{row.next_action_date || "—"}</td><td>{row.source || "—"}</td><td><MoreHorizontal size={16}/></td></tr>) : <tr><td colSpan={8} className="rm-empty">No opportunities recorded yet. <Link href="/growth/pipeline">Open the pipeline</Link> to add one.</td></tr>}</tbody></table></div>{(data?.opportunities.length??0)>4&&<button className="rm-more" onClick={()=>setShowAll(!showAll)}>{showAll?"Show less":"View all opportunities"} <ChevronDown size={14}/></button>}</section>
    </div><aside className="revenue-mission__aside"><section className="rm-panel"><div className="rm-panel__heading"><span className="rm-icon rm-icon--violet"><BarChart3 size={19}/></span><h2>Activity &amp; Pace</h2><StyledSelect className="rm-dropdown" label="Activity period" value={period} onChange={value=>setPeriod(value as "This week"|"Mission to date")} options={[{value:"This week",label:"This week"},{value:"Mission to date",label:"Mission to date"}]}/></div><div className="rm-video"><span className="rm-icon rm-icon--violet"><Play size={20}/></span><div><small>Personalized Videos</small><strong>{data?.videoAudits ?? "—"} / {goals.videos}</strong><div className="rm-track"><span style={{width:`${progress(data?.videoAudits??0,goals.videos)}%`}}/></div></div><small>{progress(data?.videoAudits??0,goals.videos)}%</small></div><div className="rm-pace"><span><strong>{data?.videoAuditsToday??"—"}</strong><small>Today</small></span><span><strong>{period === "This week" ? data?.videoAuditsWeek ?? "—" : data?.videoAudits ?? "—"}</strong><small>{period === "This week" ? "This week" : "Recorded"}</small></span><span><strong>{data ? (data.videoAudits/Math.max(1,day??duration)).toFixed(1) : "—"}</strong><small>Avg / day</small></span><span><strong>{Math.max(0,Math.ceil((goals.videos-(data?.videoAudits??0))/Math.max(1,duration-(day??0)+1)))}</strong><small>Required / day</small></span></div></section>
      <section className="rm-panel"><div className="rm-panel__heading"><span className="rm-icon rm-icon--violet"><BarChart3 size={19}/></span><h2>30-Day Pace</h2><StyledSelect className="rm-dropdown rm-dropdown--metric" label="Pace metric" value={metric} onChange={setMetric} options={["All metrics","Prospects","Contacted","Videos","Replies","Meetings","Proposals","Clients","Revenue (USD)"].map(label=>({value:label,label}))}/></div><div className="rm-table-wrap"><table className="rm-pace-table"><thead><tr><th>Metric</th><th>Current</th><th>Should be</th><th>Goal</th><th>Status</th></tr></thead><tbody>{rows.map(row=><tr key={row.label}><td>{row.label}</td><td>{number(row.current)}</td><td>{day == null ? "—" : number(Math.round(row.goal*day/duration))}</td><td>{number(row.goal)}</td><td><span className={row.current>=(day == null ? Infinity : row.goal*day/duration)?"rm-status rm-status--good":"rm-status"}>{row.current>=(day == null ? Infinity : row.goal*day/duration)?"On track":day == null ? "Pending" : "Behind"}</span></td></tr>)}</tbody></table></div></section>
      <section className="rm-panel"><div className="rm-panel__heading"><span className="rm-icon rm-icon--violet"><Clock3 size={19}/></span><h2>Follow-up Engine</h2><Link className="rm-text-link" href="/growth">View all <ArrowRight size={14}/></Link></div><div className="rm-follow-stats"><Link href="/growth"><Bell size={20}/><strong>{data?.followupsDue??"—"}</strong><small>follow-ups due by today</small></Link><Link href="/growth"><Clock3 size={20}/><strong>{data?.staleOpportunities??"—"}</strong><small>stale opportunities</small></Link></div><div className="rm-follow-sequence">{["Initial outreach","Follow up","Second follow up","Break up message"].map((label,index)=><span key={label}><i>{[<Mail size={15} key="mail"/>,<Clock3 size={15} key="clock"/>,<MessageSquare size={15} key="message"/>,<Target size={15} key="target"/>][index]}</i><strong>{label}</strong><small>Day {[1,3,7,14][index]}</small></span>)}</div></section>
      <section className="rm-panel"><div className="rm-panel__heading"><span className="rm-icon rm-icon--violet"><BarChart3 size={19}/></span><h2>Last 7 Days</h2><Link className="rm-text-link" href="/growth/reviews">Review <ArrowRight size={14}/></Link></div><div className="rm-review-grid">{["Prospects added","Outreach sent","Replies","Meetings","Proposals","Clients"].map((label,index)=><span key={label}><strong>{data ? [data.weekReview.prospects,data.weekReview.outreach,data.weekReview.replies,data.weekReview.meetings,data.weekReview.proposals,data.weekReview.clients][index] : "—"}</strong><small>{label}</small></span>)}</div><div className="rm-review-notes"><div><Trophy size={18}/><span><small>Best source</small><strong>{data?.bestSource ?? "No source recorded"}</strong></span></div><div><Target size={18}/><span><small>Current bottleneck</small><strong>{bottleneck}</strong></span></div></div></section></aside></div>
    <MissionSettingsCard onSaved={() => void load()} onSettings={setSettings} startRequest={startRequest}/>
    {logAction && <div className="rm-dialog-backdrop" onMouseDown={() => setLogAction(null)}><div className="rm-dialog rm-quick-log" role="dialog" aria-modal="true" aria-label={`Log ${logAction.title}`} onMouseDown={event => event.stopPropagation()}><button className="rm-dialog__close" onClick={() => setLogAction(null)} aria-label="Close">×</button><span className="rm-icon rm-icon--violet"><Check size={20}/></span><h2>Log today’s progress</h2><p>{logAction.title} · Target {logAction.daily_target} per day</p><label>Completed today<input type="number" min={0} max={100000} value={quickQuantity} onChange={event => setQuickQuantity(Number(event.target.value))}/></label><StyledSelect label="Status" value={quickStatus} onChange={value => setQuickStatus(value as MissionLog["status"])} options={[{value:"not_started",label:"Not started"},{value:"in_progress",label:"In progress"},{value:"completed",label:"Completed"},{value:"blocked",label:"Blocked"}]}/><label>Note (optional)<textarea className="resize-none audit-textarea" value={quickNote} maxLength={1000} onChange={event => setQuickNote(event.target.value)} placeholder="What happened today?"/></label>{quickError && <p role="alert" className="revenue-mission__error">{quickError}</p>}<button type="button" className="rm-dialog__link" disabled={quickBusy} onClick={() => void saveQuickLog()}>{quickBusy ? "Saving…" : "Save progress"}</button></div></div>}
    {selected&&<div className="rm-dialog-backdrop" onMouseDown={()=>setSelected(null)}><div className="rm-dialog" role="dialog" aria-modal="true" aria-label="Opportunity details" onMouseDown={event=>event.stopPropagation()}><button className="rm-dialog__close" onClick={()=>setSelected(null)} aria-label="Close">×</button><span className="rm-icon rm-icon--violet"><Target size={22}/></span><h2>{selected.title}</h2><p><span className="rm-stage">{selected.stage}</span> {money(selected.estimated_value_usd)}</p><dl><div><dt>Next action</dt><dd>{selected.next_action||"No action recorded"}</dd></div><div><dt>Due</dt><dd>{selected.next_action_date||"No date"}</dd></div><div><dt>Lead source</dt><dd>{selected.source||"Not recorded"}</dd></div></dl><Link href="/growth/pipeline" className="rm-dialog__link">Open in pipeline <ArrowRight size={16}/></Link></div></div>}
  </main>;
}
