"use client";
import Link from "next/link";
import { useDeferredEffect } from "@/lib/use-deferred-effect";
import { useCallback, useEffect, useMemo, useRef, useState, useSyncExternalStore, type FormEvent } from "react";
import { Activity, ChartNoAxesColumnIncreasing, Check, ChevronRight, Copy, FileText, Layers, LayoutGrid, List, Pencil, Play, Plus, Search, Star, X, Braces, Clock } from "lucide-react";
import { Modal } from "@/components/ui/modal";
import { Button } from "@/components/ui/button";
import { StyledSelect } from "@/components/ui/styled-select";
import { useToast } from "@/components/toast-provider";
import { filterPrompts, previewPrompts, promptCategories, type PromptRecord } from "@/lib/prompts-dashboard";
import { promptVariables, renderPrompt } from "@/lib/v2";
import "./prompts-dashboard.css";
type Version={id:string;version_number:number;prompt_text:string;change_note?:string;created_at:string};
type Draft={title:string;description:string;category:string;prompt_text:string;favorite:boolean};
const empty:Draft={title:"",description:"",category:"Writing",prompt_text:"",favorite:false};
const date=(value?:string|null)=>value?new Date(value).toLocaleDateString("en",{month:"short",day:"numeric",year:"numeric"}):"Not recorded";
const subscribe=(cb:()=>void)=>{const m=window.matchMedia("(max-width:1000px)");m.addEventListener("change",cb);return()=>m.removeEventListener("change",cb)};
async function request(url:string,init?:RequestInit){const response=await fetch(url,init);const body=await response.json();if(!response.ok)throw new Error(body.error||"The request could not be completed. Try again.");return body;}
export function PromptsDashboard({preview=false}:{preview?:boolean}){
 const [records,setRecords]=useState<PromptRecord[]>(preview?previewPrompts:[]),[loading,setLoading]=useState(!preview),[error,setError]=useState(""),[retry,setRetry]=useState(0);
 const [query,setQuery]=useState(""),[category,setCategory]=useState("all"),[favorites,setFavorites]=useState("all"),[sort,setSort]=useState("updated"),[grid,setGrid]=useState(false),[selected,setSelected]=useState<string|null>(null),[tab,setTab]=useState("Overview");
 const [versions,setVersions]=useState<Version[]>([]),[versionLoading,setVersionLoading]=useState(false),[versionError,setVersionError]=useState(""),[localVersions,setLocalVersions]=useState<Record<string,Version[]>>({});
 const [editor,setEditor]=useState(false),[editing,setEditing]=useState<string|null>(null),[draft,setDraft]=useState<Draft>(empty),[formError,setFormError]=useState(""),[busy,setBusy]=useState(false),[runner,setRunner]=useState(false),[values,setValues]=useState<Record<string,string>>({}),[result,setResult]=useState("");
 const lock=useRef(false),searchRef=useRef<HTMLInputElement>(null),detailRef=useRef<HTMLElement>(null),triggerRef=useRef<HTMLElement|null>(null);const {showToast}=useToast();
 const mobile=useSyncExternalStore(subscribe,()=>window.matchMedia("(max-width:1000px)").matches,()=>false);
 const current=records.find(row=>row.id===selected);const text=current?.prompt_text??current?.prompt??"";const variables=useMemo(()=>promptVariables(text),[text]);
 const rows=useMemo(()=>filterPrompts(records,query,category,favorites,sort),[records,query,category,favorites,sort]);
 useEffect(()=>{if(preview)return;const c=new AbortController();async function load(){setLoading(true);setError("");try{const all:PromptRecord[]=[];for(let page=1;;page++){const body=await request(`/api/entities/prompts?page=${page}&pageSize=100`,{signal:c.signal,cache:"no-store"});all.push(...body.records);if(!body.records.length||all.length>=body.total)break;}setRecords(all);}catch(e){if(!c.signal.aborted)setError(e instanceof Error?e.message:"Could not load prompts.");}finally{if(!c.signal.aborted)setLoading(false)}}void load();return()=>c.abort()},[preview,retry]);
 useDeferredEffect(useCallback(()=>{if(!selected)return;const c=new AbortController();if(preview){setVersions(localVersions[selected]??[]);return;}setVersionLoading(true);setVersionError("");setVersions([]);request(`/api/prompts/${selected}?refresh=${retry}`,{signal:c.signal,cache:"no-store"}).then(body=>setVersions(body.versions)).catch(e=>{if(!c.signal.aborted)setVersionError(e.message)}).finally(()=>{if(!c.signal.aborted)setVersionLoading(false)});return()=>c.abort()},[selected,preview,localVersions,retry]));
 useEffect(()=>{if(!selected)return;detailRef.current?.querySelector<HTMLButtonElement>('[aria-label="Close prompt details"]')?.focus({preventScroll:true});const previous=triggerRef.current;return()=>previous?.focus({preventScroll:true})},[selected]);
 useEffect(()=>{if(!selected||editor||runner)return;const key=(e:KeyboardEvent)=>{if(e.key==="Escape")setSelected(null);if(e.key!=="Tab"||!mobile)return;const controls=[...(detailRef.current?.querySelectorAll<HTMLElement>('button:not([disabled]),a[href],input')??[])];const first=controls[0],last=controls.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus()}};document.addEventListener("keydown",key);return()=>document.removeEventListener("keydown",key)},[selected,mobile,editor,runner]);
 function choose(row:PromptRecord,trigger:HTMLElement){triggerRef.current=trigger;setSelected(row.id);setTab("Overview");setResult("")}
 function edit(row?:PromptRecord,duplicate=false){setEditing(duplicate?null:row?.id??null);setDraft(row?{title:row.title+(duplicate?" (copy)":""),description:row.description??"",category:row.category,prompt_text:row.prompt_text??row.prompt??"",favorite:row.favorite??false}:empty);setFormError("");setEditor(true)}
 function replace(row:PromptRecord){setRecords(old=>old.some(item=>item.id===row.id)?old.map(item=>item.id===row.id?row:item):[row,...old])}
 async function save(e:FormEvent){e.preventDefault();if(lock.current)return;if(!draft.title.trim()||!draft.prompt_text.trim()){setFormError("Enter a title and prompt instructions.");document.getElementById(!draft.title.trim()?"prompt-title":"prompt-text")?.focus();return;}lock.current=true;setBusy(true);setFormError("");try{let row:PromptRecord;if(preview){row={...records.find(r=>r.id===editing),...draft,id:editing??crypto.randomUUID(),created_at:records.find(r=>r.id===editing)?.created_at??new Date().toISOString(),updated_at:new Date().toISOString()};if(editing&&(records.find(r=>r.id===editing)?.prompt_text??records.find(r=>r.id===editing)?.prompt??"")!==draft.prompt_text)setLocalVersions(old=>({...old,[editing]:[{id:crypto.randomUUID(),version_number:(old[editing]?.length??0)+1,prompt_text:records.find(r=>r.id===editing)?.prompt_text??records.find(r=>r.id===editing)?.prompt??"",created_at:new Date().toISOString(),change_note:"Saved before edit"},...(old[editing]??[])]}));}else{const body=await request(`/api/entities/prompts${editing?`/${editing}`:""}`,{method:editing?"PATCH":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...draft,description:draft.description.trim()||null})});row=body.record;}replace(row);setSelected(row.id);setEditor(false);setRetry(n=>n+1);showToast(editing?"Prompt updated.":"Prompt created.");}catch(e){setFormError(e instanceof Error?e.message:"Prompt could not be saved.");}finally{lock.current=false;setBusy(false)}}
 async function copy(value:string){try{await navigator.clipboard.writeText(value);showToast("Prompt copied.")}catch{showToast("Copy failed. Select the prompt text and copy it manually.","error")}}
 async function prepare(e:FormEvent){e.preventDefault();if(!current||lock.current)return;const rendered=renderPrompt(text,values);if(rendered.missing.length){setFormError(`Complete variables: ${rendered.missing.join(", ")}`);document.getElementById(`pv-${rendered.missing[0]}`)?.focus();return;}lock.current=true;setBusy(true);setFormError("");try{const body=preview?{rendered:rendered.text}:await request(`/api/prompts/${current.id}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"use",variables:values})});setResult(body.rendered);replace({...current,usage_count:Number(current.usage_count??0)+1,last_used_at:new Date().toISOString()});showToast("Prompt prepared.")}catch(e){setFormError(e instanceof Error?e.message:"Could not prepare prompt.")}finally{lock.current=false;setBusy(false)}}
 async function restore(version:Version){if(!current||lock.current)return;lock.current=true;setBusy(true);try{if(preview){setLocalVersions(old=>({...old,[current.id]:[{id:crypto.randomUUID(),version_number:(old[current.id]?.length??0)+1,prompt_text:text,created_at:new Date().toISOString(),change_note:"Snapshot before restore"},...(old[current.id]??[])]}));replace({...current,prompt_text:version.prompt_text,updated_at:new Date().toISOString()});}else{const body=await request(`/api/prompts/${current.id}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"restore",version_id:version.id})});replace(body.prompt);setRetry(n=>n+1);}showToast("Prompt version restored.")}catch(e){showToast(e instanceof Error?e.message:"Version could not be restored.","error")}finally{lock.current=false;setBusy(false)}}
 const totalUses=records.reduce((sum,row)=>sum+Number(row.usage_count??0),0),rated=records.filter(row=>row.rating);const average=rated.length?(rated.reduce((s,r)=>s+Number(r.rating),0)/rated.length).toFixed(1):"—";
 return <div className="prompt-library">
 <div inert={Boolean(mobile&&current)}><header className="pv-heading"><div><nav>Library <ChevronRight size={13}/> Prompts</nav><h1>Prompts</h1><p>Reusable instructions and prompt templates with variables, versions, and a record of what works.</p></div><button className="pv-primary" onClick={()=>edit()}><Plus size={19}/>New prompt</button></header>
 {preview&&<p className="pv-preview">Design preview · Sample prompts, changes stay in this preview.<Link href="/prompts">Return to workspace</Link></p>}
 <div className="pv-metrics">{[[FileText,"Total prompts",records.length,"Across your workspace"],[Layers,"Variable templates",records.filter(r=>promptVariables(r.prompt_text??r.prompt??"").length).length,"Ready to personalize"],[ChartNoAxesColumnIncreasing,"Total uses",totalUses,"Recorded template preparations"],[Star,"Average rating",average,rated.length?`${rated.length} rated prompts · out of 5`:"No ratings recorded"]].map(([Icon,label,value,caption])=>{const I=Icon as typeof FileText;return <section key={String(label)}><span className="pv-icon"><I size={28}/></span><div><small>{String(label)}</small><strong>{String(value)}</strong><span>{String(caption)}</span></div></section>})}</div>
 <div className="pv-toolbar"><label><Search size={18}/><input ref={searchRef} aria-label="Search prompts" placeholder="Search prompts…" value={query} onChange={e=>setQuery(e.target.value)}/>{query&&<button aria-label="Clear search" onClick={()=>{setQuery("");searchRef.current?.focus()}}><X size={16}/></button>}</label><StyledSelect label="Category" value={category} onChange={setCategory} options={[{value:"all",label:"All categories"},...promptCategories.map(value=>({value,label:value}))]}/><StyledSelect label="Favorites" value={favorites} onChange={setFavorites} options={[{value:"all",label:"All prompts"},{value:"favorites",label:"Favorites"}]}/><StyledSelect label="Sort prompts" value={sort} onChange={setSort} options={[{value:"updated",label:"Last updated"},{value:"uses",label:"Most used"},{value:"name",label:"Name"}]}/><div className="pv-view"><button aria-label="List view" aria-pressed={!grid} onClick={()=>setGrid(false)}><List size={20}/></button><button aria-label="Grid view" aria-pressed={grid} onClick={()=>setGrid(true)}><LayoutGrid size={19}/></button></div></div></div>
 <div className={`pv-layout ${current?"has-detail":""}`}><section className="pv-results" inert={Boolean(mobile&&current)} aria-label="Prompt library">
 {loading?<div className="pv-empty" role="status">Loading your prompt library…</div>:error?<div className="pv-empty" role="alert"><h2>Prompts could not be loaded</h2><p>{error}</p><button className="pv-primary" onClick={()=>setRetry(n=>n+1)}>Try again</button></div>:!rows.length?<div className="pv-empty"><span className="pv-icon"><FileText size={30}/></span><h2>{records.length?"No matching prompts":"Your prompt library starts here"}</h2><p>{records.length?"Try another search or reset your filters.":"Save instructions you use often, then personalize them with variables whenever you need them."}</p><button className="pv-primary" onClick={()=>records.length?(setQuery(""),setCategory("all"),setFavorites("all")):edit()}>{records.length?"Reset filters":"Create your first prompt"}</button></div>:<><div className={`pv-table ${grid?"is-grid":""}`}><div className="pv-table-head"><span>Prompt</span><span>Category</span><span>Variables</span><span>Uses</span><span>Last updated</span><span/></div>{rows.map(row=><article className={`pv-row ${selected===row.id?"selected":""}`} key={row.id}><button className="pv-record" onClick={e=>choose(row,e.currentTarget)} aria-expanded={selected===row.id}><span className={`pv-icon tone-${row.category.toLowerCase().replaceAll(" ","-")}`}><FileText size={25}/></span><span><strong>{row.title}</strong><span className="pv-excerpt">{row.description||"Reusable prompt template"}</span><span className="pv-tags">{promptVariables(row.prompt_text??row.prompt??"").slice(0,3).map(name=><span key={name}>{`{${name}}`}</span>)}{row.favorite&&<span><Star size={10}/>Favorite</span>}</span></span></button><span className="pv-category">{row.category}</span><span className="pv-count">{promptVariables(row.prompt_text??row.prompt??"").length}</span><span className="pv-count">{row.usage_count??0}</span><time>{date(row.updated_at)}</time><button className="pv-edit" aria-label={`Edit ${row.title}`} onClick={()=>edit(row)}><Pencil size={15}/></button></article>)}</div><footer>{rows.length} of {records.length} prompts</footer></>}
 </section>
 {current&&<><button className="pv-scrim" tabIndex={-1} aria-hidden="true" aria-label="Close prompt details" onClick={()=>setSelected(null)}/><aside ref={detailRef} className="pv-detail" role={mobile?"dialog":undefined} aria-modal={mobile||undefined} aria-labelledby="pv-detail-title"><header><span className="pv-icon"><FileText size={29}/></span><div><h2 id="pv-detail-title">{current.title}</h2><p>{current.description||"Reusable workspace instruction"}</p></div><button aria-label="Close prompt details" onClick={()=>setSelected(null)}><X size={18}/></button></header><div className="pv-actions"><button className="pv-primary" onClick={()=>{setValues({});setResult("");setFormError("");setRunner(true)}}><Play size={14}/>Use prompt</button><button onClick={()=>edit(current,true)}><Copy size={15}/>Duplicate</button><button onClick={()=>edit(current)}><Pencil size={15}/>Edit</button></div><div className="pv-tabs" role="tablist" aria-label="Prompt details">{["Overview","Versions","Variables","Activity"].map((name,index)=><button key={name} role="tab" id={`pv-tab-${name}`} aria-controls="pv-tab-panel" aria-selected={tab===name} tabIndex={tab===name?0:-1} onClick={()=>setTab(name)} onKeyDown={e=>{const names=["Overview","Versions","Variables","Activity"];const next=e.key==="ArrowRight"?(index+1)%4:e.key==="ArrowLeft"?(index+3)%4:e.key==="Home"?0:e.key==="End"?3:-1;if(next>=0){e.preventDefault();setTab(names[next]);document.getElementById(`pv-tab-${names[next]}`)?.focus()}}}>{name}</button>)}</div>
 <div id="pv-tab-panel" role="tabpanel" aria-labelledby={`pv-tab-${tab}`}>
 {tab==="Overview"?<><section className="pv-section"><FileText size={18}/><div><h3>Description</h3><p>{current.description||"Add a description to explain when to use this prompt."}</p></div></section><section className="pv-prompt"><div><h3><Pencil size={17}/>Prompt preview</h3><button onClick={()=>void copy(text)}><Copy size={14}/>Copy</button></div><pre>{text}</pre></section><section className="pv-prompt"><div><h3><Braces size={18}/>Variables</h3><button onClick={()=>{setTab("Variables")}}>View all</button></div><div className="pv-variable-chips">{variables.length?variables.map(name=><span key={name}>{`{${name}}`}</span>):<p>No variables. This prompt is ready to use.</p>}</div></section><div className="pv-meta"><span>{current.category}</span><span>{current.usage_count??0} uses</span>{current.favorite&&<span><Star size={12}/>Favorite</span>}</div></>:tab==="Versions"?<section className="pv-history"><h3>Version history</h3><p>Earlier instructions are saved automatically when you edit a prompt.</p>{versionLoading?<p role="status">Loading versions…</p>:versionError?<div role="alert"><p>{versionError}</p><button onClick={()=>setRetry(n=>n+1)}>Try again</button></div>:versions.length?versions.map(version=><details key={version.id}><summary>Version {version.version_number}<time>{date(version.created_at)}</time></summary><p>{version.change_note}</p><pre>{version.prompt_text}</pre><button disabled={busy} onClick={()=>void restore(version)}>Restore this version</button></details>):<p className="pv-note">No earlier versions yet.</p>}</section>:tab==="Variables"?<section className="pv-history"><h3>Personalize this template</h3><p>Use braces in your instructions, like {"{topic}"}. Fill these values when preparing the prompt.</p>{variables.map(name=><div className="pv-variable" key={name}><code>{`{${name}}`}</code><span>{name.replaceAll("_"," ")}</span><span>Required</span></div>)}{!variables.length&&<p className="pv-note">No variables found in this template.</p>}<button className="pv-primary" onClick={()=>edit(current)}>Edit instructions</button></section>:<section className="pv-history"><h3>Recorded activity</h3>{[[Clock,"Created",current.created_at],[Pencil,"Last updated",current.updated_at],[Activity,"Last used",current.last_used_at]].map(([Icon,label,value])=>{const I=Icon as typeof Clock;return <div className="pv-event" key={String(label)}><I size={18}/><div><strong>{String(label)}</strong><p>{date(value as string)}</p></div></div>})}<p className="pv-note">{current.usage_count??0} recorded preparations. No generated output is stored here.</p></section>}
 </div></aside></>}
 </div>
 <Modal open={editor} onClose={()=>{if(!busy)setEditor(false)}} title={editing?"Edit prompt":"New prompt"} description="Use {variable_name} to make instructions reusable."><form className="pv-form" noValidate onSubmit={save}><label htmlFor="prompt-title">Title<input id="prompt-title" maxLength={240} value={draft.title} aria-invalid={!!formError&&!draft.title.trim()} onChange={e=>setDraft({...draft,title:e.target.value})}/></label><label htmlFor="prompt-description">Description<textarea className="resize-none" id="prompt-description" rows={3} style={{resize:"none"}} value={draft.description} onChange={e=>setDraft({...draft,description:e.target.value})}/></label><label>Category<StyledSelect label="Prompt category" value={draft.category} onChange={category=>setDraft({...draft,category})} options={promptCategories.map(value=>({value,label:value}))}/></label><label htmlFor="prompt-text">Instructions<textarea className="resize-none" id="prompt-text" rows={9} maxLength={20000} style={{resize:"none"}} aria-invalid={!!formError&&!draft.prompt_text.trim()} value={draft.prompt_text} onChange={e=>setDraft({...draft,prompt_text:e.target.value})}/></label><label className="pv-check"><input type="checkbox" checked={draft.favorite} onChange={e=>setDraft({...draft,favorite:e.target.checked})}/>Save as a favorite</label>{formError&&<p role="alert" className="field-error">{formError}</p>}<footer><Button disabled={busy} emphasis="ghost" onClick={()=>setEditor(false)}>Cancel</Button><Button disabled={busy} intent="brand" type="submit">{busy?"Saving…":"Save prompt"}</Button></footer></form></Modal>
 <Modal open={runner} onClose={()=>{if(!busy)setRunner(false)}} title="Use prompt" description="Fill the variables to prepare instructions you can copy into your AI tool."><form className="pv-form" noValidate onSubmit={prepare}>{variables.map(name=><label key={name} htmlFor={`pv-${name}`}>{name.replaceAll("_"," ")}<input id={`pv-${name}`} value={values[name]??""} onChange={e=>{setResult("");setValues({...values,[name]:e.target.value})}}/></label>)}{!variables.length&&<p>This template has no variables and is ready to prepare.</p>}{formError&&<p role="alert" className="field-error">{formError}</p>}{result&&<section className="pv-output"><h3><Check size={16}/>Your prompt is ready</h3><pre>{result}</pre><Button emphasis="outline" onClick={()=>void copy(result)}>Copy prepared prompt</Button></section>}<footer><Button emphasis="ghost" disabled={busy} onClick={()=>setRunner(false)}>Close</Button><Button intent="brand" type="submit" disabled={busy||!!result}>{busy?"Preparing…":result?"Prepared":"Prepare prompt"}</Button></footer></form></Modal>
 </div>;
}
