import { NextResponse } from "next/server";
import { z } from "zod";
import { apiError } from "@/lib/api";
import { notificationCategories } from "@/lib/v4-notifications";
import { requireUser } from "@/lib/supabase/server";
const action=z.object({action:z.enum(["read","read_all","dismiss"]),id:z.uuid().optional()});
export async function GET(){try{const{supabase,userId}=await requireUser();const[items,preferences]=await Promise.all([supabase.from("notifications").select("*").eq("user_id",userId).is("dismissed_at",null).is("resolved_at",null).order("created_at",{ascending:false}).limit(60),supabase.from("notification_preferences").select("category,enabled,minimum_severity").eq("user_id",userId)]);if(items.error)throw items.error;if(preferences.error)throw preferences.error;return NextResponse.json({items:items.data??[],preferences:preferences.data??[]},{headers:{"Cache-Control":"private, no-store"}})}catch(error){return apiError(error,"Notifications could not be loaded.")}}
export async function POST(request:Request){try{const input=action.parse(await request.json());if(input.action!=="read_all"&&!input.id)return NextResponse.json({error:"Notification is required."},{status:400});const{supabase,userId}=await requireUser();let query=supabase.from("notifications").update((input.action==="dismiss"?{dismissed_at:new Date().toISOString()}:{read_at:new Date().toISOString()}) as never).eq("user_id",userId);query=input.action==="read_all"?query.is("read_at",null).is("dismissed_at",null):query.eq("id",input.id!);const{error}=await query;if(error)throw error;return NextResponse.json({ok:true})}catch(error){return apiError(error,"Notification could not be updated.")}}
export async function PUT(request:Request){try{const input=z.object({preferences:z.array(z.object({category:z.enum(notificationCategories),level:z.enum(["off","important","all"])})).length(notificationCategories.length)}).parse(await request.json());const{supabase,userId}=await requireUser();const rows=input.preferences.map(item=>({user_id:userId,category:item.category,enabled:item.level!=="off",minimum_severity:item.level==="all"?"low":"high"}));const{error}=await supabase.from("notification_preferences").upsert(rows as never,{onConflict:"user_id,category"});if(error)throw error;return NextResponse.json({preferences:rows})}catch(error){return apiError(error,"Notification preferences could not be saved.")}}
