import { NextResponse } from "next/server";
import { z } from "zod";
import { apiError } from "@/lib/api";
import { requireUser } from "@/lib/supabase/server";

const blank = (value: unknown) => typeof value === "string" && !value.trim() ? null : value;
const optionalNumber = z.preprocess(blank, z.coerce.number().nonnegative().nullable().optional());
const productSchema = z.object({ id: z.uuid().optional(), name: z.string().trim().min(1).max(240), sku: z.preprocess(blank, z.string().max(160).nullable().optional()), category: z.preprocess(blank, z.string().max(160).nullable().optional()), currency: z.string().trim().length(3).transform((value) => value.toUpperCase()).default("MAD"), unit_cost: optionalNumber, active: z.boolean().default(true) });
const inventorySchema = z.object({ product_id: z.uuid(), available_stock: optionalNumber, reserved_stock: optionalNumber, reorder_level: optionalNumber, captured_at: z.iso.datetime().optional() });

async function activeCompany() { const { supabase, userId } = await requireUser(); const company = await supabase.from("companies").select("id").eq("user_id", userId).eq("active", true).maybeSingle(); if (company.error) throw company.error; if (!company.data) throw new Error("Set up your company before managing products."); return { supabase, userId, companyId: company.data.id }; }

export async function GET() { try { const { supabase, userId, companyId } = await activeCompany(); const [products, inventory] = await Promise.all([supabase.from("product_catalog_refs").select("*").eq("user_id", userId).eq("company_id", companyId).order("name").limit(100), supabase.from("inventory_snapshots").select("*").eq("user_id", userId).eq("company_id", companyId).order("captured_at", { ascending: false }).limit(400)]); if (products.error) throw products.error; if (inventory.error) throw inventory.error; const latest = new Map<string, Record<string, unknown>>(); for (const snapshot of inventory.data ?? []) if (!latest.has(String(snapshot.product_id))) latest.set(String(snapshot.product_id), snapshot); return NextResponse.json({ products: (products.data ?? []).map((product) => ({ ...product, latest_inventory: latest.get(product.id) ?? null })) }); } catch (error) { return apiError(error, "Products could not be loaded."); } }

export async function POST(request: Request) { try { const input = productSchema.parse(await request.json()); const { supabase, userId, companyId } = await activeCompany(); const row = { ...input, user_id: userId, company_id: companyId }; const result = input.id ? await supabase.from("product_catalog_refs").update(row as never).eq("id", input.id).eq("user_id", userId).eq("company_id", companyId).select("*").maybeSingle() : await supabase.from("product_catalog_refs").insert(row as never).select("*").single(); if (result.error) throw result.error; if (!result.data) return NextResponse.json({ error: "That product is not available in your workspace." }, { status: 404 }); return NextResponse.json({ product: result.data }, { status: input.id ? 200 : 201 }); } catch (error) { return apiError(error, "Product could not be saved."); } }

export async function PUT(request: Request) { try { const input = inventorySchema.parse(await request.json()); const { supabase, userId, companyId } = await activeCompany(); const product = await supabase.from("product_catalog_refs").select("id").eq("id", input.product_id).eq("user_id", userId).eq("company_id", companyId).maybeSingle(); if (product.error) throw product.error; if (!product.data) return NextResponse.json({ error: "The product is not available in your workspace." }, { status: 422 }); const saved = await supabase.from("inventory_snapshots").insert({ ...input, captured_at: input.captured_at ?? new Date().toISOString(), source: "manual", user_id: userId, company_id: companyId } as never).select("*").single(); if (saved.error) throw saved.error; return NextResponse.json({ inventory: saved.data }, { status: 201 }); } catch (error) { return apiError(error, "Inventory snapshot could not be recorded."); } }
