import { NextResponse } from "next/server";
import { z } from "zod";
import { apiError } from "@/lib/api";
import { requireUser } from "@/lib/supabase/server";

const blank = (value: unknown) => typeof value === "string" && !value.trim() ? null : value;
const optionalNumber = z.preprocess(blank, z.coerce.number().nonnegative().nullable().optional());
const optionalDate = z.preprocess(blank, z.iso.datetime().nullable().optional());
const schema = z.object({ supplier_id: z.uuid(), status: z.enum(["draft", "ordered", "partially_received", "received", "canceled"]).default("draft"), reference: z.preprocess(blank, z.string().max(160).nullable().optional()), ordered_at: optionalDate, expected_at: optionalDate, received_at: optionalDate, total_value: optionalNumber, currency: z.string().trim().length(3).transform((value) => value.toUpperCase()).default("MAD"), notes: z.preprocess(blank, z.string().max(5000).nullable().optional()), items: z.array(z.object({ product_id: z.preprocess(blank, z.uuid().nullable().optional()), product_name: z.string().trim().min(1).max(240), quantity: z.coerce.number().positive(), unit_cost: optionalNumber })).max(100).default([]) });

export async function GET() { try { const { supabase, userId } = await requireUser(); const company = await supabase.from("companies").select("id").eq("user_id", userId).eq("active", true).maybeSingle(); if (company.error) throw company.error; if (!company.data) return NextResponse.json({ orders: [], suppliers: [], products: [] }); const [orders, suppliers, products] = await Promise.all([supabase.from("supplier_orders").select("*,supplier_records(name),supplier_order_items(*)").eq("user_id", userId).eq("company_id", company.data.id).order("updated_at", { ascending: false }).limit(50), supabase.from("supplier_records").select("id,name").eq("user_id", userId).eq("company_id", company.data.id).eq("active", true).order("name"), supabase.from("product_catalog_refs").select("id,name,sku").eq("user_id", userId).eq("company_id", company.data.id).eq("active", true).order("name")]); const failed = [orders, suppliers, products].find((result) => result.error); if (failed?.error) throw failed.error; return NextResponse.json({ orders: orders.data ?? [], suppliers: suppliers.data ?? [], products: products.data ?? [] }); } catch (error) { return apiError(error, "Supplier orders could not be loaded."); } }
export async function POST(request: Request) { try { const input = schema.parse(await request.json()); const { supabase, userId } = await requireUser(); const company = await supabase.from("companies").select("id").eq("user_id", userId).eq("active", true).maybeSingle(); if (company.error) throw company.error; if (!company.data) return NextResponse.json({ error: "Set up your company before creating an order." }, { status: 422 }); const order = { ...input, user_id: userId, company_id: company.data.id }; const { data, error } = await supabase.rpc("create_supplier_order_with_items", { order_payload: order, item_payload: input.items } as never); if (error) throw error; return NextResponse.json({ order: data }, { status: 201 }); } catch (error) { return apiError(error, "Supplier order could not be created."); } }
