import { NextResponse } from "next/server";
import { z } from "zod";
import { apiError } from "@/lib/api";
import { requireUser } from "@/lib/supabase/server";

const statuses = z.enum(["draft", "ordered", "partially_received", "received", "canceled"]);
const allowed: Record<z.infer<typeof statuses>, z.infer<typeof statuses>[]> = { draft: ["ordered", "canceled"], ordered: ["partially_received", "received", "canceled"], partially_received: ["received", "canceled"], received: [], canceled: [] };
const optionalNumber = z.preprocess((value) => value === "" ? null : value, z.coerce.number().nonnegative().nullable().optional());
const draftEdit = z.object({ supplier_id: z.uuid(), reference: z.string().max(160).nullable().optional(), ordered_at: z.string().datetime().nullable().optional(), expected_at: z.string().datetime().nullable().optional(), total_value: optionalNumber, currency: z.string().trim().length(3), notes: z.string().max(5000).nullable().optional(), items: z.array(z.object({ product_id: z.uuid().nullable(), product_name: z.string().trim().min(1).max(240), quantity: z.coerce.number().positive(), unit_cost: optionalNumber })).max(100) });
export async function PATCH(request: Request, { params }: { params: Promise<{ id: string }> }) { try { const id = z.uuid().parse((await params).id); const payload = await request.json() as unknown; const { supabase, userId } = await requireUser(); const order = await supabase.from("supplier_orders").select("id,status").eq("id", id).eq("user_id", userId).maybeSingle(); if (order.error) throw order.error; if (!order.data) return NextResponse.json({ error: "Supplier order is not available." }, { status: 404 }); if (typeof payload === "object" && payload !== null && "edit" in payload) { const input = draftEdit.parse((payload as { edit: unknown }).edit); const saved = await supabase.rpc("update_supplier_order_draft", { order_id_value: id, order_payload: input, item_payload: input.items } as never); if (saved.error) throw saved.error; await supabase.from("action_audit_log").insert({ user_id: userId, actor: "user", action_type: "supplier_order_edited", entity_type: "supplier_order", entity_id: id, summary: "Draft supplier order edited." }); return NextResponse.json({ order: saved.data }); }
 const input = z.object({ status: statuses }).parse(payload); if (!allowed[order.data.status as z.infer<typeof statuses>].includes(input.status)) return NextResponse.json({ error: "That supplier-order transition is not allowed." }, { status: 422 }); const saved = await supabase.from("supplier_orders").update({ status: input.status } as never).eq("id", id).eq("user_id", userId).select("*").single(); if (saved.error) throw saved.error; await supabase.from("action_audit_log").insert({ user_id: userId, actor: "user", action_type: "supplier_order_status_changed", entity_type: "supplier_order", entity_id: id, summary: input.status }); return NextResponse.json({ order: saved.data }); } catch (error) { return apiError(error, "Supplier order could not be updated."); } }
export async function POST(request: Request, { params }: { params: Promise<{ id: string }> }) { try { const id = z.uuid().parse((await params).id); const input = z.object({ idempotency_key: z.string().uuid(), items: z.array(z.object({ item_id: z.uuid(), quantity_received: z.coerce.number().positive() })).min(1).max(100) }).parse(await request.json()); const { supabase, userId } = await requireUser(); const result = await supabase.rpc("receive_supplier_order_items", { order_id_value: id, receipt_key: input.idempotency_key, receipt_items: input.items } as never); if (result.error) throw result.error; await supabase.from("action_audit_log").insert({ user_id: userId, actor: "user", action_type: "supplier_order_received", entity_type: "supplier_order", entity_id: id, summary: "Confirmed received supplier stock." }); return NextResponse.json({ order: result.data }); } catch (error) { return apiError(error, "Supplier receipt could not be confirmed."); } }
