create extension if not exists pgcrypto;

create type task_status as enum ('inbox','planned','in_progress','waiting','blocked','completed','cancelled');
create type task_priority as enum ('none','low','medium','high','urgent');
create type project_status as enum ('idea','planning','active','paused','completed','archived');
create type integration_status as enum ('disconnected','connected','expired','error');

create table profiles (id uuid primary key references auth.users(id) on delete cascade, display_name text, avatar_url text, timezone text not null default 'Africa/Casablanca', week_starts_on smallint not null default 1 check (week_starts_on between 0 and 6), preferences jsonb not null default '{}'::jsonb, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table clients (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, name text not null, company text, email text, phone text, website text, status text not null default 'active', notes text, last_contact_at timestamptz, next_follow_up_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), deleted_at timestamptz);
create table client_contacts (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, client_id uuid not null references clients(id) on delete cascade, name text not null, email text, phone text, role text, is_primary boolean not null default false, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table goals (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, title text not null, description text, period text not null check (period in ('quarter','month','week')), target_date date, status text not null default 'active', progress numeric(5,2) not null default 0 check (progress between 0 and 100), progress_mode text not null default 'manual', created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table projects (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, name text not null, description text, status project_status not null default 'idea', category text, color text, icon text, client_id uuid references clients(id) on delete set null, goal_id uuid references goals(id) on delete set null, start_date date, target_date date, progress numeric(5,2) not null default 0 check (progress between 0 and 100), priority task_priority not null default 'none', repository_url text, production_url text, staging_url text, notes text, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), deleted_at timestamptz);
create table tasks (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, title text not null check (length(title) between 1 and 240), description text, status task_status not null default 'inbox', priority task_priority not null default 'none', project_id uuid references projects(id) on delete set null, client_id uuid references clients(id) on delete set null, goal_id uuid references goals(id) on delete set null, due_date date, due_time time, scheduled_start timestamptz, scheduled_end timestamptz, estimated_minutes integer check (estimated_minutes between 1 and 1440), actual_minutes integer check (actual_minutes >= 0), energy_level text check (energy_level in ('low','medium','high')), context text, waiting_for text, recurrence_rule text, parent_task_id uuid references tasks(id) on delete cascade, created_by text not null default 'user' check (created_by in ('user','ai','integration')), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), completed_at timestamptz, deleted_at timestamptz);
create table tags (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, name text not null, color text, created_at timestamptz not null default now(), unique(user_id,name));
create table task_tags (task_id uuid references tasks(id) on delete cascade, tag_id uuid references tags(id) on delete cascade, primary key(task_id,tag_id));
create table task_dependencies (task_id uuid references tasks(id) on delete cascade, depends_on_task_id uuid references tasks(id) on delete cascade, primary key(task_id,depends_on_task_id), check(task_id <> depends_on_task_id));
create table milestones (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, project_id uuid not null references projects(id) on delete cascade, name text not null, description text, target_date date, status text not null default 'planned', progress numeric(5,2) not null default 0 check(progress between 0 and 100), created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table followups (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, client_id uuid references clients(id) on delete cascade, project_id uuid references projects(id) on delete set null, title text not null, due_at timestamptz, status text not null default 'open', notes text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table waiting_items (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, title text not null, client_id uuid references clients(id) on delete set null, project_id uuid references projects(id) on delete set null, requested_at timestamptz not null default now(), expected_by timestamptz, contact text, status text not null default 'waiting', notes text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table notes (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, title text not null, content text not null default '', category text not null default 'note', created_by text not null default 'user', created_at timestamptz not null default now(), updated_at timestamptz not null default now(), deleted_at timestamptz);
create table ideas (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, title text not null, description text, category text, project_id uuid references projects(id) on delete set null, potential text check (potential in ('low','medium','high','huge')), effort text, status text not null default 'captured', created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table decisions (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, title text not null, decision text not null, reasoning text, project_id uuid references projects(id) on delete set null, alternatives text, decision_date date not null default current_date, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table prompts (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, title text not null, prompt text not null, description text, category text, favorite boolean not null default false, usage_count integer not null default 0, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table note_links (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, note_id uuid not null references notes(id) on delete cascade, entity_type text not null, entity_id uuid not null, created_at timestamptz not null default now());
create table goal_links (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, goal_id uuid not null references goals(id) on delete cascade, entity_type text not null, entity_id uuid not null, created_at timestamptz not null default now());
create table calendar_events (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, title text not null, description text, starts_at timestamptz not null, ends_at timestamptz not null, all_day boolean not null default false, timezone text not null default 'Africa/Casablanca', task_id uuid references tasks(id) on delete set null, provider text not null default 'local', external_event_id text, external_updated_at timestamptz, sync_hash text, last_synced_at timestamptz, recurrence_rule text, status text not null default 'confirmed', created_at timestamptz not null default now(), updated_at timestamptz not null default now(), check(ends_at >= starts_at));
create table focus_sessions (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, task_id uuid references tasks(id) on delete set null, started_at timestamptz not null, ended_at timestamptz, duration_seconds integer check(duration_seconds >= 0), mode text not null default 'count_up', notes text, created_at timestamptz not null default now());
create table invoices (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, client_id uuid references clients(id) on delete set null, project_id uuid references projects(id) on delete set null, invoice_number text, amount numeric(14,2) not null check(amount >= 0), currency char(3) not null default 'MAD', status text not null default 'draft', invoice_date date, due_date date, paid_at timestamptz, notes text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table finance_transactions (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, client_id uuid references clients(id) on delete set null, project_id uuid references projects(id) on delete set null, type text not null check(type in ('income','expense','subscription')), amount numeric(14,2) not null check(amount >= 0), currency char(3) not null default 'MAD', occurred_on date not null, status text not null default 'recorded', notes text, created_at timestamptz not null default now());
create table content_items (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, title text not null, client_id uuid references clients(id) on delete set null, project_id uuid references projects(id) on delete set null, platform text, format text, caption text, hook text, brief text, status text not null default 'ideas', publish_date timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table fitness_activities (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, activity_type text not null, activity_date date not null, duration_seconds integer check(duration_seconds > 0), distance_meters numeric(12,2), notes text, source text not null default 'manual', external_activity_id text, created_at timestamptz not null default now(), unique(user_id,source,external_activity_id));
create table integrations (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, provider text not null, account_identifier text, status integration_status not null default 'disconnected', access_token_encrypted bytea, refresh_token_encrypted bytea, expires_at timestamptz, provider_metadata jsonb not null default '{}'::jsonb, last_synced_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(user_id,provider));
create table notifications (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, type text not null, title text not null, body text, read_at timestamptz, entity_type text, entity_id uuid, created_at timestamptz not null default now());
create table activity_log (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, action text not null, entity_type text not null, entity_id uuid, metadata jsonb not null default '{}'::jsonb, actor text not null default 'user', created_at timestamptz not null default now());
create table daily_plans (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, plan_date date not null, notes text, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(user_id,plan_date));
create table daily_priorities (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, plan_id uuid not null references daily_plans(id) on delete cascade, task_id uuid not null references tasks(id) on delete cascade, position smallint not null check(position between 1 and 3), created_at timestamptz not null default now(), unique(plan_id,position), unique(plan_id,task_id));
create table daily_reviews (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, review_date date not null, went_well text, needs_attention text, capture text, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(user_id,review_date));
create table attachments (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, entity_type text not null, entity_id uuid not null, storage_path text not null, file_name text not null, mime_type text, size_bytes bigint check(size_bytes >= 0), created_at timestamptz not null default now());
create table external_links (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, entity_type text not null, entity_id uuid not null, provider text, label text not null, url text not null, external_id text, metadata jsonb not null default '{}'::jsonb, created_at timestamptz not null default now());
create table calendar_sync_state (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, integration_id uuid not null references integrations(id) on delete cascade, calendar_id text not null, sync_token text, channel_id text, channel_expires_at timestamptz, last_synced_at timestamptz, unique(user_id,integration_id,calendar_id));
create table ai_conversations (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, title text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table ai_messages (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, conversation_id uuid not null references ai_conversations(id) on delete cascade, role text not null check(role in ('user','assistant','tool')), content text not null, tool_name text, tool_metadata jsonb not null default '{}'::jsonb, created_at timestamptz not null default now());

create index tasks_user_status_due_idx on tasks(user_id,status,due_date) where deleted_at is null; create index tasks_search_idx on tasks using gin(to_tsvector('simple',title||' '||coalesce(description,'')));
create index projects_user_status_idx on projects(user_id,status) where deleted_at is null; create index notes_search_idx on notes using gin(to_tsvector('simple',title||' '||content)); create index waiting_user_expected_idx on waiting_items(user_id,status,expected_by); create index calendar_user_start_idx on calendar_events(user_id,starts_at); create index notifications_user_unread_idx on notifications(user_id,created_at desc) where read_at is null;

create or replace function set_updated_at() returns trigger language plpgsql as $$ begin new.updated_at=now(); return new; end $$;
do $$ declare t text; begin foreach t in array array['profiles','clients','goals','projects','tasks','milestones','followups','waiting_items','notes','ideas','decisions','prompts','calendar_events','invoices','content_items','integrations','daily_plans','daily_reviews'] loop execute format('create trigger %I_updated before update on %I for each row execute function set_updated_at()',t,t); end loop; end $$;

create or replace function search_workspace(search_query text,result_limit int default 30) returns table(entity_type text,entity_id uuid,title text,snippet text,rank real,updated_at timestamptz) language sql security invoker set search_path=public as $$
  select * from (
    select 'task',id,title,coalesce(description,''),ts_rank(to_tsvector('simple',title||' '||coalesce(description,'')),plainto_tsquery('simple',search_query)),tasks.updated_at from tasks where user_id=auth.uid() and deleted_at is null and to_tsvector('simple',title||' '||coalesce(description,'')) @@ plainto_tsquery('simple',search_query)
    union all select 'project',id,name,coalesce(description,''),ts_rank(to_tsvector('simple',name||' '||coalesce(description,'')),plainto_tsquery('simple',search_query)),projects.updated_at from projects where user_id=auth.uid() and deleted_at is null and to_tsvector('simple',name||' '||coalesce(description,'')) @@ plainto_tsquery('simple',search_query)
    union all select 'note',id,title,left(content,240),ts_rank(to_tsvector('simple',title||' '||content),plainto_tsquery('simple',search_query)),notes.updated_at from notes where user_id=auth.uid() and deleted_at is null and to_tsvector('simple',title||' '||content) @@ plainto_tsquery('simple',search_query)
  ) as results(
    entity_type,
    entity_id,
    title,
    snippet,
    rank,
    updated_at
  ) order by results.rank desc,results.updated_at desc limit least(result_limit,50)
$$;

do $$ declare t text; begin foreach t in array array['profiles','clients','client_contacts','goals','projects','tasks','tags','task_tags','task_dependencies','milestones','followups','waiting_items','notes','ideas','decisions','prompts','note_links','goal_links','calendar_events','focus_sessions','invoices','finance_transactions','content_items','fitness_activities','integrations','notifications','activity_log','daily_plans','daily_priorities','daily_reviews','attachments','external_links','calendar_sync_state','ai_conversations','ai_messages'] loop execute format('alter table %I enable row level security',t); end loop; end $$;
create policy profiles_owner_all on profiles for all using(id=auth.uid()) with check(id=auth.uid());
do $$ declare t text; begin foreach t in array array['clients','client_contacts','goals','projects','tasks','tags','milestones','followups','waiting_items','notes','ideas','decisions','prompts','note_links','goal_links','calendar_events','focus_sessions','invoices','finance_transactions','content_items','fitness_activities','integrations','notifications','activity_log','daily_plans','daily_priorities','daily_reviews','attachments','external_links','calendar_sync_state','ai_conversations','ai_messages'] loop execute format('create policy %I_owner_all on %I for all using (user_id=auth.uid()) with check (user_id=auth.uid())',t,t); end loop; end $$;
create policy task_tags_owner_all on task_tags for all using (exists(select 1 from tasks where tasks.id=task_id and tasks.user_id=auth.uid())) with check (exists(select 1 from tasks where tasks.id=task_id and tasks.user_id=auth.uid()));
create policy task_dependencies_owner_all on task_dependencies for all using (exists(select 1 from tasks where tasks.id=task_id and tasks.user_id=auth.uid())) with check (exists(select 1 from tasks where tasks.id=task_id and tasks.user_id=auth.uid()));

insert into storage.buckets(id,name,public,file_size_limit) values('attachments','attachments',false,20971520) on conflict(id) do nothing;
create policy attachments_storage_read on storage.objects for select using(bucket_id='attachments' and (storage.foldername(name))[1]=auth.uid()::text);
create policy attachments_storage_write on storage.objects for insert with check(bucket_id='attachments' and (storage.foldername(name))[1]=auth.uid()::text);
