"use client";
import Link from "next/link";
import { useCallback,useEffect,useState } from "react";
import { useDeferredEffect } from "@/lib/use-deferred-effect";
import { subscribeToWorkspaceMutations,domainKeysForFounder } from "@/lib/workspace-mutations";
import type { technicalSystems } from "@/lib/founder-os/continuity";
import type { Signal } from "@/lib/founder-os/intelligence";
type Data={systems:(ReturnType<typeof technicalSystems>[number]&{businessName:unknown})[];signals:Signal[];coverage:string[]};
export function ContinuityPanel(){
 const [data,setData]=useState<Data|null>(null),[error,setError]=useState("");
 const load=useCallback(async()=>{try{const res=await fetch("/api/founder-continuity",{cache:"no-store"}),body=await res.json();if(!res.ok)throw new Error(body.error);setData(body);setError("");}catch(e){setError(String(e));}},[]);
 useDeferredEffect(useCallback(()=>{void load();},[load]));useEffect(()=>subscribeToWorkspaceMutations(domainKeysForFounder,()=>void load()),[load]);
 return <section className="founder-workspace"><h2>System continuity & technical evidence</h2><p>Recorded metadata only. A past successful check does not establish current provider health.</p><nav className="founder-module-links"><Link href="/infrastructure">System registry</Link><Link href="/infrastructure/access">Access ownership</Link><Link href="/infrastructure/health">Record component evidence</Link></nav>{error&&<p role="alert">{error}</p>}{data?.coverage.length?<p role="status">Partial evidence: {data.coverage.join(", ")} exceeds the loaded-record limit.</p>:null}{data?.systems.map(s=><details className="founder-record" key={s.id}><summary>{String(s.name)} · {String(s.businessName)} · {String(s.criticality)} · renewal {s.renewalBand}</summary><p>{String(s.owner_label??"No accountable owner")} · {s.coverage.count} distinct administrators · {s.coverage.backup?"Backup recorded":"No distinct backup"}</p><p>Version {String(s.current_version??"unknown")} · Branch {String(s.branch??"unknown")} · Migration {String(s.migration_status??"unknown")}</p><p>Latest recorded successful deployment: {s.latestSuccessful?String(s.latestSuccessful.completed_at??s.latestSuccessful.created_at):"none"}. Latest failed deployment: {s.latestFailed?String(s.latestFailed.completed_at??s.latestFailed.created_at):"none"}. Deployment/incident evidence is linked by business and project, not assumed to be a direct provider probe.</p>{s.checks.length?s.checks.map(c=><p key={c.id}><Link href={`/infrastructure/health?record=${c.id}`}>{String(c.component)} — {String(c.name)}: {c.stale?"STALE / current health unknown":String(c.status).toUpperCase()}</Link> · {String(c.reason)} · checked {String(c.checked_on)} · {String(c.source)}</p>):<p>No component observations recorded; health is unknown.</p>}{s.incidents.map(i=><p key={i.id}>{String(i.title)} · {String(i.severity)} · {String(i.status)}</p>)}{data.signals.filter(signal=>signal.sourceId===s.id||s.coverage.admins.some(a=>a.id===signal.sourceId)||s.checks.some(c=>c.id===signal.sourceId)).map(signal=><p key={signal.id}><strong>{signal.type.replaceAll("_"," ")}</strong>: {signal.reasons.join(" ")} Impact: {signal.impact} <Link href={signal.route}>{signal.action} →</Link></p>)}<Link href={`/infrastructure?record=${s.id}`}>Review system metadata →</Link></details>)}{data&&!data.systems.length&&<p>No systems recorded.</p>}</section>;
}
