"use client";
import Link from "next/link";
import { useCallback, useEffect, useState } from "react";
import { Button } from "@/components/ui/button";
import { useDeferredEffect } from "@/lib/use-deferred-effect";
import { subscribeToWorkspaceMutations, domainKeysForFounder } from "@/lib/workspace-mutations";
import type { loadTier1Briefing } from "@/lib/founder-os/briefing-server";
import { FounderStatePanel } from "./state-view";
type Data = Omit<Awaited<ReturnType<typeof loadTier1Briefing>>, "facts">;
export function ExecutiveBriefing({ mode = "executive" }: { mode?: "executive" | "weekly" | "changes" | "waiting" }) {
 const [reviewId, setReviewId] = useState<string | null>(null);
 const [data, setData] = useState<Data | null>(null), [error, setError] = useState(""), [window, setWindow] = useState(mode === "changes" ? "1" : "7"), [busy, setBusy] = useState(false);
 const load = useCallback(async () => { try { const res = await fetch(`/api/founder-briefing?window=${window}`, { cache: "no-store" }); const body = await res.json(); if (!res.ok) throw new Error(body.error); setData(body); setError(""); } catch (e) { setError(String(e)); } }, [window]);
 useDeferredEffect(useCallback(() => { void load(); }, [load]));
 useEffect(() => subscribeToWorkspaceMutations(domainKeysForFounder, () => void load()), [load]);
 const title = mode === "weekly" ? "Weekly Executive Review" : mode === "changes" ? "What Changed?" : mode === "waiting" ? "Waiting For" : "Executive Console";
 return <div className="founder-workspace"><header className="founder-page-header"><div><p className="eyebrow">Signal · context · action</p><h1>{title}</h1><p>{mode === "weekly" ? "The last 7 days of outcomes and the decisions that shape next week." : "The important state, with the evidence behind it."}</p></div><nav className="founder-module-links"><Link href="/state">Founder State</Link><Link href="/business-pulse">Business Pulse</Link><Link href="/financial-control">Financial State</Link><Link href="/experiments">Experiments</Link><Link href="/forecasts">Forecasts</Link><Link href="/assets">Assets</Link><Link href="/review/weekly">Weekly review</Link></nav></header>{error && <p role="alert">{error}</p>}{!data ? <p role="status">Assembling briefing…</p> : <>
 {data.coverage.some(c => c.status !== "available") && <p className="founder-coverage">Partial evidence: {data.coverage.filter(c => c.status !== "available").map(c => `${c.source} (${c.status})`).join(", ")}. Missing sources are not treated as healthy. New workflow storage requires the local Tier 1 migration.</p>}
 {mode === "executive" && <FounderStatePanel state={data.state} compact />}
 {mode === "executive" && (data.syntheses?.length ?? 0) > 0 && <section className="founder-record"><h2>Cross-Domain Synthesis</h2><p className="founder-coverage">Correlated patterns spanning revenue, experiments, founder capacity, and vendor commitments.</p>{data.syntheses?.map(s => <article key={s.id} className="founder-form" style={{ marginBottom: "1rem", padding: "1rem", border: "1px solid var(--border-subtle, #333)", borderRadius: "8px" }}><div><span className="eyebrow" style={{ textTransform: "uppercase" }}>{s.domain} · Synthesis</span><h3 style={{ margin: "0.25rem 0" }}>{s.title}</h3><p><strong>Observation:</strong> {s.observation}</p><ul style={{ margin: "0.5rem 0 0.5rem 1.25rem", fontSize: "0.9em" }}>{s.evidence.map((ev, i) => <li key={i}>{ev}</li>)}</ul><p><small><strong>Why it matters:</strong> {s.whyItMatters}</small></p><p><small><strong>Next step:</strong> {s.suggestedNextStep}</small></p><Link className="founder-list-row" href={s.route} style={{ display: "inline-block", marginTop: "0.5rem" }}>Take action in {s.domain} →</Link></div></article>)}</section>}
 {(mode === "executive" || mode === "waiting" || mode === "weekly") && <section className="founder-record"><h2>Who is waiting?</h2><div className="founder-form">{([['others', 'Waiting on Others'], ['me', 'Waiting on Me']] as const).map(([key, heading]) => <div key={key}><h3>{heading}</h3><p>{data.waiting[key].active} active · {data.waiting[key].overdue} overdue · {data.waiting[key].revenue} revenue blockers</p><p>{data.waiting[key].team} with a named counterpart</p>{data.waiting[key].items.slice(0, mode === "waiting" ? 100 : 3).map(r => <Link className="founder-list-row" href={r.route} key={r.id}>{String(r.title)}<span>{String(r.expected_by ?? r.due_date ?? "No date")}</span></Link>)}</div>)}</div><Link href="/commitments">Manage commitments →</Link>{mode === "waiting" && <Link href="/waiting/manage">Manage waiting records →</Link>}</section>}
 {mode !== "waiting" && <section className="founder-record"><div className="founder-section-header"><h2>What changed?</h2><label>Comparison window<select value={window} onChange={e => setWindow(e.target.value)}><option value="1">Since yesterday</option><option value="7">Last 7 days</option><option value="30">Last 30 days</option></select></label></div><p>{data.comparisonDate ? `Compared with the saved state on ${data.comparisonDate}.` : "No saved baseline exists on or before this window. Save a complete state to start building comparison history."}</p>{data.changes?.map(c => <Link className="founder-list-row" href={c.route} key={c.id}><span><strong>{c.domain}: {c.title}</strong><br />{c.before} → {c.state}</span></Link>)}{data.changes?.length === 0 && <p>No material state transitions in the compared records.</p>}<Button disabled={busy || data.coverage.some(c => c.status !== "available")} onClick={async () => { setBusy(true); try { const res = await fetch(`/api/founder-briefing?window=${window}`, { method: "POST" }); const body = await res.json(); if (!res.ok) throw new Error(body.error); await load(); } catch (e) { setError(String(e)); } finally { setBusy(false); } }}>Save reviewed state</Button></section>}
 {mode === "executive" && <><section className="founder-record"><h2>Business Pulse & financial state</h2>{data.pulse?.businesses.filter(b=>b.active).map(b=><Link className="founder-list-row" href="/business-pulse" key={b.id}><span><strong>{b.name} · {b.status}</strong><br />{b.reasons.join(" ")}</span></Link>)}{data.pulse?.metrics.slice(0, 8).map(m => <Link className="founder-list-row" href="/business-pulse" key={m.id}><span><strong>{m.name}: {m.current ?? "Unknown"} {m.unit}</strong><br />{m.reason}<br /><small>{m.limitation}</small></span></Link>)}{data.finance?.cash.map(c => <Link className="founder-list-row" href="/financial-control/accounts" key={c.id}><span>{c.name} · {c.balance ?? "Unknown"} {c.currency} · recorded {c.asOf?.slice(0, 10) ?? "date unknown"}{c.stale ? " · stale" : ""}</span></Link>)}<Link href="/business-pulse">All business metrics →</Link></section><section className="founder-record"><h2>Execution & strategic contribution</h2>{data.momentum.map(p => <details key={p.id}><summary>{p.title} · {p.status}</summary><ul>{p.reasons.map(reason => <li key={reason}>{reason}</li>)}</ul><Link href={p.route}>Review project →</Link></details>)}<h3>Alignment review</h3><p>{data.alignment.filter(r => r.aligned).length} active records contribute to recorded strategy.</p>{data.alignment.filter(r => r.review).slice(0, 10).map(r => <Link className="founder-list-row" href={r.route} key={`${r.type}:${r.id}`}><span>{r.title}<br /><small>{r.reason}</small></span></Link>)}</section><section className="founder-record"><h2>Founder bottlenecks</h2>{data.bottlenecks.length ? data.bottlenecks.map(b => <Link className="founder-list-row" key={b.id} href={b.route}><span><strong>{b.title}</strong><br />{b.reasons.join(" ")}</span></Link>) : <p>No configured bottleneck pattern was detected in the available records.</p>}</section></>}
 {(mode === "weekly" || mode === "executive") && <section className="founder-record"><h2>{mode === "weekly" ? "Review evidence" : "Review queue"}</h2><details><summary>Recorded attention · {data.attention.recordedHours.toFixed(1)} hours</summary>{Object.entries(data.attention.categories).map(([category, hours]) => <p key={category}>{category.replaceAll("_", " ")}: {hours.toFixed(1)} hours</p>)}<p>Only completed, timed sessions are counted. Missing categories remain unclassified.</p></details>{Object.entries(data.weekly).map(([heading, rows]) => <details key={heading} open={mode === "weekly" && ["Outcomes", "Next Week"].includes(heading)}><summary>{heading} · {rows.length}</summary>{rows.length ? rows.slice(0, 50).map((r, i) => <Link className="founder-list-row" href={r.route} key={`${r.id}:${i}`}><span><strong>{r.title}</strong><br />{r.why}</span></Link>) : <p>No matching evidence in the loaded records.</p>}</details>)}{mode === "weekly" && <div><Button disabled={busy || data.coverage.some(c => c.status !== "available")} onClick={async () => { setBusy(true); try { const res = await fetch("/api/founder-briefing?window=7&action=weekly", { method: "POST" }); const body = await res.json(); if (!res.ok) throw new Error(body.error); setReviewId(body.reviewId); } catch (e) { setError(String(e)); } finally { setBusy(false); } }}>Start reflection from this evidence</Button>{reviewId && <Link href={`/learning/retrospectives/${reviewId}`}>Open saved reflection →</Link>}</div>}<p>Use the existing reflection workspace to record a weekly conclusion and propose a lesson.</p><Link href="/learning/retrospectives">Record reflection & learning →</Link></section>}
 </>}</div>;
}
