"use client";

import { useCallback, useEffect, useRef, useState, type ReactNode } from "react";
import Link from "next/link";
import { Globe, Check, X, AlertTriangle, Clock3, Plus, Search, ExternalLink, Database, LockKeyhole, CreditCard, Code2, Cloud, FileText, ArrowRight, Activity, Server, RefreshCw } from "lucide-react";
import { Button } from "@/components/ui/button";
import { useDeferredEffect } from "@/lib/use-deferred-effect";
import { subscribeToWorkspaceMutations, domainKeysForFounder } from "@/lib/workspace-mutations";
import type { TechnicalSystem } from "@/lib/founder-os/continuity";
import type { Row } from "@/lib/founder-os/repository";
import "./health-dashboard.css";

type System = TechnicalSystem & { businessName: unknown };
type Data = { systems: System[]; healthChecks: Row[]; coverage: string[] };
type View = "all" | "attention" | "failed" | "recent";
type Tab = "Overview" | "Component status" | "Evidence" | "History";
const title = (value: unknown) => ({ ok: "OK", external_api: "APIs", cron: "Cron", cdn: "CDN" }[String(value)] ?? String(value ?? "Unknown").replaceAll("_", " ").replace(/^./, c => c.toUpperCase()));
const icons = { production: Server, database: Database, authentication: LockKeyhole, payments: CreditCard, external_api: Code2, storage: Cloud };
function status(check: System["checks"][number]) { return check.stale ? "unknown" : String(check.status); }
function stamp(value: unknown) { return value ? new Date(String(value).slice(0, 10) + "T12:00:00").toLocaleDateString(undefined, { month: "short", day: "numeric", year: "numeric" }) : "Not checked yet"; }
function latest(system: System) { return system.checks[0]?.checked_on; }
function score(system: System) { return system.checks.length ? Math.round(system.checks.filter(c => status(c) === "ok").length / system.checks.length * 100) : null; }
function safeUrl(value: unknown) { try { const url = new URL(String(value)); return ["https:", "http:"].includes(url.protocol) ? url.href : null; } catch { return null; } }
function StatusBadge({ value, label }: { value: string; label?: string }) { const Icon = value === "ok" ? Check : value === "failed" ? X : value === "attention" ? AlertTriangle : Clock3; return <span className={`health-status health-status--${value}`}><Icon size={14}/>{label ?? title(value)}</span>; }
function Ring({ system }: { system: System }) { const percent = score(system); const tone = system.checks.some(c => status(c) === "failed") ? "failed" : system.checks.some(c => status(c) === "attention") ? "attention" : percent === 100 ? "ok" : "unknown"; return <div className={`health-ring health-ring--${tone}`} style={{ "--health-progress": `${percent ?? 0}%` } as React.CSSProperties} aria-label={percent === null ? "No recorded health evidence" : `${percent}% of observed components OK`}><span>{percent ?? "—"}</span></div>; }

export function HealthDashboard({ onAdd, onEdit, children }: { onAdd: (systemId?: string) => void; onEdit: (row: Row) => void; children: ReactNode }) {
  const [data, setData] = useState<Data | null>(null), [error, setError] = useState("");
  const [query, setQuery] = useState(""), [view, setView] = useState<View>("all"), [selectedId, setSelectedId] = useState<string | null>(null), [tab, setTab] = useState<Tab>("Overview");
  const detail = useRef<HTMLElement>(null), opener = useRef<HTMLButtonElement | null>(null);
  const load = useCallback(async () => { try { const res = await fetch("/api/founder-continuity", { cache: "no-store" }); const body = await res.json(); if (!res.ok) throw new Error(body.error); setData(body); setError(""); } catch (e) { setError(e instanceof Error ? e.message : "Could not load health evidence."); } }, []);
  useDeferredEffect(useCallback(() => { void load(); }, [load]));
  useEffect(() => subscribeToWorkspaceMutations(domainKeysForFounder, () => void load()), [load]);
  const systems = data?.systems ?? [], selected = systems.find(s => s.id === selectedId), checks = systems.flatMap(s => s.checks);
  const counts = { ok: checks.filter(c => status(c) === "ok").length, attention: checks.filter(c => status(c) === "attention").length, failed: checks.filter(c => status(c) === "failed").length };
  const has = (s: System, value: string) => s.checks.some(c => status(c) === value);
  const attention = systems.filter(s => has(s, "attention")).length, failed = systems.filter(s => has(s, "failed")).length;
  const lastAudit = checks.map(c => String(c.checked_on)).sort().at(-1);
  const shown = systems.filter(s => `${s.name} ${s.external_url ?? ""} ${s.businessName}`.toLowerCase().includes(query.toLowerCase()) && (view === "attention" ? has(s, "attention") : view === "failed" ? has(s, "failed") : true)).sort((a,b) => view === "recent" ? String(latest(b) ?? "").localeCompare(String(latest(a) ?? "")) : 0);
  function close() { setSelectedId(null); opener.current?.focus(); }
  useEffect(() => { if (!selectedId) return; detail.current?.focus(); const escape = (event: KeyboardEvent) => { if (event.key === "Escape" && !document.querySelector('[role="dialog"]')) { setSelectedId(null); opener.current?.focus(); } }; document.addEventListener("keydown", escape); return () => document.removeEventListener("keydown", escape); }, [selectedId]);
  function open(system: System, button: HTMLButtonElement) { opener.current = button; setSelectedId(system.id); setTab("Overview"); }
  const history = selected ? (data?.healthChecks ?? []).filter(c => c.system_id === selected.id).sort((a,b) => String(b.checked_on).localeCompare(String(a.checked_on)) || String(b.created_at).localeCompare(String(a.created_at))) : [];
  const url = selected ? safeUrl(selected.external_url) : null;
  return <div className="health-dashboard">
    <header className="health-heading"><div><p className="eyebrow">Operating workspace</p><h1>System continuity &amp; technical evidence</h1><p>Track recorded health checks for your websites and systems. Dated component observations, not live provider status.</p></div><Button intent="brand" onClick={() => onAdd()}><Plus size={17}/>Add record</Button></header>
    <div className="health-stats">
      <article><span className="health-stat-icon"><Globe/></span><div><p>Total systems tracked</p><strong>{data ? systems.length : "—"}</strong><small>Registered websites &amp; systems</small></div></article>
      {(["ok", "attention", "failed"] as const).map(kind => <article key={kind}><span className={`health-stat-icon health-stat-icon--${kind}`}>{kind === "ok" ? <Check/> : kind === "attention" ? <AlertTriangle/> : <X/>}</span><div><p>Components {kind === "ok" ? "OK" : kind}</p><strong>{data ? counts[kind] : "—"}</strong><small>{checks.length ? `${Math.round(counts[kind] / checks.length * 100)}% of observed components` : "No observations recorded"}</small><div className={`health-meter health-meter--${kind}`}><i style={{ width: `${checks.length ? counts[kind] / checks.length * 100 : 0}%` }}/></div></div></article>)}
      <article><span className="health-stat-icon"><Clock3/></span><div><p>Last recorded check</p><strong className="health-date">{stamp(lastAudit)}</strong><small>Recorded evidence only</small></div></article>
    </div>
    {error && <div className="health-notice" role="alert">{error}<Button emphasis="outline" onClick={() => void load()}><RefreshCw size={14}/>Retry</Button></div>}
    {!!data?.coverage.length && <p className="health-notice" role="status">Partial evidence: {data.coverage.join(", ")} exceeds the loaded-record limit. Summaries reflect loaded records.</p>}
    <div className={`health-layout ${selected ? "health-layout--detail" : ""}`}><div className="health-main">
      <div className="health-toolbar"><div className="health-views" aria-label="System filters">{([["all",`All systems (${systems.length})`],["attention",`Attention (${attention})`],["failed",`Failed (${failed})`],["recent","Recent checks"]] as [View,string][]).map(([key,label]) => <button key={key} type="button" aria-pressed={view === key} onClick={() => setView(key)}>{label}</button>)}</div><button type="button" className="health-record-link" onClick={() => onAdd()}><FileText size={15}/>Record evidence</button><label className="health-search"><Search size={16}/><input aria-label="Search websites and systems" placeholder="Search websites…" value={query} onChange={e => setQuery(e.target.value)}/></label></div>
      {!data && !error && <div className="health-empty" role="status">Loading technical evidence…</div>}
      {data && !shown.length && <div className="health-empty"><Globe size={35}/><h2>{systems.length ? "No matching systems" : "Your systems, in one place"}</h2><p>{systems.length ? "Try another filter or search." : "Register a website or system, then record its component health checks."}</p>{systems.length ? <Button emphasis="outline" onClick={() => { setQuery(""); setView("all"); }}>Clear filters</Button> : <Link className="button button--outline" href="/infrastructure">Open system registry <ArrowRight size={15}/></Link>}</div>}
      {shown.map(system => <article key={system.id} className={`health-system ${selectedId === system.id ? "is-selected" : ""}`}><div className="health-system-top"><span className="health-system-icon"><Globe size={24}/></span><div className="health-system-name"><button type="button" onClick={e => open(system,e.currentTarget)}>{String(system.name)}</button><div className="health-system-meta"><span className="health-tag">{title(system.environment)}</span><span className="health-tag health-tag--neutral">{String(system.businessName)}</span></div><p>Last checked {stamp(latest(system))} · recorded evidence</p><small>Owner: {String(system.owner_label ?? "Not assigned")}</small></div><div className="health-system-score"><Ring system={system}/><div>Recorded health<small>{system.checks.filter(c => status(c) === "ok").length}/{system.checks.length} observations OK</small></div></div><Button emphasis="outline" onClick={e => open(system,e.currentTarget)}>View details</Button></div><div className="health-component-strip">{system.checks.length ? system.checks.map(check => <button type="button" key={check.id} className={`health-chip health-chip--${status(check)}`} onClick={() => onEdit(check)} title={String(check.reason)}><StatusBadge value={status(check)} label={title(check.component)}/></button>) : <p>No checks recorded. <button type="button" onClick={() => onAdd(system.id)}>Record first check →</button></p>}</div></article>)}
    </div>
    {selected && <aside className="health-detail" ref={detail} tabIndex={-1} aria-label={`Details for ${selected.name}`}><div className="health-detail-head"><span className="health-system-icon"><Globe size={25}/></span><div><h2>{String(selected.name)} {url && <a href={url} target="_blank" rel="noreferrer" aria-label="Open system website"><ExternalLink size={14}/></a>}</h2><span className="health-tag">{title(selected.environment)}</span><p>Last checked {stamp(latest(selected))}</p><small>Owner: {String(selected.owner_label ?? "Not assigned")}</small></div><button type="button" className="health-close" onClick={close} aria-label="Close project details"><X size={18}/></button></div><div className="health-detail-summary"><Ring system={selected}/><div><strong>Recorded component health</strong><p>{selected.checks.filter(c => status(c) === "ok").length}/{selected.checks.length} observations OK</p><small>Unknown or stale checks are not counted as healthy.</small></div></div>
      <div className="health-tabs" role="tablist" aria-label="Project details">{(["Overview","Component status","Evidence","History"] as Tab[]).map(item => <button key={item} id={`health-tab-${item.replaceAll(" ","-")}`} type="button" role="tab" aria-selected={tab === item} aria-controls="health-detail-content" onClick={() => setTab(item)} onKeyDown={e => { if (!["ArrowLeft","ArrowRight","Home","End"].includes(e.key)) return; e.preventDefault(); const tabs = ["Overview","Component status","Evidence","History"] as Tab[]; const index = e.key === "Home" ? 0 : e.key === "End" ? 3 : (tabs.indexOf(item) + (e.key === "ArrowRight" ? 1 : -1) + 4) % 4; setTab(tabs[index]); document.getElementById(`health-tab-${tabs[index].replaceAll(" ","-")}`)?.focus(); }} tabIndex={tab === item ? 0 : -1}>{item}{item === "Evidence" ? ` (${selected.checks.length})` : ""}</button>)}</div>
      <section id="health-detail-content" role="tabpanel" aria-labelledby={`health-tab-${tab.replaceAll(" ","-")}`}>
        {(tab === "Overview" || tab === "Component status") && <><div className="health-section-title"><h3>Component status</h3><Button emphasis="ghost" onClick={() => onAdd(selected.id)}><Plus size={14}/>Record check</Button></div><p className="health-muted">Based on the latest recorded observations. Not live polling.</p><div className="health-component-grid">{selected.checks.map(check => { const Icon = icons[check.component as keyof typeof icons] ?? Activity; return <button type="button" key={check.id} onClick={() => onEdit(check)}><span className="health-component-icon"><Icon size={20}/></span><div><strong>{title(check.component)}</strong><StatusBadge value={status(check)}/></div></button>; })}</div>{!selected.checks.length && <p className="health-muted">No observations yet. Record your first component check.</p>}</>}
        {tab === "Overview" && <div className="health-detail-bottom"><article><h3><FileText size={17}/>Latest evidence</h3><p>{selected.checks[0] ? String(selected.checks[0].reason) : "No evidence recorded yet."}</p>{selected.checks[0] && <Button emphasis="outline" onClick={() => setTab("Evidence")}>View latest evidence <ArrowRight size={15}/></Button>}</article><article><h3><Clock3 size={17}/>Recent activity</h3>{selected.checks.slice(0,3).map(check => <p key={check.id}><StatusBadge value={status(check)} label={String(check.name)}/><small>{stamp(check.checked_on)}</small></p>)}</article></div>}
        {tab === "Evidence" && <div className="health-evidence">{!selected.checks.length && <p className="health-muted">No component evidence yet. Use Record check to add an observation.</p>}{selected.checks.map(check => <article key={check.id}><div><h3>{String(check.name)}</h3><StatusBadge value={status(check)}/></div><p>{String(check.reason)}</p><small>{stamp(check.checked_on)} · {title(check.source ?? "recorded check")}{check.stale ? " · Stale observation" : ""}</small>{check.source_reference ? <p className="health-muted">Reference: {String(check.source_reference)}</p> : null}<Button emphasis="outline" onClick={() => onEdit(check)}>Edit evidence</Button></article>)}</div>}
        {tab === "History" && <div className="health-evidence"><p className="health-muted">Dated observations for this system, newest first.</p>{!history.length && <p className="health-muted">No recorded check history yet.</p>}{history.map(check => <article key={check.id}><small>{stamp(check.checked_on)}</small><h3>{String(check.name)}</h3><StatusBadge value={String(check.status)}/><p>{String(check.reason)}</p><Button emphasis="ghost" onClick={() => onEdit(check)}>Open recorded check <ArrowRight size={14}/></Button></article>)}{selected.incidents.map(incident => <article key={incident.id}><h3>{String(incident.title)}</h3><p>Recorded incident · {title(incident.status)}</p><Link href="/founder/development">Review incidents →</Link></article>)}</div>}
      </section><footer className="health-detail-footer"><Link href={`/infrastructure?record=${selected.id}`}>System settings <ArrowRight size={14}/></Link><Link href="/infrastructure/access">Access &amp; continuity <ArrowRight size={14}/></Link></footer>
    </aside>}
    </div>{children}
  </div>;
}
