"use client";
import Link from "next/link";
import { useCallback, useState } from "react";
import { Button } from "@/components/ui/button";
import { useDeferredEffect } from "@/lib/use-deferred-effect";
import { announceWorkspaceMutation } from "@/lib/workspace-mutations";
import { decisionWorkflow, postmortemSchema, reviewVariance } from "@/lib/founder-os/workflows";
import type { z } from "zod";
import type { Row } from "@/lib/founder-os/repository";
import { DependencyPanel } from "./dependency-panel";
import { StrategyPanel } from "./strategy-panel";
type Decision = z.infer<typeof decisionWorkflow>;
type Postmortem = z.infer<typeof postmortemSchema>;
export function LessonProposal({ kind, id, initial = "" }: { kind: string; id: string; initial?: string }) {
 const [lesson, setLesson] = useState(initial), [message, setMessage] = useState(""), [busy, setBusy] = useState(false);
 return <details className="founder-record"><summary>Save as Operating Lesson</summary><p>Propose this learning for review in Operating Memory. A source can have one linked lesson; repeated proposals return that existing lesson.</p><label>Lesson<textarea value={lesson} onChange={e => setLesson(e.target.value)} /></label><Button disabled={busy || lesson.trim().length < 5} onClick={async () => { setBusy(true); try { const res = await fetch(`/api/founder-workflows/${kind}/${id}`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ lesson }) }); const body = await res.json(); if (!res.ok) throw new Error(body.error); setMessage("Proposed lesson is ready for review in Operating Memory."); announceWorkspaceMutation("founder-os"); } catch (e) { setMessage(String(e)); } finally { setBusy(false); } }}>Propose lesson</Button><p role="status">{message}</p><Link href="/learning">Review Operating Memory →</Link></details>;
}
function TextField({ label, value, change, type = "text" }: { label: string; value: string | number | null; change: (v: string) => void; type?: string }) { return <label><span>{label}</span>{type === "text" ? <textarea rows={2} value={value ?? ""} onChange={e => change(e.target.value)} /> : <input type={type} value={value ?? ""} onChange={e => change(e.target.value)} />}</label>; }
export function WorkflowPanel({ kind, id }: { kind: "decision" | "issue"; id: string }) {
 const [relationships, setRelationships] = useState<{ title: string; route: string }[]>([]);
 const [record, setRecord] = useState<Row | null>(null), [decision, setDecision] = useState<Decision>(decisionWorkflow.parse({})), [postmortem, setPostmortem] = useState<Postmortem>(postmortemSchema.parse({})), [error, setError] = useState(""), [message, setMessage] = useState(""), [busy, setBusy] = useState(false), [reviewing, setReviewing] = useState(false);
 const load = useCallback(async () => { try { const res = await fetch(`/api/founder-workflows/${kind}/${id}`); const body = await res.json(); if (!res.ok) throw new Error(body.error); setRecord(body.record); setRelationships(body.relationships ?? []); if (kind === "decision") setDecision(decisionWorkflow.parse(body.record.workflow ?? {})); else setPostmortem(postmortemSchema.parse({ summary: body.record.description ?? "", occurred_on: String(body.record.detected_at ?? "").slice(0,10), underlying_cause: body.record.root_cause ?? "", resolution: body.record.corrective_action ?? "", prevention: body.record.preventive_action ?? "", monitoring_gap: body.record.detection_gap ?? "", customers_affected: body.record.customer_exposure ?? "", operational_impact: body.record.operational_exposure ?? "", ...(body.record.postmortem ?? {}) })); } catch (e) { setError(String(e)); } }, [kind, id]);
 useDeferredEffect(useCallback(() => { void load(); }, [load]));
 async function save() { setBusy(true); setError(""); setMessage(""); try { const res = await fetch(`/api/founder-workflows/${kind}/${id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify(kind === "decision" ? decision : postmortem) }); const body = await res.json(); if (!res.ok) throw new Error(body.error); setRecord(body.record); setMessage("Review saved."); announceWorkspaceMutation("founder-os"); announceWorkspaceMutation(kind === "decision" ? "decisions" : "tasks"); } catch (e) { setError(String(e)); } finally { setBusy(false); } }
 const review = decision.review;
 const updateReview = (key: string, value: unknown) => setDecision(d => ({ ...d, review: { ...d.review!, [key]: value } }));
 const updatePostmortem = (key: string, value: unknown) => setPostmortem(p => ({ ...p, [key]: value }));
 if (!record) return <section><p role="status">Loading review…</p>{error && <p role="alert">{error}</p>}</section>;
 return <section className="founder-workspace"><header className="founder-page-header"><div><p className="eyebrow">{kind === "decision" ? "Decision → outcome → lesson" : "Resolution → prevention → lesson"}</p><h2>{kind === "decision" ? "Decision review" : `Postmortem: ${record.title}`}</h2></div><Link href={kind === "decision" ? `/decisions?record=${id}` : `/issues?record=${id}`}>Edit source context →</Link></header>
 {kind === "decision" ? <>
 <details className="founder-record" open><summary>Context, assumptions & expected outcome</summary><dl className="founder-details">{["decision", "owner_label", "decision_date", "deadline", "reasoning", "confidence", "reversibility", "financial_exposure", "assumptions", "expected_outcome", "expected_metric", "review_date"].map(k => <div key={k}><dt>{k.replaceAll("_", " ")}</dt><dd>{String(record[k] ?? "Not recorded")}</dd></div>)}</dl></details>
 <details className="founder-record"><summary>Options & decision</summary><p>The selected option, rationale and assumptions preserve the context for the later review.</p>{decision.options.map((option, index) => <fieldset className="founder-form" key={index}><legend>Option {index + 1}</legend>{(["label", "description", "benefits", "risks", "estimated_impact"] as const).map(k => <TextField key={k} label={k.replaceAll("_", " ")} value={option[k]} change={v => setDecision(d => ({ ...d, options: d.options.map((o, i) => i === index ? { ...o, [k]: v } : o) }))} />)}<label>Selected<input type="radio" name="selected-option" checked={option.selected} onChange={() => setDecision(d => ({ ...d, options: d.options.map((o, i) => ({ ...o, selected: i === index })) }))} /></label><Button onClick={() => setDecision(d => ({ ...d, options: d.options.filter((_, i) => i !== index) }))}>Remove option</Button></fieldset>)}<Button disabled={decision.options.length >= 20} onClick={() => setDecision(d => ({ ...d, options: [...d.options, { label: "", description: "", benefits: "", risks: "", estimated_impact: "", selected: false }] }))}>Add option</Button><TextField label="Operational exposure" value={decision.operational_exposure} change={v => setDecision(d => ({ ...d, operational_exposure: v }))} /><TextField label="Expected metric value" type="number" value={decision.expected_value} change={v => setDecision(d => ({ ...d, expected_value: v === "" ? null : Number(v) }))} /></details>
 <Button onClick={() => { setReviewing(true); if (!review) setDecision(d => ({ ...d, review: { actual_outcome: "", actual_metric: null, what_was_correct: "", what_was_wrong: "", what_changed: "", lesson: "", disposition: "remain", reviewed_on: new Date().toISOString().slice(0, 10) } })); }}>Review Decision</Button>
 {(reviewing || review) && review && <section className="founder-record"><h3>Compare expectation with outcome</h3><p>Expected: {String(record.expected_outcome || "Not recorded")} · Assumptions: {String(record.assumptions || "Not recorded")}</p><div className="founder-form">{(["actual_outcome", "what_was_correct", "what_was_wrong", "what_changed", "lesson"] as const).map(k => <TextField key={k} label={k.replaceAll("_", " ")} value={review[k]} change={v => updateReview(k, v)} />)}<TextField label="Actual metric value" type="number" value={review.actual_metric} change={v => updateReview("actual_metric", v === "" ? null : Number(v))} /><TextField label="Reviewed on" type="date" value={review.reviewed_on} change={v => updateReview("reviewed_on", v)} /><label>Decision should<select value={review.disposition} onChange={e => updateReview("disposition", e.target.value)}><option value="remain">Remain — validate</option><option value="change">Change — return to review</option><option value="reverse">Reverse</option><option value="followup">Require another decision</option></select></label></div><p>Variance: {reviewVariance(decision.expected_value, review.actual_metric) ?? "Expected and actual values needed"}</p>{review.disposition === "followup" && <Link href="/decisions">Create the follow-up decision →</Link>}</section>}
 </> : <>
 <p>Source status: {String(record.status)}. Business, project and affected system remain linked on the issue.</p>
 {Object.entries({ "Incident summary": ["summary", "occurred_on", "duration_minutes"], Impact: ["customers_affected", "revenue_impact", "operational_impact", "work_blocked"], "Root cause": ["immediate_cause", "contributing_factors", "underlying_cause"], Detection: ["detection", "expected_detection", "monitoring_gap"], Resolution: ["resolution", "temporary_mitigation", "permanent_correction"], Prevention: ["prevention", "prevention_owner", "prevention_due", "followup_on"], Learning: ["lesson", "recurrence_risk"] }).map(([title, keys]) => <details className="founder-record" key={title}><summary>{title}</summary><div className="founder-form">{keys.map(k => <TextField key={k} label={k.replaceAll("_", " ")} value={postmortem[k as keyof Postmortem]} type={k === "duration_minutes" ? "number" : ["occurred_on", "prevention_due", "followup_on"].includes(k) ? "date" : "text"} change={v => updatePostmortem(k, k === "duration_minutes" ? v === "" ? null : Number(v) : v)} />)}</div></details>)}<label>Postmortem status<select value={postmortem.status} onChange={e => updatePostmortem("status", e.target.value)}><option value="draft">Draft</option><option value="completed">Completed</option></select></label>
 <div className="founder-actions">{["task", "risk", "followup", "sop"].map(action => <Button key={action} disabled={busy} onClick={async () => { setBusy(true); setError(""); try { const res = await fetch(`/api/postmortem-actions/${id}`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action }) }); const body = await res.json(); if (!res.ok) throw new Error(body.error); await load(); setMessage(`${action === "sop" ? "SOP improvement proposal" : action} created or already linked. Open the source workspace to review it.`); announceWorkspaceMutation("founder-os"); } catch (e) { setError(String(e)); } finally { setBusy(false); } }}>Create {action === "sop" ? "SOP improvement proposal" : action === "task" ? "preventive task" : action === "followup" ? "follow-up review" : "risk"}</Button>)}</div>{Object.entries((record.postmortem_actions ?? {}) as Record<string, { route: string }>).map(([action, link]) => <Link className="founder-list-row" key={action} href={link.route}>Open linked {action} →</Link>)}<p className="founder-muted">Save the postmortem first. Actions reuse the saved prevention, owner and dates; repeated clicks reuse the linked result.</p>
 </>}
 {error && <p role="alert" className="founder-error">{error}</p>}<p role="status">{message}</p><Button intent="brand" disabled={busy} onClick={() => void save()}>{busy ? "Saving…" : "Save review"}</Button>
 <LessonProposal key={String(kind === "decision" ? record.workflow && JSON.stringify(record.workflow) : record.postmortem && JSON.stringify(record.postmortem))} kind={kind} id={id} initial={kind === "decision" ? decision.review?.lesson ?? "" : postmortem.lesson} />
<section><h3>Related work</h3>{relationships.map(r => <Link className="founder-list-row" key={r.route} href={r.route}>{r.title}</Link>)}</section>
 <DependencyPanel type={kind} id={id} />{kind === "decision" && <StrategyPanel type="decision" id={id} />}
 </section>;
}
