"use client";

import Link from "next/link";
import { useRouter } from "next/navigation";
import { useCallback, useMemo, useState } from "react";
import { Button } from "@/components/ui/button";
import { Modal } from "@/components/ui/modal";
import { Icons } from "@/components/icons";
import { useToast } from "@/components/toast-provider";
import { useDeferredEffect } from "@/lib/use-deferred-effect";
import { announceWorkspaceMutation } from "@/lib/workspace-mutations";
import { opportunityStages, proposalTotals, stageProbability, type OpportunityStage } from "@/lib/business";
import { ServiceAnalytics } from "@/features/business/service-analytics";
import { ReactivationCandidates } from "@/features/business/reactivation-candidates";

type RecordRow = Record<string, unknown> & { id: string; created_at?: string; updated_at?: string };
type Screen = "business" | "leads" | "pipeline" | "services" | "proposals";
type Resource = "leads" | "opportunities" | "services" | "proposals";
type Overview = { horizon: string; forecast: { currencies: Record<string, { received: number; outstanding: number; committed: number; weightedPipeline: number; potential: number }> }; risks: Array<{ type: string; title: string; detail: string; route: string }>; projects: RecordRow[] };

const copy: Record<Screen, { eyebrow: string; title: string; intro: string; action?: string }> = {
  business: { eyebrow: "Business operating system", title: "Business", intro: "A calm view of demand, commitments, and the margin underneath the work." },
  leads: { eyebrow: "Business development", title: "Leads", intro: "Potential relationships before they become a promise or a project.", action: "New lead" },
  pipeline: { eyebrow: "Business development", title: "Pipeline", intro: "Move qualified work forward with a next action, not a vague feeling.", action: "New opportunity" },
  services: { eyebrow: "Offer design", title: "Services", intro: "A small, reusable catalogue for pricing proposals and understanding delivery.", action: "New service" },
  proposals: { eyebrow: "Commercial commitments", title: "Proposals", intro: "Shape an offer deliberately before it becomes delivery work.", action: "New proposal" },
};

const label = (value: unknown) => String(value ?? "—").replaceAll("_", " ");
const amount = (value: unknown, currency = "MAD") => value == null ? "—" : new Intl.NumberFormat(undefined, { style: "currency", currency: String(currency) }).format(Number(value));
const clean = (values: Record<string, unknown>) => Object.fromEntries(Object.entries(values).map(([key, value]) => [key, key === "active" && typeof value === "string" ? value === "true" : typeof value === "string" ? value.trim() : value]).filter(([, value]) => value !== "" && value !== undefined));

export function BusinessWorkspace({ screen }: { screen: Screen }) {
  const config = copy[screen];
  const [records, setRecords] = useState<Record<string, RecordRow[]>>({});
  const [overview, setOverview] = useState<Overview | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");
  const [editor, setEditor] = useState<Resource | null>(null);
  const [editing, setEditing] = useState<RecordRow | null>(null);
  const [conversion, setConversion] = useState<RecordRow | null>(null);
  const { showToast } = useToast();
  const router = useRouter();
  const required = useMemo(() => screen === "business" ? (["leads", "opportunities", "proposals", "services"] as Resource[]) : [screen === "pipeline" ? "opportunities" : screen as Resource], [screen]);
  const load = useCallback(async () => {
    setLoading(true); setError("");
    try {
      const responses = await Promise.all(required.map(async (resource) => {
        const response = await fetch(`/api/business/${resource}?pageSize=100`, { cache: "no-store" });
        const body = await response.json();
        if (!response.ok) throw new Error(body.error ?? "Business records could not be loaded.");
        return [resource, body.records as RecordRow[]] as const;
      }));
      setRecords(Object.fromEntries(responses));
      if (screen === "business") {
        const response = await fetch("/api/business/overview?horizon=this_month", { cache: "no-store" });
        const body = await response.json(); if (!response.ok) throw new Error(body.error ?? "Business overview could not be loaded.");
        setOverview(body as Overview);
      } else setOverview(null);
    } catch (reason) { setError(reason instanceof Error ? reason.message : "Business records could not be loaded."); }
    finally { setLoading(false); }
  }, [required, screen]);
  useDeferredEffect(useCallback(() => { void load(); }, [load]));
  const open = (resource: Resource, record?: RecordRow) => { setEditor(resource); setEditing(record ?? null); };
  const save = async (resource: Resource, values: Record<string, unknown>) => {
    const response = await fetch(`/api/business/${resource}`, { method: editing ? "PATCH" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(editing ? { ...clean(values), id: editing.id } : clean(values)) });
    const body = await response.json();
    if (!response.ok) throw new Error(body.error ?? "The record could not be saved.");
    const saved = body.record as RecordRow;
    setRecords((current) => ({ ...current, [resource]: editing ? (current[resource] ?? []).map((row) => row.id === saved.id ? { ...row, ...saved } : row) : [saved, ...(current[resource] ?? [])] }));
    announceWorkspaceMutation(resource === "opportunities" ? "projects" : resource === "leads" ? "clients" : "finance");
    showToast(editing ? "Business record updated." : "Business record created.", "success");
    setEditor(null); setEditing(null);
  };
  const setStage = async (opportunity: RecordRow, stage: OpportunityStage) => {
    if (stage === opportunity.stage) return;
    const oldStage = opportunity.stage;
    setRecords((current) => ({ ...current, opportunities: (current.opportunities ?? []).map((row) => row.id === opportunity.id ? { ...row, stage } : row) }));
    try {
      const response = await fetch("/api/business/opportunities", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ id: opportunity.id, stage }) });
      const body = await response.json(); if (!response.ok) throw new Error(body.error);
      setRecords((current) => ({ ...current, opportunities: (current.opportunities ?? []).map((row) => row.id === opportunity.id ? body.record : row) }));
      showToast(`Moved to ${label(stage)}.`, "success");
    } catch (reason) { setRecords((current) => ({ ...current, opportunities: (current.opportunities ?? []).map((row) => row.id === opportunity.id ? { ...row, stage: oldStage } : row) })); showToast(reason instanceof Error ? reason.message : "Stage could not be changed.", "error"); }
  };
  const convert = async (opportunity: RecordRow, values: { createClient: boolean; projectName: string }) => {
    const response = await fetch(`/api/business/opportunities/${opportunity.id}/convert`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(values) });
    const body = await response.json(); if (!response.ok) throw new Error(body.error ?? "The opportunity could not be converted.");
    const result = body.result as { project_id: string; already_converted?: boolean };
    showToast(result.already_converted ? "This opportunity already has a project." : "Project created from won opportunity.", "success");
    setConversion(null); router.push(`/projects/${result.project_id}`); router.refresh();
  };
  return <div className="domain-page business-workspace">
    <header className="page-header"><div><p className="eyebrow">{config.eyebrow}</p><h1>{config.title}</h1><p>{config.intro}</p></div>{config.action ? <Button intent="brand" onClick={() => open(screen === "pipeline" ? "opportunities" : screen as Resource)}><Icons.Plus size={16}/>{config.action}</Button> : <nav className="business-header-links" aria-label="Business sections"><Link href="/leads">Leads</Link><Link href="/pipeline">Pipeline</Link><Link href="/proposals">Proposals</Link><Link href="/services">Services</Link></nav>}</header>
    {error ? <div className="inline-error" role="alert"><p>{error}</p><Button emphasis="outline" onClick={() => void load()}>Try again</Button></div> : null}
    {screen === "business" ? <Link className="back-link" href="/settings/business">Business settings</Link> : null}{loading ? <div className="empty-state" aria-live="polite"><span>···</span><h2>Reading the business picture</h2></div> : screen === "business" ? <BusinessOverview records={records} overview={overview} /> : screen === "leads" ? <Leads records={records.leads ?? []} onEdit={(record) => open("leads", record)} /> : screen === "pipeline" ? <Pipeline records={records.opportunities ?? []} onEdit={(record) => open("opportunities", record)} onStage={setStage} onConvert={setConversion} /> : screen === "services" ? <Services records={records.services ?? []} onEdit={(record) => open("services", record)} /> : <Proposals records={records.proposals ?? []} onEdit={(record) => open("proposals", record)} />}
    <BusinessEditor key={`${editor ?? "closed"}-${editing?.id ?? "new"}`} resource={editor} record={editing} onClose={() => { setEditor(null); setEditing(null); }} onSave={save}/>
    <ConversionEditor key={conversion?.id ?? "none"} opportunity={conversion} onClose={() => setConversion(null)} onConvert={convert}/>
  </div>;
}

function BusinessOverview({ records, overview }: { records: Record<string, RecordRow[]>; overview: Overview | null }) {
  const leads = records.leads ?? []; const opportunities = records.opportunities ?? []; const proposals = records.proposals ?? [];
  const pipeline = opportunities.filter((row) => !["won", "lost"].includes(String(row.stage))).reduce((sum, row) => sum + Number(row.estimated_value ?? 0) * (Number(row.probability ?? stageProbability[row.stage as OpportunityStage]) / 100), 0);
  const committed = proposals.filter((row) => row.status === "accepted").reduce((sum, row) => sum + Number(row.total ?? 0), 0);
  const next = opportunities.filter((row) => row.next_action).sort((a, b) => String(a.next_action_date ?? "9999").localeCompare(String(b.next_action_date ?? "9999"))).slice(0, 5);
  return <div className="business-overview"><section className="metric-ledger metric-ledger--four"><div><strong>{leads.length}</strong><span>Open leads</span></div><div><strong>{opportunities.filter((row) => !["won", "lost"].includes(String(row.stage))).length}</strong><span>Active opportunities</span></div><div><strong>{amount(pipeline)}</strong><span>Weighted pipeline</span></div><div><strong>{amount(committed)}</strong><span>Committed proposals</span></div></section><section className="business-summary-grid"><div className="data-surface"><p className="eyebrow">Next sales actions</p>{next.length ? next.map((row) => <Link className="signal-row" href={`/pipeline?opportunity=${row.id}`} key={row.id}><span><strong>{String(row.title)}</strong>{String(row.next_action)} · {row.next_action_date ? String(row.next_action_date) : "No date"}</span></Link>) : <p className="dataset-note">No opportunity needs a next action yet.</p>}</div><div className="data-surface"><p className="eyebrow">Commercial state</p><div className="business-state-lines"><span><strong>{proposals.filter((row) => row.status === "sent").length}</strong> proposals awaiting a decision</span><span><strong>{opportunities.filter((row) => row.stage === "negotiation").length}</strong> opportunities in negotiation</span><span><strong>{opportunities.filter((row) => row.stage === "won").length}</strong> opportunities won</span></div></div></section><section className="data-surface business-forecast"><p className="eyebrow">Revenue forecast · this month</p>{overview ? Object.entries(overview.forecast.currencies).map(([currency, values]) => <div className="metric-ledger metric-ledger--four" key={currency}><div><strong>{amount(values.received, currency)}</strong><span>Received · {currency}</span></div><div><strong>{amount(values.outstanding, currency)}</strong><span>Outstanding invoices</span></div><div><strong>{amount(values.committed, currency)}</strong><span>Committed</span></div><div><strong>{amount(values.weightedPipeline, currency)}</strong><span>Weighted pipeline</span></div></div>) : <p className="dataset-note">No forecast data is available yet.</p>}</section>{overview?.risks.length ? <section className="data-surface"><p className="eyebrow">Needs attention</p>{overview.risks.map((risk) => <Link href={risk.route} className="signal-row" key={`${risk.type}-${risk.title}`}><span><strong>{risk.title}</strong>{risk.detail}</span></Link>)}</section> : null}<ReactivationCandidates/></div>;
}
function Leads({ records, onEdit }: { records: RecordRow[]; onEdit: (row: RecordRow) => void }) { return <BusinessList rows={records} empty="No leads yet. Add a relationship worth following up on." columns={["Lead", "Source", "Next follow-up"]} values={(row) => [String(row.name), label(row.source), row.next_follow_up_at ? new Date(String(row.next_follow_up_at)).toLocaleDateString() : "—"]} onEdit={onEdit}/>; }
function Services({ records, onEdit }: { records: RecordRow[]; onEdit: (row: RecordRow) => void }) { const [selected, setSelected] = useState<RecordRow | null>(null); return <><BusinessList rows={records} empty="No services yet. Add the work you can price and deliver repeatedly." columns={["Service", "Pricing", "Default price"]} values={(row) => [String(row.name), label(row.pricing_type), amount(row.default_price, String(row.currency ?? "MAD"))]} onEdit={(row) => { setSelected(row); onEdit(row); }}/>{selected ? <section className="data-surface"><div className="integration-actions"><p className="eyebrow">Service detail · {String(selected.name)}</p><Button emphasis="ghost" onClick={() => setSelected(null)}>Close performance</Button></div><ServiceAnalytics serviceId={selected.id}/></section> : null}</>; }
function Proposals({ records, onEdit }: { records: RecordRow[]; onEdit: (row: RecordRow) => void }) { return <BusinessList rows={records} empty="No proposals yet. Create a draft when an opportunity needs a clear commercial offer." columns={["Proposal", "Status", "Total"]} values={(row) => [String(row.proposal_number ?? row.title), label(row.status), amount(row.total, String(row.currency ?? "MAD"))]} onEdit={onEdit}/>; }
function BusinessList({ rows, columns, values, empty, onEdit }: { rows: RecordRow[]; columns: string[]; values: (row: RecordRow) => string[]; empty: string; onEdit: (row: RecordRow) => void }) { return <section className="data-surface"><div className="data-header">{columns.map((column) => <span key={column}>{column}</span>)}</div>{rows.length ? rows.map((row) => <button type="button" className="data-row data-row--button" onClick={() => onEdit(row)} key={row.id}>{values(row).map((value, index) => index === 0 ? <strong key={index}>{value}</strong> : <span key={index}>{value}</span>)}<Icons.MoreHorizontal size={17}/></button>) : <div className="empty-state"><span>∅</span><h2>{empty}</h2></div>}</section>; }
function Pipeline({ records, onEdit, onStage, onConvert }: { records: RecordRow[]; onEdit: (row: RecordRow) => void; onStage: (row: RecordRow, stage: OpportunityStage) => Promise<void>; onConvert: (row: RecordRow) => void }) { return <div className="business-pipeline" aria-label="Opportunity pipeline">{opportunityStages.map((stage) => { const rows = records.filter((row) => row.stage === stage); return <section key={stage}><header><strong>{label(stage)}</strong><span>{rows.length}</span></header>{rows.length ? rows.map((row) => <article className="business-ticket" key={row.id}><button type="button" onClick={() => onEdit(row)}><strong>{String(row.title)}</strong><small>{amount(row.estimated_value, String(row.currency ?? "MAD"))} · {Number(row.probability ?? stageProbability[stage])}% likely</small>{row.next_action ? <em>{String(row.next_action)}</em> : null}</button><label className="sr-only" htmlFor={`stage-${row.id}`}>Move {String(row.title)} to stage</label><select id={`stage-${row.id}`} value={stage} onChange={(event) => void onStage(row, event.target.value as OpportunityStage)}>{opportunityStages.map((option) => <option value={option} key={option}>{label(option)}</option>)}</select>{stage === "won" ? <Button emphasis="outline" onClick={() => onConvert(row)}>Create project</Button> : null}</article>) : <p className="dataset-note">No opportunities.</p>}</section>; })}</div>; }

function BusinessEditor({ resource, record, onClose, onSave }: { resource: Resource | null; record: RecordRow | null; onClose: () => void; onSave: (resource: Resource, values: Record<string, unknown>) => Promise<void> }) {
  const [values, setValues] = useState<Record<string, unknown>>({}); const [saving, setSaving] = useState(false); const [error, setError] = useState("");
  const key = `${resource ?? "none"}-${record?.id ?? "new"}`;
  const initial = useMemo(() => editorValues(resource, record), [resource, record]);
  if (!resource) return null;
  const update = (field: string, value: unknown) => setValues((current) => ({ ...(Object.keys(current).length ? current : initial), [field]: value }));
  const current = Object.keys(values).length ? values : initial;
  const submit = async (event: React.FormEvent) => { event.preventDefault(); setSaving(true); setError(""); try { await onSave(resource, current); setValues({}); } catch (reason) { setError(reason instanceof Error ? reason.message : "Changes could not be saved."); } finally { setSaving(false); } };
  return <Modal key={key} open onClose={onClose} title={record ? `Edit ${singular(resource)}` : `New ${singular(resource)}`} description="Business records remain private to this workspace."><form className="simple-form business-editor" onSubmit={submit} noValidate>{resource === "leads" ? <LeadFields values={current} update={update}/> : resource === "opportunities" ? <OpportunityFields values={current} update={update}/> : resource === "services" ? <ServiceFields values={current} update={update}/> : <ProposalFields values={current} update={update}/>} {error ? <p className="field-error" role="alert">{error}</p> : null}<div className="modal__actions"><Button emphasis="ghost" onClick={onClose}>Cancel</Button><Button intent="brand" type="submit" disabled={saving}>{saving ? "Saving…" : "Save"}</Button></div></form></Modal>;
}
function ConversionEditor({ opportunity, onClose, onConvert }: { opportunity: RecordRow | null; onClose: () => void; onConvert: (opportunity: RecordRow, values: { createClient: boolean; projectName: string }) => Promise<void> }) { const [projectName, setProjectName] = useState(""); const [createClient, setCreateClient] = useState(true); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); if (!opportunity) return null; return <Modal open onClose={onClose} title="Create project" description="Create delivery work from this won opportunity. The operation is idempotent, so a retry will return the existing project."><form className="simple-form" onSubmit={(event) => { event.preventDefault(); setBusy(true); setError(""); void onConvert(opportunity, { projectName, createClient }).catch((reason) => setError(reason instanceof Error ? reason.message : "The project could not be created.")).finally(() => setBusy(false)); }} noValidate><label htmlFor="conversion-project">Project name<input id="conversion-project" value={projectName} placeholder={String(opportunity.title)} onChange={(event) => setProjectName(event.target.value)}/></label><label className="business-check"><input type="checkbox" checked={createClient} onChange={(event) => setCreateClient(event.target.checked)}/>Create a client from this lead when no client is linked</label>{error ? <p className="field-error" role="alert">{error}</p> : null}<div className="modal__actions"><Button emphasis="ghost" onClick={onClose}>Cancel</Button><Button intent="brand" type="submit" disabled={busy}>{busy ? "Creating…" : "Create project"}</Button></div></form></Modal>; }
const singular = (resource: Resource) => resource === "opportunities" ? "opportunity" : resource.slice(0, -1);
function editorValues(resource: Resource | null, record: RecordRow | null) { const defaults: Record<Resource, Record<string, unknown>> = { leads: { name: "", company: "", email: "", phone: "", source: "other", status: "new", potential_value: "", currency: "MAD", notes: "" }, opportunities: { title: "", stage: "new", estimated_value: "", currency: "MAD", probability: "", expected_close_date: "", source: "", project_type: "", next_action: "", next_action_date: "" }, services: { name: "", description: "", category: "", default_price: "", currency: "MAD", pricing_type: "custom", estimated_hours: "", active: "true" }, proposals: { title: "", proposal_number: "", status: "draft", currency: "MAD", discount_amount: "0", tax_amount: "0", valid_until: "", timeline: "", notes: "", terms: "", items: record?.items ?? [] } }; const base = resource ? defaults[resource] : {}; return { ...base, ...Object.fromEntries(Object.entries(record ?? {}).map(([key, value]) => [key, key === "items" ? value : value == null ? "" : String(value)])) }; }
function Field({ id, label: text, value, update, type = "text", options }: { id: string; label: string; value: unknown; update: (id: string, value: unknown) => void; type?: "text" | "number" | "date" | "textarea"; options?: readonly string[] }) { const stringValue = String(value ?? ""); return <label htmlFor={`business-${id}`}>{text}{type === "textarea" ? <textarea className="resize-none" id={`business-${id}`} rows={4} value={stringValue} onChange={(event) => update(id, event.target.value)}/> : options ? <select id={`business-${id}`} value={stringValue} onChange={(event) => update(id, event.target.value)}>{options.map((option) => <option value={option} key={option}>{label(option)}</option>)}</select> : <input id={`business-${id}`} type={type} value={stringValue} onChange={(event) => update(id, event.target.value)}/>}</label>; }
function LeadFields({ values, update }: { values: Record<string, unknown>; update: (id: string, value: unknown) => void }) { return <><Field id="name" label="Name" value={values.name} update={update}/><Field id="company" label="Company" value={values.company} update={update}/><Field id="email" label="Email" value={values.email} update={update}/><Field id="phone" label="Phone" value={values.phone} update={update}/><Field id="source" label="Source" value={values.source} update={update} options={["referral","instagram","website","email","whatsapp_manual","networking","existing_client","other"]}/><Field id="potential_value" label="Potential value" value={values.potential_value} update={update} type="number"/><Field id="notes" label="Notes" value={values.notes} update={update} type="textarea"/></>; }
function OpportunityFields({ values, update }: { values: Record<string, unknown>; update: (id: string, value: unknown) => void }) { return <><Field id="title" label="Opportunity" value={values.title} update={update}/><Field id="stage" label="Stage" value={values.stage} update={update} options={opportunityStages}/><Field id="estimated_value" label="Estimated value" value={values.estimated_value} update={update} type="number"/><Field id="probability" label="Probability (0–100)" value={values.probability} update={update} type="number"/><Field id="expected_close_date" label="Expected close" value={values.expected_close_date} update={update} type="date"/><Field id="next_action" label="Next action" value={values.next_action} update={update}/><Field id="next_action_date" label="Next action date" value={values.next_action_date} update={update} type="date"/></>; }
function ServiceFields({ values, update }: { values: Record<string, unknown>; update: (id: string, value: unknown) => void }) { return <><Field id="name" label="Service" value={values.name} update={update}/><Field id="description" label="Description" value={values.description} update={update} type="textarea"/><Field id="category" label="Category" value={values.category} update={update}/><Field id="pricing_type" label="Pricing" value={values.pricing_type} update={update} options={["fixed","hourly","monthly","custom"]}/><Field id="default_price" label="Default price" value={values.default_price} update={update} type="number"/><Field id="estimated_hours" label="Estimated hours" value={values.estimated_hours} update={update} type="number"/></>; }
function ProposalFields({ values, update }: { values: Record<string, unknown>; update: (id: string, value: unknown) => void }) { const items = Array.isArray(values.items) ? values.items as Array<Record<string, unknown>> : []; const patch = (index: number, field: string, value: unknown) => update("items", items.map((item, position) => position === index ? { ...item, [field]: value } : item)); const totals = proposalTotals(items.map((item) => ({ quantity: Number(item.quantity ?? 1), unit_price: Number(item.unit_price ?? 0) })), Number(values.discount_amount ?? 0), Number(values.tax_amount ?? 0)); return <><Field id="title" label="Proposal title" value={values.title} update={update}/><Field id="proposal_number" label="Proposal number" value={values.proposal_number} update={update}/><Field id="status" label="Status" value={values.status} update={update} options={["draft","sent","accepted","rejected","expired"]}/><Field id="valid_until" label="Valid until" value={values.valid_until} update={update} type="date"/><div className="proposal-lines"><div><p className="eyebrow">Line items</p><Button emphasis="outline" onClick={() => update("items", [...items, { title: "", quantity: 1, unit_price: 0, position: items.length }])}>Add line</Button></div>{items.length ? items.map((item, index) => <div className="proposal-line" key={index}><label>Item<input value={String(item.title ?? "")} onChange={(event) => patch(index, "title", event.target.value)}/></label><label>Qty<input type="number" min="0.01" value={String(item.quantity ?? 1)} onChange={(event) => patch(index, "quantity", event.target.value)}/></label><label>Unit price<input type="number" min="0" value={String(item.unit_price ?? 0)} onChange={(event) => patch(index, "unit_price", event.target.value)}/></label><Button emphasis="ghost" onClick={() => update("items", items.filter((_, position) => position !== index))}>Remove</Button></div>) : <p className="dataset-note">Add the services or deliverables included in this proposal.</p>}<p className="proposal-total">Subtotal {amount(totals.subtotal, String(values.currency ?? "MAD"))} · Total {amount(totals.total, String(values.currency ?? "MAD"))}</p></div><Field id="discount_amount" label="Discount" value={values.discount_amount} update={update} type="number"/><Field id="tax_amount" label="Tax" value={values.tax_amount} update={update} type="number"/><Field id="timeline" label="Timeline" value={values.timeline} update={update} type="textarea"/><Field id="notes" label="Notes" value={values.notes} update={update} type="textarea"/><Field id="terms" label="Terms" value={values.terms} update={update} type="textarea"/></>; }
