"use client";
import Link from "next/link";
import { useCallback,useState } from "react";
import { Icons } from "@/components/icons";
import { Button } from "@/components/ui/button";
import { useDeferredEffect } from "@/lib/use-deferred-effect";
type Calendar={id?:string;summary?:string;primary?:boolean;timeZone?:string};type State={connected:boolean;calendars:Calendar[];selectedCalendar:string|null;lastSyncedAt:string|null};
export function GoogleCalendarCard(){const[state,setState]=useState<State|null>(null);const[error,setError]=useState("");const[busy,setBusy]=useState(false);const load=useCallback(async()=>{try{const response=await fetch("/api/integrations/google",{cache:"no-store"});const data=await response.json();if(!response.ok)throw new Error(data.error);setState(data)}catch(reason){setError(reason instanceof Error?reason.message:"Connection status unavailable.")}},[]);useDeferredEffect(useCallback(()=>{void load()},[load]));async function action(method:"POST"|"DELETE"){setBusy(true);setError("");try{const response=await fetch("/api/integrations/google",{method});if(!response.ok){const data=await response.json();throw new Error(data.error)}await load()}catch(reason){setError(reason instanceof Error?reason.message:"Google Calendar could not be updated.")}finally{setBusy(false)}}async function select(calendarId:string){setState((current)=>current?{...current,selectedCalendar:calendarId}:current);const calendar=state?.calendars.find((item)=>item.id===calendarId);const response=await fetch("/api/integrations/google",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({calendarId,timezone:calendar?.timeZone})});if(!response.ok){const data=await response.json();setError(data.error);await load()}}
 return <article className="project-card"><div className="project-card__top"><span className="command-result__icon"><Icons.CalendarDays size={17}/></span><span className={state?.connected?"status status--blue":"status"}>{state?.connected?"Connected":"Not connected"}</span></div><h2>Google Calendar</h2><p>Two-way event sync with encrypted server-side OAuth tokens, recurrence, all-day events, and incremental updates.</p>{state?.connected?<><label className="integration-label" htmlFor="sync-calendar">Sync calendar</label><select id="sync-calendar" value={state.selectedCalendar??"primary"} onChange={(event)=>void select(event.target.value)}>{state.calendars.map((calendar)=><option value={calendar.id} key={calendar.id}>{calendar.summary}{calendar.primary?" (primary)":""}</option>)}</select><div className="integration-actions"><Button emphasis="outline" onClick={()=>void action("POST")} disabled={busy}>{busy?"Syncing…":"Sync now"}</Button><Button emphasis="ghost" onClick={()=>void action("DELETE")} disabled={busy}>Disconnect</Button></div><small>Last sync · {state.lastSyncedAt?new Date(state.lastSyncedAt).toLocaleString():"Never"}</small></>:<Link className="button button--outline button--neutral" href="/api/integrations/google/connect">Connect Google</Link>}{error?<p className="field-error" role="alert">{error}</p>:null}</article>}
